# <ins>Project Title</ins>: 

## Naive Bayes Investment Tool

# <ins>Created By</ins>: 

## Daniel Ramirez Jr.

# <ins>Project Description</ins>:
## Type: Personal (For Fun)

## Tool Introduction:

This code/model has successfully created an investment tool that is based soley on technical analysis, but should be used in conjunction with fundamental practices that drive investment decisions. This model provides several different types of information to the user of the tool, of which can be used to predict whether or not a stock will increase by 1% - 5%, the day following a stock's earnings report. 

For example, assume that stock x releases their earnings report after market close today. By this time, the model would be able to give a prediction on whether stock x will increase by 1% to 5% by the end of the following trading day. This would give the investor enough time to purchase the stock the following morning, and then sell before the market closes to realize the 1% to 5% gain. 

The underlying algothrim used to perform predictions was the Naive Bayes Classifier. What this classifier helps determine is the probability that a certain stock x will increase by 1% to 5%, given that certain events have already occured. To be more specific, the model answers the following question:

"What is the probability that the price of stock x will increase by 1% to 5%, by the time the market closes on the trading day following the reported earnings date, given that events x1 through x5 occur:"


- x1 = Reported earnings per share (EPS) were higher than the previous reported date 


- x2 = Reported EPS was higher than the estimated EPS (i.e. the EPS surprise was positive)


- x3 = Adjusted stock price is larger than the previous reported date


- x4 = Intraday return of the stock x, on reported date, is greater than or equal to its median intraday return of the last 5 trading days


- x5 = Intraday return of the SPY etf is on reported date, is greater than or equal to its median intraday return of the last 5 trading days

## Explaining Events


x_1:

The first event informs the investor that that growth is currently in place or that the company is becoming more efficient by decreasing their cost of goods/expenses. Both could lead to an increase interest in the company and drive the stock price up based on demand.   


x_2:

The second event gives us a better understanding of how incorrect the market was at estimating the performance of a company. The higher the percentage error, also known as the surprise percentage, the better, because it signals under-valuation. During these periods, the investor has the opportunity to purchase a stock for a relatively "low" price and then sell at a 'fair' market price.


x_3:

The third event could be telling us that the market thinks that the company is going to perform well in the upcoming earnings report, and it reflects that through the price. The adjusted price was used because it takes into account any stock-splits that may have occured. However, the first event could also be a signal that the market is overvaluing the future performance of the company, potentially making it a relatively bad time to buy the stock. 



x_4:

The fourth event shows that the market has a positive sentiment regarding earnings. It is common to see a stock's intraday return fluctulate throughout the week and it is possible that one of those days, the market overvalued the stock and increased the average intraday return. Thus, the median was used to better reflect the distribution of the most recent intraday returns. If the stock increased higher than its weekly median return, it could signal that the stock has the ability to increase.

x_5:

The fifth event informs the investor on how the overall market is performing in the span of one week. The S&P 500 is index that tracks slightly over 500 publicly traded companies in the United States. This index is constantly used as a benchmark to gage how the overall market is performing. Moreover, this index is tracked by an exchange-traded-fund (ETF) called SPY that was used in this analysis. If the return on SPY, at the end of the reported date, was higher than its weekly median intraday return , it could potentially signal that the market has a positive outlook.

## Model Breakdown

The model provides the following information to the user:

1. Upcoming Earnings Calendar (3 month horizon):

    - Dataframe of companies that are reporting earnings on a given date within the next three months


2. Historical Earnings Report (Individual Company):

    - Dataframe of all the reported EPS instances along with their estimated EPS, surprise EPS, and corresponding dates
    
    
3. Daily Adjusted Prices Report (Individual Company):

    - Dataframe of the 5,000 most recent trading dates that contain intraday data
    
    
4. Naive Bayes Prediciton Model:

    - Current Date provides a buying signal and Future Date provides a model accuracy score for a specific stock:


        - Individual Analysis (Current Date/Future Date | Logical Display/Clean Display)
        - Multi-Company Analysis (Current Date/ Future Date | Logical Display/Clean Display)

## Showcasing Model Outputs

Below are six different ways to use this model. If interested in the underlying code and explained logic, go to the "Model Creation: Fundamental Functions" section. Moreover, to see more ways to use this model, go to the "Other User Options" section.

### 1. Upcoming Earnings Calendar

In [25]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#the present date and time is Monday, 2021-11-01 at 6 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)
2. Historical Earnings (last 5 earning reports for a specific company)
3. Daily Adjusted Price History (displays 15 trading dates for a specific company)
4. Naive Bayes Prediction Model

1

Pick a date that is within the next three months (yyyy-mm-dd):
2021-11-02

Total API Calls: 1

    symbol                           name  reportDate estimate
55    ACRS       Aclaris Therapeutics Inc  2021-11-02    -0.28
58     ACT             Enact Holdings Inc  2021-11-02     0.81
66    ADCT            Adc Therapeutics SA  2021-11-02    -0.92
102    AFG   American Financial Group Inc  2021-11-02     1.86
122   AGRX         Agile Therapeutics Inc  2021-11-02    -0.19
131    AHH  Armada Hoffler Properties Inc  2021-11-02     0.05
142    AIZ                   Assurant Inc  2021-11-02      1.9
146   AKAM        Akamai Technologies Inc  2021-11-02     1.39
206   AMCR                      Amcor Plc  2021-11-02     0.18
209    AME                     Ametek Inc  2021-11-02     1.18
210   AMED                   Amedisys Inc  2021-11-02     1.36
214   AMGN                      AMGEN Inc  2021-11-02     4.27
232   AMSC   American Superconductor Corp  2021-11-02    -0.16
239   ANAB                 AnaptysBio Inc  2021-11-02    -0.91
242   ANDE                  Andersons Inc  2021-11-02    -0.11

This is not investment advice.
Please wait 60 seconds before running the model again.

### 2. Historical Earnings Report (Specific Stock)

In [121]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z
#PSA
#the present date and time is Monday, 2021-11-01 at 6 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)
2. Historical Earnings (last 5 earning reports for a specific company)
3. Daily Adjusted Price History (displays 15 trading dates for a specific company)
4. Naive Bayes Prediction Model

2

Enter the ticker symbol:

PSA

  reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0   2021-11-01        None          2.1     None               None
1   2021-08-03        3.15       2.9413   0.2087             7.0955
2   2021-04-28        2.82       2.7132   0.1068             3.9363
3   2021-02-24        2.93       2.8472   0.0828             2.9081
4   2020-11-04        2.63       2.5975   0.0325             1.2512

This is not investment advice.
Please wait 60 seconds before running the model again.
Total API Calls: 1

### 3. Daily Adjusted Price Report (Specific Stock)

In [128]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z
#PSA
#the present date and time is Monday, 2021-11-01 at 6 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)
2. Historical Earnings (last 5 earning reports for a specific company)
3. Daily Adjusted Price History (displays 15 trading dates for a specific company)
4. Naive Bayes Prediction Model

3

Enter the ticker symbol:

PSA

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,332.66,333.800,323.4400,331.64,331.64,522662,0.0,1.0,-0.3066,0.4864,2021-11-01
1,329.31,335.710,328.2900,332.18,332.18,1358977,0.0,1.0,0.8715,0.4864,2021-10-29
2,323.67,332.220,323.6700,331.62,331.62,746742,0.0,1.0,2.4562,-0.2807,2021-10-28
3,327.79,327.790,321.8000,322.44,322.44,421235,0.0,1.0,-1.6321,0.2082,2021-10-27
4,327.80,328.910,324.3000,326.88,326.88,411413,0.0,1.0,-0.2807,0.2082,2021-10-26
5,326.92,329.910,324.1500,328.51,328.51,353980,0.0,1.0,0.4864,0.2082,2021-10-25
6,324.03,327.180,323.7200,326.33,326.33,451917,0.0,1.0,0.7098,-0.3769,2021-10-22
7,323.73,324.030,320.2500,322.51,322.51,425934,0.0,1.0,-0.3769,0.2082,2021-10-21
8,321.77,322.975,319.9700,322.44,322.44,501029,0.0,1.0,0.2082,0.5398,2021-10-20
9,322.86,323.920,320.1000,321.00,321.00,387275,0.0,1.0,-0.5761,2.0847,2021-10-19
10,320.49,323.830,318.5800,322.22,322.22,655562,0.0,1.0,0.5398,2.0847,2021-10-18
11,326.86,327.040,316.5300,319.42,319.42,972847,0.0,1.0,-2.2762,2.0847,2021-10-15
12,318.90,326.170,317.0200,325.88,325.88,755667,0.0,1.0,2.1888,0.7067,2021-10-14
13,310.84,317.970,310.0201,317.32,317.32,505078,0.0,1.0,2.0847,0.7067,2021-10-13
14,303.93,313.180,303.1500,311.31,311.31,582250,0.0,1.0,2.4282,-0.2547,2021-10-12

This is not investment advice.
Please wait 60 seconds before running the model again.

Total API Calls: 1

### 4.1. Naive Bayes Prediction Model (Specific Stock | Prediction | Clean Display)

In [132]:
if __name__=="__main__":
    main()        
    
#alphavantage API key
#TQ6TR98HVUPE3L9Z
#PSA

#finhub API key
#c5d5iiqad3i9ue38pn9g

#the model will provide a buying decision for AME 
#the present date and time is Monday, 2021-11-01 at 6 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)
2. Historical Earnings (last 5 earning reports for a specific company)
3. Daily Adjusted Price History (displays 15 trading dates for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

1

Enter the date of interest:

2021-11-01

Enter the ticker symbol:

PSA


PSA has reported earnings 95 times, as of the current date.

PSA's most recent/upcoming reporting date is:

2021-11-01

Enter your finhub API-Key:

c5d5iiqad3i9ue38pn9g


This is PSA's most updated earnings report:

,symbol,reportedDate,hour,reportedEPS,estimatedEPS,surprise,surprisePercentage
0,PSA,2021-11-01,amc,3.42,2.147,1.273,59.292

What type of output would you like?:

Logic will display how the model variables were created, while Clean will provides results:

 1.Logic

 2.Clean

2




This is the buy signal:

Result dataframe:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal
0,0,1,0,3,0.8125,0.75,0.642857,75.0,Valid,Do NOT buy

Thank you for using the model.
Please wait 60 seconds before running the model again.

### 4.2. Naive Bayes Prediction Model (Multi-Stock | Current Date | Clean Display)

In [139]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#finhub API key
#c5d5iiqad3i9ue38pn9g

#the present date and time is Monday, 2021-11-01 at 6 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)
2. Historical Earnings (last 5 earning reports for a specific company)
3. Daily Adjusted Price History (displays 15 trading dates for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

2

Enter the date of interest:

2021-11-01

What type of output would you like?:

Logic will display how the model variables were created, while Clean Variables will display results:

 1.Logic

 2.Clean

2

Enter your finhub API-Key:

c5d5iiqad3i9ue38pn9g

Below is the list of companies that reported earnings (15 Max)

,symbol,reportedDate,hour,reportedEPS,estimatedEPS,surprise,surprisePercentage
0,BRX,2021-11-01,amc,0.39,0.1023,0.2877,281.2317
1,WMB,2021-11-01,amc,0.34,0.2859,0.0541,18.9227
2,WTRG,2021-11-01,bmo,0.19,0.2131,-0.0231,-10.8400
3,CAR,2021-11-01,amc,10.74,6.5861,4.1539,63.0707
4,CLX,2021-11-01,amc,1.21,1.0423,0.1677,16.0894
5,CNA,2021-11-01,bmo,0.87,0.6085,0.2615,42.9745
6,CVI,2021-11-01,amc,-0.24,-0.0403,-0.1997,495.5335
7,AROC,2021-11-01,amc,0.06,0.0709,-0.0109,-15.3738
10,IPI,2021-11-01,amc,0.30,0.5824,-0.2824,-48.4890
11,KMT,2021-11-01,amc,0.44,0.3818,0.0582,15.2436
12,BCC,2021-11-01,amc,2.31,2.0629,0.2471,11.9783
13,APEN,2021-11-01,amc,-0.23,-0.2856,0.0556,-19.4678
14,CHGG,2021-11-01,amc,0.20,0.2033,-0.0033,-1.6232
15,VRNS,2021-11-01,amc,0.05,0.0190,0.0310,163.1579
16,SMLR,2021-11-01,amc,0.51,0.6582,-0.1482,-22.5160

Stock Count: 88

There are 88 companies reporting earings on the specified date. Analysis will only be provided for the first 15 companies in the list. This should take about 9 minutes. Please wait patiently.


There are a total of 45 stock calls





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.8125,0.75,0.642857,75.0,Valid,Do NOT buy,BRX

Model has been put to sleep after historical earnings call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,2,0,2,0.75,0.5,0.333333,50.0,Valid,Do NOT buy,WMB

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,1,1,1,1,0.5,0.5,0.5,50.0,Invalid,Do NOT buy,WTRG

Model has been put to sleep after the alpha spy





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,CAR

Model has been put to sleep after the daily adjusted call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,CLX

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,2,0,2,0.75,0.5,0.333333,50.0,Valid,Do NOT buy,CNA

Model has been put to sleep after historical earnings call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,1,2,0.5,0.5,0.5,50.0,Invalid,Do NOT buy,CVI

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,1,2,0.5,0.5,0.5,50.0,Invalid,Do NOT buy,AROC

Model has been put to sleep after the alpha spy





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.8125,0.75,0.642857,75.0,Valid,Do NOT buy,IPI

Model has been put to sleep after the daily adjusted call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.8125,0.75,0.642857,75.0,Valid,Do NOT buy,KMT

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,1,0,0,3,1.0,1.0,1.0,100.0,Valid,Do NOT buy,BCC

Model has been put to sleep after historical earnings call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,2,0,2,0.75,0.5,0.333333,50.0,Valid,Do NOT buy,APEN

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,CHGG

Model has been put to sleep after the alpha spy





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,VRNS

Model has been put to sleep after the daily adjusted call





This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,1,1,0,2,0.833333,0.75,0.733333,75.0,Valid,Do NOT buy,SMLR

Model performance across all the stock in the list:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,[0],[1],[0],[3],[0.8125],[0.75],[0.6428571428571428],[75.0],[Valid],[Do NOT buy],BRX
1,[0],[2],[0],[2],[0.75],[0.5],[0.3333333333333333],[50.0],[Valid],[Do NOT buy],WMB
2,[1],[1],[1],[1],[0.5],[0.5],[0.5],[50.0],[Invalid],[Do NOT buy],WTRG
3,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],CAR
4,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],CLX
5,[0],[2],[0],[2],[0.75],[0.5],[0.3333333333333333],[50.0],[Valid],[Do NOT buy],CNA
6,[0],[1],[1],[2],[0.5],[0.5],[0.5],[50.0],[Invalid],[Do NOT buy],CVI
7,[0],[1],[1],[2],[0.5],[0.5],[0.5],[50.0],[Invalid],[Do NOT buy],AROC
8,[0],[1],[0],[3],[0.8125],[0.75],[0.6428571428571428],[75.0],[Valid],[Do NOT buy],IPI
9,[0],[1],[0],[3],[0.8125],[0.75],[0.6428571428571428],[75.0],[Valid],[Do NOT buy],KMT
10,[1],[0],[0],[3],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],BCC
11,[0],[2],[0],[2],[0.75],[0.5],[0.3333333333333333],[50.0],[Valid],[Do NOT buy],APEN
12,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],CHGG
13,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],VRNS
14,[1],[1],[0],[2],[0.8333333333333333],[0.75],[0.7333333333333334],[75.0],[Valid],[Do NOT buy],SMLR

Thank you for using the model.
Please wait 60 seconds before running the model again.

## Gathering Financial Data

The majority of the financial data will be pulled from alphavantage's financial APIs as well as Finhub's financial API. In order to conduct a naive bayes analysis, the user will need a historical earnings report that contains at least 3 years (12 quarters) worth of reported earnings history. This dataframe will yield the first 2 events (x1 and x2).

Moreover, the user will need a record of all the daily adjusted prices (most recent 5,000 trading dates) for a specific stock so that it can be matched up with the dates that earnings were reported. The user will also need a record of all the daily adjusted prices (most recent 5,000 trading dates) for the SPY ETF. 

Finally, the Finhub historical earnings function was used to get the most recent reported earnings information to make buying predictions on the current date (day of reported earnings).

The majority of this model consists of cleaning the dataframes, deriving variables from them using statistics, and merging them properly based on conditions. In addition, given that the alphavantage API has a 5 call per minute limit, the model needed to efficiently call the API so that calls were wasted nor limits exceeded.

## Model Creation: Fundamental Functions

###  1. Creating the finhubEarningsCalendar Function

This function can only return historical earnings data.

In [2]:
#this function pulls earnings data from finhub and then cleans it so that it can be used in the analysis
#this function only works for past data and does not give upcoming earnings, that is why the alphaVantage api was used in conjuction
#earnings calendar should be different than the alpha because it is more up to date and gives BMO o AMC datapoints
#inputs include:
#date range
#symbol - if no symbol is given, api will return all the stocks that are releasing earnings on that date

def finhubEarningsCalendar(finhub_api,from_date,to_date,symbol):
    
    
    #gathering the earnings calendar data:
    
    #import the library
    import finnhub
      
    #create an instance of the finhub library that contains API key
    finnhub_client = finnhub.Client(api_key=finhub_api)
    
    #get the stock earnings data that from the specified date range
    #this returns a nested dictionary that needs to be pulled apart 
    finub_earn_calendar = finnhub_client.earnings_calendar(_from=from_date, to=to_date, symbol=symbol, international=False)
    
    #the earningsCalendar key contains the values neede for the analysis
    finub_earn_calendar = finub_earn_calendar['earningsCalendar']
    
    #import pandas library
    import pandas as pd
    
    #convert the dictionary into a readable dataframe
    earningsCalendar = pd.DataFrame(data=finub_earn_calendar)
    
    
    #editing the dataframe so that it can be compatible with the alphaVantage dataframes and to use in the model:
    
    #filter out the following columns: quarter, revenueActual, revenueEstimate, and year:
    earningsCalendar.loc[:,['date', 'epsActual','epsEstimate','hour','symbol']]
    
    #change the column names:
    earningsCalendar.rename(columns = {'epsEstimate':'estimatedEPS'},inplace=True)
    earningsCalendar.rename(columns = {'date':'reportedDate'},inplace=True)
    earningsCalendar.rename(columns = {'epsActual':'reportedEPS'},inplace=True)
    
    #change the positions of the columns:
    #list of the column names
    column_names = ["symbol", "reportedDate", "hour","reportedEPS","estimatedEPS"]
    
    #reoder the dataframe
    earningsCalendar = earningsCalendar.reindex(columns=column_names)  
    
    #filter out the nones, of which can be found in the following columns:
    earningsCalendar =  earningsCalendar.loc[(earningsCalendar['estimatedEPS'].notnull())]
    earningsCalendar =  earningsCalendar.loc[(earningsCalendar['reportedEPS'].notnull())]
    
    
    #add the surprise amount column
    earningsCalendar['surprise'] = earningsCalendar['reportedEPS'] - earningsCalendar['estimatedEPS'] 

    #add the surprise perecentage column
    earningsCalendar['surprisePercentage'] = round(((earningsCalendar['reportedEPS'] /earningsCalendar['estimatedEPS'])-1)*100,4)
    
    
    #return the dataframe
    return earningsCalendar

### 2. Creating the alphaDataRetriever Function

In [3]:
#create a function that:
#individual earnings table for a specific stock
#daily adjusted prices for a specific stock:
#it also calculates the Intraday_Return and Weekly_Median_Return to be used later in the analysis section

#inputs include:
#type of data to retrieve where:
#1 = historical earnings
#2 = daily ajusted prices
#api key for alphaVantage


def alphaDataRetriever(api_key, data_of_interest, symbol,date_of_interest):
    #import necessary libraries
    import pandas as pd
    import csv
    import requests
    
    
    #remember that alphavantage only takes 5 calls per mintute and 500 throughout the entire day
    #for the earnings calendar call, symbol is not important

    if data_of_interest == '1':

        CSV_URL = 'https://www.alphavantage.co/query?function=EARNINGS_CALENDAR&horizon=3month&apikey=' + api_key

        with requests.Session() as s:

            download = s.get(CSV_URL)
            decoded_content = download.content.decode('utf-8')
            cr = csv.reader(decoded_content.splitlines(), delimiter=',')
            earnings_calendar = pd.DataFrame(data =cr)

        #edit the dataframe:
        #make the first row the column names
        earnings_calendar = earnings_calendar.rename(columns=earnings_calendar.iloc[0])

        #delete the first row since it has been used already to name the columns
        earnings_calendar = earnings_calendar.iloc[1:,:]

        #filter by the date of interest and loc the dataframe
        ec = earnings_calendar.loc[earnings_calendar.reportDate == date_of_interest]

        #not all stocks have an EPS estimate, these should be excluded from the dataframe
        #dataframe = dataframe[dataframe.column then the condition]
        ec = ec[ec.estimate != '']

        #not all stocks are traded in USD, but this project will only focus on the USD currency
        ec = ec[ec.currency == 'USD']

        #remove the irrelevant columns
        ec = ec.drop(['fiscalDateEnding','currency'],1)

        #display dataframe
        return ec


    
    elif data_of_interest == '2':

        #format of how the url should be structured before using the api
        earnings_history_url = 'https://www.alphavantage.co/query?function=EARNINGS&symbol=' + symbol +'&apikey=' + api_key

        #makes the request using the formatted url
        r = requests.get(earnings_history_url)
        data = r.json()

        #the data variable stores the data in json structure and the value of key = quarterlyEarnings is the point of interest
        quarterly_earnings = data['quarterlyEarnings']

        #convert this json into a dataframe
        quarterly_earnings = pd.DataFrame(quarterly_earnings)
        
        quarterly_earnings = quarterly_earnings.drop('fiscalDateEnding',1)
        
        return quarterly_earnings
    
    #this api call will return the most recent data avaialble
    
    elif data_of_interest == '3':
        #getting the time series data
        #this url contains the format needed to make the api call for time series data
        daily_prices_url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=' + symbol + '&outputsize=full' +'&apikey=' + api_key

        #makes the api request/call
        daily_price_request = requests.get(daily_prices_url)

        #stores the values into a dictionary
        daily_prices = daily_price_request.json()
        
        #stores the relevant information into a dictionary
        dictionary_of_dp = daily_prices['Time Series (Daily)']

        #convert this json into a dataframe, where the keys are the rows and the values are the columns 
        historical_prices = pd.DataFrame.from_dict(dictionary_of_dp, orient = 'index')
        
        #turn column values into numeric values
        historical_prices = historical_prices.apply(pd.to_numeric)
    
        #perform return calculations for each specific date
        historical_prices['Intraday_Returns'] = round((historical_prices['5. adjusted close']/historical_prices['1. open']-1)*100,4)

        #find the previous 5 day median intraday return and create the column 
        #the value will take into account the previous 5 trading days
        historical_prices['Weekly_Median_Return'] = historical_prices['Intraday_Returns'].rolling(window=5).median().shift(-5)

        #the indexes are the dates thus make that a column labeled reportedDate because that will be the key column for the inner join
        historical_prices['trading_date'] = historical_prices.index
        
        #reset the index since its a column now
        historical_prices.reset_index(drop=True, inplace=True)
        
        #remember that the model could break if there is not enough historical data
        return historical_prices
    
    #tell the analyst that their value is not valid
    else:
        print('Wrong Input for the alphaDataRetriever - Try again.')

### 3. Creating the historicalEarningsTransformer Function

In [4]:
#the model needs to understand what date the user is inputting
def historicalEarningsTransformer(date_type,historical_earnings,finhub_function):
    
    #assuming that the date provided by the analyst is after market close on the reported date:

    #import necessary libraries
    import pandas as pd

    #don't alter the dataframes that were used as inputs, instead, make a copy of each:
    
    #this variable holds a stock's individual earnings history
    earnings_hist = historical_earnings.copy(deep=True)
    

    #for training purposes,only keep the rows that are relevant.
    #the api feeds in the most current earnings and as a result, the historical prices will not line up
    #let those rows be used for the testing portion, while the remaining events get analyzed
    #no need for rows that don't contain information such as none. If none is found in the estimate, then the remaining 2 columns will be none
   
    
    #if analyst chooses the reporting date of today, after market close: 
    
    if date_type == '1':
        
        #keep the first cell in the first row because it contains the date of the most recent/upcoming earnings event
        #this date will be used to gather several variables such as intraday event, SPY event, Adjusted Price event
        report_date_of_interest = earnings_hist.iloc[0,0]

        
        #create common column name so that the dataframes can be merged properly 
        #common name is equal to 'column_of_interest'
        earnings_hist.rename(columns = {'reportedDate':'column_of_interest'}, inplace = True)

        #filter out the nones, of which can be found in the following columns:

        #the first row will almost always be none because it is a future date or the current report date
        #the first row can be filled if the API itself refreshes for the day
        #this api does not update in real time
        
        earnings_hist =  earnings_hist.loc[(earnings_hist['column_of_interest']!= report_date_of_interest)]
        earnings_hist =  earnings_hist.loc[(earnings_hist['reportedEPS']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['estimatedEPS']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['surprise']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['surprisePercentage']!= 'None')]
        
        
        #drop the columns that don't align with the earnings_hist dataframe. This is needed to merge properly
        finhub_function = finhub_function.drop('hour',1)
        finhub_function = finhub_function.drop('symbol',1)
        
        #create common column name
        finhub_function.rename(columns = {'reportedDate':'column_of_interest'}, inplace = True)
        
        
        #concat the dataframes so that the surprise_event and earnings_event x variables can be calculated 
        earnings_hist = pd.concat([finhub_function,earnings_hist])
        
        #convert the following columns to numeric in order to do math operations
        earnings_hist["reportedEPS"] = pd.to_numeric(earnings_hist["reportedEPS"])
        earnings_hist["estimatedEPS"] = pd.to_numeric(earnings_hist["estimatedEPS"])
        earnings_hist["surprisePercentage"] = pd.to_numeric(earnings_hist["surprisePercentage"])


        #add the column that determines if current earnings were greater than last time
        earnings_hist['earnings_event'] = (earnings_hist['reportedEPS'] > earnings_hist['reportedEPS'].shift(-1)).astype(int)

        #add the column that determines if the surprise variable is positive or not
        earnings_hist['surprise_event'] = (earnings_hist['surprisePercentage'] > 0).astype(int)
        
        return earnings_hist

     
    elif date_type == '2':

        #create common column name so that the dataframes can be merged properly 
        #common name is equal to 'column_of_interest'
        earnings_hist.rename(columns = {'reportedDate':'column_of_interest'}, inplace = True)

        #filter out the nones, of which can be found in the following columns:

        #the first row will always be none because it is a future date or the current report date
        #this api does not update in real time
        earnings_hist =  earnings_hist.loc[(earnings_hist['reportedEPS']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['estimatedEPS']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['surprise']!= 'None')]
        earnings_hist =  earnings_hist.loc[(earnings_hist['surprisePercentage']!= 'None')]
        
        #convert the following columns to numeric in order to do math operations
        earnings_hist["reportedEPS"] = pd.to_numeric(earnings_hist["reportedEPS"])
        earnings_hist["estimatedEPS"] = pd.to_numeric(earnings_hist["estimatedEPS"])
        earnings_hist["surprisePercentage"] = pd.to_numeric(earnings_hist["surprisePercentage"])


        #add the column that determines if current earnings were greater than last time
        earnings_hist['earnings_event'] = (earnings_hist['reportedEPS'] > earnings_hist['reportedEPS'].shift(-1)).astype(int)

        #add the column that determines if the surprise variable is positive or not
        earnings_hist['surprise_event'] = (earnings_hist['surprisePercentage'] > 0).astype(int)
        
        return earnings_hist


    else:
        print('Invalid input. Please Try Again')

### 4. Creating the dailyAdjustedPriceTransformer Function

In [5]:
#this function takes in the daily adjusted dataframe, individual earnings dataframe, and the spy dataframe 
#it calculates 2 x variables and returns a new merged dataframe that will be merged one final time in the next function

def dailyAdustedPriceTransformer(hp,individual_earnings,spy):
    
    #editing dataframes via renaming columns and removing unnessary columns:

    #before joining the 3 dataframes, there needs to be a common column name
    #change the name of the date columns to column_of_interest
    
    historical_prices = hp.copy(deep=True)
    
    #change the name
    historical_prices.rename(columns = {'trading_date':'column_of_interest'}, inplace = True)


    #historical_prices dataframe editting:
    #in historical_prices, change the column name of '5. adjusted close' to 'stock_adjusted_close'
    historical_prices.rename(columns = {'5. adjusted close':'stock_adjusted_close'}, inplace = True)

    #in historical_prices, change the column name of 'Intraday_Returns' to 'stock_intraday_returns'
    historical_prices.rename(columns = {'Intraday_Returns':'stock_intraday_returns'}, inplace = True)

    #in historical_prices, change the column name of 'Weekly_Median_Return' to 'stock_weekly_median_return'
    historical_prices.rename(columns = {'Weekly_Median_Return':'stock_weekly_median_return'}, inplace = True)
    
    #code below is used to calculate the intraday_event and adjusted_price_event variables:
    
    
    #use the 'column_of_interest' of the individual earnings dataframe 
    reported_dates_list = individual_earnings['column_of_interest'].tolist()
    
    #this line filters out all the dates that are not a previous reporting date
    historical_prices = historical_prices.loc[historical_prices['column_of_interest'].isin(reported_dates_list)]

    #add the column that determines if the intraday return of the earnings release date is larger than that of the median
    historical_prices['intraday_event'] = (historical_prices['stock_intraday_returns'] > historical_prices['stock_weekly_median_return']).astype(int)

    #add the column that determines if the adjusted share price is larger than that of last earnings call
    historical_prices['adjusted_price_event'] = (historical_prices['stock_adjusted_close'] > historical_prices['stock_adjusted_close'].shift(-1)).astype(int)


    #spy dataframe editting:

    #change name
    spy.rename(columns = {'trading_date':'column_of_interest'}, inplace = True)
    #in spy, change the column name '5. adjusted close' to 'stock_adjusted_close'
    spy.rename(columns = {'5. adjusted close':'spy_adjusted_close'}, inplace = True)

    #in spy, change the column name 'Intraday_Returns' to 'stock_adjusted_close'
    spy.rename(columns = {'Intraday_Returns':'spy_intraday_returns'}, inplace = True)

    #in historical_prices, change the column name of 'Weekly_Median_Return' to 'spy_weekly_median_return'
    spy.rename(columns = {'Weekly_Median_Return':'spy_weekly_median_return'}, inplace = True)
    
    #add the column that determines if the intraday return of the earnings release date is larger than that of the median
    spy['spy_event'] = (spy['spy_intraday_returns'] > spy['spy_weekly_median_return']).astype(int)
    
    #add the spy intraday so that the analyst can see how the variables were created
    historical_prices['spy_intraday_returns'] = spy['spy_intraday_returns']
    
    #add the spy median so that the analyst can see how the variables were created
    historical_prices['spy_weekly_median_return'] = spy['spy_weekly_median_return']
        
    #add the spy median so that the analyst can see how the variables were created
    historical_prices['spy_adjusted_close'] = spy['spy_adjusted_close']
        
    #now put the values of spy dataframe into the  hist prices
    historical_prices['spy_event'] = spy['spy_event']
    
    
    #display the new dataframe with the 3 variables
    return(historical_prices)

### 5. Creating the finalTransformation Function

In [100]:
#merges the dataframes and returns the clean variables

def finalTransformation(individual_hist_earn,both_dailyAdjustedPrices,daily_prices,output_type,date_type):
    
    #merge cells
    inner_merged_master = individual_hist_earn.merge(both_dailyAdjustedPrices,on='column_of_interest')
    print()
#     print('inner merged function')
#     display(inner_merged_master)
    #add the class variable:

    #this variable holds all the daily adjusted values for a particular stock, not just values that pertain to date of interest
    master_daily_adjusted = daily_prices.copy(deep=True)
        
    #change the name
    master_daily_adjusted.rename(columns={'trading_date':'column_of_interest'},inplace=True)

    #create list to reference
    reported_dates_list = inner_merged_master['column_of_interest'].tolist()
    
    #master_hist is the dataframe that only includes the dates that match up with the dates that earnings are reported
    master_hist = master_daily_adjusted.loc[master_daily_adjusted['column_of_interest'].isin(reported_dates_list)]
    
    
    #if the current date is the reported earnings date then remove the first row of the master_hist because it will appear there
    if date_type == '1':
        #remove the first row
        master_hist = master_hist.iloc[1:,:]
    
    else:
        master_hist = master_hist
        
    
    
    #notice how the dates in the column_of_interest are one day after the reported earnings date
    #store the index values from the list. This will tell us the index where the earnings reported date is located at
    row_index_list = master_hist.index.tolist()


    #alter the values of the elements in the list so that element = element -1
    #this will give us the value of the index pertaining to returns one trading day following reported release
    #the way the dataframe is filtered is by most recent date to the most future date

    for i in range( len(row_index_list)):
        row_index_list[i] = row_index_list[i] - 1


    #lock the dataframe so that only the row indexes from the list come up
    master_daily_adjusted = master_daily_adjusted.loc[row_index_list,:]

    #display the master_daily_adjusted 
#     print('This dataframe contains the price information associated with the date that is one trading day after the reported earnings date:\n')
#     display(master_daily_adjusted.head(15))

    #rename the column so that the analyst knows what this value is. It's the price of the stock one full trading day after earnings have been released
    master_daily_adjusted.rename(columns = {'5. adjusted close':'after_report_adjusted_price'},inplace=True)
    
    print()
#     print('master daily adjsuted')
#     display(master_daily_adjusted)
    
    #up to this point, the after_report_adjusted_price column exists
    #store the values of the after_report_adjusted_price in a list to 
    reported_adjusted_close_prices = master_daily_adjusted['after_report_adjusted_price'].tolist()
    
    if date_type == '1':
        
        #since the first row was deleted, a value needs to be inserted to keep the lengths of the arrays the same
        #put the value zero in the first position of the list
        reported_adjusted_close_prices.insert(0,0)

    else:
        reported_adjusted_close_prices = reported_adjusted_close_prices



    #add the values from the list to a new column in the inner master df
    inner_merged_master['after_report_adjusted_price'] = reported_adjusted_close_prices

    #calculate the adjusted price in a new column
    inner_merged_master['return_pct_difference'] = round((inner_merged_master['after_report_adjusted_price']/inner_merged_master['stock_adjusted_close']-1)*100,2)

    #calculate the class variable
    inner_merged_master['class_variable'] = ((inner_merged_master['return_pct_difference'] >= 1) & (inner_merged_master['return_pct_difference'] <= 5) ).astype(int)
    
    #display inner_merged
#     print('This dataframe contains all the variables associated with building the model:\n')
#     display(inner_merged_master)

    #keep relevant columns:
    
    #relevant columns
    model_variables = ['earnings_event','surprise_event','adjusted_price_event','intraday_event','spy_event','class_variable']

    #filter the dataframe
    training_data = inner_merged_master[model_variables]        

    
    #this is the logical display of how the variables were created
    if output_type  == '1':
         
        #display the following dataframe
        #relevant columns
        relevantColumns = ['column_of_interest','reportedEPS','estimatedEPS','surprise','surprisePercentage','stock_adjusted_close','stock_intraday_returns','stock_weekly_median_return','spy_adjusted_close','spy_intraday_returns','spy_weekly_median_return','after_report_adjusted_price','return_pct_difference','earnings_event','surprise_event','adjusted_price_event','intraday_event','spy_event','class_variable']
        
        #filter the dataframe
        logical_dataframe = inner_merged_master[relevantColumns]
        
        #display
        print('This is the dataframe with the columns that were used to construct the variables of the model:\n')
        display(logical_dataframe)

            
#     #this returns the clean variables, ready to be analyzed
#     elif output_type  == '2':
#         print()
#         print('Clean Variables:\n')
#         display()
        
        

#     else:
#         print('Invalid Input. Please try again.')
   

    return training_data

### 6. Creating the naiveBayesPredictor Function

In [96]:
#create the function to peform the analysis
#most import input of this function are the clean variables created in the variableTransformer function that holds the clean variables
#this holds the dataframe that will be broken down into train and test data

def naiveBayesPredictor(cleanVariables,dateType):
    
    #import the tools
    from sklearn.naive_bayes import BernoulliNB

    #start by breaking down the data into their respective sections
    #at this point, the variableTransformer made sure there was enough data to conduct a proper analysis
    
    #break the data into x and y variables
    #for training purposes the test data will consist of full year prediction
    #the dataframe has the most recent quarters at the beginning, thus use the first 4 rows as the testing data
    
    #if the current date is the earnings report date
    if dateType == '1':
            
        #the train variables will be the actual results of one year prior
        x_train_variables = cleanVariables.iloc[5:,0:5]

        y_train_variables = cleanVariables.iloc[5:,5]

        #the first row contains the data for the prediction that is going to be used for the buy or not buy signal
        x_prediction_set = cleanVariables.iloc[0:1,0:5]
        
        #test the model on a full year worth of data (most recent year)
        x_test_variables = cleanVariables.iloc[1:5,0:5]
        y_test_variables = cleanVariables.iloc[1:5,5]
    
    #if the current date is not the same as earnings report date  
    elif dateType == '2':
        
        #the train variables will be the actual results of one year prior
        x_train_variables = cleanVariables.iloc[4:,0:5]
        y_train_variables = cleanVariables.iloc[4:,5]

        #test the model on a full year worth of data (most recent year)
        x_test_variables = cleanVariables.iloc[0:4,0:5]
        y_test_variables = cleanVariables.iloc[0:4,5]
    
    #create an instance of the model
    naive_bayes_model = BernoulliNB(binarize=0.0)
    
    #fit the training variables to the model model
    naive_bayes_model.fit(x_train_variables, y_train_variables)
    
    #make predictions with the model
    predictions = naive_bayes_model.predict(x_test_variables)
    
    #import the metric tools
    from sklearn.metrics import multilabel_confusion_matrix
    from sklearn.metrics import classification_report
    
    #create an instance where the confusion matrix will live
    multi_cm = multilabel_confusion_matrix(y_test_variables, predictions)

    #first row
    tp = multi_cm[0][0][0]
    fp = multi_cm[0][0][1]

    #second row
    fn = multi_cm[0][1][0]
    tn = multi_cm[0][1][1]

    #get the relevant metrics from the classification report
    cr = classification_report(y_test_variables, predictions,output_dict=True,zero_division=1)
    precision = cr['weighted avg']['precision'] 
    recall = cr['weighted avg']['recall'] 
    f1_score = cr['weighted avg']['f1-score'] 

    #score the model
    model_score = round(naive_bayes_model.score(x_test_variables,y_test_variables)*100,2)
        
    #both models need to be evaluated for their performance:
    
    #create the point at which one could deem this model accurate
    bench_mark_precision_WA = 0.75

    #if the models precisionWA is greater than or equal to the bench_mark_precision_WA then recommend the analyst use the model
    if precision >= bench_mark_precision_WA:
        model_recommendation = 'Valid'

    #if precision wa is less than the benchmark, the model should NOT be used to make any buying decisions
    else:
        model_recommendation = 'Invalid'
    
    
    #buy or not buy signal:
    if dateType == '1':
    
        #give the analyst a prediction
        signal = naive_bayes_model.predict(x_prediction_set)
        
        print()
        print('This is the buy signal:')
        
        #create a prediction variable
        predicition_value = signal[0] 
        
        if predicition_value == 0:
            buy_signal = 'Do NOT buy'

        
        #if the prediciton value is not equal to zero then it is equal to one, thus signaling a buying opportunity
        else:
            #assign the buy value to the variable
            buy_signal = 'Buy'

        
        #add the buy signal to the dictionary
        confusion_matrix_values = {'TP':[tp],'FP':[fp],'FN':[fn],'TN':[tn],'Precision WA':[precision],'Recall WA':[recall],'F1-Score WA':[f1_score],'Model Score %':[model_score],'Model Recommendation':[model_recommendation],'Buy Signal':[buy_signal]}
        
        return (confusion_matrix_values)

    #if datetype is not equal to 1 it is equal to 2 which means that the results will be the model accuracy and model recommendations
    else:
        #create the dictionary that will store the relevant values (buy signal is excluded because there isnt one to give)
        confusion_matrix_values = {'TP':[tp],'FP':[fp],'FN':[fn],'TN':[tn],'Precision WA':[precision],'Recall WA':[recall],'F1-Score WA':[f1_score],'Model Score %':[model_score],'Model Recommendation':[model_recommendation]}

#         print('This is the confusion matrix:')
#         print(confusion_matrix_values)

        #return confusion_matrix_values
        return (confusion_matrix_values)

### 7. Creating the User Interface Main Function

In [138]:
#revised main function
def main():
    
    #will help display the dataframes
    from IPython.display import display
    import pandas as pd
       
    #to ensure the model is only ran once at time, a 60 second timer will be placed in the main function
    import time
    
    #model trigger (model turns off if equal to false)
    modelValidation = True
    
    #add a print statement at the bottom to signal that the model has ended
    while  modelValidation == True:
                
        #there needs to be a tracker for how many calls have been used and when 
        total_api_calls = 0

        from datetime import datetime

        #ask for the API key
        api_q = input('What is your alphavantage API Key?:\n\n')
        api_q = 'TQ6TR98HVUPE3L9Z'
        print()

        #ask the data type
        data_type_q = input('What kind of data are you looking for?\n\nType the number in the input box:\n\n1. Upcoming Earnings Calendar (3 month horizon | Displays 15 max)\n2. Historical Earnings (last 5 earning reports for a specific company)\n3. Daily Adjusted Price History (displays 15 trading dates for a specific company)\n4. Naive Bayes Prediction Model\n\n')

    
        if data_type_q == '1':

            print()
            date_of_interest = input('Pick a date that is within the next three months (yyyy-mm-dd):\n')
            print()

            #make the symbol equal to n/a because the function requires the parameter to be defined before performing what it needs to do
            symbol = 'N/A'

            #this function pulls the upcoming earnings calendar
            alphaEarningsCalendar  = alphaDataRetriever(api_q,data_type_q,symbol,date_of_interest)
            
            #api is called in the alphaEarningsCalendar 
            total_api_calls = total_api_calls + 1 

            print('Total API Calls: %i'%(total_api_calls))
            print()


            #if the dataframe does not contain any rows, that means its empty and no company is reporting earnings
            if alphaEarningsCalendar.shape[0] == 0:
                print('No publicly traded company is reporting their earnings on %s'%(date_of_interest))
                print('Please wait 60 seconds before running the model.')
#                 time.sleep(60)
                modelValidation = False

            else:

                #for some reason, if you put return dataframe, the function will not spit out the dataframe - use display instead
                #display
                display(alphaEarningsCalendar.head(15))

                print()
                
                
                #print disclaimers
                print('This is not investment advice.')
                print('Please wait 60 seconds before running the model again.')
                
                #sleep the model
#                 time.sleep(60)
                modelValidation = False
         
        #input 2 refers to the historical earnings table for a specific stock; it requires an api key and ticker symbol
        elif data_type_q == '2':
            print()
            symbol_q = input('Enter the ticker symbol:\n\n')
            print()
            
            #date_of_interest is not relevant when just pulling data
            date_of_interest = 'N/A'
      
            #this runs the historical earnings report for the symbol specified
            alphaHistoricalEarnings  = alphaDataRetriever(api_q,data_type_q,symbol_q,date_of_interest)
            
            #api is called in alphaHistoricalEarnings
            total_api_calls = total_api_calls + 1 
            
            #display first then sleep so that the analyst can look at something in the meantime
            display(alphaHistoricalEarnings.head(5))
            print()
            #print disclaimers
            print('This is not investment advice.')
            print('Please wait 60 seconds before running the model again.')
            
            print('Total API Calls: %i'%(total_api_calls))

            #sleep the model
            time.sleep(60)
            
            modelValidation = False
    
        #input 3 refers to the daily adjusted price table for a specific stock; it requires an api key and ticker symbol
        elif data_type_q == '3':
            
            #ask the analyst what ticker they want
            print()
            symbol_q = input('Enter the ticker symbol:\n\n')
            print()
            
            #date_of_interest is not relevant when just pulling data because this function pulls most recent data
            date_of_interest = 'N/A'
            
            #runs the function that pulls daily adjusted prices for a specific stock
            alphaDailyAdjusted  = alphaDataRetriever(api_q,data_type_q,symbol_q,date_of_interest)
            
            #api is called
            total_api_calls = total_api_calls + 1 
            
            #display first then sleep so that the analyst can look at something in the meantime
            display(alphaDailyAdjusted.head(15))
            print()

            #disclaimer
            print('This is not investment advice.')
            print('Please wait 60 seconds before running the model again.')
            print()
            
            #print the total calls, this should be 1
            print('Total API Calls: %i'%(total_api_calls))
            print()
            

            #sleep the model
            time.sleep(60)
            
            modelValidation = False

################################################################################################################################################################################################################################################        
        #naive bayes prediction option
        elif data_type_q == '4':
            
            import math         
            print()
            
            #ask the analyst what data the model should do analysis on
            analysis_type = input('What type of analysis are you looking to do?:\n\n1.Individual Company\n\n2.Multi-Company\n\n')

            print()
            
            
            #the model must know whe 
            date_of_interest = input('Enter the date of interest:\n\n')
            print()
            
            #individual stock analysis
            if analysis_type == '1':

                #ask what stock they want analyzed
                ticker = input('Enter the ticker symbol:\n\n')
                print()

                #the historical earnings should be pulled first to see if the analysis can be done
                #switch the value of data_type_q to 2 so that the historical earnings table can be pulled via alphaDataRetriever
                data_type_q = '2'
                
                try:
                    
                    #run the alphaDataretriever to get the historical earnings for each symbol in the list
                    alphaHistoricalEarnings  = alphaDataRetriever(api_q,data_type_q,ticker,date_of_interest)
                    print()
#                     print('This dataframe contains %s\'s historical earnings report. The row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the most upcoming earnings report date (if the date is in the future)'%(ticker))
#                     display(alphaHistoricalEarnings)
            
                except:
                    print('Function Broke. Check your inputs.')
                    #turn the model off
                    modelValidation = False
                #count the call
                total_api_calls = total_api_calls + 1


                #check to see if the company chosen has enough data to run a proper analysis on
                #the model should have at least 3 years worth of quarterly reports so that 2 years (8 quarters) can be used to train the model and 1 year (4 quarters) can be used to test
                if alphaHistoricalEarnings.shape[0] >= 12:
                    print(ticker,'has reported earnings',alphaHistoricalEarnings.shape[0],'times, as of the current date.')

                    #change the value of data_type_q to 3 to call the adjusted price function
                    data_type_q = '3'

                    #run the function that gets the daily adjusted prices for the ticker symbol in the loop
                    alphaDailyAdjusted  = alphaDataRetriever(api_q,data_type_q,ticker,date_of_interest)
                    
#                     print('This dataframe contains %s\'s 5,000 most recent daily adjusted prices:\n '%(ticker))
#                     display(alphaDailyAdjusted.head(15))

                    #count the call
                    total_api_calls = total_api_calls + 1

                    #change value of symbol so that the function can pull daily prices for SPY
                    symbol = 'SPY'

                    #the symbol here SPY will be constant and won't change
                    alphaSPY  = alphaDataRetriever(api_q,data_type_q,symbol,date_of_interest)
                    print()
#                     print('This dataframe contains SPY\'s most 5,000 most recent daily adjusted prices:\n')
#                     print(alphaSPY.head(15))

                    #this is the second call, but the SPY wont be called again for the remaining of the analysis
                    total_api_calls = total_api_calls + 1 
                
                
                    #the most recent date will be located in this cell
                    most_recent_date = alphaHistoricalEarnings.iloc[0,0]
                    #print the most recent earnings date (aka the first cell value of first row)
                    print('%s\'s most recent/upcoming reporting date is:\n'%(ticker))
                    print(most_recent_date)
#                     print()
                    #alphaHistoricalEarnings will return an earnings history report that includes the most upcoming earnings date
                    #if the date in the most upcoming earnings date happens to be the same as today and the time is after 4:01 (market close) then do the following:
                    from datetime import datetime 
                    #current time instance that is number based
                    current_time_1 = datetime.now()
                    
                    #current time instance that is string based
                    current_time = str(datetime.now())

                    #split the result into a list that seperated by the date and time
                    current_time_list = current_time.split(' ')

                    #date element yyyy-mm-dd
                    current_date = current_time_list[0]
                                    
#                     print('This is the current date',current_date)
                    #calculate this so that the model knows if the market has closed (after 4 PM)
                    current_hour = current_time_1.hour
#                     print('Time',current_hour)
                    #if the most recent date in the historical earnings dataframe is equal to today's date and the market has closed then change the date_type and call the finhub function that has the most updated earnings information :
                    if most_recent_date == current_date and current_hour >= 16:
#                         print('test')
                        
                        date_type = '1'
                        
                        #ask the analyst for thier finhub api key
                        print()
                        
                        finhubapi = input('Enter your finhub API-Key:\n\n') 
                        print()
                                                
                        #ticker should be equal to empty space to get the most updated data point
                        ticker = ticker
                        #call the finhub function that will be used to create buying signals
                        finhub_function = finhubEarningsCalendar(finhubapi, date_of_interest,date_of_interest,ticker)
                        
                        #display
                        print()
                        print('This is %s\'s most updated earnings report:\n'%(ticker))
                        display(finhub_function)
                            
                        
                    
                    #if it is not the current date AND the market has not closed, then switch the date_type and assign the finhub function to 'N/A' because it's not needed
                    else:
                        date_type = '2'
                        finhub_function = 'N/A'    
    
    
                    #call the historicalEarningsTransformer to calculate the first 2 variables
                    historical_earnings_main = historicalEarningsTransformer(date_type,alphaHistoricalEarnings,finhub_function)
                    
                    #display
                    print()
#                     print('This is %s\'s most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:\n'%(ticker))
#                     display(historical_earnings_main.head(15)) 

                    #this runs the first part of the model where the variables are transformed only if the api call count is within the 5 call limit
                    dailyAdustedPriceTransformer_main = dailyAdustedPriceTransformer(alphaDailyAdjusted,historical_earnings_main,alphaSPY)
                            
                    #display
#                     print()
#                     print('This is %s\'s most updated dataframe that contains the three price-oriented variables (intraday_event, adjusted_price_event, spy_event) that will be used in the analysis:\n'%(ticker))
#                     display(dailyAdustedPriceTransformer_main.head(15)) 
                    
#                     print()
                    #call the finalTransformation function that will get all the x and y variables ready
                    output_type = input('What type of output would you like?:\n\nLogic will display how the model variables were created, while Clean will provides results:\n\n 1.Logic\n\n 2.Clean\n\n')
                    print()
                    
                    #if the user picks logic
                    if output_type == '1':
                        #print the displays down to the order:
                        
                        #first run the historical earnings report for the stock 
                        print('1. Retrieve the historical earnings report for the stock:\n')
                        print('This dataframe contains %s\'s historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)'%(ticker))
                        display(alphaHistoricalEarnings.head(15))
                        print()
                        
                        #secondly
                        print('2. Insert the historical earnings report into the historicalEarningsTransformer function:\n')
                        print('This is %s\'s most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:\n'%(ticker))
                        display(historical_earnings_main.head(15))
                        print()
                        
                        #thirdly
                        print('3. Retrieve the last 5,000 daily adjusted prices for %s in order to create the intraday_event and adjusted_price_event variables:\n'%(ticker))
                        display(alphaDailyAdjusted.head(15))
                        print()
                        
                        #fourth
                        print('4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:\n')
                        display(alphaSPY.head(15))
                        print()
                        
                        #fifth
                        print('5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:\n')
                        display(dailyAdustedPriceTransformer_main.head(15))
                        print()
                        
                        #sixth
                        print('6. Run the final tranformer function to generate the class variable:\n')
                        print()
  
                        
                        
                    
                    #parameters include : individual_hist_earn,both_dailyAdjustedPrices,daily_prices,output_type
                    finTransformationTransformer_main = finalTransformation(historical_earnings_main,dailyAdustedPriceTransformer_main,alphaDailyAdjusted,output_type,date_type)
#                     print()
#                     print('This is the dataframe that contains all the clean variables necessary for analysis:')
#                     display(finTransformationTransformer_main.head(15))
                    
                    #run the model by calling the naivebayesPredictor function (returns a dictionary):
                    model_output = naiveBayesPredictor(finTransformationTransformer_main,date_type)

                    #convert the dictionary into a readable dataframe:
                    individual_analysis_results = pd.DataFrame.from_dict(model_output)
                    
                    #display the pretty dataframe
                    print()
                    print('Result dataframe:\n')
                    display(individual_analysis_results)
                    
                    #say bye
                    print('Thank you for using the model.')
                    print('Please wait 60 seconds before running the model again.')

                    #sleep the model
                    #time.sleep(60)
                
                    #turn model off
                    modelValidation = False
                
                #if the rows are less than 12 and not equal to 0 then:
                else:
                    
                    #print diagnosis
                    print('Company does not have enough reported earnings history to conduct a proper naive bayes prediction analysis.')
                    print('Please wait 60 seconds before running the model again.')

                    #sleep the model
#                     time.sleep(60)
                    
                    #turn the model off since the naive bayes cannot be done
                    modelValidation = False

#code works up to this point. Below is the multi-company analysis                    
############################################################################################################################
      
            #if the analysis type is not 1 then it is equal to 2 which refers to the multi-company analysis
            else:
                
                #big assumption: date_of_interest can only be the current date or plus three months because a past date will break the model
                #if the date of interest is equal to today and the time is after market close, then the model will assume that it's go time
                #if the date of interest is equal to today but the time is before market close, then the model will just give back model results
                #if the date of interest is not equal to today, then it has to be 
                
                #call the finalTransformation function that will get all the x and y variables ready
                output_type = input('What type of output would you like?:\n\nLogic will display how the model variables were created, while Clean Variables will display results:\n\n 1.Logic\n\n 2.Clean\n\n')
#                 print()
                
                

                from datetime import datetime 
                #current time instance that is number based
                current_time_1 = datetime.now()

                #current time instance that is string based
                current_time = str(datetime.now())

                #split the result into a list that seperated by the date and time
                current_time_list = current_time.split(' ')

                #date element yyyy-mm-dd
                current_date = current_time_list[0]

#                     print('This is the current date',current_date)
                #calculate this so that the model knows if the market has closed (after 4 PM)
                current_hour = current_time_1.hour

################################################################################################################################################################################################################################################################                
                #if the date of interest is the same as the current date and the market is closed, then run the finhub function
                #finhub is the most updated API and it will have the actual companies that reported earnings
                #the earnings calendar gives estimates of when the stock is going to report earnings and when they are wrong, finhub is used fill in the gap as a discrepancy check
                if date_of_interest == current_date and current_hour >= 16:
                                       
#                     print('test')
                    #change the data_type because the model is in its prime time mode, ready to make a prediciton for the next trading date
                    date_type = '1'

                    #ask the analyst for thier finhub api key
                    print()
                    finhubapi = input('Enter your finhub API-Key:\n\n') 

                    #empty space as the value for ticker will return all the stocks that reported earnings on that date
                    ticker = ''

                    #call the finhub function that will be used to create buying signals
                    finhub_function = finhubEarningsCalendar(finhubapi, date_of_interest,date_of_interest,ticker)

                    #debug
                    print()
                    print('Below is the list of companies that reported earnings (15 Max)')
                    print()
                    display(finhub_function.head(15))

                    #loop through the symbol column so that the model knows what stocks to analyze and give a buy signal to
                    #create the list of symbols that will be used in the for loop
                    list_of_ticker_symbols =  finhub_function.symbol.tolist()
                        

#                         #get the length of the list to determine how many stocks are in your dataset
#                         stock_count = len(list_of_ticker_symbols)    
                        
#                         #print stock count
#                         print('Stock Count:\n',stock_count)

#                         #for a naive bayes analyis, each stock will need its earnings history and daily adjusted prices 
#                         stock_api_calls = stock_count * 3

#                         #5 api calls per minute
#                         api_calls_per_minute = 5

#                         #how many sets of 5 api calls/min need to be done in order to do an analysis on all of the stocks
#                         #this will round up to the nearest integer
#                         #this essentially how long (in minutes) the model will take to run an analysis on all of the stocks on the earnings calendar for the specified date
#                         api_sets  = math.ceil(stock_api_calls / api_calls_per_minute)
                        
################################################################################################################################################################################################################################################################
                #if it is not the current date AND the market has not closed, then switch the date_type and assign the finhub function to 'N/A' because it's not needed                
                #model results, NO buy signal
                #different thought process here
                else:
                    
                    #not go time
                    date_type = '2'
                    finhub_function = 'N/A'    
                    
                    #code for the earnings calendar
                    data_type_q = '1'
                    
                    #change symbol value
                    symbol = ''
                    
                    #run the alphaDataRetriever to get the earnings calendar 
                    alphaEarningsCalendar  = alphaDataRetriever(api_q,data_type_q,symbol,date_of_interest)
#                     print('This is the alpha earnings calendar:\n')
#                     print('Symbol: ',symbol)
#                     print('Date of Interest: ',date_of_interest)
#                     print('Data Type: ',data_type_q)
#                     print()
#                     display(alphaEarningsCalendar)
                    
                    print()
                    print('Model is sleeping so that it can reset')
                    #sleep model so that the count resets
                    time.sleep(60)
                    
                    #reference the list from the alpha earnings calendar
                    list_of_ticker_symbols = alphaEarningsCalendar.symbol.tolist()
#                     print('List of Stocks from the alphaEarningsCalendar: ',list_of_ticker_symbols)
################################################################################################################################################################################################################################################################                      
                #Calculate the api information:        
                        
                #get the length of the list to determine how many stocks are in your dataset
                stock_count = len(list_of_ticker_symbols)    

                #print stock count
                print()
                print('Stock Count:',stock_count)
                print()

                #for a naive bayes analyis, each stock will need its earnings history and daily adjusted prices and the SPY call
                stock_api_calls = stock_count * 3

                #5 api calls per minute
                api_calls_per_minute = 5

                #how many sets of 5 api calls/min need to be done in order to do an analysis on all of the stocks
                #this will round up to the nearest integer
                #this essentially how long (in minutes) the model will take to run an analysis on all of the stocks on the earnings calendar for the specified date
                api_sets  = math.ceil(stock_api_calls / api_calls_per_minute)        
                        

                #12 min should be the longest an analyst waits for an analysis, this equal to 30 stocks that have 3 dataframes each 
                if stock_count > 14:

                    #only get the first 30 symbols
                    list_of_ticker_symbols = list_of_ticker_symbols[0:15]
                    
                    #15 stocks * 3 dataframes = 45
                    stock_api_calls = 15 * 3
                    
                    #api_sets are set to 9 mintutes
                    api_sets  = math.ceil(stock_api_calls / api_calls_per_minute)  
                
                    #user experience
                    print('There are %i companies reporting earings on the specified date. Analysis will only be provided for the first 15 companies in the list. This should take about %i minutes. Please wait patiently.'%(stock_count,api_sets))

                
                
                #if there is 15 or less stocks in the list, keep the symbol list the same
                else:
                    #keep the same
                    list_of_ticker_symbols = list_of_ticker_symbols
                    stock_api_calls = stock_api_calls
                                    
                    #tell the analyst how long the analysis is going to take
                    print('The model will take about %i minutes to run. Please wait patiently.'%(api_sets))



                print()
                #list of symbols stay the same
                list_of_ticker_symbols  = list_of_ticker_symbols

                #stock_api_calls stay the same
                stock_api_calls = stock_api_calls 
                print()
                print('There are a total of %i stock calls'%(stock_api_calls))
################################################################################################################################################################################################################
                #for loop begins here:
                #this list will contain the confusion matrix for each stock in the for loop
                #list of dictionaries
                model_result_list = []

                #for each ticker in the list of symbols, run each ticker through the functions
                for ticker in list_of_ticker_symbols:

#                     print()
#                     print('This is the stock_api_call at each loop:')
#                     print()
#                     print(stock_api_calls)
#                     print()
#                     print('This is the ticker:')
#                     print()
#                     print(ticker)
#                     print()


                    #change value of data_type_q so that the function can pull daily prices for SPY
                    data_type_q = '3'
#                     print(date_of_interest)
                    #the symbol here SPY will be constant and won't change
                    alphaSPY  = alphaDataRetriever(api_q,data_type_q,'SPY',date_of_interest)
#                     print()
#                     print('This is the alphaSPY')
#                     display(alphaSPY.head(15))

                    #this is the second call
                    total_api_calls = total_api_calls + 1 

#                     #subtract the call from the stock count
#                     stock_api_calls = stock_api_calls - 1


                    if total_api_calls == api_calls_per_minute:
                        total_api_calls = 0
                        print('Model has been put to sleep after the alpha spy')
                        time.sleep(60)

                    else:
                        total_api_calls = total_api_calls


                    #assign symbol the same value as ticker so that the tickers in the column are inputted into the historical earnings function
                    symbol = ticker    

                    #switch the value of data_type_q to 2 so that the historical earnings table can be pulled via alphaDataRetriever
                    data_type_q = '2'

                    #run the alphaDataretriever to get the historical earnings for each symbol in the list

                    try:
#                         print(symbol)
#                         print()
                        alphaHistoricalEarnings  = alphaDataRetriever(api_q,data_type_q,symbol,date_of_interest)
#                         print()
#                         print('This is the historical earnings dataframe')
#                         display(alphaHistoricalEarnings)
                    except:
#                         print()
                        print(ticker)
                        print('An error has occured in the historical earnings function. Check inputs.')
                        #skip to the next ticker and run analysis on it
                        print('This will fuck up the rest of the functions')
#                         total_api_calls = total_api_calls -1
                        
                        continue
        
                    

                    #the historical earnings are called 
                    total_api_calls = total_api_calls + 1

#                     #subtract the call from the stock count
#                     stock_api_calls = stock_api_calls - 1


                    #if the total api calls are 5 then a full set has been completed and it can be subtracted from the total sets needed to gather the information
                    if total_api_calls == api_calls_per_minute:

                        #reset the number of total api calls
                        total_api_calls = 0
#                         print()
                        print('Model has been put to sleep after historical earnings call')
                        #sleep the model because an additional api call will break the model
                        time.sleep(60)

                    #if the total api calls isn't equal to 5 then keep the value the same
                    else:

                        total_api_calls = total_api_calls 
################################################################################################################################################################################################################
                    #this section analyzes the stock only if there is enough training data available
    
                    #still within the for loop
                    #the model should have at least 3 years worth of quarterly reports so that 2 years (8 quarters) can be used to train the model and 1 year (4 quarters) can be used to test
                    #if the model has 12 or more instances, then conduct the analysis and provide a buying signal
                    if alphaHistoricalEarnings.shape[0] >= 12:
#                         print(symbol,'has reported earnings',alphaHistoricalEarnings.shape[0],'times, as of the current date.')
#                         print()

                        #change the value of data_type_q to 3 to call the adjusted price function
                        data_type_q = '3'

                        #run the function that gets the daily adjusted prices for the ticker symbol in the loop
                        try:
#                             print('This is the daily adjusted dataframe:')
#                             print('Symbol: ',symbol)
#                             print('Date of Interest: ',date_of_interest)
#                             print('Daily Adjusted Dataframe:\n')
                            
                            alphaDailyAdjusted  = alphaDataRetriever(api_q,data_type_q,symbol,date_of_interest)
#                             print('This is the daily adjusted price for 
                            
#                             print()
                            
                        except:
#                             total_api_calls = total_api_calls -1
                            print('symbol:',symbol)
                            print('date_of_interest',date_of_interest)
                            print()

                    
                    
                    
                        
#                         print('An error has occured in the alphaDailyAdjusted function. Check inputs.')
                        #skip to the next ticker and run analysis on it
#                         print('skip to the next ticker and run analysis on it')
#                         continue


                        #count the call
                        total_api_calls = total_api_calls + 1

                        #subtract the set from the stock count
#                         stock_api_calls = stock_api_calls - 1


                        #if the total api calls are 5 then a full set has been completed and it can be subtracted from the total sets needed to gather the information
                        if total_api_calls == api_calls_per_minute:
                            #reset the number of total api calls
                            total_api_calls = 0
                            print()
                            print('Model has been put to sleep after the daily adjusted call')
                            #sleep the model because an additional api call will break the model
                            time.sleep(60)

                        #keep as is if the total api calls isnt equal to 5 
                        else:

                            total_api_calls = total_api_calls


                        #make sure to call the finhub_function for each stock

              

                        try:
#                             #call the finhub function that will be used to create buying signals
#                             finhub_function = finhubEarningsCalendar(finhubapi, date_of_interest,date_of_interest,ticker)
                            
                            if date_type == '1':
                                
                                #call the finhub function that will be used to create buying signals
                                finhub_function = finhubEarningsCalendar(finhubapi, date_of_interest,date_of_interest,ticker)

                                #call the historicalEarningsTransformer to calculate the first 2 variables
                                historical_earnings_main = historicalEarningsTransformer(date_type,alphaHistoricalEarnings,finhub_function)
                            
                            else:
                                #call the historicalEarningsTransformer to calculate the first 2 variables
                                historical_earnings_main = historicalEarningsTransformer(date_type,alphaHistoricalEarnings,finhub_function)
                      
                            
                            #display
                            print()
#                             print('Below is the historical main function that returns the two x variables')
#                             display(historical_earnings_main.head(15)) 
                        except:
                            print()
                            print('An error has occured in the historicalEarningsTransformer function. Check inputs.')
                            print('')
                            print('finhub api',finhubapi)
                            print()
                            print('Display historical earnings')
                            print()
                            display(alphaHistoricalEarnings.head(5))
                            print()
                            print('finhub function',finhub_function)
                            
                            #skip to the next ticker and run analysis on it
                            print('skip to the next ticker and run analysis on it')
                            
                            continue



                        try:
                            #this runs the first part of the model where the variables are transformed only if the api call count is within the 5 call limit
                            dailyAdustedPriceTransformer_main = dailyAdustedPriceTransformer(alphaDailyAdjusted,historical_earnings_main,alphaSPY)

                            #display
                            print()
#                             print('This is the dataframe with the remaining 3 variables that pertain to the earnings data')
#                             display(dailyAdustedPriceTransformer_main.head(15)) 
                        except:
                            print()
                            #skip to the next ticker and run analysis on it
                            print('skip to the next ticker and run analysis on it')
                            continue

                            print('An error has occured in the dailyAdustedPriceTransformer function. Check inputs.')


                        #call the finalTransformation function that will get all the x and y variables ready
#                             output_type = input('What type of output would you like?:\n\nLogic will display how the model variables were created, while Clean Variables will not:\n\n 1.Logic\n\n 2.Clean Variables\n\n')

#                                         output_type = '2'

                        #if the user chooses output type logic, then print the following statements before running final transformer
                        if output_type == '1':

                            #print the following statements:
                            #first run the historical earnings report for the stock 
                            print('1. Retrieve the historical earnings report for the stock:\n')
                            print('This dataframe contains %s\'s historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)'%(ticker))
                            print()
                            try:
                                display(alphaHistoricalEarnings.head(15))
                                print()
                            except:
                                print('Does not exist.')
                            #secondly
                            print('2. Insert the historical earnings report into the historicalEarningsTransformer function:\n')
                            print('This is %s\'s most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:\n'%(ticker))

                            try:
                                display(historical_earnings_main.head(15))
                                print()
                            except:
                                print('Does not exist.')

                            #thirdly
                            print('3. Retrieve the last 5,000 daily adjusted prices for %s in order to create the intraday_event and adjusted_price_event variables:\n'%(ticker))

                            try:
                                display(alphaDailyAdjusted.head(15))
                                print()
                            except:
                                print('Does not exist.')

                            #fourth

                            try:
                                print('4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:\n')
                                display(alphaSPY.head(15))
                                print()
                            except:
                                print('Does not exist.')

                            #fifth
                            try:
                                print('5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:\n')
                                display(dailyAdustedPriceTransformer_main.head(15))
                                print()
                                
                            except:
                                print('Does not exist.')

                            #sixth
                            print('6. Run the final tranformer function to generate the class variable:\n')
                            print()
                            
#                             try:
                                
#                           #see what's breaking specifically     

                            print('Run the analysis with just clean variables')
                            #parameters include : individual_hist_earn,both_dailyAdjustedPrices,daily_prices,output_type
                            finTransformationTransformer_main = finalTransformation(historical_earnings_main,dailyAdustedPriceTransformer_main,alphaDailyAdjusted,output_type,date_type)
                            display(finTransformationTransformer_main)
#                             else:
#                                 print('No variables to display.')
                                #debug
#                                 print()
#                                 print()
                            
                            
                            
                            try:
                                #run the model by calling the naivebayesPredictor function (returns a dictionary):
                                model_output = naiveBayesPredictor(finTransformationTransformer_main,date_type)

                                #add the symbol to the dictionary values 
                                model_output['symbol'] = symbol 

                                model_result_list.append(model_output)

                                #convert the dictionary into a readable dataframe:
                                individual_analysis_results = pd.DataFrame.from_dict(model_output)

                                #display the pretty dataframe
                                display(individual_analysis_results)
                            except:
                                print('No predicitive output to display.')
                                print()




                        
                        #if the output type is equal to 2 aka clean
                        else:
                            
                            try:
                                
#                                 print('Run the analysis with just clean variables')
                                #parameters include : individual_hist_earn,both_dailyAdjustedPrices,daily_prices,output_type
                                finTransformationTransformer_main = finalTransformation(historical_earnings_main,dailyAdustedPriceTransformer_main,alphaDailyAdjusted,output_type,date_type)
#                                 display(finTransformationTransformer_main.head(15))
                            except:
                                print('No variables to display.')
                                print()
                                
                                
                                
                                
                            try:
                                #run the model by calling the naivebayesPredictor function (returns a dictionary):
                                model_output = naiveBayesPredictor(finTransformationTransformer_main,date_type)

                                #add the symbol to the dictionary values 
                                model_output['symbol'] = symbol 

                                model_result_list.append(model_output)

                                #convert the dictionary into a readable dataframe:
                                individual_analysis_results = pd.DataFrame.from_dict(model_output)

                                #display the pretty dataframe
                                display(individual_analysis_results)
                            
                            except:
                                print('No predicitive output to display.')
                                print()



################################################################################################################################################################################################################
                    #if the stock does not have enough data then skip and go on to the next one
                    else:
                        print('This stock does not have enough data to conduct a proper naive bayes analysis.')

                        #if there are not enough data points for a proper analysis, that means that this stock will not pull the remaining 2 dataframes
                        #subtract the api call count by 2
#                         stock_api_calls = stock_api_calls - 2
#                         print(stock_api_calls)

                                    
                                
                                


                #at this point, the for loop has ended and the results of the multi-company analysis shoudl be displayed
                #say bye
#                 print()
#                 print(model_result_list)
                print()
                print('Model performance across all the stock in the list:\n')
                multi_analysis_results = pd.DataFrame.from_dict(model_result_list)
                display(multi_analysis_results)
                print('Thank you for using the model.')
                print('Please wait 60 seconds before running the model again.')

                #sleep the model
                time.sleep(60)

                #turn model off
                modelValidation = False     

                        
#############################################################################################################################################################################################################                        
        #this else was put here to incase the analyst put invalid option to the first question of data of interest
        else:
            
            print('Invalid input. Please run the model again.')
            #turn the model off since the user put an invalid option
            modelValidation = False
        
        print()

## Other User Options

### Naive Bayes Prediction Model (Specific Stock | Current Date | Logical Display)

In [54]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#finhub API key
#c5d5iiqad3i9ue38pn9g

#Autoliv Inc (ALV) reported earnings today before market open
#the model will provide a buying decision for ALV 
#the present date and time is Friday, 10/22/2021 at 5 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon)
2. Historical Earnings (for a specific company)
3. Daily Adjusted Price History (for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

1

Enter the date of interest:

2021-10-22

Enter the ticker symbol:

ALV


ALV has reported earnings 98 times, as of the current date.


Enter your finhub API-Key:

c5d5iiqad3i9ue38pn9g


This is ALV's most updated earnings report:

,symbol,reportedDate,hour,reportedEPS,estimatedEPS,surprise,surprisePercentage
0,ALV,2021-10-22,bmo,0.73,0.926342,-0.196342,-21.1954

What type of output would you like?:

Logic will display how the model variables were created, while Clean Variables will not:

 1.Logic

 2.Clean Variables

1

1. Retrieve the historical earnings report for the stock:

This dataframe contains ALV's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.86     None               None
1    2021-07-16         1.2        1.369   -0.169           -12.3448
2    2021-04-23        1.79        1.417    0.373            26.3232
3    2021-01-26        2.19       1.8577   0.3323            17.8877
4    2020-10-23        1.48       1.2004   0.2796            23.2922
5    2020-07-17        -1.4      -1.2537  -0.1463           -11.6695
6    2020-04-24        0.88       0.7415   0.1385            18.6784
7    2020-01-28        1.84       1.7745   0.0655             3.6912
8    2019-10-25         1.3       1.4114  -0.1114            -7.8929
9    2019-07-19        1.38       1.4293  -0.0493            -3.4492
10   2019-04-26         1.2       1.5935  -0.3935           -24.6941
11   2019-01-29        1.42       1.7136  -0.2936           -17.1335
12   2018-10-26        1.35       1.6234  -0.2734           -16.8412
13   2018-07-27        2.22       1.8812   0.3388            18.0098
14   2018-04-27        1.66       1.8256  -0.1656             -9.071

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ALV's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.73,0.926342,-0.196342,-21.1954,0,0
1,2021-07-16,1.20,1.369000,-0.169,-12.3448,0,0
2,2021-04-23,1.79,1.417000,0.373,26.3232,0,1
3,2021-01-26,2.19,1.857700,0.3323,17.8877,1,1
4,2020-10-23,1.48,1.200400,0.2796,23.2922,1,1
5,2020-07-17,-1.40,-1.253700,-0.1463,-11.6695,0,0
6,2020-04-24,0.88,0.741500,0.1385,18.6784,0,1
7,2020-01-28,1.84,1.774500,0.0655,3.6912,1,1
8,2019-10-25,1.30,1.411400,-0.1114,-7.8929,0,0
9,2019-07-19,1.38,1.429300,-0.0493,-3.4492,1,0
10,2019-04-26,1.20,1.593500,-0.3935,-24.6941,0,0
11,2019-01-29,1.42,1.713600,-0.2936,-17.1335,1,0
12,2018-10-26,1.35,1.623400,-0.2734,-16.8412,0,0
13,2018-07-27,2.22,1.881200,0.3388,18.0098,1,1
14,2018-04-27,1.66,1.825600,-0.1656,-9.0710,0,0

3. Retrieve the last 5,000 daily adjusted prices for ALV in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,96.44,96.590,92.130,92.27,92.27,1032429,0.0,1.0,-4.3239,0.5700,2021-10-22
1,94.73,95.995,94.305,95.27,95.27,533976,0.0,1.0,0.5700,1.1608,2021-10-21
2,92.65,95.780,92.520,95.11,95.11,523510,0.0,1.0,2.6552,0.0108,2021-10-20
3,95.00,95.615,94.230,94.44,94.44,522438,0.0,1.0,-0.5895,0.4281,2021-10-19
4,94.84,96.060,94.680,94.81,94.81,559014,0.0,1.0,-0.0316,0.4281,2021-10-18
5,95.62,97.100,95.140,96.73,96.73,581969,0.0,1.0,1.1608,0.4281,2021-10-15
6,93.69,95.400,93.225,95.22,95.22,307887,0.0,1.0,1.6330,0.4281,2021-10-14
7,92.98,93.990,92.520,92.99,92.99,616354,0.0,1.0,0.0108,0.7361,2021-10-13
8,93.43,94.710,93.320,93.83,93.83,536533,0.0,1.0,0.4281,0.7757,2021-10-12
9,92.69,93.770,91.760,92.56,92.56,477350,0.0,1.0,-0.1403,0.7757,2021-10-11
10,91.02,92.380,90.750,91.69,91.69,374801,0.0,1.0,0.7361,0.7757,2021-10-08
11,89.90,91.400,89.860,90.82,90.82,481677,0.0,1.0,1.0234,0.7419,2021-10-07
12,86.11,87.620,85.570,87.61,87.61,643432,0.0,1.0,1.7420,-0.1276,2021-10-06
13,86.37,87.340,85.180,87.04,87.04,499931,0.0,1.0,0.7757,-1.1075,2021-10-05
14,86.26,87.670,86.050,86.90,86.90,481212,0.0,1.0,0.7419,-1.1075,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,57525377,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,96.44,96.5900,92.13,92.27,92.270000,1032429,0.0,1.0,-4.3239,0.5700,2021-10-22,0,1,-0.0022,0.3831,453.120000,0
69,90.53,92.0655,90.23,90.44,89.790934,1163480,0.0,1.0,-0.8164,0.1438,2021-07-16,0,0,-1.3901,-0.3363,429.948932,0
127,101.55,106.1200,100.83,105.85,104.481463,831542,0.0,1.0,2.8867,-1.9429,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
188,92.19,93.2400,90.31,91.31,90.129451,1038639,0.0,1.0,-2.2351,-0.9363,2021-01-26,0,1,-1.3930,-0.8136,380.041108,0
251,85.00,86.6200,84.75,84.94,83.841808,730671,0.0,1.0,-1.3626,-1.1740,2020-10-23,0,1,-1.4416,-1.5711,340.943239,1
320,65.76,66.4800,63.71,64.51,63.675948,1215485,0.0,1.0,-3.1692,-0.8390,2020-07-17,0,1,-1.8454,-1.4895,315.940145,0
378,60.53,61.4000,58.81,60.75,59.964562,1112588,0.0,1.0,-0.9341,0.3121,2020-04-24,0,0,-1.4492,-2.5822,276.661622,1
439,77.19,79.0000,76.57,78.24,76.608606,1837960,0.0,1.0,-0.7532,-2.7802,2020-01-28,1,0,-2.2792,-2.7088,317.651107,1
502,82.36,83.3700,81.33,82.07,79.741903,801336,0.0,1.0,-3.1788,-2.0690,2019-10-25,0,1,-2.6996,-3.4732,291.648236,1
571,72.20,74.5400,71.85,71.89,69.184618,1597731,0.0,1.0,-4.1764,-3.0826,2019-07-19,0,0,-4.6669,-3.8676,286.037580,0
629,81.17,83.0100,80.29,82.57,78.737660,1375242,0.0,1.0,-2.9966,-4.7306,2019-04-26,1,1,-3.7830,-4.2355,281.049894,1
690,79.04,79.2300,76.38,77.61,73.433878,1855151,0.0,1.0,-7.0928,-4.3673,2019-01-29,0,0,-4.8149,-4.5696,251.212496,0
752,75.99,81.9500,75.99,81.77,76.803888,1888922,0.0,1.0,1.0710,-3.3310,2018-10-26,1,0,-5.4063,-5.4970,251.543523,1
816,100.19,103.2100,99.22,101.20,94.423683,1443561,0.0,1.0,-5.7554,-7.0354,2018-07-27,1,1,-6.3852,-5.5768,265.594453,0
879,142.77,143.7400,135.94,136.67,91.490381,1921032,0.0,1.0,-35.9176,-32.9935,2018-04-27,0,0,-6.2006,-6.2883,250.444441,1

6. Run the final tranformer function to generate the class variable:




This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.73,0.926342,-0.196342,-21.1954,92.270000,-4.3239,0.5700,453.120000,-0.0022,0.3831,0.000000,-100.00,0,0,1,0,0,0
1,2021-07-16,1.20,1.369000,-0.169,-12.3448,89.790934,-0.8164,0.1438,429.948932,-1.3901,-0.3363,89.939858,0.17,0,0,0,0,0,0
2,2021-04-23,1.79,1.417000,0.373,26.3232,104.481463,2.8867,-1.9429,414.023116,0.2793,-0.9025,105.261249,0.75,0,1,1,1,1,0
3,2021-01-26,2.19,1.857700,0.3323,17.8877,90.129451,-2.2351,-0.9363,380.041108,-1.3930,-0.8136,87.572937,-2.84,1,1,1,0,0,0
4,2020-10-23,1.48,1.200400,0.2796,23.2922,83.841808,-1.3626,-1.1740,340.943239,-1.4416,-1.5711,81.759089,-2.48,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,2001-11-01,0.18,0.120000,0.06,50.0000,7.390910,-53.0736,-55.3310,73.931941,-30.6455,-32.5673,7.491841,1.37,0,1,0,1,1,1
79,2001-07-26,0.31,0.420000,-0.11,-26.1905,9.624504,-51.6357,-53.8791,81.689114,-31.3883,-32.1848,9.775101,1.56,0,0,0,1,1,1
80,2000-07-20,0.54,0.590000,-0.05,-8.4746,11.083563,-54.7610,-55.5591,101.091704,-32.1532,-32.9761,11.056759,-0.24,0,0,0,1,1,0
81,2000-04-19,0.54,0.540000,0,0.0000,11.901853,-55.8209,-55.8238,95.830333,-33.6814,-34.5057,12.320086,3.51,0,0,0,1,1,1
82,2000-01-27,0.60,0.580000,0.02,3.4483,12.960878,-54.6188,-56.0555,93.668967,-33.9633,-33.7006,12.433581,-4.07,1,1,0,1,0,0

This is the dataframe that contains all the clean variables necessary for analysis:

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,1,0,0,0
1,0,0,0,0,0,0
2,0,1,1,1,1,0
3,1,1,1,0,0,0
4,1,1,1,0,1,0
5,0,0,1,0,0,1
6,0,1,0,0,1,1
7,1,1,0,1,1,0
8,0,0,1,0,1,0
9,1,0,0,0,0,0
10,0,0,1,1,1,0
11,1,0,0,0,0,1
12,0,0,0,1,1,1
13,1,1,1,1,0,0
14,0,0,0,0,1,0

This is the buy signal:

Result dataframe:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy

Thank you for using the model.
Please wait 60 seconds before running the model again.

### Naive Bayes Prediction Model (Specific Stock | Future Date | Logical Display)

In [39]:
### Naive Bayes Prediction Model (Specific Stock | Future Date | Logical Display)
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#the present date and time is Friday, 10/22/2021 at 5 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon)
2. Historical Earnings (for a specific company)
3. Daily Adjusted Price History (for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

1

Enter the date of interest:

2021-10-25

Enter the ticker symbol:

ACC


ACC has reported earnings 61 times, as of the current date.


What type of output would you like?:

Logic will display how the model variables were created, while Clean Variables will not:

 1.Logic

 2.Clean Variables

1

1. Retrieve the historical earnings report for the stock:

This dataframe contains ACC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.42       0.3731   0.0469            12.5704
1    2021-04-19        0.57       0.5518   0.0182             3.2983
2    2021-02-22        0.59       0.5382   0.0518             9.6247
3    2020-10-26        0.32       0.3028   0.0172             5.6803
4    2020-07-20        0.37       0.3639   0.0061             1.6763
5    2020-04-20         0.7        0.683    0.017              2.489
6    2020-02-18        0.72       0.7213  -0.0013            -0.1802
7    2019-10-21        0.46       0.4512   0.0088             1.9504
8    2019-07-22        0.56       0.5355   0.0245             4.5752
9    2019-04-22        0.69       0.6509   0.0391             6.0071
10   2019-02-19        0.72       0.7256  -0.0056            -0.7718
11   2018-10-22        0.44       0.4339   0.0061             1.4059
12   2018-07-23        0.52        0.527   -0.007            -1.3283
13   2018-04-23        0.62       0.6318  -0.0118            -1.8677
14   2018-02-20        0.72       0.7114   0.0086             1.2089

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ACC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.42,0.3731,0.0469,12.5704,0,1
1,2021-04-19,0.57,0.5518,0.0182,3.2983,0,1
2,2021-02-22,0.59,0.5382,0.0518,9.6247,1,1
3,2020-10-26,0.32,0.3028,0.0172,5.6803,0,1
4,2020-07-20,0.37,0.3639,0.0061,1.6763,0,1
5,2020-04-20,0.70,0.6830,0.017,2.4890,0,1
6,2020-02-18,0.72,0.7213,-0.0013,-0.1802,1,0
7,2019-10-21,0.46,0.4512,0.0088,1.9504,0,1
8,2019-07-22,0.56,0.5355,0.0245,4.5752,0,1
9,2019-04-22,0.69,0.6509,0.0391,6.0071,0,1
10,2019-02-19,0.72,0.7256,-0.0056,-0.7718,1,0
11,2018-10-22,0.44,0.4339,0.0061,1.4059,0,1
12,2018-07-23,0.52,0.5270,-0.007,-1.3283,0,0
13,2018-04-23,0.62,0.6318,-0.0118,-1.8677,0,0
14,2018-02-20,0.72,0.7114,0.0086,1.2089,1,1

3. Retrieve the last 5,000 daily adjusted prices for ACC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,51.62,51.650,51.120,51.39,51.39,300468,0.0,1.0,-0.4456,0.1363,2021-10-21
1,50.58,51.640,50.430,51.61,51.61,599514,0.0,1.0,2.0364,0.1363,2021-10-20
2,51.49,51.530,50.480,50.54,50.54,810077,0.0,1.0,-1.8450,0.3476,2021-10-19
3,51.36,51.860,51.285,51.43,51.43,315908,0.0,1.0,0.1363,0.3476,2021-10-18
4,52.16,52.400,51.420,51.62,51.62,331392,0.0,1.0,-1.0353,0.3476,2021-10-15
5,51.79,52.079,51.540,51.97,51.97,307641,0.0,1.0,0.3476,0.2387,2021-10-14
6,50.82,51.480,50.525,51.37,51.37,286670,0.0,1.0,1.0823,0.2387,2021-10-13
7,50.42,51.320,50.140,50.94,50.94,383356,0.0,1.0,1.0313,-0.4767,2021-10-12
8,50.28,50.515,50.000,50.40,50.40,302026,0.0,1.0,0.2387,-0.4767,2021-10-11
9,50.35,50.430,49.950,50.11,50.11,436758,0.0,1.0,-0.4767,1.2734,2021-10-08
10,50.96,51.130,50.290,50.48,50.48,507322,0.0,1.0,-0.9419,1.2734,2021-10-07
11,50.05,50.940,48.980,50.92,50.92,629021,0.0,1.0,1.7383,0.2406,2021-10-06
12,51.16,51.270,50.330,50.36,50.36,1288014,0.0,1.0,-1.5637,0.4864,2021-10-05
13,50.02,51.050,50.020,50.92,50.92,1009971,0.0,1.0,1.7993,0.2406,2021-10-04
14,48.69,49.600,48.110,49.31,49.31,1125864,0.0,1.0,1.2734,-0.4994,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,50.22,50.635,49.930,50.19,49.710640,1459237,0.0,1.0,-1.0143,-0.8558,2021-07-26,0,1,0.0655,0.1870,439.597714,0
130,43.92,44.340,43.490,44.30,43.431011,986167,0.0,1.0,-1.1134,-1.3521,2021-04-19,1,0,-0.9025,-0.4609,412.503091,0
169,42.77,44.525,42.550,44.32,43.450618,850522,0.0,1.0,1.5913,-2.5586,2021-02-22,1,1,-0.9845,-0.6896,383.249460,0
249,37.35,37.350,36.505,37.05,35.497625,1369707,0.0,1.0,-4.9595,-3.4484,2020-10-26,0,1,-2.1885,-1.4416,334.642622,0
318,33.94,33.940,32.900,33.62,31.782949,969687,0.0,1.0,-6.3555,-4.3922,2020-07-20,0,1,-0.9136,-1.8454,318.493435,1
381,32.95,33.580,31.650,31.70,29.520295,1363316,0.0,1.0,-10.4088,-7.4806,2020-04-20,0,0,-2.5822,-2.1624,275.312387,0
424,48.00,48.150,47.710,48.09,44.783313,491097,0.0,1.0,-6.7014,-6.2505,2020-02-18,0,0,-2.7628,-2.6561,327.212999,0
505,49.09,49.710,48.930,49.57,45.241932,555837,0.0,1.0,-7.8388,-8.0642,2019-10-21,1,1,-3.1156,-3.2931,290.091360,1
569,47.83,48.170,47.500,48.08,43.445251,636222,0.0,1.0,-9.1674,-9.9000,2019-07-22,1,1,-3.6524,-4.0247,286.740233,1
632,47.05,47.050,46.140,46.51,41.600710,730436,0.0,1.0,-11.5819,-11.3116,2019-04-22,0,1,-3.8482,-4.3017,278.042169,1
675,45.12,45.790,45.120,45.58,40.768874,1121809,0.0,1.0,-9.6435,-10.3799,2019-02-19,1,1,-4.1580,-4.4216,264.983835,1
755,40.45,40.670,39.610,39.69,34.759732,677015,0.0,1.0,-14.0674,-11.9304,2018-10-22,0,0,-5.8771,-5.4970,260.720553,0
819,41.97,42.100,41.600,41.77,36.170831,637795,0.0,1.0,-13.8174,-13.3638,2018-07-23,0,1,-5.3702,-5.6538,264.443059,1
882,38.11,38.220,37.780,37.97,32.504811,638080,0.0,1.0,-14.7079,-14.0892,2018-04-23,0,1,-6.2883,-6.1499,250.453837,0
925,36.15,36.360,35.480,35.57,30.450254,1432759,0.0,1.0,-15.7669,-13.7445,2018-02-20,0,0,-6.6368,-5.8845,253.975941,0

6. Run the final tranformer function to generate the class variable:




This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.4200,0.3731,0.0469,12.5704,49.710640,-1.0143,-0.8558,439.597714,0.0655,0.1870,50.443572,1.47,0,1,1,0,0,1
1,2021-04-19,0.5700,0.5518,0.0182,3.2983,43.431011,-1.1134,-1.3521,412.503091,-0.9025,-0.4609,43.999634,1.31,0,1,0,1,0,1
2,2021-02-22,0.5900,0.5382,0.0518,9.6247,43.450618,1.5913,-2.5586,383.249460,-0.9845,-0.6896,42.538861,-2.10,1,1,1,1,0,0
3,2020-10-26,0.3200,0.3028,0.0172,5.6803,35.497625,-4.9595,-3.4484,334.642622,-2.1885,-1.4416,36.005418,1.43,0,1,1,0,0,1
4,2020-07-20,0.3700,0.3639,0.0061,1.6763,31.782949,-6.3555,-4.3922,318.493435,-0.9136,-1.8454,31.574970,-0.65,0,1,1,0,1,0
5,2020-04-20,0.7000,0.6830,0.017,2.4890,29.520295,-10.4088,-7.4806,275.312387,-2.5822,-2.1624,28.216560,-4.42,0,1,0,0,0,0
6,2020-02-18,0.7200,0.7213,-0.0013,-0.1802,44.783313,-6.7014,-6.2505,327.212999,-2.7628,-2.6561,44.364255,-0.94,1,0,0,0,0,0
7,2019-10-21,0.4600,0.4512,0.0088,1.9504,45.241932,-7.8388,-8.0642,290.091360,-3.1156,-3.2931,46.300649,2.34,0,1,1,1,1,1
8,2019-07-22,0.5600,0.5355,0.0245,4.5752,43.445251,-9.1674,-9.9000,286.740233,-3.6524,-4.0247,42.866945,-1.33,0,1,1,1,1,0
9,2019-04-22,0.6900,0.6509,0.0391,6.0071,41.600710,-11.5819,-11.3116,278.042169,-3.8482,-4.3017,41.806432,0.49,0,1,1,0,1,0
10,2019-02-19,0.7200,0.7256,-0.0056,-0.7718,40.768874,-9.6435,-10.3799,264.983835,-4.1580,-4.4216,39.883372,-2.17,1,0,1,1,1,0
11,2018-10-22,0.4400,0.4339,0.0061,1.4059,34.759732,-14.0674,-11.9304,260.720553,-5.8771,-5.4970,34.269295,-1.41,0,1,0,0,0,0
12,2018-07-23,0.5200,0.5270,-0.007,-1.3283,36.170831,-13.8174,-13.3638,264.443059,-5.3702,-5.6538,35.157667,-2.80,0,0,1,0,1,0
13,2018-04-23,0.6200,0.6318,-0.0118,-1.8677,32.504811,-14.7079,-14.0892,250.453837,-6.2883,-6.1499,32.402083,-0.32,0,0,1,0,0,0
14,2018-02-20,0.7200,0.7114,0.0086,1.2089,30.450254,-15.7669,-13.7445,253.975941,-6.6368,-5.8845,30.715634,0.87,1,1,0,0,0,0
15,2017-10-23,0.4400,0.4592,-0.0192,-4.1812,36.388391,-16.7314,-16.4821,238.458471,-7.3876,-6.8046,35.350158,-2.85,0,0,0,0,0,0
16,2017-07-24,0.5300,0.5392,-0.0092,-1.7062,40.592527,-17.2594,-16.9716,228.675814,-7.3399,-7.1858,39.107839,-3.66,0,0,1,0,0,0
17,2017-04-24,0.6200,0.6234,-0.0034,-0.5454,40.497079,-18.7947,-17.6061,218.668975,-7.8046,-7.7416,39.831711,-1.64,0,0,0,0,0,0
18,2017-02-21,0.6500,0.6440,0.006,0.9317,41.252805,-16.4077,-17.7555,217.095794,-7.8228,-7.7535,41.063874,-0.46,1,1,0,1,0,0
19,2016-10-24,0.4500,0.4309,0.0191,4.4326,41.269745,-19.5522,-18.7269,196.109090,-8.7865,-8.7355,41.980179,1.72,0,1,0,0,0,1
20,2016-07-25,0.5400,0.5258,0.0142,2.7006,41.991339,-20.5161,-19.3369,196.717646,-9.3467,-9.0153,42.095437,0.25,0,1,1,0,0,0
21,2016-04-25,0.6200,0.6313,-0.0113,-1.7900,35.732287,-18.8640,-20.6477,188.433359,-9.5201,-9.6030,36.097388,1.02,0,0,1,1,1,1
22,2016-02-22,0.7200,0.6870,0.033,4.8035,34.502055,-21.1922,-20.0052,175.042050,-9.7116,-9.6526,33.978214,-1.52,1,1,1,0,0,0
23,2015-10-26,0.0100,-0.0100,0.02,200.0000,30.989201,-21.9416,-21.8619,184.894821,-10.8081,-10.5581,31.822118,2.69,0,1,1,0,0,1
24,2015-07-27,0.1400,0.1300,0.01,7.6923,29.780536,-23.2460,-23.0675,183.699758,-11.6828,-11.4248,29.033520,-2.51,0,1,0,0,0,0
25,2015-04-27,0.6200,0.2600,0.36,138.4615,32.287286,-23.6527,-23.6885,186.369983,-12.2263,-11.3156,32.241542,-0.14,1,1,0,1,0,0
26,2015-02-17,0.2500,0.2600,-0.01,-3.8462,32.615114,-23.9564,-23.8849,184.968128,-11.6676,-11.6671,32.973438,1.10,1,0,1,0,0,1
27,2014-10-21,-0.0600,-0.0300,-0.03,-100.0000,29.644589,-24.3760,-24.5763,169.913731,-11.3555,-11.8467,29.232755,-1.39,0,0,0,1,1,0
28,2014-07-22,0.1200,0.1100,0.01,9.0909,29.733004,-25.9452,-25.6297,172.721399,-12.7714,-12.9210,29.881298,0.50,0,1,1,0,1,0
29,2014-04-22,0.2400,0.2200,0.02,9.0909,27.864385,-26.3432,-26.5565,162.957731,-12.9639,-12.9905,27.820331,-0.16,0,1,1,1,1,0
30,2014-02-12,0.2400,0.2400,0,0.0000,25.169727,-28.2505,-26.1986,157.213781,-13.7373,-12.9886,26.395907,4.87,1,0,0,0,0,1
31,2013-10-21,-0.0500,0.0400,-0.09,-225.0000,26.214048,-28.9400,-27.2753,149.782210,-14.1403,-13.4366,25.833197,-1.45,0,0,0,0,0,0
32,2013-07-23,0.0700,0.1600,-0.09,-56.2500,30.213960,-28.6565,-28.9934,144.555172,-14.8674,-14.4898,28.741323,-4.87,0,0,0,1,0,0
33,2013-04-23,0.1900,0.2500,-0.06,-24.0000,30.933252,-29.2793,-29.8570,134.138766,-14.5341,-14.7708,30.559201,-1.21,0,0,0,1,1,0
34,2013-02-12,0.2100,0.1900,0.02,10.5263,33.128150,-28.9553,-29.6209,128.669020,-15.2266,-15.0358,33.106978,-0.06,1,1,1,1,0,0
35,2012-10-22,0.0048,0.1100,-0.1052,-95.6364,30.635447,-30.6420,-30.2003,120.519101,-15.8092,-15.6387,30.378123,-0.84,0,0,0,0,0,0
36,2012-07-24,0.1800,0.1400,0.04,28.5714,32.270366,-31.3396,-30.2766,111.954063,-17.1876,-16.1688,32.401547,0.41,0,1,1,0,0,0
37,2012-04-24,0.2600,0.2900,-0.03,-10.3448,30.756021,-30.6985,-31.4861,114.193539,-16.5923,-16.7451,30.269462,-1.58,1,0,1,1,1,0
38,2012-02-14,0.2200,0.2300,-0.01,-4.3478,29.364873,-31.5664,-31.8284,111.940643,-17.0810,-17.0741,28.604196,-2.59,1,0,1,1,0,0
39,2011-10-25,0.0200,-0.0100,0.03,300.0000,26.439976,-33.3670,-32.2347,101.247143,-18.9309,-17.1304,25.947975,-1.86,0,1,1,0,0,0
40,2011-07-26,0.3100,0.1900,0.12,63.1579,25.045362,-33.2302,-32.9472,109.144352,-18.3906,-17.8142,24.611242,-1.73,1,1,1,0,0,0
41,2011-04-26,0.2500,0.2000,0.05,25.0000,22.756134,-33.4616,-33.5036,109.797121,-18.0924,-18.5482,22.842106,0.38,1,1,1,1,1,0
42,2011-02-15,0.2000,0.1700,0.03,17.6471,21.413648,-34.0916,-33.9909,107.879949,-18.8995,-18.5986,21.810442,1.85,1,1,1,0,0,1
43,2010-10-26,0.0600,-0.0300,0.09,300.0000,20.789767,-35.8934,-35.1947,95.786786,-18.8935,-19.5010,20.653759,-0.65,1,1,1,0,1,0
44,2010-07-27,0.0100,0.0200,-0.01,-50.0000,18.524116,-36.7346,-34.4746,89.522628,-20.1902,-18.9170,18.658534,0.73,1,0,0,0,0,0
45,2010-04-27,-0.0500,0.1200,-0.17,-141.6667,18.645434,-37.5989,-35.8772,94.634197,-21.5630,-19.9144,18.196832,-2.41,0,0,1,0,0,0
46,2010-02-16,-0.0400,0.0900,-0.13,-144.4444,16.819433,-36.0235,-35.8624,87.291662,-19.8129,-20.3891,17.091122,1.62,1,0,1,0,1,1
47,2009-10-27,-0.1100,-0.1200,0.01,8.3333,16.459342,-38.6761,-39.3863,84.199896,-21.3306,-21.4674,16.323925,-0.82,0,1,1,1,1,0
48,2009-04-28,0.0100,0.0400,-0.03,-75.0000,13.062640,-36.2953,-37.4681,67.005101,-21.1426,-21.1221,13.204690,1.09,1,0,1,1,0,1
49,2009-02-17,-0.0800,-0.2700,0.19,70.3704,10.239578,-40.4676,-41.5434,61.582060,-23.1761,-22.1394,10.724044,4.73,1,1,0,1,0,1
50,2008-10-28,-0.2800,0.0600,-0.34,-566.6667,14.262229,-35.7847,-42.5054,72.295111,-17.2257,-23.7761,14.001228,-1.83,0,0,0,1,1,0
51,2008-08-04,-0.0300,0.0500,-0.08,-160.0000,16.173352,-44.0755,-43.1370,95.841978,-23.9591,-23.6634,16.809963,3.94,0,0,0,0,0,1
52,2008-04-29,0.1800,0.1500,0.03,20.0000,17.298812,-44.1794,-42.8226,106.106492,-23.8780,-23.8447,17.315827,0.10,0,1,1,0,0,0
53,2008-02-26,0.2300,0.1900,0.04,21.0526,15.001757,-42.3231,-43.1306,105.046632,-23.1835,-23.7117,14.859963,-0.95,1,1,1,1,1,0
54,2007-07-30,-0.0300,0.0500,-0.08,-160.0000,13.481325,-46.0531,-46.5262,110.788223,-24.0813,-25.7217,13.962215,3.57,1,0,0,1,1,1
55,2007-05-04,-0.2000,0.2900,-0.49,-168.9655,15.924605,-46.3818,-46.4888,112.965468,-25.0644,-24.9591,15.816642,-0.68,0,0,0,1,0,0
56,2007-02-28,0.9800,0.4100,0.57,139.0244,16.329468,-45.6771,-45.9665,105.069710,-25.1587,-25.6705,16.610173,1.72,1,1,1,1,1,1
57,2006-08-01,-0.1200,0.3300,-0.45,-136.3636,13.250648,-47.7086,-47.4649,93.910737,-26.2520,-26.0425,13.188145,-0.47,0,0,1,0,0,0
58,2005-10-31,-0.0300,-0.2200,0.19,86.3636,12.384765,-48.8233,-49.9605,87.469001,-27.2849,-27.1880,12.169595,-1.74,0,1,0,1,0,0

This is the dataframe that contains all the clean variables necessary for analysis:

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,0,0,1
1,0,1,0,1,0,1
2,1,1,1,1,0,0
3,0,1,1,0,0,1
4,0,1,1,0,1,0
5,0,1,0,0,0,0
6,1,0,0,0,0,0
7,0,1,1,1,1,1
8,0,1,1,1,1,0
9,0,1,1,0,1,0
10,1,0,1,1,1,0
11,0,1,0,0,0,0
12,0,0,1,0,1,0
13,0,0,1,0,0,0
14,1,1,0,0,0,0

Result dataframe:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation
0,0,3,0,1,0.0625,0.25,0.1,25.0,Invalid

Thank you for using the model.
Please wait 60 seconds before running the model again.

### Naive Bayes Prediction Model (Multi-Stock | Current Date | Logical Display)

In [58]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#finhub API key
#c5d5iiqad3i9ue38pn9g

#the present date and time is Friday, 10/22/2021 at 5 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon)
2. Historical Earnings (for a specific company)
3. Daily Adjusted Price History (for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

2

Enter the date of interest:

2021-10-22

What type of output would you like?:

Logic will display how the model variables were created, while Clean Variables will not:

 1.Logic

 2.Clean Variables

1


Enter your finhub API-Key:

c5d5iiqad3i9ue38pn9g
Below is the finhub function

,symbol,reportedDate,hour,reportedEPS,estimatedEPS,surprise,surprisePercentage
0,ALV,2021-10-22,bmo,0.73,0.926342,-0.196342,-21.1954
1,VFC,2021-10-22,bmo,1.11,1.161167,-0.051167,-4.4065
13,SLB,2021-10-22,bmo,0.36,0.359055,0.000945,0.2632
14,ROP,2021-10-22,bmo,3.91,3.871976,0.038024,0.9820
15,AXP,2021-10-22,bmo,2.27,1.792578,0.477422,26.6332
16,SMPL,2021-10-22,bmo,0.29,0.260100,0.029900,11.4956
17,GNTX,2021-10-22,bmo,0.32,0.394873,-0.074873,-18.9612
18,STX,2021-10-22,bmo,2.35,2.232777,0.117223,5.2501
19,FHB,2021-10-22,bmo,0.51,0.482275,0.027725,5.7488
20,AIMC,2021-10-22,bmo,0.80,0.840480,-0.040480,-4.8163
21,HCA,2021-10-22,bmo,4.57,4.041778,0.528222,13.0691
22,BLFY,2021-10-22,bmo,-0.68,0.000000,-0.680000,-inf
23,DSKE,2021-10-22,bmo,0.43,0.323003,0.106997,33.1255
24,CLF,2021-10-22,bmo,2.33,2.282459,0.047541,2.0829
25,HON,2021-10-22,bmo,2.02,2.015334,0.004666,0.2315
26,RF,2021-10-22,bmo,0.66,0.540596,0.119405,22.0876

Stock Count: 16

The model will take about 10 minutes to run. Please wait patiently.


There are a total of 48 stock calls

This is the ticker:

ALV

2021-10-22



ALV has reported earnings 98 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ALV's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.86     None               None
1    2021-07-16         1.2        1.369   -0.169           -12.3448
2    2021-04-23        1.79        1.417    0.373            26.3232
3    2021-01-26        2.19       1.8577   0.3323            17.8877
4    2020-10-23        1.48       1.2004   0.2796            23.2922
5    2020-07-17        -1.4      -1.2537  -0.1463           -11.6695
6    2020-04-24        0.88       0.7415   0.1385            18.6784
7    2020-01-28        1.84       1.7745   0.0655             3.6912
8    2019-10-25         1.3       1.4114  -0.1114            -7.8929
9    2019-07-19        1.38       1.4293  -0.0493            -3.4492
10   2019-04-26         1.2       1.5935  -0.3935           -24.6941
11   2019-01-29        1.42       1.7136  -0.2936           -17.1335
12   2018-10-26        1.35       1.6234  -0.2734           -16.8412
13   2018-07-27        2.22       1.8812   0.3388            18.0098
14   2018-04-27        1.66       1.8256  -0.1656             -9.071

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ALV's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.73,0.926342,-0.196342,-21.1954,0,0
1,2021-07-16,1.20,1.369000,-0.169,-12.3448,0,0
2,2021-04-23,1.79,1.417000,0.373,26.3232,0,1
3,2021-01-26,2.19,1.857700,0.3323,17.8877,1,1
4,2020-10-23,1.48,1.200400,0.2796,23.2922,1,1
5,2020-07-17,-1.40,-1.253700,-0.1463,-11.6695,0,0
6,2020-04-24,0.88,0.741500,0.1385,18.6784,0,1
7,2020-01-28,1.84,1.774500,0.0655,3.6912,1,1
8,2019-10-25,1.30,1.411400,-0.1114,-7.8929,0,0
9,2019-07-19,1.38,1.429300,-0.0493,-3.4492,1,0
10,2019-04-26,1.20,1.593500,-0.3935,-24.6941,0,0
11,2019-01-29,1.42,1.713600,-0.2936,-17.1335,1,0
12,2018-10-26,1.35,1.623400,-0.2734,-16.8412,0,0
13,2018-07-27,2.22,1.881200,0.3388,18.0098,1,1
14,2018-04-27,1.66,1.825600,-0.1656,-9.0710,0,0

3. Retrieve the last 5,000 daily adjusted prices for ALV in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,96.44,96.590,92.130,92.27,92.27,1034318,0.0,1.0,-4.3239,0.5700,2021-10-22
1,94.73,95.995,94.305,95.27,95.27,533976,0.0,1.0,0.5700,1.1608,2021-10-21
2,92.65,95.780,92.520,95.11,95.11,523510,0.0,1.0,2.6552,0.0108,2021-10-20
3,95.00,95.615,94.230,94.44,94.44,522438,0.0,1.0,-0.5895,0.4281,2021-10-19
4,94.84,96.060,94.680,94.81,94.81,559014,0.0,1.0,-0.0316,0.4281,2021-10-18
5,95.62,97.100,95.140,96.73,96.73,581969,0.0,1.0,1.1608,0.4281,2021-10-15
6,93.69,95.400,93.225,95.22,95.22,307887,0.0,1.0,1.6330,0.4281,2021-10-14
7,92.98,93.990,92.520,92.99,92.99,616354,0.0,1.0,0.0108,0.7361,2021-10-13
8,93.43,94.710,93.320,93.83,93.83,536533,0.0,1.0,0.4281,0.7757,2021-10-12
9,92.69,93.770,91.760,92.56,92.56,477350,0.0,1.0,-0.1403,0.7757,2021-10-11
10,91.02,92.380,90.750,91.69,91.69,374801,0.0,1.0,0.7361,0.7757,2021-10-08
11,89.90,91.400,89.860,90.82,90.82,481677,0.0,1.0,1.0234,0.7419,2021-10-07
12,86.11,87.620,85.570,87.61,87.61,643432,0.0,1.0,1.7420,-0.1276,2021-10-06
13,86.37,87.340,85.180,87.04,87.04,499931,0.0,1.0,0.7757,-1.1075,2021-10-05
14,86.26,87.670,86.050,86.90,86.90,481212,0.0,1.0,0.7419,-1.1075,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58465974,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,96.44,96.5900,92.13,92.27,92.270000,1034318,0.0,1.0,-4.3239,0.5700,2021-10-22,0,1,-0.0022,0.3831,453.120000,0
69,90.53,92.0655,90.23,90.44,89.790934,1163480,0.0,1.0,-0.8164,0.1438,2021-07-16,0,0,-1.3901,-0.3363,429.948932,0
127,101.55,106.1200,100.83,105.85,104.481463,831542,0.0,1.0,2.8867,-1.9429,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
188,92.19,93.2400,90.31,91.31,90.129451,1038639,0.0,1.0,-2.2351,-0.9363,2021-01-26,0,1,-1.3930,-0.8136,380.041108,0
251,85.00,86.6200,84.75,84.94,83.841808,730671,0.0,1.0,-1.3626,-1.1740,2020-10-23,0,1,-1.4416,-1.5711,340.943239,1
320,65.76,66.4800,63.71,64.51,63.675948,1215485,0.0,1.0,-3.1692,-0.8390,2020-07-17,0,1,-1.8454,-1.4895,315.940145,0
378,60.53,61.4000,58.81,60.75,59.964562,1112588,0.0,1.0,-0.9341,0.3121,2020-04-24,0,0,-1.4492,-2.5822,276.661622,1
439,77.19,79.0000,76.57,78.24,76.608606,1837960,0.0,1.0,-0.7532,-2.7802,2020-01-28,1,0,-2.2792,-2.7088,317.651107,1
502,82.36,83.3700,81.33,82.07,79.741903,801336,0.0,1.0,-3.1788,-2.0690,2019-10-25,0,1,-2.6996,-3.4732,291.648236,1
571,72.20,74.5400,71.85,71.89,69.184618,1597731,0.0,1.0,-4.1764,-3.0826,2019-07-19,0,0,-4.6669,-3.8676,286.037580,0
629,81.17,83.0100,80.29,82.57,78.737660,1375242,0.0,1.0,-2.9966,-4.7306,2019-04-26,1,1,-3.7830,-4.2355,281.049894,1
690,79.04,79.2300,76.38,77.61,73.433878,1855151,0.0,1.0,-7.0928,-4.3673,2019-01-29,0,0,-4.8149,-4.5696,251.212496,0
752,75.99,81.9500,75.99,81.77,76.803888,1888922,0.0,1.0,1.0710,-3.3310,2018-10-26,1,0,-5.4063,-5.4970,251.543523,1
816,100.19,103.2100,99.22,101.20,94.423683,1443561,0.0,1.0,-5.7554,-7.0354,2018-07-27,1,1,-6.3852,-5.5768,265.594453,0
879,142.77,143.7400,135.94,136.67,91.490381,1921032,0.0,1.0,-35.9176,-32.9935,2018-04-27,0,0,-6.2006,-6.2883,250.444441,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.73,0.926342,-0.196342,-21.1954,92.270000,-4.3239,0.5700,453.120000,-0.0022,0.3831,0.000000,-100.00,0,0,1,0,0,0
1,2021-07-16,1.20,1.369000,-0.169,-12.3448,89.790934,-0.8164,0.1438,429.948932,-1.3901,-0.3363,89.939858,0.17,0,0,0,0,0,0
2,2021-04-23,1.79,1.417000,0.373,26.3232,104.481463,2.8867,-1.9429,414.023116,0.2793,-0.9025,105.261249,0.75,0,1,1,1,1,0
3,2021-01-26,2.19,1.857700,0.3323,17.8877,90.129451,-2.2351,-0.9363,380.041108,-1.3930,-0.8136,87.572937,-2.84,1,1,1,0,0,0
4,2020-10-23,1.48,1.200400,0.2796,23.2922,83.841808,-1.3626,-1.1740,340.943239,-1.4416,-1.5711,81.759089,-2.48,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,2001-11-01,0.18,0.120000,0.06,50.0000,7.390910,-53.0736,-55.3310,73.931941,-30.6455,-32.5673,7.491841,1.37,0,1,0,1,1,1
79,2001-07-26,0.31,0.420000,-0.11,-26.1905,9.624504,-51.6357,-53.8791,81.689114,-31.3883,-32.1848,9.775101,1.56,0,0,0,1,1,1
80,2000-07-20,0.54,0.590000,-0.05,-8.4746,11.083563,-54.7610,-55.5591,101.091704,-32.1532,-32.9761,11.056759,-0.24,0,0,0,1,1,0
81,2000-04-19,0.54,0.540000,0,0.0000,11.901853,-55.8209,-55.8238,95.830333,-33.6814,-34.5057,12.320086,3.51,0,0,0,1,1,1
82,2000-01-27,0.60,0.580000,0.02,3.4483,12.960878,-54.6188,-56.0555,93.668967,-33.9633,-33.7006,12.433581,-4.07,1,1,0,1,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,1,0,0,0
1,0,0,0,0,0,0
2,0,1,1,1,1,0
3,1,1,1,0,0,0
4,1,1,1,0,1,0
...,...,...,...,...,...,...
78,0,1,0,1,1,1
79,0,0,0,1,1,1
80,0,0,0,1,1,0
81,0,0,0,1,1,1
82,1,1,0,1,0,0

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,ALV

This is the ticker:

VFC

2021-10-22




Model has been put to sleep after historical earnings call
VFC has reported earnings 103 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains VFC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         1.15     None               None
1    2021-07-30         0.2       0.1093   0.0907            82.9826
2    2021-05-21        0.21       0.2878  -0.0778           -27.0327
3    2021-01-27        0.93       0.9004   0.0296             3.2874
4    2020-10-16        0.67       0.4806   0.1894            39.4091
5    2020-07-31       -0.57      -0.6775   0.1075            15.8672
6    2020-05-15         0.1       0.1365  -0.0365           -26.7399
7    2020-01-23        1.23       1.2135   0.0165             1.3597
8    2019-10-25        1.26       1.3037  -0.0437             -3.352
9    2019-07-24         0.3       0.2887   0.0113             3.9141
10   2019-05-22         0.6       0.5856   0.0144              2.459
11   2019-01-18        1.31       1.0994   0.2106            19.1559
12   2018-10-19        1.43       1.3321   0.0979             7.3493
13   2018-07-20        0.43        0.328    0.102            31.0976
14   2018-05-04        0.67       0.6577   0.0123             1.8702

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is VFC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,1.11,1.161167,-0.0511667,-4.4065,1,0
1,2021-07-30,0.20,0.109300,0.0907,82.9826,0,1
2,2021-05-21,0.21,0.287800,-0.0778,-27.0327,0,0
3,2021-01-27,0.93,0.900400,0.0296,3.2874,1,1
4,2020-10-16,0.67,0.480600,0.1894,39.4091,1,1
5,2020-07-31,-0.57,-0.677500,0.1075,15.8672,0,1
6,2020-05-15,0.10,0.136500,-0.0365,-26.7399,0,0
7,2020-01-23,1.23,1.213500,0.0165,1.3597,0,1
8,2019-10-25,1.26,1.303700,-0.0437,-3.3520,1,0
9,2019-07-24,0.30,0.288700,0.0113,3.9141,0,1
10,2019-05-22,0.60,0.585600,0.0144,2.4590,0,1
11,2019-01-18,1.31,1.099400,0.2106,19.1559,0,1
12,2018-10-19,1.43,1.332100,0.0979,7.3493,1,1
13,2018-07-20,0.43,0.328000,0.102,31.0976,0,1
14,2018-05-04,0.67,0.657700,0.0123,1.8702,0,1

3. Retrieve the last 5,000 daily adjusted prices for VFC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,71.27,73.580,69.4500,70.74,70.74,6452186,0.0,1.0,-0.7437,0.0817,2021-10-22
1,74.16,75.400,73.7100,74.07,74.07,2680929,0.0,1.0,-0.1214,0.2577,2021-10-21
2,73.74,74.129,73.1200,73.93,73.93,1696662,0.0,1.0,0.2577,0.0817,2021-10-20
3,73.45,73.630,72.7500,73.51,73.51,2013299,0.0,1.0,0.0817,0.5331,2021-10-19
4,72.54,73.700,72.3249,72.93,72.93,2314006,0.0,1.0,0.5376,0.5331,2021-10-18
5,74.01,74.250,73.1100,73.55,73.55,2752837,0.0,1.0,-0.6215,0.5331,2021-10-15
6,73.16,73.685,72.5650,73.55,73.55,2710699,0.0,1.0,0.5331,0.2358,2021-10-14
7,72.33,73.140,71.9300,72.30,72.30,4334976,0.0,1.0,-0.0415,0.2358,2021-10-13
8,69.52,73.030,69.5100,72.30,72.30,6053830,0.0,1.0,3.9988,0.2245,2021-10-12
9,68.19,70.670,68.1900,69.37,69.37,4324228,0.0,1.0,1.7305,0.2245,2021-10-11
10,67.84,68.220,67.1700,68.00,68.00,2841654,0.0,1.0,0.2358,0.2245,2021-10-08
11,68.35,69.350,67.9100,68.40,68.40,3510187,0.0,1.0,0.0732,0.2245,2021-10-07
12,66.83,67.070,65.6600,66.98,66.98,3101143,0.0,1.0,0.2245,0.4102,2021-10-06
13,68.08,68.680,67.2900,67.46,67.46,3708686,0.0,1.0,-0.9107,0.4102,2021-10-05
14,68.36,70.010,68.2500,68.78,68.78,3711059,0.0,1.0,0.6144,-0.0147,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58465974,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,71.27,73.58,69.450,70.74,70.740000,6452186,0.0,1.0,-0.7437,0.0817,2021-10-22,0,0,-0.0022,0.3831,453.120000,0
59,83.41,83.64,78.900,80.20,79.659003,7096810,0.0,1.0,-4.4971,-0.2077,2021-07-30,0,1,-0.1859,-0.1333,437.095809,0
107,80.26,81.33,77.135,77.24,76.242817,11165436,0.0,1.0,-5.0052,-1.0109,2021-05-21,0,0,-1.1119,0.1583,412.234851,0
187,83.77,85.96,78.720,79.15,77.649564,6890790,0.0,1.0,-7.3062,-1.4845,2021-01-27,0,1,-2.4899,-0.8136,370.752733,0
256,78.00,79.00,74.180,75.82,73.971411,4039638,0.0,1.0,-5.1649,-2.5508,2020-10-16,0,1,-1.8707,-1.0307,342.432117,0
310,59.10,62.03,58.080,60.36,58.475577,4157078,0.0,1.0,-1.0566,-2.4159,2020-07-31,1,1,-1.6097,-1.3111,320.653911,0
363,52.91,54.56,51.470,51.96,49.965697,6502198,0.0,1.0,-5.5647,-4.1837,2020-05-15,0,0,-0.8755,-1.7759,279.897831,1
442,87.80,88.75,84.880,85.41,81.504775,9031669,0.0,1.0,-7.1700,-4.9554,2020-01-23,0,1,-2.5059,-2.7088,322.344597,1
502,84.90,85.83,81.490,84.15,79.880344,7369271,0.0,1.0,-5.9124,-5.5605,2019-10-25,0,0,-2.6996,-3.4732,291.648236,1
568,90.33,91.54,86.440,89.33,84.392644,4663961,0.0,1.0,-6.5730,-6.2569,2019-07-24,0,1,-3.0223,-3.6524,290.147620,1
611,85.71,90.57,85.460,90.33,79.874454,4812602,0.0,1.0,-6.8085,-11.1138,2019-05-22,1,1,-4.1522,-3.9774,273.597632,0
696,82.22,84.39,80.000,82.34,72.375033,6281860,0.0,1.0,-11.9739,-11.7101,2019-01-18,0,1,-4.0979,-4.1495,254.121262,1
757,83.99,85.94,77.730,77.76,67.893712,7203409,0.0,1.0,-19.1645,-12.3982,2018-10-19,0,0,-5.4970,-5.4769,261.896123,0
821,92.00,93.51,91.010,92.94,80.732485,4380674,0.0,1.0,-12.2473,-12.9775,2018-07-20,1,1,-5.6538,-5.4815,263.952301,0
874,78.01,78.39,73.900,76.27,65.889080,4676612,0.0,1.0,-15.5376,-13.9088,2018-05-04,0,1,-4.4291,-6.2006,249.937088,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,1.11,1.161167,-0.0511667,-4.4065,70.740000,-0.7437,0.0817,453.120000,-0.0022,0.3831,0.000000,-100.00,1,0,0,0,0,0
1,2021-07-30,0.20,0.109300,0.0907,82.9826,79.659003,-4.4971,-0.2077,437.095809,-0.1859,-0.1333,81.278008,2.03,0,1,1,0,0,1
2,2021-05-21,0.21,0.287800,-0.0778,-27.0327,76.242817,-5.0052,-1.0109,412.234851,-1.1119,0.1583,75.620950,-0.82,0,0,0,0,0,0
3,2021-01-27,0.93,0.900400,0.0296,3.2874,77.649564,-7.3062,-1.4845,370.752733,-2.4899,-0.8136,77.865393,0.28,1,1,1,0,0,0
4,2020-10-16,0.67,0.480600,0.1894,39.4091,73.971411,-5.1649,-2.5508,342.432117,-1.8707,-1.0307,70.771382,-4.33,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2001-02-06,0.20,0.180000,0.02,11.1111,5.003331,-85.6843,-86.0524,91.386466,-32.4564,-32.0927,4.994939,-0.17,0,1,1,1,0,0
84,2000-10-18,0.22,0.280000,-0.06,-21.4286,3.158043,-86.3051,-86.3417,90.333274,-31.8882,-33.2474,3.574488,13.19,1,0,0,1,1,0
85,2000-07-18,0.17,0.170000,0,0.0000,3.602543,-86.1441,-86.3835,100.514915,-33.2681,-32.8782,3.515884,-2.41,0,0,0,1,0,0
86,2000-04-25,0.17,0.160000,0.01,6.2500,4.044649,-85.1572,-86.2500,99.199010,-31.4095,-32.6894,3.864463,-4.45,0,1,1,1,1,0
87,2000-02-08,0.20,0.200000,0,0.0000,3.514293,-86.5507,-86.3857,96.382194,-33.0534,-33.3007,3.514293,0.00,0,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,0,0,0,0,0
1,0,1,1,0,0,1
2,0,0,0,0,0,0
3,1,1,1,0,0,0
4,1,1,1,0,0,0
...,...,...,...,...,...,...
83,0,1,1,1,0,0
84,1,0,0,1,1,0
85,0,0,0,1,0,0
86,0,1,1,1,1,0
87,0,0,0,0,1,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,VFC

This is the ticker:

SLB

2021-10-22



SLB has reported earnings 101 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains SLB's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.36     None               None
1    2021-07-23         0.3       0.2591   0.0409            15.7854
2    2021-04-23        0.21       0.1862   0.0238             12.782
3    2021-01-22        0.22       0.1705   0.0495            29.0323
4    2020-10-16        0.16        0.127    0.033            25.9843
5    2020-07-24        0.05       -0.013    0.063           484.6154
6    2020-04-17        0.25       0.2428   0.0072             2.9654
7    2020-01-17        0.39        0.365    0.025             6.8493
8    2019-10-18        0.43       0.4035   0.0265             6.5675
9    2019-07-19        0.35       0.3484   0.0016             0.4592
10   2019-04-18         0.3       0.3029  -0.0029            -0.9574
11   2019-01-18        0.36       0.3726  -0.0126            -3.3816
12   2018-10-19        0.46       0.4514   0.0086             1.9052
13   2018-07-20        0.43       0.4252   0.0048             1.1289
14   2018-04-20        0.38       0.3677   0.0123             3.3451

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is SLB's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.36,0.359055,0.000945,0.2632,1,1
1,2021-07-23,0.30,0.259100,0.0409,15.7854,1,1
2,2021-04-23,0.21,0.186200,0.0238,12.7820,0,1
3,2021-01-22,0.22,0.170500,0.0495,29.0323,1,1
4,2020-10-16,0.16,0.127000,0.033,25.9843,1,1
5,2020-07-24,0.05,-0.013000,0.063,484.6154,0,1
6,2020-04-17,0.25,0.242800,0.0072,2.9654,0,1
7,2020-01-17,0.39,0.365000,0.025,6.8493,0,1
8,2019-10-18,0.43,0.403500,0.0265,6.5675,1,1
9,2019-07-19,0.35,0.348400,0.0016,0.4592,1,1
10,2019-04-18,0.30,0.302900,-0.0029,-0.9574,0,0
11,2019-01-18,0.36,0.372600,-0.0126,-3.3816,0,0
12,2018-10-19,0.46,0.451400,0.0086,1.9052,1,1
13,2018-07-20,0.43,0.425200,0.0048,1.1289,1,1
14,2018-04-20,0.38,0.367700,0.0123,3.3451,0,1

3. Retrieve the last 5,000 daily adjusted prices for SLB in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,33.85,34.55,33.390,33.94,33.94,12075289,0.0,1.0,0.2659,0.0589,2021-10-22
1,34.35,34.61,33.850,34.30,34.30,12151389,0.0,1.0,-0.1456,0.4070,2021-10-21
2,34.03,34.76,33.800,34.74,34.74,10818746,0.0,1.0,2.0864,0.4070,2021-10-20
3,34.40,34.77,33.700,34.54,34.54,10417075,0.0,1.0,0.4070,0.7817,2021-10-19
4,34.14,34.64,33.810,34.16,34.16,11548259,0.0,1.0,0.0586,0.7817,2021-10-18
5,33.98,34.21,33.760,34.00,34.00,9352100,0.0,1.0,0.0589,0.8601,2021-10-15
6,33.26,33.58,32.940,33.52,33.52,8678736,0.0,1.0,0.7817,0.9242,2021-10-14
7,32.46,32.93,31.895,32.76,32.76,12505280,0.0,1.0,0.9242,0.8601,2021-10-13
8,32.45,33.46,32.220,32.88,32.88,18377939,0.0,1.0,1.3251,0.5265,2021-10-12
9,32.29,33.24,32.050,32.46,32.46,16941817,0.0,1.0,0.5265,-0.1617,2021-10-11
10,31.39,31.96,31.115,31.66,31.66,11854094,0.0,1.0,0.8601,-0.1617,2021-10-08
11,30.63,31.20,30.550,31.02,31.02,15928005,0.0,1.0,1.2733,-0.4985,2021-10-07
12,30.09,30.54,29.480,29.94,29.94,12070707,0.0,1.0,-0.4985,-2.0191,2021-10-06
13,31.26,31.69,30.552,30.59,30.59,12264592,0.0,1.0,-2.1433,-0.1617,2021-10-05
14,30.93,31.47,30.645,30.88,30.88,16285568,0.0,1.0,-0.1617,0.3246,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58539485,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,33.85,34.5500,33.39,33.94,33.940000,12075289,0.0,1.0,0.2659,0.0589,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
64,28.28,28.7800,27.62,28.41,28.283913,12759176,0.0,1.0,0.0138,0.0065,2021-07-23,1,1,0.2288,-0.1574,438.521197,1
127,24.81,25.9800,24.57,25.71,25.499103,12876679,0.0,1.0,2.7775,-2.5569,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
190,23.71,24.5300,23.45,24.41,24.097414,13559454,0.0,1.0,1.6340,-2.0533,2021-01-22,1,1,-0.8136,-1.0412,379.139997,1
256,15.62,16.2600,14.90,14.97,14.691143,39866358,0.0,1.0,-5.9466,-1.3118,2020-10-16,0,0,-1.8707,-1.0307,342.432117,0
315,19.50,19.6566,18.90,19.48,18.989718,16738625,0.0,1.0,-2.6168,-3.1735,2020-07-24,1,1,-1.8180,-1.8454,315.115236,1
383,14.72,15.4000,14.20,15.28,14.797352,33932740,0.0,1.0,0.5255,-7.0614,2020-04-17,1,0,-1.7977,-2.1624,280.249806,1
445,39.01,39.9700,38.18,38.37,36.623977,17518049,0.0,1.0,-6.1164,-4.3102,2020-01-17,0,1,-2.7531,-2.5769,322.568096,0
507,32.19,33.2000,32.09,32.31,30.405252,17218326,0.0,1.0,-5.5444,-4.9098,2019-10-18,0,0,-3.5328,-3.2931,288.138014,0
571,39.34,39.3400,37.29,38.71,35.862657,12811713,0.0,1.0,-8.8392,-8.0316,2019-07-19,0,0,-4.6669,-3.8676,286.037580,0
634,48.13,48.8800,45.51,45.56,41.626288,15721558,0.0,1.0,-13.5128,-9.1155,2019-04-18,0,1,-4.2390,-4.4182,277.802701,1
696,43.85,44.9400,43.00,44.73,40.409379,26638570,0.0,1.0,-7.8463,-9.1758,2019-01-18,1,0,-4.0979,-4.1495,254.121262,1
757,58.00,61.1900,57.59,58.47,52.230275,11348123,0.0,1.0,-9.9478,-10.9849,2018-10-19,1,0,-5.4970,-5.4769,261.896123,0
821,68.34,68.4300,66.03,66.09,58.564192,7766048,0.0,1.0,-14.3047,-10.9556,2018-07-20,0,0,-5.6538,-5.4815,263.952301,0
884,70.81,71.2500,68.63,69.23,60.901834,9967395,0.0,1.0,-13.9926,-11.7205,2018-04-20,0,0,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.36,0.359055,0.000945,0.2632,33.940000,0.2659,0.0589,453.120000,-0.0022,0.3831,0.000000,-100.00,1,1,1,1,0,0
1,2021-07-23,0.30,0.259100,0.0409,15.7854,28.283913,0.0138,0.0065,438.521197,0.2288,-0.1574,29.329253,3.70,1,1,1,1,1,1
2,2021-04-23,0.21,0.186200,0.0238,12.7820,25.499103,2.7775,-2.5569,414.023116,0.2793,-0.9025,26.153689,2.57,0,1,1,1,1,1
3,2021-01-22,0.22,0.170500,0.0495,29.0323,24.097414,1.6340,-2.0533,379.139997,-0.8136,-1.0412,23.435994,-2.74,1,1,1,1,1,0
4,2020-10-16,0.16,0.127000,0.033,25.9843,14.691143,-5.9466,-1.3118,342.432117,-1.8707,-1.0307,14.730397,0.27,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2001-01-18,0.21,0.200000,0.01,5.0000,24.359294,-68.1827,-66.1007,90.975537,-31.8216,-32.0699,24.653707,1.21,1,1,0,0,1,1
84,2000-10-17,0.18,0.170000,0.01,5.8824,27.325438,-66.3189,-67.0464,90.669711,-34.5049,-33.2474,27.178598,-0.54,1,1,1,1,0,0
85,2000-07-18,0.14,0.130000,0.01,7.6923,25.204935,-66.0540,-66.6143,100.514915,-33.2681,-32.8782,25.328146,0.49,1,1,1,1,0,0
86,2000-04-18,0.12,0.120000,0,0.0000,24.535409,-64.7632,-67.3438,96.730019,-31.1836,-34.5057,24.492236,-0.18,0,0,1,1,1,0
87,2000-01-26,0.12,0.120000,0,0.0000,20.822391,-67.5916,-66.9457,94.044644,-33.3017,-33.7006,20.696556,-0.60,0,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,0
1,1,1,1,1,1,1
2,0,1,1,1,1,1
3,1,1,1,1,1,0
4,1,1,0,0,0,0
...,...,...,...,...,...,...
83,1,1,0,0,1,1
84,1,1,1,1,0,0
85,1,1,1,1,0,0
86,0,0,1,1,1,0
87,0,0,0,0,1,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,2,0,2,0.25,0.5,0.333333,50.0,Invalid,Do NOT buy,SLB

This is the ticker:

ROP

2021-10-22

Model has been put to sleep after the alpha spy


ROP has reported earnings 102 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ROP's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         3.83     None               None
1    2021-07-23        3.76        3.663    0.097             2.6481
2    2021-04-27         3.6        3.315    0.285             8.5973
3    2021-01-29        3.56       3.4917   0.0683             1.9561
4    2020-10-27        3.17        3.035    0.135             4.4481
5    2020-07-28        2.94         2.68     0.26             9.7015
6    2020-04-28        3.05       2.8807   0.1693              5.877
7    2020-01-30        3.39       3.3431   0.0469             1.4029
8    2019-10-24        3.29       3.2096   0.0804              2.505
9    2019-07-25        3.07       3.0464   0.0236             0.7747
10   2019-04-25         3.3       2.7842   0.5158             18.526
11   2019-02-01        3.22       3.1292   0.0908             2.9017
12   2018-10-26        3.09       2.9396   0.1504             5.1163
13   2018-07-26        2.89        2.707    0.183             6.7603
14   2018-04-20        2.61       2.4946   0.1154              4.626

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ROP's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,3.91,3.871976,0.0380236,0.9820,1,1
1,2021-07-23,3.76,3.663000,0.097,2.6481,1,1
2,2021-04-27,3.60,3.315000,0.285,8.5973,1,1
3,2021-01-29,3.56,3.491700,0.0683,1.9561,1,1
4,2020-10-27,3.17,3.035000,0.135,4.4481,1,1
5,2020-07-28,2.94,2.680000,0.26,9.7015,0,1
6,2020-04-28,3.05,2.880700,0.1693,5.8770,0,1
7,2020-01-30,3.39,3.343100,0.0469,1.4029,1,1
8,2019-10-24,3.29,3.209600,0.0804,2.5050,1,1
9,2019-07-25,3.07,3.046400,0.0236,0.7747,0,1
10,2019-04-25,3.30,2.784200,0.5158,18.5260,1,1
11,2019-02-01,3.22,3.129200,0.0908,2.9017,1,1
12,2018-10-26,3.09,2.939600,0.1504,5.1163,1,1
13,2018-07-26,2.89,2.707000,0.183,6.7603,1,1
14,2018-04-20,2.61,2.494600,0.1154,4.6260,0,1

3. Retrieve the last 5,000 daily adjusted prices for ROP in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,490.00,505.0000,485.000,487.20,487.20000,598481,0.0000,1.0,-0.5714,0.6009,2021-10-22
1,473.12,481.4600,470.120,481.24,481.24000,418078,0.0000,1.0,1.7163,0.6009,2021-10-21
2,474.89,476.7500,471.130,474.94,474.94000,292135,0.0000,1.0,0.0105,0.7238,2021-10-20
3,472.41,475.4600,469.290,474.13,474.13000,271665,0.0000,1.0,0.3641,0.7238,2021-10-19
4,464.52,470.3100,463.710,468.53,468.53000,295743,0.0000,1.0,0.8633,0.6009,2021-10-18
5,464.30,469.8750,464.300,467.09,467.09000,299831,0.0000,1.0,0.6009,0.2194,2021-10-15
6,459.21,463.1600,457.340,462.79,462.79000,233994,0.0000,1.0,0.7796,-0.3153,2021-10-14
7,453.16,457.7700,451.160,456.44,456.44000,512822,0.0000,1.0,0.7238,-0.3153,2021-10-13
8,453.60,454.4799,450.560,452.17,452.17000,311949,0.0000,1.0,-0.3153,0.2194,2021-10-12
9,451.25,454.9600,451.250,452.24,452.24000,275123,0.0000,1.0,0.2194,-0.5418,2021-10-11
10,454.05,455.9300,448.470,451.59,451.59000,306094,0.0000,1.0,-0.5418,-0.3994,2021-10-08
11,456.85,462.3900,451.970,453.35,453.35000,338299,0.0000,1.0,-0.7661,-0.3994,2021-10-07
12,443.58,454.0750,442.360,453.82,453.82000,510503,0.0000,1.0,2.3085,-0.3994,2021-10-06
13,445.51,453.5300,443.985,446.90,446.90000,467413,0.5625,1.0,0.3120,-1.5816,2021-10-05
14,452.08,457.6000,444.500,445.49,444.92998,547380,0.0000,1.0,-1.5816,-0.4706,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58539485,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,490.00,505.000,485.00,487.20,487.200000,598481,0.0,1.0,-0.5714,0.6009,2021-10-22,0,0,-0.0022,0.3831,453.120000,0
64,495.91,499.210,490.20,496.63,496.005692,521020,0.0,1.0,0.0193,-0.1775,2021-07-23,1,1,0.2288,-0.1574,438.521197,1
125,432.15,447.935,430.07,445.86,444.780256,792160,0.0,1.0,2.9227,0.1388,2021-04-27,1,1,-0.7494,-0.6115,414.798031,0
185,420.00,425.580,392.56,392.91,391.421932,1192739,0.0,1.0,-6.8043,-0.6915,2021-01-29,0,0,-2.4425,-0.8136,366.455126,0
249,405.00,405.740,390.00,394.60,392.592658,1415044,0.0,1.0,-3.0635,-1.0765,2020-10-27,0,0,-1.8457,-1.4416,333.488988,0
313,425.40,441.034,423.05,423.09,420.400701,697558,0.0,1.0,-1.1752,-0.2995,2020-07-28,0,1,-2.1803,-1.8180,315.400026,0
376,345.00,354.940,323.33,336.79,334.210605,1144828,0.0,1.0,-3.1274,-1.4321,2020-04-28,0,0,-4.0066,-1.9659,279.360093,0
437,383.46,393.000,377.91,389.38,385.756176,808801,0.0,1.0,0.5988,-0.8055,2020-01-30,1,1,-1.8317,-2.6849,318.418779,1
503,338.64,339.150,322.20,332.33,328.775320,1069242,0.0,1.0,-2.9130,-1.6401,2019-10-24,0,0,-3.4732,-3.4287,290.458822,0
567,369.53,372.000,351.24,370.99,366.523341,1389790,0.0,1.0,-0.8136,-1.5014,2019-07-25,1,1,-4.0468,-3.4598,288.761564,0
630,355.20,363.850,341.84,347.15,342.549107,742360,0.0,1.0,-3.5616,-1.4015,2019-04-25,0,1,-4.2355,-4.2390,279.747185,1
687,290.00,293.320,286.12,292.23,287.971478,706283,0.0,1.0,-0.6995,-1.0940,2019-02-01,1,1,-4.6624,-4.4966,257.554560,0
752,275.10,297.970,272.07,285.38,280.738868,1710186,0.0,1.0,2.0498,-1.6440,2018-10-26,1,0,-5.4063,-5.4970,251.543523,1
817,294.30,312.380,291.88,303.58,298.227123,1429429,0.0,1.0,1.3344,-1.4216,2018-07-26,1,1,-5.5768,-5.6538,267.406482,1
884,277.94,284.710,274.97,282.14,276.751810,915878,0.0,1.0,-0.4275,-1.8956,2018-04-20,1,0,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,3.91,3.871976,0.0380236,0.9820,487.200000,-0.5714,0.6009,453.120000,-0.0022,0.3831,0.000000,-100.00,1,1,0,0,0,0
1,2021-07-23,3.76,3.663000,0.097,2.6481,496.005692,0.0193,-0.1775,438.521197,0.2288,-0.1574,489.164303,-1.38,1,1,1,1,1,0
2,2021-04-27,3.60,3.315000,0.285,8.5973,444.780256,2.9227,0.1388,414.798031,-0.7494,-0.6115,441.268781,-0.79,1,1,1,1,0,0
3,2021-01-29,3.56,3.491700,0.0683,1.9561,391.421932,-6.8043,-0.6915,366.455126,-2.4425,-0.8136,389.877803,-0.39,1,1,0,0,0,0
4,2020-10-27,3.17,3.035000,0.135,4.4481,392.592658,-3.0635,-1.0765,333.488988,-1.8457,-1.4416,365.630516,-6.87,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2000-12-11,0.24,0.240000,0,0.0000,14.345227,-55.6013,-56.2799,93.277096,-32.1004,-33.3207,14.016710,-2.29,1,0,1,1,1,0
82,2000-08-24,0.18,0.180000,0,0.0000,12.894410,-56.1116,-56.1848,101.553118,-32.8158,-32.6755,13.659333,5.93,0,0,0,1,0,0
83,2000-05-18,0.22,0.220000,0,0.0000,14.934887,-56.9476,-55.9147,95.997722,-34.0788,-32.5722,14.991574,0.38,1,0,0,0,0,0
84,2000-02-08,0.16,0.150000,0.01,6.6667,15.417818,-57.0295,-56.4235,96.382194,-33.0534,-33.3007,14.521635,-5.81,0,1,0,0,1,0
85,1999-12-08,0.24,0.230000,0.01,4.3478,16.280540,-56.5157,-56.7380,93.753640,-33.6697,-33.0790,15.737856,-3.33,1,1,0,1,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,0,0,0
1,1,1,1,1,1,0
2,1,1,1,1,0,0
3,1,1,0,0,0,0
4,1,1,0,0,0,0
...,...,...,...,...,...,...
81,1,0,1,1,1,0
82,0,0,0,1,0,0
83,1,0,0,0,0,0
84,0,1,0,0,1,0
85,1,1,0,1,0,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,2,2,1.0,0.5,0.666667,50.0,Valid,Buy,ROP

This is the ticker:

AXP

2021-10-22



AXP has reported earnings 103 times, as of the current date.


model has been put to sleep after the daily adjusted call


1. Retrieve the historical earnings report for the stock:

This dataframe contains AXP's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None          1.8     None               None
1    2021-07-23         2.8        1.623    1.177              72.52
2    2021-04-23        2.74       1.6178   1.1222            69.3658
3    2021-01-26        1.76       1.3021   0.4579            35.1663
4    2020-10-23         1.3        1.352   -0.052            -3.8462
5    2020-07-24        0.29       0.0239   0.2661          1113.3891
6    2020-04-24        0.41       1.6718  -1.2618           -75.4755
7    2020-01-24        2.03       2.0116   0.0184             0.9147
8    2019-10-18        2.08       2.0244   0.0556             2.7465
9    2019-07-19        2.07       2.0246   0.0454             2.2424
10   2019-04-18        2.01       1.9712   0.0388             1.9683
11   2019-01-17        1.74        1.797   -0.057             -3.172
12   2018-10-18        1.88       1.7652   0.1148             6.5035
13   2018-07-18        1.84        1.816    0.024             1.3216
14   2018-04-18        1.86       1.7105   0.1495             8.7401

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AXP's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,2.27,1.792578,0.477422,26.6332,0,1
1,2021-07-23,2.80,1.623000,1.177,72.5200,1,1
2,2021-04-23,2.74,1.617800,1.1222,69.3658,1,1
3,2021-01-26,1.76,1.302100,0.4579,35.1663,1,1
4,2020-10-23,1.30,1.352000,-0.052,-3.8462,1,0
5,2020-07-24,0.29,0.023900,0.2661,1113.3891,0,1
6,2020-04-24,0.41,1.671800,-1.2618,-75.4755,0,0
7,2020-01-24,2.03,2.011600,0.0184,0.9147,0,1
8,2019-10-18,2.08,2.024400,0.0556,2.7465,1,1
9,2019-07-19,2.07,2.024600,0.0454,2.2424,1,1
10,2019-04-18,2.01,1.971200,0.0388,1.9683,1,1
11,2019-01-17,1.74,1.797000,-0.057,-3.1720,0,0
12,2018-10-18,1.88,1.765200,0.1148,6.5035,1,1
13,2018-07-18,1.84,1.816000,0.024,1.3216,0,1
14,2018-04-18,1.86,1.710500,0.1495,8.7401,1,1

3. Retrieve the last 5,000 daily adjusted prices for AXP in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,185.00,189.0300,182.20,187.08,187.080000,6012961,0.00,1.0,1.1243,0.7062,2021-10-22
1,179.58,179.7900,176.01,177.47,177.470000,3313778,0.00,1.0,-1.1750,0.7062,2021-10-21
2,176.95,179.7700,176.21,179.60,179.600000,2398543,0.00,1.0,1.4976,0.2982,2021-10-20
3,177.73,178.0000,176.26,177.31,177.310000,1400085,0.00,1.0,-0.2363,0.7062,2021-10-19
4,175.58,177.6050,174.33,176.82,176.820000,2623346,0.00,1.0,0.7062,0.2982,2021-10-18
5,173.77,177.7700,173.15,175.81,175.810000,3043939,0.00,1.0,1.1740,0.2982,2021-10-15
6,171.00,172.3800,169.81,171.51,171.510000,3062078,0.00,1.0,0.2982,-0.6895,2021-10-14
7,172.78,174.0861,167.08,168.72,168.720000,5608682,0.00,1.0,-2.3498,0.2453,2021-10-13
8,173.61,176.5600,173.10,174.91,174.910000,3069585,0.00,1.0,0.7488,0.2453,2021-10-12
9,175.79,176.7900,173.33,173.46,173.460000,2499347,0.00,1.0,-1.3254,0.2453,2021-10-11
10,173.85,176.9800,173.53,175.15,175.150000,2375299,0.00,1.0,0.7478,0.2453,2021-10-08
11,175.50,176.8681,173.70,174.29,174.290000,3578801,0.43,1.0,-0.6895,0.2453,2021-10-07
12,172.55,174.9000,169.90,173.40,172.973249,2922239,0.00,1.0,0.2453,-0.9460,2021-10-06
13,173.43,176.0600,172.64,174.76,174.329902,2629648,0.00,1.0,0.5189,-1.0250,2021-10-05
14,173.88,177.2300,171.88,172.66,172.235070,3613872,0.00,1.0,-0.9460,-1.0250,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58541363,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,185.00,189.03,182.20,187.08,187.080000,6012961,0.0,1.0,1.1243,0.7062,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
64,176.53,179.67,172.95,173.18,172.753790,6326617,0.0,1.0,-2.1391,-1.0279,2021-07-23,0,1,0.2288,-0.1574,438.521197,1
127,141.54,144.98,140.68,144.33,143.604898,6400505,0.0,1.0,1.4589,-0.7788,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
188,118.75,120.29,115.72,116.15,115.216197,8932506,0.0,1.0,-2.9758,-0.4884,2021-01-26,0,1,-1.3930,-0.8136,380.041108,0
251,100.63,103.64,100.00,100.98,99.815366,8921228,0.0,1.0,-0.8095,-0.9613,2020-10-23,1,1,-1.4416,-1.5711,340.943239,1
315,95.30,97.15,93.30,95.33,93.850033,4790446,0.0,1.0,-1.5215,-0.8024,2020-07-24,0,1,-1.8180,-1.8454,315.115236,1
378,84.13,84.78,81.31,83.17,81.506164,9125401,0.0,1.0,-3.1188,-2.6725,2020-04-24,0,0,-1.4492,-2.5822,276.661622,1
441,136.36,138.13,133.85,135.11,131.668538,8611025,0.0,1.0,-3.4405,-2.4953,2020-01-24,0,1,-3.8991,-2.7088,319.477973,0
507,119.73,119.98,116.67,116.76,113.398485,6188096,0.0,1.0,-5.2882,-2.6699,2019-10-18,0,0,-3.5328,-3.2931,288.138014,0
571,126.80,128.00,123.80,124.82,120.765052,7819016,0.0,1.0,-4.7594,-3.0072,2019-07-19,0,1,-4.6669,-3.8676,286.037580,0
634,112.25,114.14,111.32,113.67,109.637543,6186823,0.0,1.0,-2.3274,-3.8866,2019-04-18,1,1,-4.2390,-4.4182,277.802701,1
697,99.41,100.24,98.57,99.49,95.621927,5693263,0.0,1.0,-3.8106,-3.4313,2019-01-17,0,0,-3.5486,-4.1495,250.783334,1
758,104.53,104.76,102.29,102.84,98.430807,4538224,0.0,1.0,-5.8349,-4.5015,2018-10-18,0,1,-6.2139,-5.4769,262.038329,0
823,101.55,103.07,101.42,102.98,98.209305,5923812,0.0,1.0,-3.2897,-4.5194,2018-07-18,1,1,-5.4553,-5.4815,265.254697,1
886,94.04,95.24,94.00,95.15,90.420846,4981434,0.0,1.0,-3.8485,-5.1526,2018-04-18,1,0,-6.1499,-5.9296,254.042889,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,2.27,1.792578,0.477422,26.6332,187.080000,1.1243,0.7062,453.120000,-0.0022,0.3831,0.000000,-100.00,0,1,1,1,0,0
1,2021-07-23,2.80,1.623000,1.177,72.5200,172.753790,-2.1391,-1.0279,438.521197,0.2288,-0.1574,172.185193,-0.33,1,1,1,0,1,0
2,2021-04-23,2.74,1.617800,1.1222,69.3658,143.604898,1.4589,-0.7788,414.023116,0.2793,-0.9025,149.584704,4.16,1,1,1,1,1,1
3,2021-01-26,1.76,1.302100,0.4579,35.1663,115.216197,-2.9758,-0.4884,380.041108,-1.3930,-0.8136,113.172758,-1.77,1,1,1,0,0,0
4,2020-10-23,1.30,1.352000,-0.052,-3.8462,99.815366,-0.8095,-0.9613,340.943239,-1.4416,-1.5711,95.762653,-4.06,1,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2001-01-22,0.50,0.500000,0,0.0000,29.458665,-39.7327,-35.8293,91.059910,-32.1714,-32.8511,30.440620,3.33,0,0,0,0,1,1
83,2000-10-23,0.54,0.550000,-0.01,-1.8182,35.548322,-37.1494,-33.6714,94.559730,-32.4272,-31.9681,37.346003,5.06,0,0,0,0,0,0
84,2000-07-24,0.54,0.530000,0.01,1.8868,37.251293,-37.1286,-34.7985,98.553894,-33.4657,-33.2681,36.480937,-2.07,1,1,1,0,0,0
85,2000-04-24,0.48,0.470000,0.01,2.1277,32.613924,-77.1611,-78.1207,95.244471,-32.6894,-32.9277,34.330446,5.26,1,1,0,1,1,0
86,2000-01-24,0.44,0.440000,0,0.0000,33.008292,-78.6077,-78.4685,93.731549,-35.6488,-33.0135,34.398115,4.21,0,0,0,0,0,1

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,1,0,0
1,1,1,1,0,1,0
2,1,1,1,1,1,1
3,1,1,1,0,0,0
4,1,0,1,1,1,0
...,...,...,...,...,...,...
82,0,0,0,0,1,1
83,0,0,0,0,0,0
84,1,1,1,0,0,0
85,1,1,0,1,1,0
86,0,0,0,0,0,1

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,AXP

This is the ticker:

SMPL

2021-10-22



SMPL has reported earnings 20 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains SMPL's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.25     None               None
1    2021-07-01        0.43       0.2832   0.1468            51.8362
2    2021-04-07        0.25       0.2248   0.0252              11.21
3    2021-01-06        0.29       0.2094   0.0806            38.4909
4    2020-10-26         0.2       0.1609   0.0391            24.3008
5    2020-07-08        0.26       0.1518   0.1082             71.278
6    2020-04-06        0.18       0.1671   0.0129             7.7199
7    2020-01-09        0.19        0.195   -0.005            -2.5641
8    2019-10-29      0.0962       0.1517  -0.0555           -36.5854
9    2019-07-02      0.1663       0.1331   0.0332            24.9437
10   2019-04-04      0.1526       0.1291   0.0235            18.2029
11   2019-01-03      0.1972        0.186   0.0112             6.0215
12   2018-10-24      0.1581       0.1277   0.0304            23.8058
13   2018-07-10       0.106       0.0959   0.0101            10.5318
14   2018-04-10      0.1426        0.138   0.0046             3.3333

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is SMPL's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.2900,0.2601,0.0299,11.4956,0,1
1,2021-07-01,0.4300,0.2832,0.1468,51.8362,1,1
2,2021-04-07,0.2500,0.2248,0.0252,11.2100,0,1
3,2021-01-06,0.2900,0.2094,0.0806,38.4909,1,1
4,2020-10-26,0.2000,0.1609,0.0391,24.3008,0,1
5,2020-07-08,0.2600,0.1518,0.1082,71.2780,1,1
6,2020-04-06,0.1800,0.1671,0.0129,7.7199,0,1
7,2020-01-09,0.1900,0.1950,-0.005,-2.5641,1,0
8,2019-10-29,0.0962,0.1517,-0.0555,-36.5854,0,0
9,2019-07-02,0.1663,0.1331,0.0332,24.9437,1,1
10,2019-04-04,0.1526,0.1291,0.0235,18.2029,0,1
11,2019-01-03,0.1972,0.1860,0.0112,6.0215,1,1
12,2018-10-24,0.1581,0.1277,0.0304,23.8058,1,1
13,2018-07-10,0.1060,0.0959,0.0101,10.5318,0,1
14,2018-04-10,0.1426,0.1380,0.0046,3.3333,0,1

3. Retrieve the last 5,000 daily adjusted prices for SMPL in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,35.690,37.360,34.450,37.27,37.27,1025874,0.0,1.0,4.4270,-1.0145,2021-10-22
1,34.795,34.795,33.880,34.31,34.31,592524,0.0,1.0,-1.3939,-0.3132,2021-10-21
2,34.500,35.080,34.120,34.15,34.15,418708,0.0,1.0,-1.0145,-0.3132,2021-10-20
3,35.120,35.180,34.300,34.50,34.50,191972,0.0,1.0,-1.7654,-0.1442,2021-10-19
4,34.900,35.450,34.560,35.23,35.23,174927,0.0,1.0,0.9456,-0.1442,2021-10-18
5,35.120,35.750,34.800,35.01,35.01,339074,0.0,1.0,-0.3132,-0.1442,2021-10-15
6,34.680,35.010,34.350,34.63,34.63,290962,0.0,1.0,-0.1442,-0.0282,2021-10-14
7,35.210,35.620,34.230,34.45,34.45,244359,0.0,1.0,-2.1585,0.3967,2021-10-13
8,35.290,35.750,35.200,35.43,35.43,222366,0.0,1.0,0.3967,-0.0282,2021-10-12
9,35.420,35.730,35.340,35.41,35.41,108605,0.0,1.0,-0.0282,-0.1977,2021-10-11
10,36.160,36.160,35.410,35.49,35.49,163225,0.0,1.0,-1.8529,0.5833,2021-10-08
11,36.000,36.870,36.000,36.21,36.21,296176,0.0,1.0,0.5833,-0.1977,2021-10-07
12,34.880,35.960,34.820,35.89,35.89,279691,0.0,1.0,2.8956,-0.1977,2021-10-06
13,35.350,35.740,35.070,35.17,35.17,416246,0.0,1.0,-0.5092,-0.1977,2021-10-05
14,35.400,35.810,35.031,35.33,35.33,214238,0.0,1.0,-0.1977,0.3714,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58548809,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,35.69,37.3600,34.4500,37.270,37.270,1025874,0.0,1.0,4.4270,-1.0145,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
79,38.50,38.5000,35.8200,37.170,37.170,1123071,0.0,1.0,-3.4545,-0.0821,2021-07-01,0,1,0.0401,-0.2525,429.041867,1
139,31.45,32.6700,31.3200,31.480,31.480,971302,0.0,1.0,0.0954,0.3381,2021-04-07,0,1,-0.4929,-0.4032,403.939288,0
201,30.50,30.9900,29.1900,30.060,30.060,1443878,0.0,1.0,-1.4426,1.7080,2021-01-06,0,1,0.0517,-1.0699,369.901133,1
250,20.51,21.4399,19.9400,20.080,20.080,1537724,0.0,1.0,-2.0965,-0.1437,2020-10-26,0,0,-2.1885,-1.4416,334.642622,0
327,22.30,22.9000,21.4200,22.180,22.180,3830200,0.0,1.0,-0.5381,1.2910,2020-07-08,0,1,-1.3065,-1.5855,310.499674,1
391,19.51,20.0000,16.6300,17.140,17.140,2827914,0.0,1.0,-12.1476,4.9776,2020-04-06,0,0,0.4326,-2.9509,258.955357,1
451,26.95,27.1000,24.6400,24.840,24.840,4661684,0.0,1.0,-7.8293,0.0360,2020-01-09,0,1,-2.6803,-2.4268,317.417890,0
500,24.25,24.5000,22.6600,23.635,23.635,1826720,0.0,1.0,-2.5361,-1.1618,2019-10-29,0,0,-3.2326,-3.1847,293.205112,0
583,25.58,26.0000,24.4650,25.380,25.380,1726918,0.0,1.0,-0.7819,0.0000,2019-07-02,0,1,-3.4791,-4.0771,285.325302,1
644,22.40,23.2800,21.4850,22.110,22.110,1074155,0.0,1.0,-1.2946,0.6813,2019-04-04,0,1,-4.0790,-4.1820,275.082338,1
707,17.86,20.5900,17.6600,19.920,19.920,1368984,0.0,1.0,11.5342,1.3948,2019-01-03,1,1,-6.1751,-3.0022,232.901574,0
754,18.79,19.5800,17.7134,18.330,18.330,2067329,0.0,1.0,-2.4481,0.5294,2018-10-24,0,1,-7.9742,-5.4970,251.534043,0
829,16.96,17.0000,15.7100,16.880,16.880,4892978,0.0,1.0,-0.4717,0.0665,2018-07-10,0,1,-5.4574,-5.1628,263.216164,0
892,13.50,13.5329,12.6000,12.900,12.900,1063893,0.0,1.0,-4.4444,-0.0759,2018-04-10,0,0,-5.7329,-6.0139,249.119686,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.2900,0.2601,0.0299,11.4956,37.270,4.4270,-1.0145,453.120000,-0.0022,0.3831,0.00,-100.00,0,1,1,1,0,0
1,2021-07-01,0.4300,0.2832,0.1468,51.8362,37.170,-3.4545,-0.0821,429.041867,0.0401,-0.2525,37.51,0.91,1,1,1,0,1,0
2,2021-04-07,0.2500,0.2248,0.0252,11.2100,31.480,0.0954,0.3381,403.939288,-0.4929,-0.4032,31.76,0.89,0,1,1,0,0,0
3,2021-01-06,0.2900,0.2094,0.0806,38.4909,30.060,-1.4426,1.7080,369.901133,0.0517,-1.0699,30.07,0.03,1,1,1,0,1,0
4,2020-10-26,0.2000,0.1609,0.0391,24.3008,20.080,-2.0965,-0.1437,334.642622,-2.1885,-1.4416,20.24,0.80,0,1,0,0,0,0
5,2020-07-08,0.2600,0.1518,0.1082,71.2780,22.180,-0.5381,1.2910,310.499674,-1.3065,-1.5855,21.31,-3.92,1,1,1,0,1,0
6,2020-04-06,0.1800,0.1671,0.0129,7.7199,17.140,-12.1476,4.9776,258.955357,0.4326,-2.9509,17.02,-0.70,0,1,0,0,1,0
7,2020-01-09,0.1900,0.1950,-0.005,-2.5641,24.840,-7.8293,0.0360,317.417890,-2.6803,-2.4268,24.02,-3.30,1,0,1,0,0,0
8,2019-10-29,0.0962,0.1517,-0.0555,-36.5854,23.635,-2.5361,-1.1618,293.205112,-3.2326,-3.1847,24.26,2.64,0,0,0,0,0,1
9,2019-07-02,0.1663,0.1331,0.0332,24.9437,25.380,-0.7819,0.0000,285.325302,-3.4791,-4.0771,26.67,5.08,1,1,1,0,1,0
10,2019-04-04,0.1526,0.1291,0.0235,18.2029,22.110,-1.2946,0.6813,275.082338,-4.0790,-4.1820,22.73,2.80,0,1,1,0,1,1
11,2019-01-03,0.1972,0.1860,0.0112,6.0215,19.920,11.5342,1.3948,232.901574,-6.1751,-3.0022,19.11,-4.07,1,1,1,1,0,0
12,2018-10-24,0.1581,0.1277,0.0304,23.8058,18.330,-2.4481,0.5294,251.534043,-7.9742,-5.4970,17.74,-3.22,1,1,1,0,0,0
13,2018-07-10,0.1060,0.0959,0.0101,10.5318,16.880,-0.4717,0.0665,263.216164,-5.4574,-5.1628,17.04,0.95,0,1,1,0,0,0
14,2018-04-10,0.1426,0.1380,0.0046,3.3333,12.900,-4.4444,-0.0759,249.119686,-5.7329,-6.0139,12.95,0.39,0,1,0,0,1,0
15,2018-01-09,0.1640,0.1533,0.0107,6.9798,14.220,-11.1250,-0.7057,256.914351,-6.3723,-6.1076,13.97,-1.76,1,1,1,0,0,0
16,2017-11-08,0.1061,0.0700,0.0361,51.5714,11.950,1.0998,0.3422,241.251706,-6.6616,-6.8271,11.94,-0.08,0,1,0,1,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,1,0,0
1,1,1,1,0,1,0
2,0,1,1,0,0,0
3,1,1,1,0,1,0
4,0,1,0,0,0,0
5,1,1,1,0,1,0
6,0,1,0,0,1,0
7,1,0,1,0,0,0
8,0,0,0,0,0,1
9,1,1,1,0,1,0
10,0,1,1,0,1,1
11,1,1,1,1,0,0
12,1,1,1,0,0,0
13,0,1,1,0,0,0
14,0,1,0,0,1,0
15,1,1,1,0,0,0
16,0,1,0,1,1,0

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,SMPL

This is the ticker:

GNTX

2021-10-22




Model has been put to sleep after historical earnings call
GNTX has reported earnings 103 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains GNTX's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.38     None               None
1    2021-07-23        0.36       0.4347  -0.0747           -17.1843
2    2021-04-23        0.46         0.49    -0.03            -6.1224
3    2021-01-29        0.58       0.4994   0.0806            16.1394
4    2020-10-23        0.48       0.4116   0.0684            16.6181
5    2020-07-24        0.02       0.1274  -0.1074           -84.3014
6    2020-04-24        0.36       0.3487   0.0113             3.2406
7    2020-01-31        0.39       0.3733   0.0167             4.4736
8    2019-10-18        0.44       0.4213   0.0187             4.4386
9    2019-07-19        0.42       0.3983   0.0217             5.4482
10   2019-04-24         0.4       0.3939   0.0061             1.5486
11   2019-01-30        0.41       0.4361  -0.0261            -5.9849
12   2018-10-19        0.42       0.4111   0.0089             2.1649
13   2018-07-20         0.4       0.4053  -0.0053            -1.3077
14   2018-04-20         0.4       0.3986   0.0014             0.3512

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is GNTX's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.32,0.394873,-0.0748726,-18.9612,0,0
1,2021-07-23,0.36,0.434700,-0.0747,-17.1843,0,0
2,2021-04-23,0.46,0.490000,-0.03,-6.1224,0,0
3,2021-01-29,0.58,0.499400,0.0806,16.1394,1,1
4,2020-10-23,0.48,0.411600,0.0684,16.6181,1,1
5,2020-07-24,0.02,0.127400,-0.1074,-84.3014,0,0
6,2020-04-24,0.36,0.348700,0.0113,3.2406,0,1
7,2020-01-31,0.39,0.373300,0.0167,4.4736,0,1
8,2019-10-18,0.44,0.421300,0.0187,4.4386,1,1
9,2019-07-19,0.42,0.398300,0.0217,5.4482,1,1
10,2019-04-24,0.40,0.393900,0.0061,1.5486,0,1
11,2019-01-30,0.41,0.436100,-0.0261,-5.9849,0,0
12,2018-10-19,0.42,0.411100,0.0089,2.1649,1,1
13,2018-07-20,0.40,0.405300,-0.0053,-1.3077,0,0
14,2018-04-20,0.40,0.398600,0.0014,0.3512,1,1

3. Retrieve the last 5,000 daily adjusted prices for GNTX in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,36.2600,36.9200,34.2100,34.36,34.360000,2555516,0.00,1.0,-5.2399,0.2952,2021-10-22
1,36.5300,36.8999,36.4800,36.86,36.860000,1199598,0.00,1.0,0.9034,0.2952,2021-10-21
2,36.2900,36.7100,35.9400,36.43,36.430000,1577416,0.00,1.0,0.3858,-0.3820,2021-10-20
3,36.6500,36.9600,36.4500,36.51,36.510000,1565700,0.00,1.0,-0.3820,0.2952,2021-10-19
4,37.1900,37.2900,36.5700,36.66,36.660000,1478157,0.00,1.0,-1.4251,1.3249,2021-10-18
5,37.2600,37.4600,37.1100,37.37,37.370000,2214486,0.00,1.0,0.2952,1.3249,2021-10-15
6,36.1055,37.2600,36.1055,37.06,37.060000,2160880,0.00,1.0,2.6436,1.3249,2021-10-14
7,36.7000,36.7300,36.0900,36.28,36.280000,2213433,0.00,1.0,-1.1444,1.3249,2021-10-13
8,36.2300,36.7700,36.1900,36.71,36.710000,2286805,0.00,1.0,1.3249,1.3199,2021-10-12
9,35.4100,36.3700,35.3800,36.36,36.360000,2316878,0.00,1.0,2.6829,0.5182,2021-10-11
10,34.8500,35.3300,34.5400,35.31,35.310000,1232354,0.00,1.0,1.3199,0.4669,2021-10-08
11,34.2000,34.7950,33.9600,34.71,34.710000,1828920,0.12,1.0,1.4912,0.4259,2021-10-07
12,33.6300,33.9200,33.2700,33.89,33.773239,1647541,0.00,1.0,0.4259,0.2853,2021-10-06
13,33.7000,33.9800,33.5100,33.91,33.793170,1297852,0.00,1.0,0.2765,0.2853,2021-10-05
14,33.5000,33.8600,33.4000,33.79,33.673583,1530336,0.00,1.0,0.5182,0.2853,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58548809,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,36.26,36.92,34.21,34.36,34.360000,2555516,0.0,1.0,-5.2399,0.2952,2021-10-22,0,1,-0.0022,0.3831,453.120000,0
64,32.30,32.65,31.51,32.37,32.258475,1488293,0.0,1.0,-0.1286,-0.6224,2021-07-23,1,0,0.2288,-0.1574,438.521197,1
127,35.15,35.67,34.75,35.35,35.098135,1480749,0.0,1.0,-0.1476,-1.3728,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
185,34.26,34.73,32.95,33.05,32.703787,2710594,0.0,1.0,-4.5424,-2.6702,2021-01-29,0,1,-2.4425,-0.8136,366.455126,0
251,30.19,30.61,29.33,29.44,29.036815,3290534,0.0,1.0,-3.8198,-0.9993,2020-10-23,0,1,-1.4416,-1.5711,340.943239,1
315,25.81,26.60,25.32,26.29,25.816185,3651960,0.0,1.0,0.0240,-1.9525,2020-07-24,1,1,-1.8180,-1.8454,315.115236,1
378,23.49,24.74,23.35,24.13,23.581514,2829626,0.0,1.0,0.3896,-1.2292,2020-04-24,1,0,-1.4492,-2.5822,276.661622,1
436,30.37,30.57,29.43,29.77,28.946871,2689241,0.0,1.0,-4.6860,-2.7650,2020-01-31,0,1,-4.3924,-2.6849,312.636944,0
507,27.63,28.91,27.07,27.96,27.081096,2968595,0.0,1.0,-1.9866,-1.8817,2019-10-18,0,1,-3.5328,-3.2931,288.138014,0
571,24.97,25.90,24.44,25.82,24.896307,5312576,0.0,1.0,-0.2951,-3.6592,2019-07-19,1,1,-4.6669,-3.8676,286.037580,0
631,22.75,23.56,22.22,23.42,22.472705,2507168,0.0,1.0,-1.2189,-3.7399,2019-04-24,1,1,-4.3958,-4.2390,279.919603,0
689,21.40,22.41,20.90,22.25,21.233805,5593370,0.0,1.0,-0.7766,-4.2705,2019-01-30,1,1,-3.7384,-4.5696,255.189399,1
757,18.15,20.04,17.80,19.93,18.920749,7347500,0.0,1.0,4.2465,-6.1051,2018-10-19,1,0,-5.4970,-5.4769,261.896123,0
821,22.67,23.40,21.92,22.23,20.993678,5145725,0.0,1.0,-7.3945,-5.0034,2018-07-20,0,1,-5.6538,-5.4815,263.952301,0
884,22.13,23.15,21.82,21.99,20.668815,4506452,0.0,1.0,-6.6027,-7.2318,2018-04-20,1,0,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.32,0.394873,-0.0748726,-18.9612,34.360000,-5.2399,0.2952,453.120000,-0.0022,0.3831,0.000000,-100.00,0,0,1,0,0,0
1,2021-07-23,0.36,0.434700,-0.0747,-17.1843,32.258475,-0.1286,-0.6224,438.521197,0.2288,-0.1574,32.148854,-0.34,0,0,0,1,1,0
2,2021-04-23,0.46,0.490000,-0.03,-6.1224,35.098135,-0.1476,-1.3728,414.023116,0.2793,-0.9025,35.227209,0.37,0,0,1,1,1,0
3,2021-01-29,0.58,0.499400,0.0806,16.1394,32.703787,-4.5424,-2.6702,366.455126,-2.4425,-0.8136,33.643835,2.87,1,1,1,0,0,1
4,2020-10-23,0.48,0.411600,0.0684,16.6181,29.036815,-3.8198,-0.9993,340.943239,-1.4416,-1.5711,28.356265,-2.34,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2001-01-24,0.06,0.060000,0,0.0000,4.104451,-82.8981,-83.4180,92.051328,-32.4394,-32.1714,4.089255,-0.37,1,0,1,1,0,0
84,2000-10-17,0.05,0.060000,-0.01,-16.6667,3.704305,-85.2594,-83.4825,90.669711,-34.5049,-33.2474,3.640146,-1.73,0,0,0,0,0,0
85,2000-07-18,0.06,0.060000,0,0.0000,4.759542,-82.9651,-83.3373,100.514915,-33.2681,-32.8782,4.600834,-3.33,0,0,0,1,0,0
86,2000-04-17,0.06,0.060000,0,0.0000,5.402815,-84.2254,-82.9726,94.240135,-30.2893,-34.5057,5.421387,0.34,0,0,1,0,1,0
87,2000-01-25,0.06,0.060000,0,0.0000,5.154623,-83.9219,-83.1524,94.796000,-32.5370,-33.7006,5.065139,-1.74,1,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,1,0,0,0
1,0,0,0,1,1,0
2,0,0,1,1,1,0
3,1,1,1,0,0,1
4,1,1,1,0,1,0
...,...,...,...,...,...,...
83,1,0,1,1,0,0
84,0,0,0,0,0,0
85,0,0,0,1,0,0
86,0,0,1,0,1,0
87,1,0,0,0,1,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,GNTX

This is the ticker:

STX

2021-10-22



STX has reported earnings 74 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains STX's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22           2         2.22    -0.22            -9.9099
1    2021-07-21           2       1.8814   0.1186             6.3038
2    2021-04-22        1.48       1.3181   0.1619            12.2828
3    2021-01-21        1.29       1.1339   0.1561            13.7666
4    2020-10-22        0.93       0.9022   0.0278             3.0814
5    2020-07-28         1.2       1.2959  -0.0959            -7.4003
6    2020-02-04        1.35       1.3285   0.0215             1.6184
7    2019-11-01        1.03       1.0118   0.0182             1.7988
8    2019-08-02        0.86        0.837    0.023             2.7479
9    2019-06-28      3.5394         None     None               None
10   2019-04-30        0.83       0.7126   0.1174            16.4749
11   2018-11-02         1.7       1.5421   0.1579            10.2393
12   2018-09-28        1.54         1.46     0.08             5.4795
13   2018-05-01        1.46       1.3333   0.1267             9.5027
14   2018-03-30        1.31         1.33    -0.02            -1.5038

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is STX's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,2.35,2.232777,0.117223,5.2501,1,1
1,2021-07-21,2.00,1.881400,0.1186,6.3038,1,1
2,2021-04-22,1.48,1.318100,0.1619,12.2828,1,1
3,2021-01-21,1.29,1.133900,0.1561,13.7666,1,1
4,2020-10-22,0.93,0.902200,0.0278,3.0814,0,1
5,2020-07-28,1.20,1.295900,-0.0959,-7.4003,0,0
6,2020-02-04,1.35,1.328500,0.0215,1.6184,1,1
7,2019-11-01,1.03,1.011800,0.0182,1.7988,1,1
8,2019-08-02,0.86,0.837000,0.023,2.7479,1,1
10,2019-04-30,0.83,0.712600,0.1174,16.4749,0,1
11,2018-11-02,1.70,1.542100,0.1579,10.2393,1,1
12,2018-09-28,1.54,1.460000,0.08,5.4795,1,1
13,2018-05-01,1.46,1.333300,0.1267,9.5027,1,1
14,2018-03-30,1.31,1.330000,-0.02,-1.5038,0,0
15,2018-01-29,1.48,1.345200,0.1348,10.0208,1,1

3. Retrieve the last 5,000 daily adjusted prices for STX in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,86.50,88.9700,85.10,87.23,87.23,5172515,0.0,1.0,0.8439,-0.1843,2021-10-22
1,80.15,82.2500,79.84,82.24,82.24,2606339,0.0,1.0,2.6076,-0.1843,2021-10-21
2,81.23,82.1893,80.48,80.53,80.53,1983381,0.0,1.0,-0.8618,-0.1600,2021-10-20
3,81.25,81.5100,79.84,81.12,81.12,2425549,0.0,1.0,-0.1600,-0.1843,2021-10-19
4,81.39,82.2133,80.79,81.24,81.24,1911840,0.0,1.0,-0.1843,0.4291,2021-10-18
5,82.46,83.3000,81.72,81.99,81.99,1733209,0.0,1.0,-0.5700,0.4291,2021-10-15
6,80.50,83.4900,80.32,82.50,82.50,2105233,0.0,1.0,2.4845,0.4291,2021-10-14
7,79.23,80.3000,78.76,79.57,79.57,1357399,0.0,1.0,0.4291,-0.6899,2021-10-13
8,81.95,82.1000,78.20,79.01,79.01,2558116,0.0,1.0,-3.5876,0.5162,2021-10-12
9,79.85,82.2150,79.70,81.63,81.63,2514382,0.0,1.0,2.2292,-0.1069,2021-10-11
10,82.23,82.5500,79.84,79.93,79.93,1985705,0.0,1.0,-2.7970,0.5162,2021-10-08
11,81.36,82.6300,80.67,81.78,81.78,2111259,0.0,1.0,0.5162,-0.1069,2021-10-07
12,81.17,81.9500,79.36,80.61,80.61,4414089,0.0,1.0,-0.6899,-0.1069,2021-10-06
13,84.43,85.7800,82.83,85.15,85.15,2084958,0.0,1.0,0.8528,-1.0007,2021-10-05
14,84.23,85.7100,83.58,84.14,84.14,2131665,0.0,1.0,-0.1069,-1.0007,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58554099,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,86.50,88.97,85.10,87.23,87.230000,5172515,0.0,1.0,0.8439,-0.1843,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
66,81.75,83.99,78.86,82.60,81.927067,6407581,0.0,1.0,0.2166,-0.6817,2021-07-21,1,0,0.1870,-0.5868,433.148580,1
128,84.12,85.07,83.13,84.08,82.755931,4529337,0.0,1.0,-1.6216,-1.0321,2021-04-22,0,1,-1.5167,-0.6496,409.582258,0
191,61.42,63.01,61.15,62.94,61.382362,6147643,0.0,1.0,-0.0613,-2.4350,2021-01-21,1,1,-1.0412,-0.8957,380.486712,0
252,51.30,52.10,51.23,51.79,49.982664,3960272,0.0,1.0,-2.5679,-2.5807,2020-10-22,1,1,-0.9244,-1.5711,339.789605,1
313,49.57,50.07,48.32,48.57,46.244993,4440318,0.0,1.0,-6.7077,-3.8727,2020-07-28,0,0,-2.1803,-1.8180,315.400026,0
434,59.54,59.85,58.04,58.97,54.593647,4698163,0.0,1.0,-8.3076,-7.5322,2020-02-04,0,1,-2.5331,-2.5949,319.759776,1
497,55.50,58.19,54.61,57.62,52.767289,4875688,0.0,1.0,-4.9238,-7.6866,2019-11-01,1,1,-2.9128,-3.1847,296.038432,1
561,42.22,46.32,42.10,44.93,40.652184,5655196,0.0,1.0,-3.7134,-9.9384,2019-08-02,1,0,-4.1490,-3.8801,281.658030,0
627,47.23,48.83,46.07,48.32,43.122729,7424453,0.0,1.0,-8.6963,-12.1586,2019-04-30,1,1,-4.0396,-4.0951,281.634198,1
747,41.00,44.84,40.55,44.27,38.341536,10706038,0.0,1.0,-6.4841,-11.0533,2018-11-02,1,0,-6.1828,-5.2030,257.762667,0
772,46.34,47.78,46.29,47.35,41.009074,3493915,0.0,1.0,-11.5039,-14.6414,2018-09-28,1,0,-4.9573,-5.4496,275.614266,1
877,51.91,54.39,49.08,54.21,45.843533,15641511,0.0,1.0,-11.6865,-15.7449,2018-05-01,1,0,-5.6505,-6.2006,248.959964,1
941,54.00,55.62,53.51,55.11,46.119649,8889515,0.0,1.0,-14.5932,-15.2453,2018-01-29,1,1,-6.8292,-6.2380,266.403357,0
1007,39.65,40.90,37.64,39.35,32.446037,33542604,0.0,1.0,-18.1689,-17.1824,2017-10-23,0,1,-7.3876,-6.8046,238.458471,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,2.35,2.232777,0.117223,5.2501,87.230000,0.8439,-0.1843,453.120000,-0.0022,0.3831,0.000000,-100.00,1,1,1,1,0,0
1,2021-07-21,2.00,1.881400,0.1186,6.3038,81.927067,0.2166,-0.6817,433.148580,0.1870,-0.5868,82.462668,0.65,1,1,0,1,1,0
2,2021-04-22,1.48,1.318100,0.1619,12.2828,82.755931,-1.6216,-1.0321,409.582258,-1.5167,-0.6496,87.746090,6.03,1,1,1,0,0,0
3,2021-01-21,1.29,1.133900,0.1561,13.7666,61.382362,-0.0613,-2.4350,380.486712,-1.0412,-0.8957,58.515121,-4.67,1,1,1,1,0,0
4,2020-10-22,0.93,0.902200,0.0278,3.0814,49.982664,-2.5679,-2.5807,339.789605,-0.9244,-1.5711,48.969306,-2.03,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2004-10-19,0.08,0.040000,0.04,100.0000,7.689162,-45.4669,-46.7064,79.046937,-29.4350,-28.4650,7.408181,-3.65,1,1,0,1,0,0
61,2004-04-20,0.07,0.070000,0,0.0000,7.765321,-47.3538,-46.8361,79.270964,-30.5128,-28.9971,7.396308,-4.75,0,0,0,0,0,0
62,2004-01-20,0.41,0.450000,-0.04,-8.8889,10.828817,-46.3920,-47.4609,80.599359,-29.6260,-29.2921,8.579919,-20.77,1,0,0,1,0,0
63,2003-08-15,0.33,0.310000,0.02,6.4516,11.011920,-46.8023,-46.7543,69.708865,-29.8421,-29.8770,11.410902,3.62,0,1,1,0,1,1
64,2003-05-15,0.37,0.280000,0.09,32.1429,7.115337,-47.8730,-46.3948,66.312765,-30.1162,-30.1451,7.194986,1.12,0,1,0,0,1,1

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,0
1,1,1,0,1,1,0
2,1,1,1,0,0,0
3,1,1,1,1,0,0
4,0,1,1,1,1,0
...,...,...,...,...,...,...
60,1,1,0,1,0,0
61,0,0,0,0,0,0
62,1,0,0,1,0,0
63,0,1,1,0,1,1
64,0,1,0,0,1,1

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,STX

This is the ticker:

FHB

2021-10-22

Model has been put to sleep after the alpha spy


FHB has reported earnings 22 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains FHB's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.48     None               None
1    2021-07-23        0.68       0.4661   0.2139            45.8914
2    2021-04-23        0.44       0.4386   0.0014             0.3192
3    2021-01-22         0.5       0.4302   0.0698             16.225
4    2020-10-23         0.5       0.2692   0.2308            85.7355
5    2020-07-24        0.16       0.2268  -0.0668           -29.4533
6    2020-04-24         0.3       0.4328  -0.1328           -30.6839
7    2020-01-28        0.54        0.506    0.034             6.7194
8    2019-10-24        0.57       0.5379   0.0321             5.9677
9    2019-07-25        0.54         0.53     0.01             1.8868
10   2019-04-25        0.53       0.5278   0.0022             0.4168
11   2019-01-24        0.58       0.5233   0.0567            10.8351
12   2018-10-25        0.52       0.5141   0.0059             1.1476
13   2018-07-26         0.5       0.4912   0.0088             1.7915
14   2018-04-26        0.49       0.4796   0.0104             2.1685

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is FHB's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.51,0.482275,0.027725,5.7488,0,1
1,2021-07-23,0.68,0.466100,0.2139,45.8914,1,1
2,2021-04-23,0.44,0.438600,0.0014,0.3192,0,1
3,2021-01-22,0.50,0.430200,0.0698,16.2250,0,1
4,2020-10-23,0.50,0.269200,0.2308,85.7355,1,1
5,2020-07-24,0.16,0.226800,-0.0668,-29.4533,0,0
6,2020-04-24,0.30,0.432800,-0.1328,-30.6839,0,0
7,2020-01-28,0.54,0.506000,0.034,6.7194,0,1
8,2019-10-24,0.57,0.537900,0.0321,5.9677,1,1
9,2019-07-25,0.54,0.530000,0.01,1.8868,1,1
10,2019-04-25,0.53,0.527800,0.0022,0.4168,0,1
11,2019-01-24,0.58,0.523300,0.0567,10.8351,1,1
12,2018-10-25,0.52,0.514100,0.0059,1.1476,1,1
13,2018-07-26,0.50,0.491200,0.0088,1.7915,1,1
14,2018-04-26,0.49,0.479600,0.0104,2.1685,1,1

3. Retrieve the last 5,000 daily adjusted prices for FHB in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,29.97,30.140,29.320,29.64,29.64,752106,0.0,1.0,-1.1011,0.3470,2021-10-22
1,29.53,29.650,29.180,29.41,29.41,601484,0.0,1.0,-0.4064,0.6314,2021-10-21
2,28.77,29.490,28.715,29.49,29.49,377420,0.0,1.0,2.5026,0.3470,2021-10-20
3,28.82,28.970,28.550,28.92,28.92,361638,0.0,1.0,0.3470,0.1049,2021-10-19
4,28.51,29.010,28.440,28.69,28.69,271344,0.0,1.0,0.6314,-0.8065,2021-10-18
5,28.59,28.990,28.590,28.62,28.62,429726,0.0,1.0,0.1049,-0.8065,2021-10-15
6,28.06,28.410,27.840,28.41,28.41,541022,0.0,1.0,1.2473,-0.8065,2021-10-14
7,28.16,28.160,27.490,27.84,27.84,546101,0.0,1.0,-1.1364,-0.4086,2021-10-13
8,28.52,28.560,28.130,28.29,28.29,406359,0.0,1.0,-0.8065,-0.2360,2021-10-12
9,29.35,29.610,28.580,28.58,28.58,317232,0.0,1.0,-2.6235,0.0339,2021-10-11
10,29.04,29.400,28.990,29.22,29.22,576345,0.0,1.0,0.6198,0.0339,2021-10-08
11,29.52,29.905,29.465,29.53,29.53,411551,0.0,1.0,0.0339,-0.2360,2021-10-07
12,29.37,29.395,28.760,29.25,29.25,345406,0.0,1.0,-0.4086,0.0339,2021-10-06
13,29.66,29.790,29.320,29.59,29.59,448497,0.0,1.0,-0.2360,0.0339,2021-10-05
14,29.53,29.950,29.270,29.54,29.54,300647,0.0,1.0,0.0339,0.3389,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58554099,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,29.97,30.140,29.320,29.64,29.640000,752106,0.0,1.0,-1.1011,0.3470,2021-10-22,0,1,-0.0022,0.3831,453.120000,0
64,28.03,28.250,27.315,27.79,27.527640,632862,0.0,1.0,-1.7922,-2.6832,2021-07-23,1,1,0.2288,-0.1574,438.521197,1
127,25.01,27.370,24.750,27.14,26.638779,1492932,0.0,1.0,6.5125,-2.4594,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
190,25.07,25.860,24.930,25.13,24.434837,606075,0.0,1.0,-2.5336,-2.3483,2021-01-22,0,1,-0.8136,-1.0412,379.139997,1
251,17.01,17.980,16.940,17.78,17.081542,1979369,0.0,1.0,0.4206,-2.3147,2020-10-23,1,1,-1.4416,-1.5711,340.943239,1
315,18.14,18.340,17.420,17.64,16.679998,3559331,0.0,1.0,-8.0485,-3.1741,2020-07-24,0,1,-1.8180,-1.8454,315.115236,1
378,16.25,17.045,15.930,16.70,15.536931,1180589,0.0,1.0,-4.3881,-5.3404,2020-04-24,1,0,-1.4492,-2.5822,276.661622,1
439,28.59,28.890,28.540,28.81,26.559523,673745,0.0,1.0,-7.1021,-7.7154,2020-01-28,1,1,-2.2792,-2.7088,317.651107,1
503,28.27,28.270,27.758,27.87,25.458969,347936,0.0,1.0,-9.9435,-8.2925,2019-10-24,0,1,-3.4732,-3.4287,290.458822,0
567,26.45,26.570,26.010,26.09,23.583898,772712,0.0,1.0,-10.8359,-8.6533,2019-07-25,0,0,-4.0468,-3.4598,288.761564,0
630,26.98,27.000,26.670,26.82,24.003374,1109813,0.0,1.0,-11.0327,-10.5349,2019-04-25,0,1,-4.2355,-4.2390,279.747185,1
693,24.92,25.295,24.620,25.07,22.225256,709553,0.0,1.0,-10.8136,-10.7009,2019-01-24,0,1,-4.5074,-4.5758,251.346013,1
753,23.30,23.870,23.300,23.76,20.863057,2094773,0.0,1.0,-10.4590,-13.5240,2018-10-25,1,0,-4.2386,-5.8771,256.046715,1
817,27.99,28.400,27.890,28.28,24.627436,815884,0.0,1.0,-12.0134,-13.0367,2018-07-26,1,1,-5.5768,-5.6538,267.406482,1
880,28.27,28.510,28.050,28.28,24.424044,581655,0.0,1.0,-13.6044,-13.5126,2018-04-26,0,0,-5.5064,-6.3106,250.209555,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.51,0.482275,0.027725,5.7488,29.640000,-1.1011,0.3470,453.120000,-0.0022,0.3831,0.000000,-100.00,0,1,1,0,0,0
1,2021-07-23,0.68,0.466100,0.2139,45.8914,27.527640,-1.7922,-2.6832,438.521197,0.2288,-0.1574,27.844619,1.15,1,1,1,1,1,1
2,2021-04-23,0.44,0.438600,0.0014,0.3192,26.638779,6.5125,-2.4594,414.023116,0.2793,-0.9025,26.491549,-0.55,0,1,1,1,1,0
3,2021-01-22,0.50,0.430200,0.0698,16.2250,24.434837,-2.5336,-2.3483,379.139997,-0.8136,-1.0412,24.318157,-0.48,0,1,1,0,1,0
4,2020-10-23,0.50,0.269200,0.2308,85.7355,17.081542,0.4206,-2.3147,340.943239,-1.4416,-1.5711,16.985471,-0.56,1,1,1,1,1,0
5,2020-07-24,0.16,0.226800,-0.0668,-29.4533,16.679998,-8.0485,-3.1741,315.115236,-1.8180,-1.8454,15.980270,-4.20,0,0,1,0,1,0
6,2020-04-24,0.30,0.432800,-0.1328,-30.6839,15.536931,-4.3881,-5.3404,276.661622,-1.4492,-2.5822,16.858036,8.50,0,0,0,1,1,0
7,2020-01-28,0.54,0.506000,0.034,6.7194,26.559523,-7.1021,-7.7154,317.651107,-2.2792,-2.7088,26.836088,1.04,0,1,1,1,1,1
8,2019-10-24,0.57,0.537900,0.0321,5.9677,25.458969,-9.9435,-8.2925,290.458822,-3.4732,-3.4287,25.267136,-0.75,1,1,1,0,0,0
9,2019-07-25,0.54,0.530000,0.01,1.8868,23.583898,-10.8359,-8.6533,288.761564,-4.0468,-3.4598,24.542079,4.06,1,1,0,0,0,1
10,2019-04-25,0.53,0.527800,0.0022,0.4168,24.003374,-11.0327,-10.5349,279.747185,-4.2355,-4.2390,24.513513,2.13,0,1,1,0,1,1
11,2019-01-24,0.58,0.523300,0.0567,10.8351,22.225256,-10.8136,-10.7009,251.346013,-4.5074,-4.5758,23.040862,3.67,1,1,1,0,1,1
12,2018-10-25,0.52,0.514100,0.0059,1.1476,20.863057,-10.4590,-13.5240,256.046715,-4.2386,-5.8771,20.643538,-1.05,1,1,0,1,1,0
13,2018-07-26,0.50,0.491200,0.0088,1.7915,24.627436,-12.0134,-13.0367,267.406482,-5.5768,-5.6538,24.488101,-0.57,1,1,1,1,1,0
14,2018-04-26,0.49,0.479600,0.0104,2.1685,24.424044,-13.6044,-13.5126,250.209555,-5.5064,-6.3106,24.251314,-0.71,1,1,0,0,1,0
15,2018-01-25,0.42,0.411100,0.0089,2.1649,26.471192,-16.0710,-15.1086,265.111954,-6.7033,-6.2380,24.792657,-6.34,1,1,1,0,0,0
16,2017-10-26,0.41,0.418900,-0.0089,-2.1246,25.414539,-14.9162,-15.2550,238.002243,-7.0267,-6.9067,24.768766,-2.54,0,0,0,1,0,0
17,2017-07-27,0.41,0.407000,0.003,0.7371,25.424597,-15.2796,-15.5578,229.027879,-7.6352,-7.4186,24.649046,-3.05,0,1,1,1,0,0
18,2017-04-27,0.41,0.396100,0.0139,3.5092,25.339606,-17.4068,-16.3157,219.987432,-7.8664,-7.8046,24.904592,-1.72,1,1,0,0,0,0
19,2017-01-24,0.40,0.387800,0.0122,3.1460,27.667753,-15.3374,-16.8628,208.934851,-7.7143,-8.2252,28.373987,2.55,0,1,1,1,1,1
20,2016-10-27,0.40,0.379300,0.0207,5.4574,22.209438,-17.9252,-17.3139,194.539413,-9.3394,-8.7355,22.341539,0.59,1,1,1,0,0,0
21,2016-09-09,0.39,0.384500,0.0055,1.4304,21.903955,-16.2373,-17.6260,193.657700,-10.7445,-9.1919,22.060825,0.72,0,1,0,1,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,0,0,0
1,1,1,1,1,1,1
2,0,1,1,1,1,0
3,0,1,1,0,1,0
4,1,1,1,1,1,0
5,0,0,1,0,1,0
6,0,0,0,1,1,0
7,0,1,1,1,1,1
8,1,1,1,0,0,0
9,1,1,0,0,0,1
10,0,1,1,0,1,1
11,1,1,1,0,1,1
12,1,1,0,1,1,0
13,1,1,1,1,1,0
14,1,1,0,0,1,0
15,1,1,1,0,0,0
16,0,0,0,1,0,0
17,0,1,1,1,0,0
18,1,1,0,0,0,0
19,0,1,1,1,1,1
20,1,1,1,0,0,0
21,0,1,0,1,0,0

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,2,1,0.375,0.25,0.3,25.0,Invalid,Do NOT buy,FHB

This is the ticker:

AIMC

2021-10-22



AIMC has reported earnings 60 times, as of the current date.


model has been put to sleep after the daily adjusted call


1. Retrieve the historical earnings report for the stock:

This dataframe contains AIMC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.81     None               None
1    2021-07-23        0.89        0.815    0.075             9.2025
2    2021-04-29        0.86       0.7633   0.0967            12.6687
3    2021-02-12        0.76         0.69     0.07            10.1449
4    2020-10-23        0.87         0.46     0.41            89.1304
5    2020-07-24         0.6         0.31     0.29            93.5484
6    2020-04-30        0.65         0.54     0.11            20.3704
7    2020-02-13        0.66       0.6433   0.0167              2.596
8    2019-10-24        0.69       0.6633   0.0267             4.0253
9    2019-07-25        0.71       0.7867  -0.0767            -9.7496
10   2019-04-26         0.8       0.7225   0.0775            10.7266
11   2019-02-21        0.65       0.7133  -0.0633            -8.8742
12   2018-10-25        0.64       0.6025   0.0375             6.2241
13   2018-07-26        0.71       0.6675   0.0425              6.367
14   2018-04-27        0.66        0.576    0.084            14.5833

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AIMC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.80,0.84048,-0.04048,-4.8163,0,0
1,2021-07-23,0.89,0.81500,0.075,9.2025,1,1
2,2021-04-29,0.86,0.76330,0.0967,12.6687,1,1
3,2021-02-12,0.76,0.69000,0.07,10.1449,0,1
4,2020-10-23,0.87,0.46000,0.41,89.1304,1,1
5,2020-07-24,0.60,0.31000,0.29,93.5484,0,1
6,2020-04-30,0.65,0.54000,0.11,20.3704,0,1
7,2020-02-13,0.66,0.64330,0.0167,2.5960,0,1
8,2019-10-24,0.69,0.66330,0.0267,4.0253,0,1
9,2019-07-25,0.71,0.78670,-0.0767,-9.7496,0,0
10,2019-04-26,0.80,0.72250,0.0775,10.7266,1,1
11,2019-02-21,0.65,0.71330,-0.0633,-8.8742,1,0
12,2018-10-25,0.64,0.60250,0.0375,6.2241,0,1
13,2018-07-26,0.71,0.66750,0.0425,6.3670,1,1
14,2018-04-27,0.66,0.57600,0.084,14.5833,1,1

3. Retrieve the last 5,000 daily adjusted prices for AIMC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,52.91,55.070,51.000,54.76,54.76,445592,0.0,1.0,3.4965,0.7067,2021-10-22
1,56.60,57.150,55.890,57.00,57.00,253571,0.0,1.0,0.7067,0.5395,2021-10-21
2,55.97,57.380,55.970,57.01,57.01,150512,0.0,1.0,1.8581,0.1787,2021-10-20
3,55.95,56.380,55.250,56.05,56.05,145147,0.0,1.0,0.1787,-0.4873,2021-10-19
4,54.24,55.750,54.240,55.59,55.59,138822,0.0,1.0,2.4889,-0.5667,2021-10-18
5,55.41,55.679,54.090,55.14,55.14,354577,0.0,1.0,-0.4873,-0.5667,2021-10-15
6,53.75,54.310,53.350,54.04,54.04,231975,0.0,1.0,0.5395,-0.5667,2021-10-14
7,54.37,54.370,52.860,52.99,52.99,193745,0.0,1.0,-2.5382,-0.5667,2021-10-13
8,54.70,55.085,53.970,54.39,54.39,118328,0.0,1.0,-0.5667,-0.3206,2021-10-12
9,56.16,56.250,54.400,54.56,54.56,170354,0.0,1.0,-2.8490,-0.3206,2021-10-11
10,54.88,56.260,53.590,55.82,55.82,209190,0.0,1.0,1.7128,-0.3206,2021-10-08
11,55.05,55.820,54.705,54.94,54.94,316553,0.0,1.0,-0.1998,-0.5692,2021-10-07
12,55.12,55.450,52.940,54.26,54.26,185002,0.0,1.0,-1.5602,-0.3341,2021-10-06
13,56.15,56.970,55.005,55.97,55.97,175375,0.0,1.0,-0.3206,-0.5692,2021-10-05
14,56.22,56.930,55.330,55.90,55.90,123296,0.0,1.0,-0.5692,-0.3341,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58583638,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,52.91,55.07,51.0000,54.76,54.760000,445592,0.0,1.0,3.4965,0.7067,2021-10-22,1,0,-0.0022,0.3831,453.120000,0
64,65.00,65.00,60.5200,62.20,62.110840,251370,0.0,1.0,-4.4449,-0.4607,2021-07-23,0,0,0.2288,-0.1574,438.521197,1
123,65.71,65.88,61.8400,63.68,63.507830,420115,0.0,1.0,-3.3513,0.6349,2021-04-29,0,1,-0.7134,-0.7494,417.321472,1
175,53.00,54.96,50.1201,53.01,52.815118,835986,0.0,1.0,-0.3488,0.3248,2021-02-12,0,1,-0.2681,-1.1018,388.804661,1
251,42.99,45.03,41.3000,44.82,44.606414,909288,0.0,1.0,3.7600,-0.2991,2020-10-23,1,1,-1.4416,-1.5711,340.943239,1
315,35.67,35.67,32.9800,34.55,34.351436,482613,0.0,1.0,-3.6966,-0.9890,2020-07-24,0,1,-1.8180,-1.8454,315.115236,1
374,26.80,29.20,25.4000,27.91,27.713837,1371135,0.0,1.0,3.4098,5.0431,2020-04-30,0,0,-2.6416,-1.6659,284.004199,0
427,36.60,38.43,36.6000,37.40,36.740324,794422,0.0,1.0,0.3834,-2.1444,2020-02-13,1,1,-2.4791,-2.8059,327.533672,1
503,30.45,30.45,29.1800,29.35,28.692150,581808,0.0,1.0,-5.7729,-0.3411,2019-10-24,0,1,-3.4732,-3.4287,290.458822,0
567,32.45,33.50,28.2200,28.58,27.774889,2915595,0.0,1.0,-14.4071,-1.3228,2019-07-25,0,0,-4.0468,-3.4598,288.761564,0
629,36.09,38.15,35.2000,37.60,36.368094,942356,0.0,1.0,0.7706,-3.1636,2019-04-26,1,1,-3.7830,-4.2355,281.049894,1
674,28.71,35.85,28.7100,33.58,32.306713,1400170,0.0,1.0,12.5277,-1.9137,2019-02-21,1,1,-4.7268,-4.4216,264.573747,0
753,33.15,34.02,31.6700,32.68,31.237995,3113591,0.0,1.0,-5.7677,-8.0293,2018-10-25,1,0,-4.2386,-5.8771,256.046715,1
817,45.85,46.35,44.8000,45.45,43.260432,272809,0.0,1.0,-5.6479,-4.3893,2018-07-26,0,1,-5.5768,-5.6538,267.406482,1
879,46.05,46.55,41.5500,42.50,40.298081,341802,0.0,1.0,-12.4906,-6.3569,2018-04-27,0,0,-6.2006,-6.2883,250.444441,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.80,0.84048,-0.04048,-4.8163,54.760000,3.4965,0.7067,453.120000,-0.0022,0.3831,0.000000,-100.00,0,0,0,1,0,0
1,2021-07-23,0.89,0.81500,0.075,9.2025,62.110840,-4.4449,-0.4607,438.521197,0.2288,-0.1574,60.742804,-2.20,1,1,0,0,1,0
2,2021-04-29,0.86,0.76330,0.0967,12.6687,63.507830,-3.3513,0.6349,417.321472,-0.7134,-0.7494,58.850456,-7.33,1,1,1,0,1,0
3,2021-02-12,0.76,0.69000,0.07,10.1449,52.815118,-0.3488,0.3248,388.804661,-0.2681,-1.1018,54.359419,2.92,0,1,1,0,1,1
4,2020-10-23,0.87,0.46000,0.41,89.1304,44.606414,3.7600,-0.2991,340.943239,-1.4416,-1.5711,43.441990,-2.61,1,1,1,1,1,0
5,2020-07-24,0.60,0.31000,0.29,93.5484,34.351436,-3.6966,-0.9890,315.115236,-1.8180,-1.8454,34.082988,-0.78,0,1,1,0,1,0
6,2020-04-30,0.65,0.54000,0.11,20.3704,27.713837,3.4098,5.0431,284.004199,-2.6416,-1.6659,25.370424,-8.46,0,1,0,0,0,0
7,2020-02-13,0.66,0.64330,0.0167,2.5960,36.740324,0.3834,-2.1444,327.533672,-2.4791,-2.8059,35.767786,-2.65,0,1,1,1,1,0
8,2019-10-24,0.69,0.66330,0.0267,4.0253,28.692150,-5.7729,-0.3411,290.458822,-3.4732,-3.4287,29.053857,1.26,0,1,1,0,0,1
9,2019-07-25,0.71,0.78670,-0.0767,-9.7496,27.774889,-14.4071,-1.3228,288.761564,-4.0468,-3.4598,27.648551,-0.45,0,0,0,0,0,0
10,2019-04-26,0.80,0.72250,0.0775,10.7266,36.368094,0.7706,-3.1636,281.049894,-3.7830,-4.2355,36.542196,0.48,1,1,1,1,1,0
11,2019-02-21,0.65,0.71330,-0.0633,-8.8742,32.306713,12.5277,-1.9137,264.573747,-4.7268,-4.4216,32.585717,0.86,1,0,1,1,0,0
12,2018-10-25,0.64,0.60250,0.0375,6.2241,31.237995,-5.7677,-8.0293,256.046715,-4.2386,-5.8771,30.167415,-3.43,0,1,0,1,1,0
13,2018-07-26,0.71,0.66750,0.0425,6.3670,43.260432,-5.6479,-4.3893,267.406482,-5.5768,-5.6538,42.498972,-1.76,1,1,1,0,1,0
14,2018-04-27,0.66,0.57600,0.084,14.5833,40.298081,-12.4906,-6.3569,250.444441,-6.2006,-6.2883,39.492119,-2.00,1,1,0,0,1,0
15,2018-02-21,0.47,0.46800,0.002,0.4274,41.616925,-6.6885,-5.3181,252.712612,-7.0568,-5.9170,41.900355,0.68,0,1,0,0,0,0
16,2017-10-20,0.48,0.46000,0.02,4.3478,45.514789,-8.9704,-5.6718,239.389549,-6.7435,-6.8630,45.467721,-0.10,0,1,1,0,1,0
17,2017-07-25,0.57,0.50000,0.07,14.0000,40.006154,-4.2915,-6.4355,229.231707,-7.4484,-7.1858,39.818552,-0.47,1,1,0,1,0,0
18,2017-04-28,0.53,0.39170,0.1383,35.3076,41.249138,0.4851,-6.4535,219.507992,-8.1172,-7.8433,40.735276,-1.25,1,1,1,1,0,0
19,2017-02-27,0.41,0.34000,0.07,20.5882,38.160087,-18.6352,-6.9266,217.664945,-8.0185,-7.8228,36.159010,-5.24,1,1,1,0,0,0
20,2016-10-21,0.35,0.34170,0.0083,2.4290,26.925473,-4.6886,-7.9482,195.278619,-8.6971,-8.9655,27.481592,2.07,0,1,1,1,1,1
21,2016-07-21,0.42,0.38330,0.0367,9.5747,25.798973,-8.9662,-8.0861,196.372617,-9.4890,-9.0867,26.121575,1.25,1,1,0,0,0,1
22,2016-04-29,0.38,0.32500,0.055,16.9231,26.310352,-10.7519,-7.6827,186.373880,-9.8424,-9.5201,26.842060,2.02,1,1,1,0,0,1
23,2016-02-17,0.36,0.34000,0.02,5.8824,21.419744,-4.2479,-9.3071,173.334591,-9.3249,-9.6526,21.210104,-0.98,0,1,0,1,1,0
24,2015-10-23,0.43,0.39000,0.04,10.2564,23.797601,-7.1856,-10.0414,185.368246,-10.5581,-10.4807,23.308237,-2.06,0,1,1,1,0,0
25,2015-07-23,0.43,0.43000,0,0.0000,22.978831,-11.9585,-10.1651,186.720844,-11.7284,-11.0692,22.519435,-2.00,1,0,0,0,0,0
26,2015-04-30,0.42,0.40000,0.02,5.0000,23.626611,-14.1475,-11.2714,184.327403,-12.1749,-11.5808,24.728649,4.66,0,1,0,0,0,1
27,2015-02-18,0.42,0.38000,0.04,10.5263,24.601350,-10.4428,-10.5345,184.985735,-11.7687,-11.6671,23.379310,-4.97,0,1,0,1,0,0
28,2014-10-24,0.45,0.43000,0.02,4.6512,26.714011,-11.8931,-10.8977,171.979977,-11.9181,-12.3077,26.403176,-1.16,0,1,0,0,1,0
29,2014-07-24,0.48,0.49000,-0.01,-2.0408,31.982892,-11.9414,-10.5749,173.113552,-12.9339,-12.7714,30.169201,-5.67,0,0,1,0,0,0
30,2014-04-25,0.48,0.50000,-0.02,-4.0000,30.641450,-8.1216,-10.9602,161.570045,-13.7004,-13.0316,29.636234,-3.28,1,0,1,1,0,0
31,2014-02-19,0.38,0.38000,0,0.0000,29.850941,-12.0997,-11.8924,158.034087,-13.9997,-13.0947,31.380857,5.13,0,0,1,0,0,0
32,2013-10-24,0.40,0.37000,0.03,8.1081,25.682565,-9.2489,-12.1260,150.426343,-14.0028,-13.8702,26.077007,1.54,0,1,0,1,0,1
33,2013-07-25,0.41,0.47000,-0.06,-12.7660,26.198240,-11.4026,-12.8167,144.375696,-14.1745,-14.4898,22.259772,-15.03,0,0,1,1,1,0
34,2013-04-26,0.45,0.45000,0,0.0000,22.359665,-12.3838,-12.3351,134.529842,-15.0320,-14.7708,22.585872,1.01,1,0,1,0,0,1
35,2013-02-14,0.36,0.24000,0.12,50.0000,21.670138,-13.4233,-13.7087,128.897547,-15.0257,-15.3437,22.997412,6.12,1,1,1,1,1,0
36,2012-10-25,0.34,0.30000,0.04,13.3333,14.817483,-11.1129,-13.5497,118.855146,-16.3110,-16.2225,15.379734,3.79,0,1,1,1,0,1
37,2012-07-27,0.42,0.41000,0.01,2.4390,14.356630,-6.4715,-13.9510,115.924658,-15.3155,-16.5642,14.020147,-2.34,1,1,0,1,1,0
38,2012-04-27,0.40,0.37000,0.03,8.1081,16.066048,-9.7920,-14.3287,116.755013,-16.9476,-16.5923,15.722021,-2.14,1,1,0,1,0,0
39,2012-02-16,0.24,0.33000,-0.09,-27.2727,17.674373,-7.2211,-13.9933,112.652745,-16.2869,-17.1731,17.244340,-2.43,0,0,1,1,1,0
40,2011-11-01,0.35,0.33000,0.02,6.0606,12.875200,-12.4136,-14.2742,100.383189,-17.7389,-17.7518,13.924482,8.15,1,1,1,1,1,0
41,2011-08-08,0.34,0.42000,-0.08,-19.0476,11.447489,-26.3827,-17.4305,91.896385,-21.3956,-19.4285,13.692264,19.61,0,0,0,0,0,0
42,2011-04-26,0.40,0.33000,0.07,21.2121,20.727610,-14.8414,-14.0998,109.797121,-18.0924,-18.5482,21.467268,3.57,1,1,1,0,1,1
43,2011-02-28,0.24,0.22000,0.02,9.0909,18.603245,-14.8593,-14.2264,107.993499,-18.6918,-18.8624,17.648571,-5.13,0,1,1,0,1,0
44,2010-11-01,0.26,0.19000,0.07,36.8421,12.505371,-16.2400,-13.1378,95.633489,-19.6830,-19.1738,13.761069,10.04,0,1,0,0,0,0
45,2010-08-02,0.27,0.25000,0.02,8.0000,12.978408,-12.3081,-14.2863,90.493694,-19.1948,-20.0999,12.488170,-3.78,1,1,1,1,1,0
46,2010-05-04,0.24,0.19000,0.05,26.3158,12.857999,-16.6688,-14.5659,93.867411,-21.1265,-19.9050,12.857999,0.00,1,1,1,0,0,0
47,2010-03-03,0.14,0.06000,0.08,133.3333,10.389607,-13.9933,-13.2718,89.327990,-20.5903,-19.9648,11.000255,5.88,1,1,1,0,0,0
48,2009-08-03,0.01,0.07000,-0.06,-85.7143,7.706199,-12.8258,-12.8311,79.091767,-20.7894,-21.0850,7.671796,-0.45,0,0,1,1,1,0
49,2009-05-04,0.12,0.05000,0.07,140.0000,5.298012,-8.6550,-12.2558,71.163064,-19.6352,-21.2926,6.192481,16.88,0,1,1,1,1,0
50,2009-03-04,0.34,0.22000,0.12,54.5455,4.317535,-14.5042,-15.8698,55.759673,-21.7188,-23.9362,3.079039,-28.69,0,1,0,1,1,0
51,2008-11-05,0.35,0.33000,0.02,6.0606,6.605313,-25.0248,-11.3902,74.168801,-25.2331,-22.4748,6.742924,2.08,0,1,0,0,0,1
52,2008-08-04,0.39,0.36000,0.03,8.3333,13.829874,-14.3130,-14.3530,95.841978,-23.9591,-23.6634,14.036290,1.49,1,1,1,1,0,1
53,2008-05-05,0.37,0.32000,0.05,15.6250,13.081616,-13.8801,-13.3103,107.441597,-23.8273,-23.8780,14.105096,7.82,1,1,1,0,1,0
54,2008-03-10,0.22,0.23000,-0.01,-4.3478,9.839164,-23.4902,-13.7965,97.181040,-25.1532,-23.8720,10.578822,7.52,0,0,0,0,0,0
55,2007-11-02,0.25,0.22000,0.03,13.6364,13.339636,-13.6034,-14.4152,114.197318,-24.6372,-24.3745,14.165300,6.19,0,1,0,1,0,0
56,2007-07-26,0.31,0.28000,0.03,10.7143,14.199703,-15.8785,-15.2820,111.269322,-25.9143,-25.0309,14.535129,2.36,1,1,1,0,0,1
57,2007-04-26,0.29,0.25000,0.04,16.0000,14.070693,-13.5176,-12.7215,112.014854,-25.0687,-24.9468,14.535129,3.30,1,1,1,0,0,1
58,2007-02-27,-0.46,0.12000,-0.58,-483.3333,13.546052,-17.1495,-14.8124,104.003585,-27.7151,-25.5373,12.952606,-4.38,0,0,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,0,1,0,0
1,1,1,0,0,1,0
2,1,1,1,0,1,0
3,0,1,1,0,1,1
4,1,1,1,1,1,0
5,0,1,1,0,1,0
6,0,1,0,0,0,0
7,0,1,1,1,1,0
8,0,1,1,0,0,1
9,0,0,0,0,0,0
10,1,1,1,1,1,0
11,1,0,1,1,0,0
12,0,1,0,1,1,0
13,1,1,1,0,1,0
14,1,1,0,0,1,0
15,0,1,0,0,0,0
16,0,1,1,0,1,0
17,1,1,0,1,0,0
18,1,1,1,1,0,0
19,1,1,1,0,0,0
20,0,1,1,1,1,1
21,1,1,0,0,0,1
22,1,1,1,0,0,1
23,0,1,0,1,1,0
24,0,1,1,1,0,0
25,1,0,0,0,0,0
26,0,1,0,0,0,1
27,0,1,0,1,0,0
28,0,1,0,0,1,0
29,0,0,1,0,0,0
30,1,0,1,1,0,0
31,0,0,1,0,0,0
32,0,1,0,1,0,1
33,0,0,1,1,1,0
34,1,0,1,0,0,1
35,1,1,1,1,1,0
36,0,1,1,1,0,1
37,1,1,0,1,1,0
38,1,1,0,1,0,0
39,0,0,1,1,1,0
40,1,1,1,1,1,0
41,0,0,0,0,0,0
42,1,1,1,0,1,1
43,0,1,1,0,1,0
44,0,1,0,0,0,0
45,1,1,1,1,1,0
46,1,1,1,0,0,0
47,1,1,1,0,0,0
48,0,0,1,1,1,0
49,0,1,1,1,1,0
50,0,1,0,1,1,0
51,0,1,0,0,0,1
52,1,1,1,1,0,1
53,1,1,1,0,1,0
54,0,0,0,0,0,0
55,0,1,0,1,0,0
56,1,1,1,0,0,1
57,1,1,1,0,0,1
58,0,0,0,0,0,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,AIMC

This is the ticker:

HCA

2021-10-22



HCA has reported earnings 43 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains HCA's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None            4     None               None
1    2021-07-20        4.37       3.1589   1.2111            38.3393
2    2021-04-22        4.14       3.3273   0.8127            24.4252
3    2021-02-02        4.13       3.5882   0.5418            15.0995
4    2020-10-26        1.92       2.2585  -0.3385           -14.9878
5    2020-07-22         1.5      -0.3327   1.8327           550.8566
6    2020-04-21      2.3337       2.6549  -0.3212           -12.0984
7    2020-01-28        3.09        3.089    0.001             0.0324
8    2019-10-29        2.23       2.1288   0.1012             4.7539
9    2019-07-30        2.21       2.4593  -0.2493            -10.137
10   2019-04-30        2.97       2.3348   0.6352            27.2058
11   2019-01-29        2.99       2.5836   0.4064              15.73
12   2018-10-30        2.16       1.9054   0.2546             13.362
13   2018-07-25        2.29       2.1564   0.1336             6.1955
14   2018-05-01        2.33        2.068    0.262            12.6692

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is HCA's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,4.5700,4.041778,0.528222,13.0691,1,1
1,2021-07-20,4.3700,3.158900,1.2111,38.3393,1,1
2,2021-04-22,4.1400,3.327300,0.8127,24.4252,1,1
3,2021-02-02,4.1300,3.588200,0.5418,15.0995,1,1
4,2020-10-26,1.9200,2.258500,-0.3385,-14.9878,1,0
5,2020-07-22,1.5000,-0.332700,1.8327,550.8566,0,1
6,2020-04-21,2.3337,2.654900,-0.3212,-12.0984,0,0
7,2020-01-28,3.0900,3.089000,0.001,0.0324,1,1
8,2019-10-29,2.2300,2.128800,0.1012,4.7539,1,1
9,2019-07-30,2.2100,2.459300,-0.2493,-10.1370,0,0
10,2019-04-30,2.9700,2.334800,0.6352,27.2058,0,1
11,2019-01-29,2.9900,2.583600,0.4064,15.7300,1,1
12,2018-10-30,2.1600,1.905400,0.2546,13.3620,0,1
13,2018-07-25,2.2900,2.156400,0.1336,6.1955,0,1
14,2018-05-01,2.3300,2.068000,0.262,12.6692,1,1

3. Retrieve the last 5,000 daily adjusted prices for HCA in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,246.52,257.8800,243.03,253.11,253.11,2830542,0.0,1.0,2.6732,0.4324,2021-10-22
1,255.28,260.1800,249.87,260.00,260.00,1878640,0.0,1.0,1.8490,0.4324,2021-10-21
2,249.78,253.4500,249.78,250.86,250.86,1106142,0.0,1.0,0.4324,0.2136,2021-10-20
3,248.15,251.5100,248.06,248.68,248.68,897972,0.0,1.0,0.2136,0.2558,2021-10-19
4,246.10,247.6591,243.96,246.59,246.59,911269,0.0,1.0,0.1991,0.2558,2021-10-18
5,244.09,248.5500,243.31,246.88,246.88,1127142,0.0,1.0,1.1430,-0.2088,2021-10-15
6,241.22,244.4625,240.49,242.51,242.51,1145979,0.0,1.0,0.5348,-0.2088,2021-10-14
7,239.51,241.0650,236.99,239.01,239.01,1166695,0.0,1.0,-0.2088,-0.6388,2021-10-13
8,238.46,240.4000,237.35,239.07,239.07,1070624,0.0,1.0,0.2558,-0.7066,2021-10-12
9,240.02,241.8262,237.17,237.52,237.52,908974,0.0,1.0,-1.0416,-0.7066,2021-10-11
10,242.23,244.1500,240.24,240.42,240.42,817444,0.0,1.0,-0.7472,-0.6388,2021-10-08
11,240.35,243.5800,240.04,242.28,242.28,1512103,0.0,1.0,0.8030,-0.7066,2021-10-07
12,241.07,242.0000,236.03,239.53,239.53,1170244,0.0,1.0,-0.6388,-0.7066,2021-10-06
13,244.84,247.5500,242.92,243.11,243.11,1396127,0.0,1.0,-0.7066,-0.7528,2021-10-05
14,247.80,250.8000,243.32,244.38,244.38,1312973,0.0,1.0,-1.3801,-0.4751,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58586483,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,246.52,257.880,243.0300,253.11,253.110000,2830542,0.0,1.0,2.6732,0.4324,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
67,239.10,252.000,237.6800,248.90,248.435002,4824140,0.0,1.0,3.9042,-0.5362,2021-07-20,1,1,0.9373,-0.5868,429.669835,1
128,203.00,205.580,198.7300,201.51,200.673890,2607087,0.0,1.0,-1.1459,0.2483,2021-04-22,0,1,-1.5167,-0.6496,409.582258,0
183,168.71,170.915,165.0127,165.85,164.735627,3009225,0.0,1.0,-2.3557,-0.8854,2021-02-02,0,1,-0.4812,-1.3930,377.822989,1
250,134.50,137.450,130.4900,135.43,134.002771,1966779,0.0,1.0,-0.3697,-1.2130,2020-10-26,1,1,-2.1885,-1.4416,334.642622,0
317,115.30,124.380,115.1000,122.42,121.129877,5347855,0.0,1.0,5.0563,1.1168,2020-07-22,1,1,-1.1189,-1.8454,320.987802,1
381,103.81,114.290,100.5600,105.47,104.358504,4037650,0.0,1.0,0.5284,1.4549,2020-04-21,0,0,-3.5330,-2.1624,266.952996,0
439,147.50,148.000,144.1700,145.50,143.480885,2380002,0.0,1.0,-2.7248,-1.7214,2020-01-28,0,1,-2.2792,-2.7088,317.651107,1
500,133.89,136.060,130.0000,134.99,132.733828,3163985,0.0,1.0,-0.8635,-1.2276,2019-10-29,1,1,-3.2326,-3.1847,293.205112,0
564,131.29,136.950,128.3200,132.80,130.147329,6907333,0.0,1.0,-0.8703,-1.6245,2019-07-30,1,1,-3.4862,-3.4598,289.454592,0
627,130.46,131.590,123.5800,127.23,124.277618,3623944,0.0,1.0,-4.7389,-1.0995,2019-04-30,0,0,-4.0396,-4.0951,281.634198,1
690,135.00,138.100,132.0100,138.03,134.440236,2669717,0.0,1.0,-0.4146,-3.1760,2019-01-29,1,1,-4.8149,-4.5696,251.212496,0
750,128.00,136.070,121.1700,135.21,131.374242,4695800,0.0,1.0,2.6361,-2.7910,2018-10-30,1,1,-3.7218,-5.4063,253.856742,1
818,111.85,119.400,111.4100,118.13,114.480013,4995076,0.0,1.0,2.3514,-3.0808,2018-07-25,1,1,-4.7244,-5.6538,268.038805,1
877,96.63,96.750,93.0300,96.20,92.912314,3118964,0.0,1.0,-3.8473,-4.1699,2018-05-01,1,0,-5.6505,-6.2006,248.959964,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,4.5700,4.041778,0.528222,13.0691,253.110000,2.6732,0.4324,453.120000,-0.0022,0.3831,0.000000,-100.00,1,1,1,1,0,0
1,2021-07-20,4.3700,3.158900,1.2111,38.3393,248.435002,3.9042,-0.5362,429.669835,0.9373,-0.5868,248.784348,0.14,1,1,1,1,1,0
2,2021-04-22,4.1400,3.327300,0.8127,24.4252,200.673890,-1.1459,0.2483,409.582258,-1.5167,-0.6496,201.659782,0.49,1,1,1,0,0,0
3,2021-02-02,4.1300,3.588200,0.5418,15.0995,164.735627,-2.3557,-0.8854,377.822989,-0.4812,-1.3930,171.956779,4.38,1,1,1,0,1,1
4,2020-10-26,1.9200,2.258500,-0.3385,-14.9878,134.002771,-0.3697,-1.2130,334.642622,-2.1885,-1.4416,129.184093,-3.60,1,0,1,1,0,0
5,2020-07-22,1.5000,-0.332700,1.8327,550.8566,121.129877,5.0563,1.1168,320.987802,-1.1189,-1.8454,125.631926,3.72,0,1,1,1,1,1
6,2020-04-21,2.3337,2.654900,-0.3212,-12.0984,104.358504,0.5284,1.4549,266.952996,-3.5330,-2.1624,103.418516,-0.90,0,0,0,0,0,0
7,2020-01-28,3.0900,3.089000,0.001,0.0324,143.480885,-2.7248,-1.7214,317.651107,-2.2792,-2.7088,143.224493,-0.18,1,1,1,0,1,0
8,2019-10-29,2.2300,2.128800,0.1012,4.7539,132.733828,-0.8635,-1.2276,293.205112,-3.2326,-3.1847,132.517505,-0.16,1,1,1,1,0,0
9,2019-07-30,2.2100,2.459300,-0.2493,-10.1370,130.147329,-0.8703,-1.6245,289.454592,-3.4862,-3.4598,130.843146,0.53,0,0,1,1,0,0
10,2019-04-30,2.9700,2.334800,0.6352,27.2058,124.277618,-4.7389,-1.0995,281.634198,-4.0396,-4.0951,121.210482,-2.47,0,1,0,0,1,0
11,2019-01-29,2.9900,2.583600,0.4064,15.7300,134.440236,-0.4146,-3.1760,251.212496,-4.8149,-4.5696,135.443449,0.75,1,1,1,1,0,0
12,2018-10-30,2.1600,1.905400,0.2546,13.3620,131.374242,2.6361,-2.7910,253.856742,-3.7218,-5.4063,129.741901,-1.24,0,1,1,1,1,0
13,2018-07-25,2.2900,2.156400,0.1336,6.1955,114.480013,2.3514,-3.0808,268.038805,-4.7244,-5.6538,120.459372,5.22,0,1,1,1,1,0
14,2018-05-01,2.3300,2.068000,0.262,12.6692,92.912314,-3.8473,-4.1699,248.959964,-5.6505,-6.2006,94.399684,1.60,1,1,0,1,1,1
15,2018-01-30,2.1300,1.875500,0.2545,13.5697,97.638575,-3.8517,-2.9098,263.670823,-6.6982,-6.6968,97.359470,-0.29,1,1,1,0,0,0
16,2017-10-31,1.2100,1.212500,-0.0025,-0.2062,72.807868,-4.4014,-3.9824,239.426793,-6.9030,-6.9067,73.943536,1.56,0,0,0,0,1,1
17,2017-07-25,1.7500,1.807800,-0.0578,-3.1973,79.092539,-4.2463,-4.2150,229.231707,-7.4484,-7.1858,78.563203,-0.67,1,0,0,0,0,0
18,2017-05-02,1.7400,1.735200,0.0048,0.2766,81.556361,-3.2087,-3.8606,220.144169,-7.8278,-7.8433,79.737368,-2.23,0,1,1,1,1,0
19,2017-01-31,1.8900,1.777600,0.1124,6.3231,77.263921,-3.0566,-3.9991,208.870585,-7.9784,-8.2289,78.880805,2.09,1,1,1,1,1,1
20,2016-10-27,1.6100,1.422400,0.1876,13.1890,76.330364,-3.4770,-4.0856,194.539413,-9.3394,-8.7355,74.405503,-2.52,0,1,1,1,0,0
21,2016-07-28,1.6600,1.557500,0.1025,6.5811,74.954088,0.0989,-3.5390,196.826615,-8.9987,-9.3467,74.232265,-0.96,0,1,0,1,1,0
22,2016-05-03,1.7100,1.488200,0.2218,14.9039,76.089756,-4.3017,-3.0884,186.220324,-9.8294,-9.7238,76.801955,0.94,1,1,1,0,0,0
23,2016-01-28,1.6900,1.396700,0.2933,20.9995,64.973684,-5.5478,-2.2722,169.946619,-10.5356,-9.9018,66.965915,3.07,1,1,0,0,0,1
24,2015-10-27,1.1700,1.200000,-0.03,-2.5000,66.215219,-4.9178,-3.3327,184.519654,-10.5142,-10.5600,66.388457,0.26,0,0,0,0,1,0
25,2015-08-05,1.3700,1.340000,0.03,2.2388,88.793839,-5.2664,-3.7569,186.685301,-11.2923,-11.3056,87.946900,-0.95,1,1,1,0,1,0
26,2015-05-05,1.3500,1.200000,0.15,12.5000,70.844510,-6.1662,-3.5109,184.716466,-12.4691,-11.5389,71.701073,1.21,1,1,1,0,0,1
27,2015-02-03,1.3300,1.230000,0.1,8.1301,67.264268,-0.7023,-4.7258,180.328739,-11.1681,-12.0658,66.369208,-1.33,1,1,0,1,1,0
28,2014-10-28,1.1800,1.060000,0.12,11.3208,68.602047,-5.0491,-3.3778,173.713523,-11.7399,-12.2548,67.293141,-1.91,0,1,1,0,1,0
29,2014-07-29,1.3700,0.920000,0.45,48.9130,62.625353,-1.8104,-3.6037,171.632087,-13.3915,-12.8374,63.770646,1.83,1,1,1,1,0,1
30,2014-04-29,0.8400,0.850000,-0.01,-1.1765,49.468928,-3.0021,-3.7180,162.836308,-13.1447,-13.4405,50.046387,1.17,0,0,1,1,1,1
31,2014-02-04,0.9200,0.860000,0.06,6.9767,46.697128,-5.6624,-3.7375,151.445736,-13.4348,-13.4589,46.167792,-1.13,1,1,1,0,1,0
32,2013-11-05,0.7900,0.760000,0.03,3.9474,44.704897,-5.2059,-2.8822,151.388247,-14.0523,-14.0477,43.598102,-2.48,0,1,1,0,0,0
33,2013-08-01,0.9100,0.830000,0.08,9.6386,37.611784,-3.5595,-4.0276,145.854237,-14.1983,-14.5808,37.573287,-0.10,1,1,0,1,1,0
34,2013-05-02,0.7700,0.820000,-0.05,-6.0976,38.949563,-1.3935,-4.0659,135.813588,-14.4104,-14.8870,39.459651,1.31,0,0,1,1,1,1
35,2013-02-05,0.9200,0.820000,0.1,12.1951,36.100768,-2.5620,-4.0881,127.848017,-14.9664,-15.4678,35.783166,-0.88,1,1,1,1,1,0
36,2012-11-01,0.7800,0.790000,-0.01,-1.2658,27.124090,-3.1283,-15.5757,120.031680,-15.2618,-16.2581,27.720621,2.20,0,0,1,1,1,1
37,2012-08-06,0.8500,0.780000,0.07,8.9744,21.225225,-18.9258,-17.6389,116.710418,-16.4684,-16.3534,22.338407,5.24,0,1,0,0,0,0
38,2012-05-03,0.8800,0.940000,-0.06,-6.3830,22.230412,-17.7869,-17.3516,115.806935,-17.4812,-16.5975,22.172261,-0.26,0,0,1,0,0,0
39,2012-02-06,0.9400,0.760000,0.18,23.6842,21.851004,-24.6257,-22.6260,111.327905,-16.9071,-17.0849,22.174153,1.48,1,1,1,0,1,1
40,2011-11-01,0.6000,0.430000,0.17,39.5349,18.080937,-21.1816,-23.6748,100.383189,-17.7389,-17.7518,17.965526,-0.64,1,1,0,1,1,0
41,2011-07-25,0.5100,0.590000,-0.08,-13.5593,21.520162,-28.3855,-22.9440,109.553654,-17.8142,-18.1032,21.574020,0.25,0,0,0,0,1,0
42,2011-05-04,0.8500,0.750000,0.1,13.3333,25.813422,-22.0138,-22.3496,109.829704,-19.0464,-18.3806,26.421250,2.35,0,1,0,1,0,1

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,0
1,1,1,1,1,1,0
2,1,1,1,0,0,0
3,1,1,1,0,1,1
4,1,0,1,1,0,0
5,0,1,1,1,1,1
6,0,0,0,0,0,0
7,1,1,1,0,1,0
8,1,1,1,1,0,0
9,0,0,1,1,0,0
10,0,1,0,0,1,0
11,1,1,1,1,0,0
12,0,1,1,1,1,0
13,0,1,1,1,1,0
14,1,1,0,1,1,1
15,1,1,1,0,0,0
16,0,0,0,0,1,1
17,1,0,0,0,0,0
18,0,1,1,1,1,0
19,1,1,1,1,1,1
20,0,1,1,1,0,0
21,0,1,0,1,1,0
22,1,1,1,0,0,0
23,1,1,0,0,0,1
24,0,0,0,0,1,0
25,1,1,1,0,1,0
26,1,1,1,0,0,1
27,1,1,0,1,1,0
28,0,1,1,0,1,0
29,1,1,1,1,0,1
30,0,0,1,1,1,1
31,1,1,1,0,1,0
32,0,1,1,0,0,0
33,1,1,0,1,1,0
34,0,0,1,1,1,1
35,1,1,1,1,1,0
36,0,0,1,1,1,1
37,0,1,0,0,0,0
38,0,0,1,0,0,0
39,1,1,1,0,1,1
40,1,1,0,1,1,0
41,0,0,0,0,1,0
42,0,1,0,1,0,1

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,HCA

This is the ticker:

BLFY

2021-10-22




Model has been put to sleep after historical earnings call
This stock does not have enough data to conduct a proper naive bayes analysis.

This is the ticker:

DSKE

2021-10-22



DSKE has reported earnings 24 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains DSKE's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.32     None               None
1    2021-08-03        0.49       0.0933   0.3967           425.1876
2    2021-05-07       -0.13        -0.05    -0.08               -160
3    2021-01-29        0.09      -0.0367   0.1267           345.2316
4    2020-10-30        0.22        -0.03     0.25           833.3333
5    2020-08-06       -0.01      -0.0933   0.0833            89.2819
6    2020-05-07       -0.29      -0.0667  -0.2233          -334.7826
7    2020-03-10       -0.31      -0.2033  -0.1067            -52.484
8    2019-11-12       -4.25       -0.164   -4.086         -2491.4634
9    2019-08-05       -0.12       -0.055   -0.065          -118.1818
10   2019-05-06       -0.16       -0.108   -0.052           -48.1481
11   2019-03-08       -0.33       -0.246   -0.084           -34.1463
12   2018-11-06        0.01         0.04    -0.03                -75
13   2018-08-09         0.2       0.0414   0.1586           383.0918
14   2018-05-08       -0.04       -0.076    0.036            47.3684

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is DSKE's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.43,0.323003,0.106997,33.1255,0,1
1,2021-08-03,0.49,0.093300,0.3967,425.1876,1,1
2,2021-05-07,-0.13,-0.050000,-0.08,-160.0000,0,0
3,2021-01-29,0.09,-0.036700,0.1267,345.2316,0,1
4,2020-10-30,0.22,-0.030000,0.25,833.3333,1,1
5,2020-08-06,-0.01,-0.093300,0.0833,89.2819,1,1
6,2020-05-07,-0.29,-0.066700,-0.2233,-334.7826,1,0
7,2020-03-10,-0.31,-0.203300,-0.1067,-52.4840,1,0
8,2019-11-12,-4.25,-0.164000,-4.086,-2491.4634,0,0
9,2019-08-05,-0.12,-0.055000,-0.065,-118.1818,1,0
10,2019-05-06,-0.16,-0.108000,-0.052,-48.1481,1,0
11,2019-03-08,-0.33,-0.246000,-0.084,-34.1463,0,0
12,2018-11-06,0.01,0.040000,-0.03,-75.0000,0,0
13,2018-08-09,0.20,0.041400,0.1586,383.0918,1,1
14,2018-05-08,-0.04,-0.076000,0.036,47.3684,0,1

3. Retrieve the last 5,000 daily adjusted prices for DSKE in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,10.36,10.4000,9.79,9.84,9.84,644739,0.0,1.0,-5.0193,0.1974,2021-10-22
1,10.15,10.3400,9.92,10.32,10.32,451758,0.0,1.0,1.6749,0.1974,2021-10-21
2,10.13,10.2100,10.05,10.15,10.15,216175,0.0,1.0,0.1974,-1.0536,2021-10-20
3,10.43,10.4300,10.06,10.19,10.19,271842,0.0,1.0,-2.3011,-1.0536,2021-10-19
4,10.44,10.5000,10.12,10.33,10.33,537773,0.0,1.0,-1.0536,-0.2000,2021-10-18
5,9.92,10.3500,9.92,10.20,10.20,736834,0.0,1.0,2.8226,-0.2000,2021-10-15
6,9.58,9.8500,9.54,9.76,9.76,333512,0.0,1.0,1.8789,-0.4103,2021-10-14
7,9.68,9.7572,9.37,9.54,9.54,345073,0.0,1.0,-1.4463,-0.2000,2021-10-13
8,10.05,10.0500,9.51,9.73,9.73,345329,0.0,1.0,-3.1841,1.7895,2021-10-12
9,10.00,10.2300,9.57,9.98,9.98,719552,0.0,1.0,-0.2000,1.7895,2021-10-11
10,9.71,10.0200,9.69,9.91,9.91,581593,0.0,1.0,2.0597,1.7895,2021-10-08
11,9.75,9.9500,9.68,9.71,9.71,1021239,0.0,1.0,-0.4103,1.7895,2021-10-07
12,9.50,9.6900,9.40,9.67,9.67,394500,0.0,1.0,1.7895,0.2176,2021-10-06
13,9.37,9.5850,9.28,9.55,9.55,355979,0.0,1.0,1.9210,-0.9605,2021-10-05
14,9.56,9.5600,9.24,9.41,9.41,255788,0.0,1.0,-1.5690,0.2176,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58586639,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,10.36,10.40,9.7900,9.84,9.84,644739,0.0,1.0,-5.0193,0.1974,2021-10-22,0,1,-0.0022,0.3831,453.120000,0
57,8.25,8.70,7.6100,7.97,7.97,1806685,0.0,1.0,-3.3939,-0.5857,2021-08-03,0,1,0.2936,-0.5152,439.727295,1
117,7.80,7.81,6.5200,6.93,6.93,1195658,0.0,1.0,-11.1538,-0.2460,2021-05-07,0,1,-0.1243,-0.7594,419.368042,1
185,5.78,5.83,5.1100,5.26,5.26,1244053,0.0,1.0,-8.9965,-0.4934,2021-01-29,0,0,-2.4425,-0.8136,366.455126,0
246,5.85,6.92,5.4601,6.57,6.57,3336691,0.0,1.0,12.3077,0.1976,2020-10-30,1,1,-1.9214,-1.8457,321.972368,0
306,4.45,5.30,4.4500,4.96,4.96,1336222,0.0,1.0,11.4607,0.9685,2020-08-06,1,1,-0.9522,-1.6069,328.323600,1
369,1.50,1.73,1.5000,1.62,1.62,355430,0.0,1.0,8.0000,-4.5181,2020-05-07,1,0,-2.2531,-2.6416,281.266620,1
410,2.97,2.97,2.0200,2.17,2.17,444057,0.0,1.0,-26.9360,-6.9307,2020-03-10,0,0,-1.5358,-3.2040,280.268385,1
490,2.60,3.07,2.5100,3.03,3.03,387245,0.0,1.0,16.5385,-4.2208,2019-11-12,1,1,-3.2214,-3.2776,298.804061,1
560,2.75,3.07,2.5100,2.53,2.53,1133896,0.0,1.0,-8.0000,-0.8427,2019-08-05,0,0,-5.1728,-4.1490,273.187691,0
623,5.52,5.65,5.1500,5.56,5.56,412810,0.0,1.0,0.7246,-1.3566,2019-05-06,1,1,-3.0303,-4.0951,280.484749,1
663,5.00,5.00,4.2100,4.62,4.62,795636,0.0,1.0,-7.6000,-1.0438,2019-03-08,0,0,-4.0995,-5.2524,261.750813,1
745,6.15,6.35,5.3300,5.66,5.66,1338301,0.0,1.0,-7.9675,-0.1647,2018-11-06,0,0,-4.5716,-4.8654,260.824837,1
807,9.80,9.82,8.8400,8.99,8.99,1091305,0.0,1.0,-8.2653,0.3550,2018-08-09,0,0,-5.7755,-5.2907,269.039196,0
872,9.50,9.65,8.9600,9.36,9.36,901064,0.0,1.0,-1.4737,1.0502,2018-05-08,0,0,-5.8977,-5.9168,250.782676,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.430,0.323003,0.106997,33.1255,9.84,-5.0193,0.1974,453.120000,-0.0022,0.3831,0.000,-100.00,0,1,1,0,0,0
1,2021-08-03,0.490,0.093300,0.3967,425.1876,7.97,-3.3939,-0.5857,439.727295,0.2936,-0.5152,8.280,3.89,1,1,1,0,1,1
2,2021-05-07,-0.130,-0.050000,-0.08,-160.0000,6.93,-11.1538,-0.2460,419.368042,-0.1243,-0.7594,6.310,-8.95,0,0,1,0,1,0
3,2021-01-29,0.090,-0.036700,0.1267,345.2316,5.26,-8.9965,-0.4934,366.455126,-2.4425,-0.8136,5.010,-4.75,0,1,0,0,0,0
4,2020-10-30,0.220,-0.030000,0.25,833.3333,6.57,12.3077,0.1976,321.972368,-1.9214,-1.8457,6.610,0.61,1,1,1,1,0,0
5,2020-08-06,-0.010,-0.093300,0.0833,89.2819,4.96,11.4607,0.9685,328.323600,-0.9522,-1.6069,5.570,12.30,1,1,1,1,1,0
6,2020-05-07,-0.290,-0.066700,-0.2233,-334.7826,1.62,8.0000,-4.5181,281.266620,-2.2531,-2.6416,1.600,-1.23,1,0,0,1,1,0
7,2020-03-10,-0.310,-0.203300,-0.1067,-52.4840,2.17,-26.9360,-6.9307,280.268385,-1.5358,-3.2040,2.000,-7.83,1,0,0,0,1,0
8,2019-11-12,-4.250,-0.164000,-4.086,-2491.4634,3.03,16.5385,-4.2208,298.804061,-3.2214,-3.2776,3.020,-0.33,0,0,1,1,1,0
9,2019-08-05,-0.120,-0.055000,-0.065,-118.1818,2.53,-8.0000,-0.8427,273.187691,-5.1728,-4.1490,2.230,-11.86,1,0,0,0,0,0
10,2019-05-06,-0.160,-0.108000,-0.052,-48.1481,5.56,0.7246,-1.3566,280.484749,-3.0303,-4.0951,5.390,-3.06,1,0,1,1,1,0
11,2019-03-08,-0.330,-0.246000,-0.084,-34.1463,4.62,-7.6000,-1.0438,261.750813,-4.0995,-5.2524,5.080,9.96,0,0,0,0,1,0
12,2018-11-06,0.010,0.040000,-0.03,-75.0000,5.66,-7.9675,-0.1647,260.824837,-4.5716,-4.8654,5.325,-5.92,0,0,0,0,1,0
13,2018-08-09,0.200,0.041400,0.1586,383.0918,8.99,-8.2653,0.3550,269.039196,-5.7755,-5.2907,9.010,0.22,1,1,0,0,0,0
14,2018-05-08,-0.040,-0.076000,0.036,47.3684,9.36,-1.4737,1.0502,250.782676,-5.8977,-5.9168,9.350,-0.11,0,1,0,0,1,0
15,2018-03-16,0.620,0.815000,-0.195,-23.9264,10.56,1.5385,0.0962,257.622546,-6.1484,-6.7186,10.580,0.19,1,0,0,1,1,0
16,2017-11-09,-0.030,0.080000,-0.11,-137.5000,12.74,-2.2256,-0.2954,240.376492,-6.7332,-6.6939,12.610,-1.02,1,0,1,0,0,0
17,2017-08-09,-0.150,0.020000,-0.17,-850.0000,12.08,-0.3300,0.1616,229.074204,-7.0580,-7.3924,12.110,0.25,1,0,1,0,1,0
18,2017-05-10,-0.320,-0.070000,-0.25,-357.1429,9.90,-1.0000,-0.9718,221.158352,-7.6159,-7.8354,10.090,1.92,1,0,0,0,1,1
19,2017-03-27,-0.564,-0.100000,-0.464,-464.0000,10.16,-0.9747,-0.5865,215.395899,-7.1289,-7.9019,10.170,0.10,0,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,0,0,0
1,1,1,1,0,1,1
2,0,0,1,0,1,0
3,0,1,0,0,0,0
4,1,1,1,1,0,0
5,1,1,1,1,1,0
6,1,0,0,1,1,0
7,1,0,0,0,1,0
8,0,0,1,1,1,0
9,1,0,0,0,0,0
10,1,0,1,1,1,0
11,0,0,0,0,1,0
12,0,0,0,0,1,0
13,1,1,0,0,0,0
14,0,1,0,0,1,0
15,1,0,0,1,1,0
16,1,0,1,0,0,0
17,1,0,1,0,1,0
18,1,0,0,0,1,1
19,0,0,0,0,1,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,DSKE

This is the ticker:

CLF

2021-10-22




Model has been put to sleep after historical earnings call
CLF has reported earnings 103 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains CLF's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         2.26     None               None
1    2021-07-22      1.4329       1.5136  -0.0807            -5.3317
2    2021-04-22      0.3059       0.3625  -0.0566           -15.6138
3    2021-02-25      0.0405       0.2767  -0.2362           -85.3632
4    2020-10-23        0.04       -0.115    0.155           134.7826
5    2020-07-30       -0.46      -0.5125   0.0525            10.2439
6    2020-05-11     -0.0744      -0.1733   0.0989            57.0687
7    2020-02-20      0.2559       0.2374   0.0185             7.7928
8    2019-10-23        0.33       0.2448   0.0852            34.8039
9    2019-07-19      0.6209       0.5186   0.1023            19.7262
10   2019-04-25      -0.071      -0.1392   0.0682            48.9943
11   2019-02-08       2.053       0.5941   1.4589           245.5647
12   2018-10-19      0.6483         0.66  -0.0117            -1.7727
13   2018-07-20      0.7292       0.5208   0.2084            40.0154
14   2018-04-20       0.005      -0.1822   0.1872           102.7442

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is CLF's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,2.3300,2.282459,0.0475414,2.0829,1,1
1,2021-07-22,1.4329,1.513600,-0.0807,-5.3317,1,0
2,2021-04-22,0.3059,0.362500,-0.0566,-15.6138,1,0
3,2021-02-25,0.0405,0.276700,-0.2362,-85.3632,1,0
4,2020-10-23,0.0400,-0.115000,0.155,134.7826,1,1
5,2020-07-30,-0.4600,-0.512500,0.0525,10.2439,0,1
6,2020-05-11,-0.0744,-0.173300,0.0989,57.0687,0,1
7,2020-02-20,0.2559,0.237400,0.0185,7.7928,0,1
8,2019-10-23,0.3300,0.244800,0.0852,34.8039,0,1
9,2019-07-19,0.6209,0.518600,0.1023,19.7262,1,1
10,2019-04-25,-0.0710,-0.139200,0.0682,48.9943,0,1
11,2019-02-08,2.0530,0.594100,1.4589,245.5647,1,1
12,2018-10-19,0.6483,0.660000,-0.0117,-1.7727,0,0
13,2018-07-20,0.7292,0.520800,0.2084,40.0154,1,1
14,2018-04-20,0.0050,-0.182200,0.1872,102.7442,0,1

3. Retrieve the last 5,000 daily adjusted prices for CLF in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,22.10,24.1000,21.950,23.85,23.85,59137920,0.0,1.0,7.9186,-0.3766,2021-10-22
1,21.24,21.6800,21.030,21.16,21.16,25914661,0.0,1.0,-0.3766,-1.5525,2021-10-21
2,20.87,21.8399,20.690,21.69,21.69,18096844,0.0,1.0,3.9291,-1.5525,2021-10-20
3,21.42,21.5500,20.815,21.02,21.02,17516955,0.0,1.0,-1.8674,-1.2862,2021-10-19
4,21.00,21.4899,20.420,21.38,21.38,21242968,0.0,1.0,1.8095,-1.2862,2021-10-18
5,21.80,21.9700,21.440,21.46,21.46,15884376,0.0,1.0,-1.5596,-0.8650,2021-10-15
6,21.90,22.2261,21.500,21.56,21.56,15606326,0.0,1.0,-1.5525,0.4623,2021-10-14
7,21.77,21.9400,21.260,21.49,21.49,13498463,0.0,1.0,-1.2862,0.4623,2021-10-13
8,21.63,22.1500,21.440,21.73,21.73,17552404,0.0,1.0,0.4623,1.3692,2021-10-12
9,21.16,22.0000,21.100,21.46,21.46,21856560,0.0,1.0,1.4178,-0.2515,2021-10-11
10,20.81,21.1000,20.591,20.63,20.63,13179914,0.0,1.0,-0.8650,-0.2515,2021-10-08
11,20.45,21.1400,20.140,20.73,20.73,22523161,0.0,1.0,1.3692,-1.0490,2021-10-07
12,20.43,20.8000,19.625,20.07,20.07,28963756,0.0,1.0,-1.7621,-1.0490,2021-10-06
13,19.91,20.8400,19.600,20.76,20.76,19983817,0.0,1.0,4.2692,-1.2060,2021-10-05
14,19.88,20.2900,19.550,19.83,19.83,19829472,0.0,1.0,-0.2515,-1.2060,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58586639,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,22.10,24.100,21.9500,23.85,23.850000,59137920,0.0,1.0,7.9186,-0.3766,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
65,20.21,21.355,19.5200,21.07,21.070000,44505369,0.0,1.0,4.2553,0.3125,2021-07-22,1,1,-0.1574,-0.3363,434.055645,1
128,17.62,17.740,16.6711,17.09,17.090000,23916704,0.0,1.0,-3.0079,-2.4678,2021-04-22,0,1,-1.5167,-0.6496,409.582258,0
167,16.35,16.880,14.4000,14.41,14.410000,35191417,0.0,1.0,-11.8654,0.8892,2021-02-25,0,1,-3.0262,-0.6896,378.595369,0
251,8.50,9.040,8.1500,8.67,8.670000,21828874,0.0,1.0,2.0000,1.6539,2020-10-23,1,1,-1.4416,-1.5711,340.943239,1
311,5.75,5.900,5.3300,5.67,5.670000,20162134,0.0,1.0,-1.3913,-0.1736,2020-07-30,0,1,-1.1681,-1.8180,318.139902,1
367,4.77,4.780,4.4200,4.69,4.690000,14644990,0.0,1.0,-1.6771,0.9070,2020-05-11,0,0,-1.5020,-2.2531,285.979166,1
423,7.35,7.350,6.8400,7.19,7.076474,26454018,0.0,1.0,-3.7214,-0.0084,2020-02-20,0,1,-3.0536,-2.6681,327.426781,0
504,7.35,7.360,6.5900,6.76,6.602732,29102305,0.0,1.0,-10.1669,-2.6043,2019-10-23,0,0,-2.9274,-3.4287,289.984990,1
571,11.13,11.610,10.9500,11.30,10.887961,30057316,0.0,1.0,-2.1747,-3.1004,2019-07-19,1,1,-4.6669,-3.8676,286.037580,0
630,10.06,10.060,9.1600,9.73,9.324441,23896068,0.0,1.0,-7.3117,-4.5695,2019-04-25,0,0,-4.2355,-4.2390,279.747185,1
682,11.20,12.260,11.2000,11.83,11.283078,39445608,0.0,1.0,0.7418,-5.4042,2019-02-08,1,1,-4.0203,-4.6481,257.945574,1
757,11.67,11.700,10.3200,11.05,10.470525,35486772,0.0,1.0,-10.2783,-5.8833,2018-10-19,0,1,-5.4970,-5.4769,261.896123,0
821,9.43,10.380,9.0000,9.96,9.437686,52060546,0.0,1.0,0.0815,-3.6085,2018-07-20,1,1,-5.6538,-5.4815,263.952301,0
884,7.34,8.030,7.3100,7.72,7.315154,32075881,0.0,1.0,-0.3385,-5.6378,2018-04-20,1,0,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,2.3300,2.282459,0.0475414,2.0829,23.850000,7.9186,-0.3766,453.120000,-0.0022,0.3831,0.000000,-100.00,1,1,1,1,0,0
1,2021-07-22,1.4329,1.513600,-0.0807,-5.3317,21.070000,4.2553,0.3125,434.055645,-0.1574,-0.3363,21.580000,2.42,1,0,1,1,1,1
2,2021-04-22,0.3059,0.362500,-0.0566,-15.6138,17.090000,-3.0079,-2.4678,409.582258,-1.5167,-0.6496,17.980000,5.21,1,0,1,0,0,0
3,2021-02-25,0.0405,0.276700,-0.2362,-85.3632,14.410000,-11.8654,0.8892,378.595369,-3.0262,-0.6896,13.340000,-7.43,1,0,1,0,0,0
4,2020-10-23,0.0400,-0.115000,0.155,134.7826,8.670000,2.0000,1.6539,340.943239,-1.4416,-1.5711,8.520000,-1.73,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2001-01-31,0.0532,-0.020000,0.0732,366.0000,1.583365,-90.2622,-90.2259,92.486697,-32.6880,-32.1423,1.617363,2.15,0,1,0,0,0,1
83,2000-10-25,0.0800,0.070000,0.01,14.2857,1.973263,-90.6303,-90.4897,91.721076,-33.8947,-31.9681,1.943697,-1.50,0,1,0,0,0,0
84,2000-07-26,0.0900,0.080000,0.01,12.5000,2.343362,-90.3605,-90.6999,97.903750,-33.3846,-33.2921,2.302020,-1.76,1,1,1,1,0,0
85,2000-04-19,-0.0400,-0.030000,-0.01,-33.3333,2.169220,-90.6459,-90.7924,95.830333,-33.6814,-34.5057,2.233075,2.94,0,0,0,1,1,1
86,2000-01-20,0.0600,0.010000,0.05,500.0000,2.681859,-90.9090,-90.8533,96.674388,-34.2211,-32.9974,2.624351,-2.14,1,1,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,0
1,1,0,1,1,1,1
2,1,0,1,0,0,0
3,1,0,1,0,0,0
4,1,1,1,1,1,0
...,...,...,...,...,...,...
82,0,1,0,0,0,1
83,0,1,0,0,0,0
84,1,1,1,1,0,0
85,0,0,0,1,1,1
86,1,1,0,0,0,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,Do NOT buy,CLF

This is the ticker:

HON

2021-10-22



HON has reported earnings 103 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains HON's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         1.99     None               None
1    2021-07-23        2.02       1.9477   0.0723             3.7121
2    2021-04-23        1.92       1.8014   0.1186             6.5838
3    2021-01-29        2.07            2     0.07                3.5
4    2020-10-30        1.56       1.4865   0.0735             4.9445
5    2020-07-24        1.26       1.2395   0.0205             1.6539
6    2020-05-01        2.21       1.9446   0.2654            13.6481
7    2020-01-31        2.06       2.0422   0.0178             0.8716
8    2019-10-17        2.08       2.0101   0.0699             3.4774
9    2019-07-18         2.1       2.0833   0.0167             0.8016
10   2019-04-18        1.92       1.8366   0.0834              4.541
11   2019-02-01        1.91       1.8905   0.0195             1.0315
12   2018-10-19        2.03       1.9914   0.0386             1.9383
13   2018-07-20        2.12       2.0102   0.1098             5.4621
14   2018-04-20        1.95       1.9001   0.0499             2.6262

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is HON's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,2.02,2.015334,0.0046662,0.2315,0,1
1,2021-07-23,2.02,1.947700,0.0723,3.7121,1,1
2,2021-04-23,1.92,1.801400,0.1186,6.5838,0,1
3,2021-01-29,2.07,2.000000,0.07,3.5000,1,1
4,2020-10-30,1.56,1.486500,0.0735,4.9445,1,1
5,2020-07-24,1.26,1.239500,0.0205,1.6539,0,1
6,2020-05-01,2.21,1.944600,0.2654,13.6481,1,1
7,2020-01-31,2.06,2.042200,0.0178,0.8716,0,1
8,2019-10-17,2.08,2.010100,0.0699,3.4774,0,1
9,2019-07-18,2.10,2.083300,0.0167,0.8016,1,1
10,2019-04-18,1.92,1.836600,0.0834,4.5410,1,1
11,2019-02-01,1.91,1.890500,0.0195,1.0315,0,1
12,2018-10-19,2.03,1.991400,0.0386,1.9383,0,1
13,2018-07-20,2.12,2.010200,0.1098,5.4621,1,1
14,2018-04-20,1.95,1.900100,0.0499,2.6262,1,1

3. Retrieve the last 5,000 daily adjusted prices for HON in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,222.97,223.8600,217.2500,217.40,217.40,3496222,0.0,1.0,-2.4981,0.4025,2021-10-22
1,223.62,224.8600,221.2400,224.52,224.52,2649235,0.0,1.0,0.4025,0.6345,2021-10-21
2,222.23,223.6900,220.8300,223.64,223.64,1657049,0.0,1.0,0.6345,0.1906,2021-10-20
3,221.36,221.8400,219.4600,221.78,221.78,1599630,0.0,1.0,0.1897,0.1906,2021-10-19
4,218.58,221.4700,217.8400,220.63,220.63,1883500,0.0,1.0,0.9379,0.1347,2021-10-18
5,220.30,221.4500,219.2601,220.72,220.72,2180601,0.0,1.0,0.1906,-0.4481,2021-10-15
6,217.16,218.7800,216.5290,218.59,218.59,1425556,0.0,1.0,0.6585,-0.4481,2021-10-14
7,215.29,216.6800,212.9400,215.58,215.58,1600202,0.0,1.0,0.1347,-0.4481,2021-10-13
8,215.70,216.2400,213.9300,214.33,214.33,1383809,0.0,1.0,-0.6351,0.1697,2021-10-12
9,217.38,218.2200,215.2600,215.29,215.29,1355214,0.0,1.0,-0.9614,0.1697,2021-10-11
10,218.68,219.5500,216.7400,217.70,217.70,1344880,0.0,1.0,-0.4481,0.9878,2021-10-08
11,218.00,219.8600,217.7100,218.37,218.37,1852850,0.0,1.0,0.1697,0.9878,2021-10-07
12,213.77,216.9900,213.1200,216.86,216.86,1736021,0.0,1.0,1.4455,-0.4216,2021-10-06
13,213.61,217.0499,213.6100,215.72,215.72,1560184,0.0,1.0,0.9878,-0.4832,2021-10-05
14,215.25,216.6200,213.1900,214.21,214.21,2632280,0.0,1.0,-0.4832,-0.4750,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58589651,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,222.97,223.86,217.250,217.40,217.400000,3496222,0.0,1.0,-2.4981,0.4025,2021-10-22,0,0,-0.0022,0.3831,453.120000,0
64,229.00,231.12,226.181,229.32,228.404177,3908545,0.0,1.0,-0.2602,-0.3865,2021-07-23,1,1,0.2288,-0.1574,438.521197,1
127,225.20,226.95,222.220,224.50,222.677595,5312728,0.0,1.0,-1.1201,-1.1285,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
185,196.51,200.94,194.550,195.37,192.908020,4635405,0.0,1.0,-1.8330,-1.0002,2021-01-29,0,1,-2.4425,-0.8136,366.455126,0
246,161.54,165.76,161.050,164.95,162.107016,4390007,0.0,1.0,0.3510,-3.0549,2020-10-30,1,1,-1.9214,-1.8457,321.972368,0
315,154.00,154.25,149.040,149.43,146.027833,4368458,0.0,1.0,-5.1767,-1.9597,2020-07-24,0,1,-1.8180,-1.8454,315.115236,1
373,139.33,139.50,134.170,137.25,133.181707,3681074,0.0,1.0,-4.4128,-3.0929,2020-05-01,0,0,-3.0929,-1.6659,276.485635,0
436,177.91,177.91,171.340,173.22,167.142673,5499968,0.0,1.0,-6.0521,-3.9126,2020-01-31,0,1,-4.3924,-2.6849,312.636944,0
508,166.30,168.99,165.590,167.52,160.836903,3593761,0.0,1.0,-3.2851,-3.9190,2019-10-17,1,0,-3.4287,-3.2899,289.404788,0
572,170.60,173.88,169.700,173.88,166.103802,4128122,0.0,1.0,-2.6355,-4.6306,2019-07-18,1,1,-3.2150,-3.8676,287.635394,1
634,167.52,169.86,165.890,169.06,160.707602,6376881,0.0,1.0,-4.0666,-4.7768,2019-04-18,1,1,-4.2390,-4.4182,277.802701,1
687,148.70,149.00,144.340,144.71,136.825426,5536461,0.0,1.0,-7.9856,-4.9043,2019-02-01,0,0,-4.6624,-4.4966,257.554560,0
757,156.10,157.74,152.400,153.47,139.832702,6791579,0.0,1.0,-10.4211,-8.6051,2018-10-19,0,1,-5.4970,-5.4769,261.896123,0
821,149.19,153.99,149.120,153.13,137.340883,6453322,0.0,1.0,-7.9423,-10.5172,2018-07-20,1,1,-5.6538,-5.4815,263.952301,0
884,150.77,151.57,147.940,150.57,134.364436,5270202,0.0,1.0,-10.8812,-11.1503,2018-04-20,1,0,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,2.02,2.015334,0.0046662,0.2315,217.400000,-2.4981,0.4025,453.120000,-0.0022,0.3831,0.000000,-100.00,0,1,0,0,0,0
1,2021-07-23,2.02,1.947700,0.0723,3.7121,228.404177,-0.2602,-0.3865,438.521197,0.2288,-0.1574,228.334457,-0.03,1,1,1,1,1,0
2,2021-04-23,1.92,1.801400,0.1186,6.5838,222.677595,-1.1201,-1.1285,414.023116,0.2793,-0.9025,219.721785,-1.33,0,1,1,1,1,0
3,2021-01-29,2.07,2.000000,0.07,3.5000,192.908020,-1.8330,-1.0002,366.455126,-2.4425,-0.8136,193.095625,0.10,1,1,1,0,0,0
4,2020-10-30,1.56,1.486500,0.0735,4.9445,162.107016,0.3510,-3.0549,321.972368,-1.9214,-1.8457,170.617757,5.25,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2001-01-26,0.70,0.710000,-0.01,-1.4085,27.655751,-41.7037,-41.0703,91.713835,-32.1423,-32.4394,27.274621,-1.38,0,0,1,0,1,0
84,2000-10-17,0.76,0.760000,0,0.0000,20.915780,-40.6645,-41.3797,90.669711,-34.5049,-33.2474,19.990145,-4.43,1,0,0,1,0,0
85,2000-07-18,0.75,0.750000,0,0.0000,21.762933,-41.9655,-40.4058,100.514915,-33.2681,-32.8782,21.945865,0.84,1,0,0,0,0,0
86,2000-04-13,0.63,0.620000,0.01,1.6129,32.602281,-41.5206,-41.3299,96.583585,-34.5057,-33.0995,31.831917,-2.36,0,1,1,0,0,0
87,2000-01-19,0.78,0.740000,0.04,5.4054,31.769757,-46.1530,-41.5554,98.177099,-32.4373,-33.0135,30.967461,-2.53,1,1,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,0,0,0,0
1,1,1,1,1,1,0
2,0,1,1,1,1,0
3,1,1,1,0,0,0
4,1,1,1,1,0,0
...,...,...,...,...,...,...
83,0,0,1,0,1,0
84,1,0,0,1,0,0
85,1,0,0,0,0,0
86,0,1,1,0,0,0
87,1,1,0,0,1,0

This is the buy signal:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,Do NOT buy,HON

This is the ticker:

RF

2021-10-22

Model has been put to sleep after the alpha spy


RF has reported earnings 103 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains RF's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-10-22        None         0.52     None               None
1    2021-07-23       0.762       0.5261   0.2359            44.8394
2    2021-04-23      0.6391       0.4772   0.1619            33.9271
3    2021-01-22        0.62       0.4152   0.2048            49.3256
4    2020-10-20        0.49       0.3269   0.1631            49.8929
5    2020-07-17       -0.23       0.0688  -0.2988          -434.3023
6    2020-04-17        0.15       0.3057  -0.1557           -50.9323
7    2020-01-17         0.4       0.3885   0.0115             2.9601
8    2019-10-22      0.3925       0.3909   0.0016             0.4093
9    2019-07-19        0.39       0.3932  -0.0032            -0.8138
10   2019-04-18      0.3731       0.3704   0.0027             0.7289
11   2019-01-18        0.38       0.3809  -0.0009            -0.2363
12   2018-10-23      0.3723       0.3625   0.0098             2.7034
13   2018-07-20      0.3489        0.332   0.0169             5.0904
14   2018-04-20      0.3341       0.3099   0.0242              7.809

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is RF's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-10-22,0.6600,0.540596,0.119405,22.0876,0,1
1,2021-07-23,0.7620,0.526100,0.2359,44.8394,1,1
2,2021-04-23,0.6391,0.477200,0.1619,33.9271,1,1
3,2021-01-22,0.6200,0.415200,0.2048,49.3256,1,1
4,2020-10-20,0.4900,0.326900,0.1631,49.8929,1,1
5,2020-07-17,-0.2300,0.068800,-0.2988,-434.3023,0,0
6,2020-04-17,0.1500,0.305700,-0.1557,-50.9323,0,0
7,2020-01-17,0.4000,0.388500,0.0115,2.9601,1,1
8,2019-10-22,0.3925,0.390900,0.0016,0.4093,1,1
9,2019-07-19,0.3900,0.393200,-0.0032,-0.8138,1,0
10,2019-04-18,0.3731,0.370400,0.0027,0.7289,0,1
11,2019-01-18,0.3800,0.380900,-0.0009,-0.2363,1,0
12,2018-10-23,0.3723,0.362500,0.0098,2.7034,1,1
13,2018-07-20,0.3489,0.332000,0.0169,5.0904,1,1
14,2018-04-20,0.3341,0.309900,0.0242,7.8090,0,1

3. Retrieve the last 5,000 daily adjusted prices for RF in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,23.50,24.3600,23.5000,24.09,24.09,10310303,0.0,1.0,2.5106,0.6173,2021-10-22
1,23.45,23.6600,23.1350,23.28,23.28,10913612,0.0,1.0,-0.7249,0.6173,2021-10-21
2,22.71,23.5300,22.6200,23.52,23.52,8524837,0.0,1.0,3.5667,0.5455,2021-10-20
3,22.68,22.8400,22.5200,22.82,22.82,5120621,0.0,1.0,0.6173,0.5455,2021-10-19
4,22.37,22.7764,22.3400,22.57,22.57,5749871,0.0,1.0,0.8941,0.4928,2021-10-18
5,22.32,22.6600,22.1200,22.43,22.43,8112577,0.0,1.0,0.4928,0.5455,2021-10-15
6,22.00,22.1300,21.7800,22.12,22.12,7092566,0.0,1.0,0.5455,-0.2283,2021-10-14
7,21.92,21.9600,21.2200,21.73,21.73,8158311,0.0,1.0,-0.8668,-0.0921,2021-10-13
8,21.76,22.0900,21.6600,22.05,22.05,8263776,0.0,1.0,1.3327,-0.2283,2021-10-12
9,22.11,22.3850,21.8200,21.85,21.85,5733547,0.0,1.0,-1.1759,-0.0921,2021-10-11
10,21.79,22.1373,21.7282,22.02,22.02,5765510,0.0,1.0,1.0555,-0.0921,2021-10-08
11,21.90,22.0400,21.7199,21.85,21.85,6513113,0.0,1.0,-0.2283,-0.0921,2021-10-07
12,21.72,21.8400,21.2600,21.70,21.70,6195054,0.0,1.0,-0.0921,-0.2759,2021-10-06
13,22.00,22.1300,21.7300,21.85,21.85,6487982,0.0,1.0,-0.6818,-0.2759,2021-10-05
14,21.70,22.0550,21.7000,21.82,21.82,7658191,0.0,1.0,0.5530,-0.2759,2021-10-04

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,453.13,454.6700,451.05,453.12,453.12,58589651,0.0,1.0,-0.0022,0.3831,2021-10-22,0
1,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
2,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
3,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
4,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
5,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
6,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
7,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
8,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
9,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
10,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
11,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
12,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
13,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
14,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
0,23.500,24.360,23.5000,24.09,24.090000,10310303,0.0,1.0,2.5106,0.6173,2021-10-22,1,1,-0.0022,0.3831,453.120000,0
64,19.175,19.715,18.9698,19.10,18.939337,8420918,0.0,1.0,-1.2290,-2.3857,2021-07-23,1,0,0.2288,-0.1574,438.521197,1
127,19.090,20.750,19.0900,20.63,20.319175,11971896,0.0,1.0,6.4388,-2.9004,2021-04-23,1,1,0.2793,-0.9025,414.023116,1
190,17.830,18.215,17.6150,17.74,17.340057,7702551,0.0,1.0,-2.7479,-2.6815,2021-01-22,0,1,-0.8136,-1.0412,379.139997,1
254,12.750,13.370,12.6800,12.94,12.527142,16365487,0.0,1.0,-1.7479,-5.0508,2020-10-20,1,1,-1.4218,-2.0006,338.576810,1
320,10.650,10.690,10.2700,10.32,9.858209,17499980,0.0,1.0,-7.4347,-2.9369,2020-07-17,0,1,-1.8454,-1.4895,315.940145,0
383,9.010,9.710,8.7700,9.52,8.986282,16875708,0.0,1.0,-0.2632,-8.5213,2020-04-17,1,0,-1.7977,-2.1624,280.249806,1
445,16.700,16.750,16.2000,16.39,15.299414,17323431,0.0,1.0,-8.3867,-6.4263,2020-01-17,0,1,-2.7531,-2.5769,322.568096,0
505,15.790,16.480,15.3600,16.22,15.001325,18765338,0.0,1.0,-4.9948,-6.8176,2019-10-22,1,1,-3.8047,-3.2899,289.143697,0
571,14.950,15.390,14.9000,15.13,13.848287,20534297,0.0,1.0,-7.3693,-8.8982,2019-07-19,1,1,-4.6669,-3.8676,286.037580,0
634,15.850,15.850,15.0500,15.25,13.820312,24412296,0.0,1.0,-12.8056,-8.7380,2019-04-18,0,0,-4.2390,-4.4182,277.802701,1
696,15.500,15.760,14.9600,15.70,14.100108,21818660,0.0,1.0,-9.0316,-8.9857,2019-01-18,0,0,-4.0979,-4.1495,254.121262,1
755,15.710,16.430,15.7100,16.28,14.488429,21101360,0.0,1.0,-7.7758,-11.5282,2018-10-23,1,0,-4.2653,-5.4970,259.393297,1
821,17.500,17.930,17.2700,17.82,15.746368,16017826,0.0,1.0,-10.0208,-11.1834,2018-07-20,1,0,-5.6538,-5.4815,263.952301,0
884,17.990,18.890,17.9900,18.89,16.613409,18950454,0.0,1.0,-7.6520,-13.0871,2018-04-20,1,1,-6.8147,-6.1499,250.491418,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-10-22,0.6600,0.540596,0.119405,22.0876,24.090000,2.5106,0.6173,453.120000,-0.0022,0.3831,0.000000,-100.00,0,1,1,1,0,0
1,2021-07-23,0.7620,0.526100,0.2359,44.8394,18.939337,-1.2290,-2.3857,438.521197,0.2288,-0.1574,19.177318,1.26,1,1,0,1,1,1
2,2021-04-23,0.6391,0.477200,0.1619,33.9271,20.319175,6.4388,-2.9004,414.023116,0.2793,-0.9025,20.791943,2.33,1,1,1,1,1,1
3,2021-01-22,0.6200,0.415200,0.2048,49.3256,17.340057,-2.7479,-2.6815,379.139997,-0.8136,-1.0412,17.320508,-0.11,1,1,1,0,1,0
4,2020-10-20,0.4900,0.326900,0.1631,49.8929,12.527142,-1.7479,-5.0508,338.576810,-1.4218,-2.0006,12.381928,-1.16,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2001-01-18,0.4700,0.470000,0,0.0000,12.228416,-57.5550,-56.2757,90.975537,-31.8216,-32.0699,12.189582,-0.32,0,0,1,0,1,0
83,2000-10-18,0.4700,0.470000,0,0.0000,8.776639,-57.5803,-57.8217,90.333274,-31.8882,-33.2474,9.284625,5.79,1,0,0,1,1,0
84,2000-07-19,0.4600,0.470000,-0.01,-2.1277,8.842621,-58.5048,-57.6329,99.707461,-33.2921,-32.9554,9.159334,3.58,0,0,0,0,0,1
85,2000-04-18,0.4700,0.480000,-0.01,-2.0833,8.869410,-57.0072,-58.3754,96.730019,-31.1836,-34.5057,8.740021,-1.46,0,0,0,1,1,0
86,2000-01-19,0.4800,0.490000,-0.01,-2.0408,10.015084,-58.4953,-58.4557,98.177099,-32.4373,-33.0135,9.500117,-5.14,0,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,1,0,0
1,1,1,0,1,1,1
2,1,1,1,1,1,1
3,1,1,1,0,1,0
4,1,1,1,1,1,0
...,...,...,...,...,...,...
82,0,0,1,0,1,0
83,1,0,0,1,1,0
84,0,0,0,0,0,1
85,0,0,0,1,1,0
86,0,0,0,0,1,0

This is the buy signal:

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,0,2,0,2,0.25,0.5,0.333333,50.0,Invalid,Do NOT buy,RF

Model performance across all the stock in the list:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,Buy Signal,symbol
0,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],ALV
1,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],VFC
2,[0],[2],[0],[2],[0.25],[0.5],[0.3333333333333333],[50.0],[Invalid],[Do NOT buy],SLB
3,[0],[0],[2],[2],[1.0],[0.5],[0.6666666666666666],[50.0],[Valid],[Buy],ROP
4,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],AXP
5,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],SMPL
6,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],GNTX
7,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],STX
8,[0],[1],[2],[1],[0.375],[0.25],[0.30000000000000004],[25.0],[Invalid],[Do NOT buy],FHB
9,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],AIMC
10,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],HCA
11,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],DSKE
12,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],[Do NOT buy],CLF
13,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],[Do NOT buy],HON
14,[0],[2],[0],[2],[0.25],[0.5],[0.3333333333333333],[50.0],[Invalid],[Do NOT buy],RF

Thank you for using the model.
Please wait 60 seconds before running the model again.

### Naive Bayes Prediction Model (Multi-Stock | Future Date | Logical Display)

In [35]:
if __name__=="__main__":
    main()        

#alphavantage API key
#TQ6TR98HVUPE3L9Z

#finhub API key
#c5d5iiqad3i9ue38pn9g

#the present date and time is Friday, 10/22/2021 at 5 PM

What is your alphavantage API Key?:

TQ6TR98HVUPE3L9Z

What kind of data are you looking for?

Type the number in the input box:

1. Upcoming Earnings Calendar (3 month horizon)
2. Historical Earnings (for a specific company)
3. Daily Adjusted Price History (for a specific company)
4. Naive Bayes Prediction Model

4

What type of analysis are you looking to do?:

1.Individual Company

2.Multi-Company

2

Enter the date of interest:

2021-10-25

What type of output would you like?:

Logic will display how the model variables were created, while Clean Variables will not:

 1.Logic

 2.Clean Variables

1


Model is sleeping so that it can reset

Stock Count: 105

There are 105 companies reporting earings on the specified date. Analysis will only be provided for the first 15 companies in the list. This should take about 9 minutes. Please wait patiently.


There are a total of 45 stock calls

This is the ticker:

ACC

2021-10-25



ACC has reported earnings 61 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ACC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.42       0.3731   0.0469            12.5704
1    2021-04-19        0.57       0.5518   0.0182             3.2983
2    2021-02-22        0.59       0.5382   0.0518             9.6247
3    2020-10-26        0.32       0.3028   0.0172             5.6803
4    2020-07-20        0.37       0.3639   0.0061             1.6763
5    2020-04-20         0.7        0.683    0.017              2.489
6    2020-02-18        0.72       0.7213  -0.0013            -0.1802
7    2019-10-21        0.46       0.4512   0.0088             1.9504
8    2019-07-22        0.56       0.5355   0.0245             4.5752
9    2019-04-22        0.69       0.6509   0.0391             6.0071
10   2019-02-19        0.72       0.7256  -0.0056            -0.7718
11   2018-10-22        0.44       0.4339   0.0061             1.4059
12   2018-07-23        0.52        0.527   -0.007            -1.3283
13   2018-04-23        0.62       0.6318  -0.0118            -1.8677
14   2018-02-20        0.72       0.7114   0.0086             1.2089

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ACC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.42,0.3731,0.0469,12.5704,0,1
1,2021-04-19,0.57,0.5518,0.0182,3.2983,0,1
2,2021-02-22,0.59,0.5382,0.0518,9.6247,1,1
3,2020-10-26,0.32,0.3028,0.0172,5.6803,0,1
4,2020-07-20,0.37,0.3639,0.0061,1.6763,0,1
5,2020-04-20,0.70,0.6830,0.017,2.4890,0,1
6,2020-02-18,0.72,0.7213,-0.0013,-0.1802,1,0
7,2019-10-21,0.46,0.4512,0.0088,1.9504,0,1
8,2019-07-22,0.56,0.5355,0.0245,4.5752,0,1
9,2019-04-22,0.69,0.6509,0.0391,6.0071,0,1
10,2019-02-19,0.72,0.7256,-0.0056,-0.7718,1,0
11,2018-10-22,0.44,0.4339,0.0061,1.4059,0,1
12,2018-07-23,0.52,0.5270,-0.007,-1.3283,0,0
13,2018-04-23,0.62,0.6318,-0.0118,-1.8677,0,0
14,2018-02-20,0.72,0.7114,0.0086,1.2089,1,1

3. Retrieve the last 5,000 daily adjusted prices for ACC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,51.62,51.650,51.120,51.39,51.39,300468,0.0,1.0,-0.4456,0.1363,2021-10-21
1,50.58,51.640,50.430,51.61,51.61,599514,0.0,1.0,2.0364,0.1363,2021-10-20
2,51.49,51.530,50.480,50.54,50.54,810077,0.0,1.0,-1.8450,0.3476,2021-10-19
3,51.36,51.860,51.285,51.43,51.43,315908,0.0,1.0,0.1363,0.3476,2021-10-18
4,52.16,52.400,51.420,51.62,51.62,331392,0.0,1.0,-1.0353,0.3476,2021-10-15
5,51.79,52.079,51.540,51.97,51.97,307641,0.0,1.0,0.3476,0.2387,2021-10-14
6,50.82,51.480,50.525,51.37,51.37,286670,0.0,1.0,1.0823,0.2387,2021-10-13
7,50.42,51.320,50.140,50.94,50.94,383356,0.0,1.0,1.0313,-0.4767,2021-10-12
8,50.28,50.515,50.000,50.40,50.40,302026,0.0,1.0,0.2387,-0.4767,2021-10-11
9,50.35,50.430,49.950,50.11,50.11,436758,0.0,1.0,-0.4767,1.2734,2021-10-08
10,50.96,51.130,50.290,50.48,50.48,507322,0.0,1.0,-0.9419,1.2734,2021-10-07
11,50.05,50.940,48.980,50.92,50.92,629021,0.0,1.0,1.7383,0.2406,2021-10-06
12,51.16,51.270,50.330,50.36,50.36,1288014,0.0,1.0,-1.5637,0.4864,2021-10-05
13,50.02,51.050,50.020,50.92,50.92,1009971,0.0,1.0,1.7993,0.2406,2021-10-04
14,48.69,49.600,48.110,49.31,49.31,1125864,0.0,1.0,1.2734,-0.4994,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,50.22,50.635,49.930,50.19,49.710640,1459237,0.0,1.0,-1.0143,-0.8558,2021-07-26,0,1,0.0655,0.1870,439.597714,0
130,43.92,44.340,43.490,44.30,43.431011,986167,0.0,1.0,-1.1134,-1.3521,2021-04-19,1,0,-0.9025,-0.4609,412.503091,0
169,42.77,44.525,42.550,44.32,43.450618,850522,0.0,1.0,1.5913,-2.5586,2021-02-22,1,1,-0.9845,-0.6896,383.249460,0
249,37.35,37.350,36.505,37.05,35.497625,1369707,0.0,1.0,-4.9595,-3.4484,2020-10-26,0,1,-2.1885,-1.4416,334.642622,0
318,33.94,33.940,32.900,33.62,31.782949,969687,0.0,1.0,-6.3555,-4.3922,2020-07-20,0,1,-0.9136,-1.8454,318.493435,1
381,32.95,33.580,31.650,31.70,29.520295,1363316,0.0,1.0,-10.4088,-7.4806,2020-04-20,0,0,-2.5822,-2.1624,275.312387,0
424,48.00,48.150,47.710,48.09,44.783313,491097,0.0,1.0,-6.7014,-6.2505,2020-02-18,0,0,-2.7628,-2.6561,327.212999,0
505,49.09,49.710,48.930,49.57,45.241932,555837,0.0,1.0,-7.8388,-8.0642,2019-10-21,1,1,-3.1156,-3.2931,290.091360,1
569,47.83,48.170,47.500,48.08,43.445251,636222,0.0,1.0,-9.1674,-9.9000,2019-07-22,1,1,-3.6524,-4.0247,286.740233,1
632,47.05,47.050,46.140,46.51,41.600710,730436,0.0,1.0,-11.5819,-11.3116,2019-04-22,0,1,-3.8482,-4.3017,278.042169,1
675,45.12,45.790,45.120,45.58,40.768874,1121809,0.0,1.0,-9.6435,-10.3799,2019-02-19,1,1,-4.1580,-4.4216,264.983835,1
755,40.45,40.670,39.610,39.69,34.759732,677015,0.0,1.0,-14.0674,-11.9304,2018-10-22,0,0,-5.8771,-5.4970,260.720553,0
819,41.97,42.100,41.600,41.77,36.170831,637795,0.0,1.0,-13.8174,-13.3638,2018-07-23,0,1,-5.3702,-5.6538,264.443059,1
882,38.11,38.220,37.780,37.97,32.504811,638080,0.0,1.0,-14.7079,-14.0892,2018-04-23,0,1,-6.2883,-6.1499,250.453837,0
925,36.15,36.360,35.480,35.57,30.450254,1432759,0.0,1.0,-15.7669,-13.7445,2018-02-20,0,0,-6.6368,-5.8845,253.975941,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.4200,0.3731,0.0469,12.5704,49.710640,-1.0143,-0.8558,439.597714,0.0655,0.1870,50.443572,1.47,0,1,1,0,0,1
1,2021-04-19,0.5700,0.5518,0.0182,3.2983,43.431011,-1.1134,-1.3521,412.503091,-0.9025,-0.4609,43.999634,1.31,0,1,0,1,0,1
2,2021-02-22,0.5900,0.5382,0.0518,9.6247,43.450618,1.5913,-2.5586,383.249460,-0.9845,-0.6896,42.538861,-2.10,1,1,1,1,0,0
3,2020-10-26,0.3200,0.3028,0.0172,5.6803,35.497625,-4.9595,-3.4484,334.642622,-2.1885,-1.4416,36.005418,1.43,0,1,1,0,0,1
4,2020-07-20,0.3700,0.3639,0.0061,1.6763,31.782949,-6.3555,-4.3922,318.493435,-0.9136,-1.8454,31.574970,-0.65,0,1,1,0,1,0
5,2020-04-20,0.7000,0.6830,0.017,2.4890,29.520295,-10.4088,-7.4806,275.312387,-2.5822,-2.1624,28.216560,-4.42,0,1,0,0,0,0
6,2020-02-18,0.7200,0.7213,-0.0013,-0.1802,44.783313,-6.7014,-6.2505,327.212999,-2.7628,-2.6561,44.364255,-0.94,1,0,0,0,0,0
7,2019-10-21,0.4600,0.4512,0.0088,1.9504,45.241932,-7.8388,-8.0642,290.091360,-3.1156,-3.2931,46.300649,2.34,0,1,1,1,1,1
8,2019-07-22,0.5600,0.5355,0.0245,4.5752,43.445251,-9.1674,-9.9000,286.740233,-3.6524,-4.0247,42.866945,-1.33,0,1,1,1,1,0
9,2019-04-22,0.6900,0.6509,0.0391,6.0071,41.600710,-11.5819,-11.3116,278.042169,-3.8482,-4.3017,41.806432,0.49,0,1,1,0,1,0
10,2019-02-19,0.7200,0.7256,-0.0056,-0.7718,40.768874,-9.6435,-10.3799,264.983835,-4.1580,-4.4216,39.883372,-2.17,1,0,1,1,1,0
11,2018-10-22,0.4400,0.4339,0.0061,1.4059,34.759732,-14.0674,-11.9304,260.720553,-5.8771,-5.4970,34.269295,-1.41,0,1,0,0,0,0
12,2018-07-23,0.5200,0.5270,-0.007,-1.3283,36.170831,-13.8174,-13.3638,264.443059,-5.3702,-5.6538,35.157667,-2.80,0,0,1,0,1,0
13,2018-04-23,0.6200,0.6318,-0.0118,-1.8677,32.504811,-14.7079,-14.0892,250.453837,-6.2883,-6.1499,32.402083,-0.32,0,0,1,0,0,0
14,2018-02-20,0.7200,0.7114,0.0086,1.2089,30.450254,-15.7669,-13.7445,253.975941,-6.6368,-5.8845,30.715634,0.87,1,1,0,0,0,0
15,2017-10-23,0.4400,0.4592,-0.0192,-4.1812,36.388391,-16.7314,-16.4821,238.458471,-7.3876,-6.8046,35.350158,-2.85,0,0,0,0,0,0
16,2017-07-24,0.5300,0.5392,-0.0092,-1.7062,40.592527,-17.2594,-16.9716,228.675814,-7.3399,-7.1858,39.107839,-3.66,0,0,1,0,0,0
17,2017-04-24,0.6200,0.6234,-0.0034,-0.5454,40.497079,-18.7947,-17.6061,218.668975,-7.8046,-7.7416,39.831711,-1.64,0,0,0,0,0,0
18,2017-02-21,0.6500,0.6440,0.006,0.9317,41.252805,-16.4077,-17.7555,217.095794,-7.8228,-7.7535,41.063874,-0.46,1,1,0,1,0,0
19,2016-10-24,0.4500,0.4309,0.0191,4.4326,41.269745,-19.5522,-18.7269,196.109090,-8.7865,-8.7355,41.980179,1.72,0,1,0,0,0,1
20,2016-07-25,0.5400,0.5258,0.0142,2.7006,41.991339,-20.5161,-19.3369,196.717646,-9.3467,-9.0153,42.095437,0.25,0,1,1,0,0,0
21,2016-04-25,0.6200,0.6313,-0.0113,-1.7900,35.732287,-18.8640,-20.6477,188.433359,-9.5201,-9.6030,36.097388,1.02,0,0,1,1,1,1
22,2016-02-22,0.7200,0.6870,0.033,4.8035,34.502055,-21.1922,-20.0052,175.042050,-9.7116,-9.6526,33.978214,-1.52,1,1,1,0,0,0
23,2015-10-26,0.0100,-0.0100,0.02,200.0000,30.989201,-21.9416,-21.8619,184.894821,-10.8081,-10.5581,31.822118,2.69,0,1,1,0,0,1
24,2015-07-27,0.1400,0.1300,0.01,7.6923,29.780536,-23.2460,-23.0675,183.699758,-11.6828,-11.4248,29.033520,-2.51,0,1,0,0,0,0
25,2015-04-27,0.6200,0.2600,0.36,138.4615,32.287286,-23.6527,-23.6885,186.369983,-12.2263,-11.3156,32.241542,-0.14,1,1,0,1,0,0
26,2015-02-17,0.2500,0.2600,-0.01,-3.8462,32.615114,-23.9564,-23.8849,184.968128,-11.6676,-11.6671,32.973438,1.10,1,0,1,0,0,1
27,2014-10-21,-0.0600,-0.0300,-0.03,-100.0000,29.644589,-24.3760,-24.5763,169.913731,-11.3555,-11.8467,29.232755,-1.39,0,0,0,1,1,0
28,2014-07-22,0.1200,0.1100,0.01,9.0909,29.733004,-25.9452,-25.6297,172.721399,-12.7714,-12.9210,29.881298,0.50,0,1,1,0,1,0
29,2014-04-22,0.2400,0.2200,0.02,9.0909,27.864385,-26.3432,-26.5565,162.957731,-12.9639,-12.9905,27.820331,-0.16,0,1,1,1,1,0
30,2014-02-12,0.2400,0.2400,0,0.0000,25.169727,-28.2505,-26.1986,157.213781,-13.7373,-12.9886,26.395907,4.87,1,0,0,0,0,1
31,2013-10-21,-0.0500,0.0400,-0.09,-225.0000,26.214048,-28.9400,-27.2753,149.782210,-14.1403,-13.4366,25.833197,-1.45,0,0,0,0,0,0
32,2013-07-23,0.0700,0.1600,-0.09,-56.2500,30.213960,-28.6565,-28.9934,144.555172,-14.8674,-14.4898,28.741323,-4.87,0,0,0,1,0,0
33,2013-04-23,0.1900,0.2500,-0.06,-24.0000,30.933252,-29.2793,-29.8570,134.138766,-14.5341,-14.7708,30.559201,-1.21,0,0,0,1,1,0
34,2013-02-12,0.2100,0.1900,0.02,10.5263,33.128150,-28.9553,-29.6209,128.669020,-15.2266,-15.0358,33.106978,-0.06,1,1,1,1,0,0
35,2012-10-22,0.0048,0.1100,-0.1052,-95.6364,30.635447,-30.6420,-30.2003,120.519101,-15.8092,-15.6387,30.378123,-0.84,0,0,0,0,0,0
36,2012-07-24,0.1800,0.1400,0.04,28.5714,32.270366,-31.3396,-30.2766,111.954063,-17.1876,-16.1688,32.401547,0.41,0,1,1,0,0,0
37,2012-04-24,0.2600,0.2900,-0.03,-10.3448,30.756021,-30.6985,-31.4861,114.193539,-16.5923,-16.7451,30.269462,-1.58,1,0,1,1,1,0
38,2012-02-14,0.2200,0.2300,-0.01,-4.3478,29.364873,-31.5664,-31.8284,111.940643,-17.0810,-17.0741,28.604196,-2.59,1,0,1,1,0,0
39,2011-10-25,0.0200,-0.0100,0.03,300.0000,26.439976,-33.3670,-32.2347,101.247143,-18.9309,-17.1304,25.947975,-1.86,0,1,1,0,0,0
40,2011-07-26,0.3100,0.1900,0.12,63.1579,25.045362,-33.2302,-32.9472,109.144352,-18.3906,-17.8142,24.611242,-1.73,1,1,1,0,0,0
41,2011-04-26,0.2500,0.2000,0.05,25.0000,22.756134,-33.4616,-33.5036,109.797121,-18.0924,-18.5482,22.842106,0.38,1,1,1,1,1,0
42,2011-02-15,0.2000,0.1700,0.03,17.6471,21.413648,-34.0916,-33.9909,107.879949,-18.8995,-18.5986,21.810442,1.85,1,1,1,0,0,1
43,2010-10-26,0.0600,-0.0300,0.09,300.0000,20.789767,-35.8934,-35.1947,95.786786,-18.8935,-19.5010,20.653759,-0.65,1,1,1,0,1,0
44,2010-07-27,0.0100,0.0200,-0.01,-50.0000,18.524116,-36.7346,-34.4746,89.522628,-20.1902,-18.9170,18.658534,0.73,1,0,0,0,0,0
45,2010-04-27,-0.0500,0.1200,-0.17,-141.6667,18.645434,-37.5989,-35.8772,94.634197,-21.5630,-19.9144,18.196832,-2.41,0,0,1,0,0,0
46,2010-02-16,-0.0400,0.0900,-0.13,-144.4444,16.819433,-36.0235,-35.8624,87.291662,-19.8129,-20.3891,17.091122,1.62,1,0,1,0,1,1
47,2009-10-27,-0.1100,-0.1200,0.01,8.3333,16.459342,-38.6761,-39.3863,84.199896,-21.3306,-21.4674,16.323925,-0.82,0,1,1,1,1,0
48,2009-04-28,0.0100,0.0400,-0.03,-75.0000,13.062640,-36.2953,-37.4681,67.005101,-21.1426,-21.1221,13.204690,1.09,1,0,1,1,0,1
49,2009-02-17,-0.0800,-0.2700,0.19,70.3704,10.239578,-40.4676,-41.5434,61.582060,-23.1761,-22.1394,10.724044,4.73,1,1,0,1,0,1
50,2008-10-28,-0.2800,0.0600,-0.34,-566.6667,14.262229,-35.7847,-42.5054,72.295111,-17.2257,-23.7761,14.001228,-1.83,0,0,0,1,1,0
51,2008-08-04,-0.0300,0.0500,-0.08,-160.0000,16.173352,-44.0755,-43.1370,95.841978,-23.9591,-23.6634,16.809963,3.94,0,0,0,0,0,1
52,2008-04-29,0.1800,0.1500,0.03,20.0000,17.298812,-44.1794,-42.8226,106.106492,-23.8780,-23.8447,17.315827,0.10,0,1,1,0,0,0
53,2008-02-26,0.2300,0.1900,0.04,21.0526,15.001757,-42.3231,-43.1306,105.046632,-23.1835,-23.7117,14.859963,-0.95,1,1,1,1,1,0
54,2007-07-30,-0.0300,0.0500,-0.08,-160.0000,13.481325,-46.0531,-46.5262,110.788223,-24.0813,-25.7217,13.962215,3.57,1,0,0,1,1,1
55,2007-05-04,-0.2000,0.2900,-0.49,-168.9655,15.924605,-46.3818,-46.4888,112.965468,-25.0644,-24.9591,15.816642,-0.68,0,0,0,1,0,0
56,2007-02-28,0.9800,0.4100,0.57,139.0244,16.329468,-45.6771,-45.9665,105.069710,-25.1587,-25.6705,16.610173,1.72,1,1,1,1,1,1
57,2006-08-01,-0.1200,0.3300,-0.45,-136.3636,13.250648,-47.7086,-47.4649,93.910737,-26.2520,-26.0425,13.188145,-0.47,0,0,1,0,0,0
58,2005-10-31,-0.0300,-0.2200,0.19,86.3636,12.384765,-48.8233,-49.9605,87.469001,-27.2849,-27.1880,12.169595,-1.74,0,1,0,1,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,1,0,0,1
1,0,1,0,1,0,1
2,1,1,1,1,0,0
3,0,1,1,0,0,1
4,0,1,1,0,1,0
5,0,1,0,0,0,0
6,1,0,0,0,0,0
7,0,1,1,1,1,1
8,0,1,1,1,1,0
9,0,1,1,0,1,0
10,1,0,1,1,1,0
11,0,1,0,0,0,0
12,0,0,1,0,1,0
13,0,0,1,0,0,0
14,1,1,0,0,0,0
15,0,0,0,0,0,0
16,0,0,1,0,0,0
17,0,0,0,0,0,0
18,1,1,0,1,0,0
19,0,1,0,0,0,1
20,0,1,1,0,0,0
21,0,0,1,1,1,1
22,1,1,1,0,0,0
23,0,1,1,0,0,1
24,0,1,0,0,0,0
25,1,1,0,1,0,0
26,1,0,1,0,0,1
27,0,0,0,1,1,0
28,0,1,1,0,1,0
29,0,1,1,1,1,0
30,1,0,0,0,0,1
31,0,0,0,0,0,0
32,0,0,0,1,0,0
33,0,0,0,1,1,0
34,1,1,1,1,0,0
35,0,0,0,0,0,0
36,0,1,1,0,0,0
37,1,0,1,1,1,0
38,1,0,1,1,0,0
39,0,1,1,0,0,0
40,1,1,1,0,0,0
41,1,1,1,1,1,0
42,1,1,1,0,0,1
43,1,1,1,0,1,0
44,1,0,0,0,0,0
45,0,0,1,0,0,0
46,1,0,1,0,1,1
47,0,1,1,1,1,0
48,1,0,1,1,0,1
49,1,1,0,1,0,1
50,0,0,0,1,1,0
51,0,0,0,0,0,1
52,0,1,1,0,0,0
53,1,1,1,1,1,0
54,1,0,0,1,1,1
55,0,0,0,1,0,0
56,1,1,1,1,1,1
57,0,0,1,0,0,0
58,0,1,0,1,0,0

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,3,0,1,0.0625,0.25,0.1,25.0,Invalid,ACC

This is the ticker:

AGNC

2021-10-25




Model has been put to sleep after historical earnings call
AGNC has reported earnings 53 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains AGNC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.76       0.6475   0.1125            17.3745
1    2021-04-26        0.76       0.6283   0.1317            20.9613
2    2021-01-25        0.75       0.6535   0.0965            14.7666
3    2020-10-26        0.81       0.5704   0.2396            42.0056
4    2020-07-27        0.58       0.4716   0.1084            22.9856
5    2020-04-29        0.57       0.5608   0.0092             1.6405
6    2020-01-29        0.57       0.5529   0.0171             3.0928
7    2019-10-30        0.59       0.5001   0.0899            17.9764
8    2019-07-24        0.49       0.5022  -0.0122            -2.4293
9    2019-04-24        0.52       0.5581  -0.0381            -6.8267
10   2019-01-30        0.53       0.5879  -0.0579            -9.8486
11   2018-10-24        0.61        0.583    0.027             4.6312
12   2018-07-25        0.63       0.6134   0.0166             2.7062
13   2018-04-25         0.6       0.5963   0.0037             0.6205
14   2018-01-31        0.63       0.6049   0.0251             4.1494

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AGNC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.76,0.6475,0.1125,17.3745,0,1
1,2021-04-26,0.76,0.6283,0.1317,20.9613,1,1
2,2021-01-25,0.75,0.6535,0.0965,14.7666,0,1
3,2020-10-26,0.81,0.5704,0.2396,42.0056,1,1
4,2020-07-27,0.58,0.4716,0.1084,22.9856,1,1
5,2020-04-29,0.57,0.5608,0.0092,1.6405,0,1
6,2020-01-29,0.57,0.5529,0.0171,3.0928,0,1
7,2019-10-30,0.59,0.5001,0.0899,17.9764,1,1
8,2019-07-24,0.49,0.5022,-0.0122,-2.4293,0,0
9,2019-04-24,0.52,0.5581,-0.0381,-6.8267,0,0
10,2019-01-30,0.53,0.5879,-0.0579,-9.8486,0,0
11,2018-10-24,0.61,0.5830,0.027,4.6312,0,1
12,2018-07-25,0.63,0.6134,0.0166,2.7062,1,1
13,2018-04-25,0.60,0.5963,0.0037,0.6205,0,1
14,2018-01-31,0.63,0.6049,0.0251,4.1494,1,1

3. Retrieve the last 5,000 daily adjusted prices for AGNC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,16.5900,16.6775,16.500,16.60,16.60,4077751,0.0,1.0,0.0603,0.5455,2021-10-21
1,16.5000,16.7450,16.475,16.59,16.59,6198593,0.0,1.0,0.5455,-0.0617,2021-10-20
2,16.3700,16.5100,16.320,16.50,16.50,6485324,0.0,1.0,0.7941,-0.0617,2021-10-19
3,16.2300,16.3700,16.140,16.34,16.34,5058778,0.0,1.0,0.6778,-0.0672,2021-10-18
4,16.2309,16.3600,16.220,16.22,16.22,5049756,0.0,1.0,-0.0672,-0.0617,2021-10-15
5,16.2000,16.2700,16.160,16.19,16.19,5607184,0.0,1.0,-0.0617,-0.0617,2021-10-14
6,16.1801,16.2090,16.080,16.14,16.14,4849612,0.0,1.0,-0.2478,0.1250,2021-10-13
7,16.2100,16.2900,16.150,16.20,16.20,7247140,0.0,1.0,-0.0617,0.1250,2021-10-12
8,16.1950,16.2700,16.130,16.17,16.17,4496498,0.0,1.0,-0.1544,0.1884,2021-10-11
9,16.0300,16.1750,16.010,16.12,16.12,3651288,0.0,1.0,0.5614,0.1884,2021-10-08
10,16.0000,16.1300,15.960,16.02,16.02,4839628,0.0,1.0,0.1250,0.1884,2021-10-07
11,15.9200,15.9650,15.810,15.95,15.95,7799220,0.0,1.0,0.1884,-0.1866,2021-10-06
12,16.0800,16.1400,15.950,16.05,16.05,6411424,0.0,1.0,-0.1866,-0.6841,2021-10-05
13,15.9500,16.2200,15.910,16.07,16.07,5631046,0.0,1.0,0.7524,-0.8069,2021-10-04
14,15.7700,15.9700,15.760,15.90,15.90,4837583,0.0,1.0,0.8244,-1.0520,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,16.14,16.335,16.1350,16.18,15.824102,7429122,0.00,1.0,-1.9572,-3.0449,2021-07-26,1,0,0.0655,0.1870,439.597714,0
125,17.51,17.530,17.3400,17.36,16.637921,7961293,0.00,1.0,-4.9805,-4.5079,2021-04-26,0,1,-0.6115,-0.9025,414.887444,1
188,16.20,16.380,16.1200,16.25,15.233480,8653451,0.00,1.0,-5.9662,-5.6622,2021-01-25,0,1,-0.7910,-0.8957,380.635247,1
249,14.10,14.149,13.9100,14.09,12.897530,6125191,0.00,1.0,-8.5282,-9.4315,2020-10-26,1,1,-2.1885,-1.4416,334.642622,0
313,13.55,13.770,13.4898,13.71,12.229970,8350526,0.00,1.0,-9.7419,-10.6637,2020-07-27,1,1,-1.3111,-1.8180,317.413197,1
374,13.03,13.060,12.5500,12.74,11.157893,11458033,0.12,1.0,-14.3677,-13.5762,2020-04-29,0,0,-1.6659,-1.9659,286.673338,1
437,18.45,18.760,18.4300,18.74,15.758724,8516242,0.00,1.0,-14.5869,-16.0465,2020-01-29,1,1,-3.3471,-2.6849,317.388738,0
498,16.45,16.530,16.4100,16.48,13.608393,3871960,0.16,1.0,-17.2742,-18.2679,2019-10-30,1,0,-3.0734,-3.1847,294.104425,1
567,17.52,17.560,17.4100,17.44,13.842746,5361770,0.00,1.0,-20.9889,-20.4905,2019-07-24,0,0,-3.0223,-3.6524,290.147620,1
630,18.19,18.290,18.1800,18.28,14.090636,5322552,0.00,1.0,-22.5364,-22.9602,2019-04-24,1,1,-4.3958,-4.2390,279.919603,0
688,18.00,18.050,17.9100,17.94,13.553232,10537690,0.18,1.0,-24.7043,-25.1198,2019-01-30,1,1,-3.7384,-4.5696,255.189399,1
753,17.63,18.060,17.5800,17.84,12.946307,9649239,0.00,1.0,-26.5666,-27.6341,2018-10-24,1,0,-7.9742,-5.4970,251.534043,0
817,19.18,19.280,19.1600,19.25,13.581923,2969937,0.00,1.0,-29.1871,-29.3339,2018-07-25,1,1,-4.7244,-5.6538,268.038805,1
880,18.82,19.000,18.7900,18.94,12.990512,4747963,0.00,1.0,-30.9750,-31.5582,2018-04-25,1,1,-5.7885,-6.3106,247.691582,1
938,19.13,19.240,18.5700,18.79,12.641669,7972221,0.00,1.0,-33.9170,-33.6891,2018-01-31,0,0,-6.6948,-6.6982,263.801834,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.76,0.6475,0.1125,17.3745,15.824102,-1.9572,-3.0449,439.597714,0.0655,0.1870,15.824102,0.00,0,1,0,1,0,0
1,2021-04-26,0.76,0.6283,0.1317,20.9613,16.637921,-4.9805,-4.5079,414.887444,-0.6115,-0.9025,17.011699,2.25,1,1,1,0,1,1
2,2021-01-25,0.75,0.6535,0.0965,14.7666,15.233480,-5.9662,-5.6622,380.635247,-0.7910,-0.8957,15.149110,-0.55,0,1,1,0,1,0
3,2020-10-26,0.81,0.5704,0.2396,42.0056,12.897530,-8.5282,-9.4315,334.642622,-2.1885,-1.4416,13.043989,1.14,1,1,1,1,0,1
4,2020-07-27,0.58,0.4716,0.1084,22.9856,12.229970,-9.7419,-10.6637,317.413197,-1.3111,-1.8180,12.105083,-1.02,1,1,1,1,1,0
5,2020-04-29,0.57,0.5608,0.0092,1.6405,11.157893,-14.3677,-13.5762,286.673338,-1.6659,-1.9659,10.877632,-2.51,0,1,0,0,1,0
6,2020-01-29,0.57,0.5529,0.0171,3.0928,15.758724,-14.5869,-16.0465,317.388738,-3.3471,-2.6849,15.674632,-0.53,0,1,1,1,0,0
7,2019-10-30,0.59,0.5001,0.0899,17.9764,13.608393,-17.2742,-18.2679,294.104425,-3.0734,-3.1847,14.079071,3.46,1,1,0,1,1,1
8,2019-07-24,0.49,0.5022,-0.0122,-2.4293,13.842746,-20.9889,-20.4905,290.147620,-3.0223,-3.6524,13.652249,-1.38,0,0,0,0,1,0
9,2019-04-24,0.52,0.5581,-0.0381,-6.8267,14.090636,-22.5364,-22.9602,279.919603,-4.3958,-4.2390,13.712933,-2.68,0,0,1,1,0,0
10,2019-01-30,0.53,0.5879,-0.0579,-9.8486,13.553232,-24.7043,-25.1198,255.189399,-3.7384,-4.5696,13.530568,-0.17,0,0,1,1,1,0
11,2018-10-24,0.61,0.5830,0.027,4.6312,12.946307,-26.5666,-27.6341,251.534043,-7.9742,-5.4970,13.105959,1.23,0,1,0,1,0,1
12,2018-07-25,0.63,0.6134,0.0166,2.7062,13.581923,-29.1871,-29.3339,268.038805,-4.7244,-5.6538,13.666590,0.62,1,1,1,1,1,0
13,2018-04-25,0.60,0.5963,0.0037,0.6205,12.990512,-30.9750,-31.5582,247.691582,-5.7885,-6.3106,13.093393,0.79,0,1,1,1,1,0
14,2018-01-31,0.63,0.6049,0.0251,4.1494,12.641669,-33.9170,-33.6891,263.801834,-6.6948,-6.6982,12.655125,0.11,1,1,0,0,1,0
15,2017-10-25,0.62,0.6114,0.0086,1.4066,13.915303,-35.5475,-35.1265,237.694987,-7.2156,-6.9067,13.324681,-4.24,0,1,1,0,0,0
16,2017-07-26,0.67,0.5948,0.0752,12.6429,13.398181,-36.5015,-36.9217,229.240972,-7.4708,-7.3399,13.524758,0.94,1,1,1,1,0,0
17,2017-04-26,0.64,0.5726,0.0674,11.7709,12.941453,-37.4809,-38.3744,219.803022,-7.8433,-7.8046,13.283655,2.64,0,1,1,1,0,1
18,2017-02-01,0.64,0.5865,0.0535,9.1219,11.242491,-39.7185,-40.1225,208.953201,-8.1645,-8.2289,11.406040,1.45,0,1,0,1,1,1
19,2016-10-24,0.64,0.5516,0.0884,16.0261,11.568999,-40.5804,-41.6885,196.109090,-8.7865,-8.7355,11.767258,1.71,1,1,1,1,0,1
20,2016-07-27,0.56,0.5130,0.047,9.1618,11.158174,-42.7492,-43.1857,196.599616,-9.4804,-9.1080,11.232600,0.67,1,1,1,1,0,0
21,2016-04-25,0.52,0.5632,-0.0432,-7.6705,10.245981,-44.8251,-45.2680,188.433359,-9.5201,-9.6030,10.009873,-2.30,0,0,1,1,1,0
22,2016-02-01,0.72,0.5671,0.1529,26.9617,9.079852,-46.7457,-46.1101,174.026553,-9.6107,-10.5356,9.364605,3.14,1,1,0,0,1,1
23,2015-10-26,0.51,0.6100,-0.1,-16.3934,9.787913,-49.0478,-48.7006,184.894821,-10.8081,-10.5581,9.315711,-4.82,0,0,1,0,0,0
24,2015-07-27,0.60,0.6700,-0.07,-10.4478,9.318476,-49.6571,-50.3788,183.699758,-11.6828,-11.4248,9.432905,1.23,0,0,0,1,0,1
25,2015-04-27,0.70,0.7000,0,0.0000,10.371815,-51.9823,-51.7813,186.369983,-12.2263,-11.3156,10.145083,-2.19,1,0,1,0,0,0
26,2015-02-02,-0.94,0.7800,-1.72,-220.5128,10.139324,-52.8842,-52.8878,177.758148,-11.1431,-12.0658,10.271679,1.31,0,0,0,1,1,1
27,2014-10-27,0.54,0.7100,-0.17,-23.9437,10.544607,-54.3524,-54.3303,171.743584,-12.2548,-11.9181,10.508246,-0.34,1,0,1,0,0,0
28,2014-07-28,0.08,0.6400,-0.56,-87.5000,10.450631,-56.0529,-55.7155,172.372819,-12.8374,-12.7935,10.357991,-0.89,1,0,1,0,0,0
29,2014-04-28,-0.41,0.6900,-1.1,-159.4203,9.695367,-57.6066,-56.6781,162.081754,-13.3484,-13.4405,9.613822,-0.84,0,0,1,0,1,0
30,2014-02-03,-0.28,0.6400,-0.92,-143.7500,8.770559,-58.2752,-58.3142,150.392290,-15.4957,-13.4589,8.883002,1.28,1,0,0,1,0,1
31,2013-10-28,-1.80,0.7700,-2.57,-333.7662,9.615447,-60.4140,-59.6086,151.353893,-13.9497,-14.0028,8.809796,-8.38,0,0,1,0,1,0
32,2013-07-29,0.97,0.9500,0.02,2.1053,8.504634,-60.8802,-61.1652,144.085116,-14.5808,-14.4898,8.987277,5.68,1,1,0,1,0,0
33,2013-05-02,0.64,1.1100,-0.47,-42.3423,12.306825,-62.9089,-62.8079,135.813588,-14.4104,-14.8870,11.399615,-7.37,0,0,1,0,1,0
34,2013-02-07,2.37,1.0300,1.34,130.0971,11.164024,-64.4345,-64.2856,127.771841,-15.5004,-15.0290,11.496797,2.98,1,1,0,0,0,1
35,2012-08-02,-0.88,0.8600,-1.74,-202.3256,11.618399,-66.7476,-66.9459,114.219392,-16.3534,-16.3120,11.548768,-0.60,0,0,1,1,0,0
36,2012-05-02,2.66,1.1900,1.47,123.5294,9.941129,-68.0658,-68.0606,116.696798,-16.5975,-16.5113,10.105564,1.65,1,1,1,0,0,1
37,2012-02-06,0.99,1.1800,-0.19,-16.1017,9.039538,-69.6253,-69.3367,111.327905,-16.9071,-17.0849,9.119262,0.88,0,0,1,0,1,0
38,2011-10-25,1.39,1.3800,0.01,0.7246,8.335211,-70.7125,-70.9102,101.247143,-18.9309,-17.1304,8.367337,0.39,1,1,1,1,0,0
39,2011-07-26,1.36,1.3600,0,0.0000,8.048245,-72.0644,-72.1626,109.144352,-18.3906,-17.8142,7.884391,-2.04,0,0,1,1,0,0
40,2011-04-25,1.48,1.3500,0.13,9.6296,7.631697,-73.5194,-73.5286,108.860355,-18.5665,-18.4072,7.631697,0.00,0,1,1,1,0,0
41,2011-02-08,2.50,2.0300,0.47,23.1527,7.389991,-74.6397,-74.7175,107.523080,-18.5986,-18.5696,7.412722,0.31,1,1,1,1,0,0
42,2010-10-26,1.69,1.2300,0.46,37.3984,6.702446,-75.8470,-75.9766,95.786786,-18.8935,-19.5010,6.820456,1.76,1,1,1,1,1,1
43,2010-07-28,1.23,1.1700,0.06,5.1282,6.433514,-77.2184,-77.1373,88.944804,-20.0999,-19.0500,6.259139,-2.71,0,1,1,0,0,0
44,2010-04-26,2.13,1.1900,0.94,78.9916,5.932814,-78.0753,-78.0478,96.926569,-20.4542,-19.5895,5.965532,0.55,1,1,1,0,0,0
45,2010-02-08,1.79,1.2900,0.5,38.7597,5.634039,-79.2790,-79.1376,84.229215,-21.0894,-20.3813,5.576084,-1.03,0,1,1,0,0,0
46,2009-10-20,1.82,1.3000,0.52,40.0000,5.498885,-80.2907,-80.3475,86.407355,-21.4121,-20.4503,5.532343,0.61,0,1,1,1,0,0
47,2009-07-29,2.02,1.1400,0.88,77.1930,4.490662,-81.2889,-80.9079,76.894775,-21.0850,-20.7655,4.494413,0.08,1,1,1,0,0,0
48,2009-04-29,1.09,0.7600,0.33,43.4211,3.113117,-82.2006,-82.4227,68.430241,-20.9082,-21.1426,3.301524,6.05,1,1,0,1,1,0
49,2009-02-04,0.73,0.9200,-0.19,-20.6522,3.328117,-83.5242,-83.3459,64.776989,-23.1590,-21.6658,2.985911,-10.28,0,0,1,0,0,0
50,2008-10-29,1.26,1.1200,0.14,12.5000,2.721976,-83.9884,-83.8401,71.770787,-23.4608,-21.6979,2.855142,4.89,1,1,1,0,0,1
51,2008-07-29,0.37,0.3200,0.05,15.6250,2.361008,-84.6488,-85.0683,96.831147,-21.8978,-23.5700,2.353494,-0.32,0,1,0,1,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,0,1,0,0
1,1,1,1,0,1,1
2,0,1,1,0,1,0
3,1,1,1,1,0,1
4,1,1,1,1,1,0
5,0,1,0,0,1,0
6,0,1,1,1,0,0
7,1,1,0,1,1,1
8,0,0,0,0,1,0
9,0,0,1,1,0,0
10,0,0,1,1,1,0
11,0,1,0,1,0,1
12,1,1,1,1,1,0
13,0,1,1,1,1,0
14,1,1,0,0,1,0
15,0,1,1,0,0,0
16,1,1,1,1,0,0
17,0,1,1,1,0,1
18,0,1,0,1,1,1
19,1,1,1,1,0,1
20,1,1,1,1,0,0
21,0,0,1,1,1,0
22,1,1,0,0,1,1
23,0,0,1,0,0,0
24,0,0,0,1,0,1
25,1,0,1,0,0,0
26,0,0,0,1,1,1
27,1,0,1,0,0,0
28,1,0,1,0,0,0
29,0,0,1,0,1,0
30,1,0,0,1,0,1
31,0,0,1,0,1,0
32,1,1,0,1,0,0
33,0,0,1,0,1,0
34,1,1,0,0,0,1
35,0,0,1,1,0,0
36,1,1,1,0,0,1
37,0,0,1,0,1,0
38,1,1,1,1,0,0
39,0,0,1,1,0,0
40,0,1,1,1,0,0
41,1,1,1,1,0,0
42,1,1,1,1,1,1
43,0,1,1,0,0,0
44,1,1,1,0,0,0
45,0,1,1,0,0,0
46,0,1,1,1,0,0
47,1,1,1,0,0,0
48,1,1,0,1,1,0
49,0,0,1,0,0,0
50,1,1,1,0,0,1
51,0,1,0,1,1,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,2,1,1,0.166667,0.25,0.2,25.0,Invalid,AGNC

This is the ticker:

AIN

2021-10-25



AIN has reported earnings 102 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains AIN's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        1.01       0.7358   0.2742            37.2656
1    2021-04-26        0.87       0.6519   0.2181            33.4561
2    2021-02-10        0.89       0.6825   0.2075            30.4029
3    2020-10-28        0.96       0.6352   0.3248            51.1335
4    2020-07-29        1.09       0.6712   0.4188            62.3957
5    2020-04-29        0.78       0.6084   0.1716            28.2051
6    2020-02-10        0.97       0.7338   0.2362            32.1886
7    2019-10-29        1.17       0.7833   0.3867            49.3681
8    2019-07-30        1.09         0.86     0.23            26.7442
9    2019-04-30        0.87         0.74     0.13            17.5676
10   2019-02-11        0.74         0.74        0                  0
11   2018-10-30        0.85          0.7     0.15            21.4286
12   2018-08-06        0.82        0.565    0.255            45.1327
13   2018-05-07        0.54         0.53     0.01             1.8868
14   2018-02-05        0.43         0.44    -0.01            -2.2727

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AIN's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,1.01,0.7358,0.2742,37.2656,1,1
1,2021-04-26,0.87,0.6519,0.2181,33.4561,0,1
2,2021-02-10,0.89,0.6825,0.2075,30.4029,0,1
3,2020-10-28,0.96,0.6352,0.3248,51.1335,0,1
4,2020-07-29,1.09,0.6712,0.4188,62.3957,1,1
5,2020-04-29,0.78,0.6084,0.1716,28.2051,0,1
6,2020-02-10,0.97,0.7338,0.2362,32.1886,0,1
7,2019-10-29,1.17,0.7833,0.3867,49.3681,1,1
8,2019-07-30,1.09,0.8600,0.23,26.7442,1,1
9,2019-04-30,0.87,0.7400,0.13,17.5676,1,1
10,2019-02-11,0.74,0.7400,0,0.0000,0,0
11,2018-10-30,0.85,0.7000,0.15,21.4286,1,1
12,2018-08-06,0.82,0.5650,0.255,45.1327,1,1
13,2018-05-07,0.54,0.5300,0.01,1.8868,1,1
14,2018-02-05,0.43,0.4400,-0.01,-2.2727,0,0

3. Retrieve the last 5,000 daily adjusted prices for AIN in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,81.55,81.9200,81.0300,81.74,81.74,100600,0.0,1.0,0.2330,0.3560,2021-10-21
1,80.53,81.6200,79.6000,81.48,81.48,44989,0.0,1.0,1.1797,-0.0869,2021-10-20
2,80.91,80.9100,79.6427,80.53,80.53,52606,0.0,1.0,-0.4697,0.3560,2021-10-19
3,79.82,81.1700,79.5100,80.40,80.40,82436,0.0,1.0,0.7266,-0.0869,2021-10-18
4,82.86,82.8600,80.2400,80.28,80.28,99090,0.0,1.0,-3.1137,-0.0869,2021-10-15
5,81.47,82.2300,81.3600,81.76,81.76,75601,0.0,1.0,0.3560,-0.0869,2021-10-14
6,80.57,80.7400,79.5100,80.50,80.50,58276,0.0,1.0,-0.0869,0.1508,2021-10-13
7,80.12,81.2000,79.8500,80.75,80.75,49955,0.0,1.0,0.7863,0.1508,2021-10-12
8,81.27,81.7100,79.7800,79.88,79.88,53224,0.0,1.0,-1.7103,0.1508,2021-10-11
9,81.38,81.7200,80.6450,81.19,81.19,38573,0.0,1.0,-0.2335,0.2493,2021-10-08
10,80.47,81.9900,80.4200,81.51,81.51,84332,0.0,1.0,1.2924,0.1508,2021-10-07
11,79.56,80.6245,77.7000,79.68,79.68,81600,0.0,1.0,0.1508,0.2493,2021-10-06
12,80.23,81.2300,78.6900,80.43,80.43,79287,0.0,1.0,0.2493,0.1005,2021-10-05
13,79.64,80.2400,78.7200,79.72,79.72,102732,0.0,1.0,0.1005,0.6655,2021-10-04
14,77.47,80.0200,77.0400,79.31,79.31,120187,0.0,1.0,2.3751,0.0894,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,82.72,83.04,81.19,81.70,81.489487,88471,0.0,1.0,-1.4876,-0.0864,2021-07-26,0,0,0.0655,0.1870,439.597714,0
125,87.42,89.39,86.26,89.01,88.578855,93402,0.0,1.0,1.3256,-0.4049,2021-04-26,1,1,-0.6115,-0.9025,414.887444,1
176,75.40,76.87,74.95,75.36,74.822233,100819,0.0,1.0,-0.7663,-0.5612,2021-02-10,0,1,-1.4920,-0.8141,386.269667,0
247,51.08,51.77,50.26,51.04,50.536235,148448,0.0,1.0,-1.0645,-2.1625,2020-10-28,1,1,-3.0139,-1.5711,322.090689,0
311,51.17,51.79,49.07,49.56,48.889240,323617,0.0,1.0,-4.4572,-1.8046,2020-07-29,0,0,-0.8820,-1.8180,319.279062,1
374,52.89,56.52,52.67,55.69,54.777813,248900,0.0,1.0,3.5693,0.2623,2020-04-29,1,0,-1.6659,-1.9659,286.673338,1
429,71.62,72.94,71.40,72.15,70.626317,247924,0.0,1.0,-1.3874,-1.8046,2020-02-10,1,0,-1.8142,-2.6538,325.220938,1
499,81.14,82.28,80.56,81.83,79.904980,196524,0.0,1.0,-1.5221,-2.6828,2019-10-29,1,1,-3.2326,-3.1847,293.205112,0
563,78.09,79.32,77.77,79.00,76.972508,181213,0.0,1.0,-1.4310,-2.8859,2019-07-30,1,1,-3.4862,-3.4598,289.454592,0
626,73.87,73.99,72.87,73.97,71.890995,221973,0.0,1.0,-2.6790,-2.7173,2019-04-30,1,1,-4.0396,-4.0951,281.634198,1
680,69.84,70.78,69.63,70.15,68.009787,135516,0.0,1.0,-2.6206,-3.0371,2019-02-11,1,1,-4.8346,-4.3996,258.088628,0
749,65.71,67.81,65.07,67.16,64.910975,164838,0.0,1.0,-1.2160,-4.3201,2018-10-30,1,1,-3.7218,-5.4063,253.856742,1
809,64.75,65.28,64.00,64.30,62.012199,180630,0.0,1.0,-4.2283,-4.2141,2018-08-06,0,1,-5.2907,-5.4487,268.633377,1
872,58.75,60.05,58.75,59.90,57.615471,88195,0.0,1.0,-1.9311,-3.9771,2018-05-07,1,1,-6.0352,-5.9168,250.782676,0
935,61.65,62.55,59.60,60.05,57.613348,120356,0.0,1.0,-6.5477,-4.0577,2018-02-05,0,1,-9.6780,-6.6982,246.985520,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,1.01,0.7358,0.2742,37.2656,81.489487,-1.4876,-0.0864,439.597714,0.0655,0.1870,85.459232,4.87,1,1,0,0,0,1
1,2021-04-26,0.87,0.6519,0.2181,33.4561,88.578855,1.3256,-0.4049,414.887444,-0.6115,-0.9025,89.434689,0.97,0,1,1,1,1,0
2,2021-02-10,0.89,0.6825,0.2075,30.4029,74.822233,-0.7663,-0.5612,386.269667,-1.4920,-0.8141,71.307494,-4.70,0,1,1,0,0,0
3,2020-10-28,0.96,0.6352,0.3248,51.1335,50.536235,-1.0645,-2.1625,322.090689,-3.0139,-1.5711,49.011434,-3.02,0,1,1,1,0,0
4,2020-07-29,1.09,0.6712,0.4188,62.3957,48.889240,-4.4572,-1.8046,319.279062,-0.8820,-1.8180,47.518053,-2.80,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2001-01-26,0.30,0.3000,0,0.0000,10.654066,-27.7690,-29.2525,91.713835,-32.1423,-32.4394,10.921827,2.51,0,0,1,1,1,1
82,2000-10-26,0.30,0.4500,-0.15,-33.3333,7.180220,-28.1978,-29.5366,91.973403,-32.9273,-32.4272,7.356379,2.45,0,0,0,1,0,1
83,2000-07-27,0.31,0.3100,0,0.0000,10.351073,-28.6133,-29.8282,97.568176,-33.1439,-33.3846,9.949432,-3.88,0,0,0,1,1,0
84,2000-04-28,0.33,0.2100,0.12,57.1429,10.703390,-24.1970,-29.5366,97.148492,-33.9126,-32.6894,10.569510,-1.25,0,1,1,1,0,0
85,2000-01-28,0.48,0.2500,0.23,92.0000,10.527232,-25.4445,-30.7343,90.747029,-34.9192,-33.7006,10.435629,-0.87,1,1,0,1,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,0,0,1
1,0,1,1,1,1,0
2,0,1,1,0,0,0
3,0,1,1,1,0,0
4,1,1,0,0,1,0
...,...,...,...,...,...,...
81,0,0,1,1,1,1
82,0,0,0,1,0,1
83,0,0,0,1,1,0
84,0,1,1,1,0,0
85,1,1,0,1,0,0

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,AIN

This is the ticker:

AJRD

2021-10-25

Model has been put to sleep after the alpha spy


AJRD has reported earnings 91 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains AJRD's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.59       0.4384   0.1516            34.5803
1    2021-04-26        0.36       0.4423  -0.0823           -18.6073
2    2021-02-18        0.47       0.4588   0.0112             2.4412
3    2020-10-26        0.38       0.4578  -0.0778           -16.9943
4    2020-07-27        0.46       0.4017   0.0583            14.5133
5    2020-04-28        0.35       0.4384  -0.0884           -20.1642
6    2020-02-19        0.27        0.456   -0.186           -40.7895
7    2019-10-29        0.35       0.4433  -0.0933           -21.0467
8    2019-07-31         0.5       0.3967   0.1033            26.0398
9    2019-04-30      0.4829         0.25   0.2329              93.16
10   2019-02-19      0.3345         0.34  -0.0055            -1.6176
11   2018-10-30       0.434       0.2725   0.1615            59.2661
12   2018-07-30        0.45        0.275    0.175            63.6364
13   2018-05-01        0.18         0.18        0                  0
14   2018-02-21      0.1671         0.28  -0.1129           -40.3214

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AJRD's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.5900,0.4384,0.1516,34.5803,1,1
1,2021-04-26,0.3600,0.4423,-0.0823,-18.6073,0,0
2,2021-02-18,0.4700,0.4588,0.0112,2.4412,1,1
3,2020-10-26,0.3800,0.4578,-0.0778,-16.9943,0,0
4,2020-07-27,0.4600,0.4017,0.0583,14.5133,1,1
5,2020-04-28,0.3500,0.4384,-0.0884,-20.1642,1,0
6,2020-02-19,0.2700,0.4560,-0.186,-40.7895,0,0
7,2019-10-29,0.3500,0.4433,-0.0933,-21.0467,0,0
8,2019-07-31,0.5000,0.3967,0.1033,26.0398,1,1
9,2019-04-30,0.4829,0.2500,0.2329,93.1600,1,1
10,2019-02-19,0.3345,0.3400,-0.0055,-1.6176,0,0
11,2018-10-30,0.4340,0.2725,0.1615,59.2661,0,1
12,2018-07-30,0.4500,0.2750,0.175,63.6364,1,1
13,2018-05-01,0.1800,0.1800,0,0.0000,1,0
14,2018-02-21,0.1671,0.2800,-0.1129,-40.3214,0,0

3. Retrieve the last 5,000 daily adjusted prices for AJRD in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,44.08,44.4900,43.080,44.25,44.25,669661,0.0,1.0,0.3857,0.0681,2021-10-21
1,44.06,44.5000,43.990,44.09,44.09,313344,0.0,1.0,0.0681,0.0458,2021-10-20
2,43.90,44.3100,43.900,44.03,44.03,309926,0.0,1.0,0.2961,0.0458,2021-10-19
3,43.58,44.2400,43.355,43.90,43.90,397159,0.0,1.0,0.7343,-0.2054,2021-10-18
4,44.23,44.5300,43.830,43.90,43.90,370962,0.0,1.0,-0.7461,0.0458,2021-10-15
5,43.82,43.9100,43.500,43.73,43.73,452077,0.0,1.0,-0.2054,0.4941,2021-10-14
6,43.65,44.0500,43.400,43.67,43.67,173948,0.0,1.0,0.0458,0.7852,2021-10-13
7,43.30,43.9500,43.270,43.64,43.64,198649,0.0,1.0,0.7852,0.4941,2021-10-12
8,43.50,43.7009,43.390,43.41,43.41,153890,0.0,1.0,-0.2069,0.4941,2021-10-11
9,42.46,45.0000,42.460,43.50,43.50,377051,0.0,1.0,2.4494,0.4474,2021-10-08
10,42.50,43.0100,42.500,42.71,42.71,273612,0.0,1.0,0.4941,0.1149,2021-10-07
11,41.10,42.9200,40.835,42.43,42.43,506128,0.0,1.0,3.2360,0.1149,2021-10-06
12,42.62,42.6500,41.280,41.41,41.41,760921,0.0,1.0,-2.8390,0.1149,2021-10-05
13,42.47,43.0200,42.450,42.66,42.66,295541,0.0,1.0,0.4474,0.1149,2021-10-04
14,43.76,43.8300,42.210,42.55,42.55,593928,0.0,1.0,-2.7651,0.2095,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,47.93,48.020,47.205,47.35,47.350000,577744,0.0,1.0,-1.2101,0.2088,2021-07-26,0,0,0.0655,0.1870,439.597714,0
125,48.75,48.750,48.410,48.47,48.470000,799620,0.0,1.0,-0.5744,0.1647,2021-04-26,0,1,-0.6115,-0.9025,414.887444,1
171,51.90,52.045,50.860,51.98,46.937315,1630604,0.0,1.0,-9.5620,-9.9081,2021-02-18,1,1,-0.6896,-1.1110,386.903415,1
249,37.10,37.170,35.930,36.28,32.760404,932782,0.0,1.0,-11.6970,-11.3188,2020-10-26,0,0,-2.1885,-1.4416,334.642622,0
313,37.24,37.240,36.480,36.81,33.238987,439855,0.0,1.0,-10.7439,-10.4311,2020-07-27,0,0,-1.3111,-1.8180,317.413197,1
375,42.53,43.040,41.420,42.24,38.142212,510536,0.0,1.0,-10.3169,-10.8388,2020-04-28,1,0,-4.0066,-1.9659,279.360093,0
423,53.60,54.200,52.870,53.13,47.975751,417852,0.0,1.0,-10.4930,-9.2797,2020-02-19,0,1,-2.6681,-2.7628,328.777496,1
499,45.29,46.400,45.290,46.02,41.555506,711190,0.0,1.0,-8.2457,-9.6416,2019-10-29,1,1,-3.2326,-3.1847,293.205112,0
562,43.53,43.790,42.600,42.72,38.575646,570218,0.0,1.0,-11.3815,-9.6385,2019-07-31,0,1,-4.8846,-3.4862,286.287840,0
626,33.79,33.950,33.320,33.86,30.575173,716055,0.0,1.0,-9.5141,-8.8925,2019-04-30,0,0,-4.0396,-4.0951,281.634198,1
675,40.03,40.520,39.590,40.35,36.435565,681457,0.0,1.0,-8.9794,-9.7012,2019-02-19,1,1,-4.1580,-4.4216,264.983835,1
749,29.60,30.340,29.400,30.26,27.324416,543629,0.0,1.0,-7.6878,-9.7602,2018-10-30,1,1,-3.7218,-5.4063,253.856742,1
814,28.09,28.100,27.690,27.72,25.030827,697155,0.0,1.0,-10.8906,-11.5501,2018-07-30,1,0,-6.1465,-5.5768,264.207117,0
876,27.72,28.200,27.520,27.94,25.229484,832433,0.0,1.0,-8.9845,-11.5320,2018-05-01,1,1,-5.6505,-6.2006,248.959964,1
924,26.93,27.520,26.820,26.98,24.362615,922372,0.0,1.0,-9.5335,-9.7666,2018-02-21,1,0,-7.0568,-5.9170,252.712612,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.5900,0.4384,0.1516,34.5803,47.350000,-1.2101,0.2088,439.597714,0.0655,0.1870,46.800000,-1.16,1,1,0,0,0,0
1,2021-04-26,0.3600,0.4423,-0.0823,-18.6073,48.470000,-0.5744,0.1647,414.887444,-0.6115,-0.9025,47.600000,-1.79,0,0,1,0,1,0
2,2021-02-18,0.4700,0.4588,0.0112,2.4412,46.937315,-9.5620,-9.9081,386.903415,-0.6896,-1.1110,47.316570,0.81,1,1,1,1,1,0
3,2020-10-26,0.3800,0.4578,-0.0778,-16.9943,32.760404,-11.6970,-11.3188,334.642622,-2.1885,-1.4416,31.351742,-4.30,0,0,0,0,0,0
4,2020-07-27,0.4600,0.4017,0.0583,14.5133,33.238987,-10.7439,-10.4311,317.413197,-1.3111,-1.8180,38.557586,16.00,1,1,0,0,1,0
5,2020-04-28,0.3500,0.4384,-0.0884,-20.1642,38.142212,-10.3169,-10.8388,279.360093,-4.0066,-1.9659,38.268630,0.33,1,0,0,1,0,0
6,2020-02-19,0.2700,0.4560,-0.186,-40.7895,47.975751,-10.4930,-9.2797,328.777496,-2.6681,-2.7628,49.095456,2.33,0,0,1,0,1,1
7,2019-10-29,0.3500,0.4433,-0.0933,-21.0467,41.555506,-8.2457,-9.6416,293.205112,-3.2326,-3.1847,41.248490,-0.74,0,0,1,1,0,0
8,2019-07-31,0.5000,0.3967,0.1033,26.0398,38.575646,-11.3815,-9.6385,286.287840,-4.8846,-3.4862,43.849096,13.67,1,1,1,0,0,0
9,2019-04-30,0.4829,0.2500,0.2329,93.1600,30.575173,-9.5141,-8.8925,281.634198,-4.0396,-4.0951,33.428615,9.33,1,1,0,0,1,0
10,2019-02-19,0.3345,0.3400,-0.0055,-1.6176,36.435565,-8.9794,-9.7012,264.983835,-4.1580,-4.4216,34.485111,-5.35,0,0,1,1,1,0
11,2018-10-30,0.4340,0.2725,0.1615,59.2661,27.324416,-7.6878,-9.7602,253.856742,-3.7218,-5.4063,31.893535,16.72,0,1,1,1,1,0
12,2018-07-30,0.4500,0.2750,0.175,63.6364,25.030827,-10.8906,-11.5501,264.207117,-6.1465,-5.5768,30.430695,21.57,1,1,0,1,0,0
13,2018-05-01,0.1800,0.1800,0,0.0000,25.229484,-8.9845,-11.5320,248.959964,-5.6505,-6.2006,23.558956,-6.62,1,0,1,1,1,0
14,2018-02-21,0.1671,0.2800,-0.1129,-40.3214,24.362615,-9.5335,-9.7666,252.712612,-7.0568,-5.9170,23.974331,-1.59,0,0,0,1,0,0
15,2017-11-02,0.1696,0.2300,-0.0604,-26.2609,29.031063,-5.6821,-10.0072,239.836467,-6.8271,-6.9030,25.256574,-13.00,0,0,1,1,1,0
16,2017-08-03,0.3200,0.1650,0.155,93.9394,21.509173,-8.6271,-10.3111,228.805522,-7.4823,-7.4036,24.579333,14.27,1,1,1,1,0,0
17,2017-05-08,0.0800,0.1133,-0.0333,-29.3910,19.865735,-10.1098,-9.9831,220.964742,-7.8354,-7.8278,19.053046,-4.09,0,0,1,0,0,0
18,2017-03-01,0.3744,0.3500,0.0244,6.9714,17.942371,-10.1534,-9.7949,220.115980,-7.6656,-8.0997,19.495510,8.66,1,1,1,0,1,0
19,2016-11-01,0.1648,0.3600,-0.1952,-54.2222,15.856469,-10.1107,-9.5966,192.568189,-9.5627,-8.9566,14.754823,-6.95,1,0,0,0,0,0
20,2016-08-09,0.0942,0.2900,-0.1958,-67.5172,16.795576,-11.0875,-9.9434,198.106882,-9.1794,-9.1583,15.657811,-6.77,0,0,1,0,0,0
21,2016-02-16,0.1200,0.2600,-0.14,-53.8462,14.204001,-8.4794,-8.4217,170.548723,-9.6526,-9.8772,14.131762,-0.51,1,0,0,0,1,0
22,2015-10-13,-0.6200,0.1700,-0.79,-464.7059,15.576542,-8.2113,-9.0738,178.874283,-10.8526,-10.6302,14.998630,-3.71,0,0,0,1,0,0
23,2015-07-10,0.2600,0.1300,0.13,100.0000,19.161405,-9.0152,-9.4809,184.357289,-11.0631,-11.4648,20.624245,7.63,1,1,0,1,1,0
24,2015-04-09,-0.0700,0.0200,-0.09,-450.0000,20.552006,-10.3316,-10.1325,184.716466,-11.1000,-11.3934,19.459391,-5.32,0,0,1,0,1,0
25,2015-01-30,0.1500,0.1400,0.01,7.1429,15.170198,-10.6584,-9.5995,175.583709,-12.4576,-12.0658,15.711991,3.57,1,1,1,0,0,1
26,2014-10-10,-0.1700,0.1400,-0.31,-221.4286,13.698328,-10.8762,-9.8666,166.823117,-13.4241,-12.9130,14.104672,2.97,1,0,0,0,0,1
27,2014-07-09,-0.8700,0.0900,-0.96,-1066.6667,16.633038,-9.3567,-10.6413,171.780233,-12.6822,-12.7754,16.235724,-2.39,0,0,1,1,1,0
28,2014-02-07,0.0100,0.0900,-0.08,-88.8889,16.172515,-6.7329,-8.7663,155.150064,-12.9886,-13.4348,16.019007,-0.95,1,0,1,1,1,0
29,2013-10-15,-0.1200,0.1200,-0.24,-200.0000,15.016690,-9.2647,-8.7134,145.745648,-14.5237,-13.4293,13.716387,-8.66,1,0,0,0,0,0
30,2013-07-09,-0.2000,-0.0100,-0.19,-1900.0000,15.161168,-11.0260,-10.0786,141.128033,-14.4575,-14.4822,15.125049,-0.24,0,0,1,0,1,0
31,2012-06-28,0.0300,0.0700,-0.04,-57.1429,5.426958,-10.0007,-9.2474,111.001120,-16.0926,-16.2308,5.878452,8.32,1,0,1,0,1,0
32,2012-02-06,0.0100,0.0400,-0.03,-75.0000,5.417928,-8.9424,-10.3113,111.327905,-16.9071,-17.0849,4.921284,-9.17,0,0,1,1,1,0
33,2011-09-29,0.0200,0.0600,-0.04,-66.6667,3.792549,-8.6133,-8.5254,95.487452,-18.4217,-18.0021,4.054416,6.90,0,0,0,0,0,0
34,2011-04-07,0.0300,-0.0500,0.08,160.0000,5.517256,-9.9958,-9.5539,108.599690,-18.6031,-18.6459,6.221587,12.77,1,1,0,0,1,0
35,2008-09-26,-0.0500,0.1500,-0.2,-133.3333,6.402185,-12.1785,-12.4312,93.183275,-21.5827,-24.3609,5.950691,-7.05,0,0,0,1,1,0
36,2008-06-30,0.1200,-0.1200,0.24,200.0000,6.465394,-10.4516,-10.5647,98.134705,-23.2663,-23.6918,6.519573,0.84,0,1,0,1,1,0
37,2008-01-24,0.2400,0.0700,0.17,242.8571,9.842569,-8.8651,-7.0825,102.488040,-23.7894,-24.2874,9.607792,-2.39,0,1,0,0,1,0
38,2007-09-26,0.2500,0.0600,0.19,316.6667,10.826826,-11.3282,-10.0131,114.945042,-24.5024,-24.8387,10.853915,0.25,1,1,0,0,1,0
39,2007-06-27,0.2100,0.0600,0.15,250.0000,11.558246,-8.9902,-10.2764,113.058403,-23.6762,-25.3094,11.774963,1.87,1,1,0,1,1,1
40,2007-01-22,-0.0400,-0.0500,0.01,20.0000,12.741160,-9.5730,-9.5032,106.150759,-25.8050,-25.3567,13.246834,3.97,1,1,1,0,0,1
41,2006-10-04,-0.2400,-0.1400,-0.1,-71.4286,11.224140,-9.9186,-10.5912,100.031937,-24.9179,-25.8861,11.007423,-1.93,1,0,0,1,1,0
42,2006-04-10,-0.2900,-0.1500,-0.14,-93.3333,17.517967,-11.9700,-10.1047,95.346059,-26.5099,-26.4987,17.247070,-1.55,1,0,0,0,0,0
43,2006-02-09,-3.1800,-3.7200,0.54,14.5161,18.159088,-10.1035,-9.4743,92.530846,-27.0951,-26.9803,17.752744,-2.24,0,1,1,0,0,0
44,2005-10-07,-0.0800,-0.1600,0.08,50.0000,16.326023,-11.7512,-10.2825,87.090382,-27.2428,-27.5406,16.371172,0.28,0,1,0,0,1,0
45,2005-07-07,0.0600,-0.1800,0.24,133.3333,17.156771,-10.6418,-9.4199,86.970557,-26.4768,-27.8196,17.427668,1.58,1,1,1,0,1,1
46,2005-02-09,-0.3000,-0.1700,-0.13,-76.4706,16.696248,-11.1902,-9.6525,85.822163,-28.7310,-28.0440,16.578859,-0.70,0,0,1,0,0,0
47,2004-01-28,0.2800,0.1500,0.13,86.6667,9.880336,-12.7949,-9.5400,80.013571,-30.4109,-29.6310,9.619854,-2.64,1,1,1,0,0,0
48,2003-10-06,-0.0500,-0.0600,0.01,16.6667,8.192552,-9.7737,-9.9720,72.956248,-29.4972,-29.3968,8.103016,-1.09,0,1,1,1,0,0
49,2003-06-26,0.2100,0.1500,0.06,40.0000,7.541602,-5.9651,-11.9331,69.135072,-29.2953,-30.7354,7.586227,0.59,0,1,1,1,1,0
50,2003-01-23,0.2800,0.2200,0.06,27.2727,7.010818,-8.8320,-11.5912,61.607070,-30.5836,-31.0217,6.878038,-1.89,1,1,0,1,1,0
51,2002-10-03,0.0600,0.0500,0.01,20.0000,8.511008,-9.9364,-11.1978,56.886900,-31.5770,-31.0640,8.158220,-4.15,0,1,0,1,0,0
52,2002-06-25,0.0900,0.1100,-0.02,-18.1818,12.314023,-14.1880,-10.7633,67.125739,-33.0750,-32.0104,12.173291,-1.14,0,0,1,0,0,0
53,2002-03-06,0.5100,0.3300,0.18,54.5455,11.938815,9.0303,-12.6118,79.817960,-30.6534,-31.6038,11.798358,-1.18,1,1,1,1,1,0
54,2001-09-24,0.1200,0.3700,-0.25,-67.5676,10.303648,-12.6809,-13.9571,68.610691,-31.1967,-32.3059,10.574337,2.63,0,0,0,1,1,1
55,2001-06-27,0.3500,0.3400,0.01,2.9412,10.795018,-8.6716,-14.1910,82.456119,-32.1907,-31.7588,10.821156,0.24,1,1,1,1,0,0
56,2001-01-16,0.2900,0.3200,-0.03,-9.3750,9.047716,-7.7987,-11.6433,89.667750,-32.0699,-32.3389,8.612663,-4.81,0,0,1,1,1,0
57,2000-09-18,0.3100,0.2800,0.03,10.7143,7.556230,-21.4937,-12.4437,97.335333,-33.5028,-32.9901,7.232392,-4.29,0,1,1,0,0,0
58,2000-06-21,0.3200,0.3400,-0.02,-5.8824,6.828147,-10.4505,-15.2947,99.246046,-32.4570,-33.0302,6.613101,-3.15,1,0,0,1,1,0
59,2000-01-12,0.2600,0.6000,-0.34,-56.6667,7.206965,-15.2122,-14.5892,95.547355,-33.9201,-33.2129,6.779911,-5.93,0,0,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,0,0,0
1,0,0,1,0,1,0
2,1,1,1,1,1,0
3,0,0,0,0,0,0
4,1,1,0,0,1,0
5,1,0,0,1,0,0
6,0,0,1,0,1,1
7,0,0,1,1,0,0
8,1,1,1,0,0,0
9,1,1,0,0,1,0
10,0,0,1,1,1,0
11,0,1,1,1,1,0
12,1,1,0,1,0,0
13,1,0,1,1,1,0
14,0,0,0,1,0,0
15,0,0,1,1,1,0
16,1,1,1,1,0,0
17,0,0,1,0,0,0
18,1,1,1,0,1,0
19,1,0,0,0,0,0
20,0,0,1,0,0,0
21,1,0,0,0,1,0
22,0,0,0,1,0,0
23,1,1,0,1,1,0
24,0,0,1,0,1,0
25,1,1,1,0,0,1
26,1,0,0,0,0,1
27,0,0,1,1,1,0
28,1,0,1,1,1,0
29,1,0,0,0,0,0
30,0,0,1,0,1,0
31,1,0,1,0,1,0
32,0,0,1,1,1,0
33,0,0,0,0,0,0
34,1,1,0,0,1,0
35,0,0,0,1,1,0
36,0,1,0,1,1,0
37,0,1,0,0,1,0
38,1,1,0,0,1,0
39,1,1,0,1,1,1
40,1,1,1,0,0,1
41,1,0,0,1,1,0
42,1,0,0,0,0,0
43,0,1,1,0,0,0
44,0,1,0,0,1,0
45,1,1,1,0,1,1
46,0,0,1,0,0,0
47,1,1,1,0,0,0
48,0,1,1,1,0,0
49,0,1,1,1,1,0
50,1,1,0,1,1,0
51,0,1,0,1,0,0
52,0,0,1,0,0,0
53,1,1,1,1,1,0
54,0,0,0,1,1,1
55,1,1,1,1,0,0
56,0,0,1,1,1,0
57,0,1,1,0,0,0
58,1,0,0,1,1,0
59,0,0,0,0,0,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,AJRD

This is the ticker:

AMG

2021-10-25



AMG has reported earnings 95 times, as of the current date.


model has been put to sleep after the daily adjusted call


1. Retrieve the historical earnings report for the stock:

This dataframe contains AMG's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-28        4.03       3.8522   0.1778             4.6155
1    2021-05-03        4.28       4.2391   0.0409             0.9648
2    2021-02-08        4.22       3.6799   0.5401             14.677
3    2020-10-26        3.27       2.8451   0.4249            14.9344
4    2020-07-27        2.74       2.7101   0.0299             1.1033
5    2020-04-27        3.16       3.0821   0.0779             2.5275
6    2020-02-03        4.52       4.0851   0.4349             10.646
7    2019-10-28        3.16       3.1361   0.0239             0.7621
8    2019-07-29        3.33       3.1845   0.1455              4.569
9    2019-05-06        3.26       3.2613  -0.0013            -0.0399
10   2019-02-04        3.53       3.5129   0.0171             0.4868
11   2018-10-29        3.45       3.4224   0.0276             0.8065
12   2018-07-30        3.61       3.5898   0.0202             0.5627
13   2018-04-30        3.92       3.8881   0.0319             0.8205
14   2018-01-29        4.68       4.5246   0.1554             3.4346

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AMG's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-28,4.03,3.8522,0.1778,4.6155,0,1
1,2021-05-03,4.28,4.2391,0.0409,0.9648,1,1
2,2021-02-08,4.22,3.6799,0.5401,14.6770,1,1
3,2020-10-26,3.27,2.8451,0.4249,14.9344,1,1
4,2020-07-27,2.74,2.7101,0.0299,1.1033,0,1
5,2020-04-27,3.16,3.0821,0.0779,2.5275,0,1
6,2020-02-03,4.52,4.0851,0.4349,10.6460,1,1
7,2019-10-28,3.16,3.1361,0.0239,0.7621,0,1
8,2019-07-29,3.33,3.1845,0.1455,4.5690,1,1
9,2019-05-06,3.26,3.2613,-0.0013,-0.0399,0,0
10,2019-02-04,3.53,3.5129,0.0171,0.4868,1,1
11,2018-10-29,3.45,3.4224,0.0276,0.8065,0,1
12,2018-07-30,3.61,3.5898,0.0202,0.5627,0,1
13,2018-04-30,3.92,3.8881,0.0319,0.8205,0,1
14,2018-01-29,4.68,4.5246,0.1554,3.4346,1,1

3. Retrieve the last 5,000 daily adjusted prices for AMG in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,163.89,164.885,163.250,164.76,164.76,98057,0.0,1.0,0.5308,0.2580,2021-10-21
1,162.02,165.260,161.270,164.17,164.17,103905,0.0,1.0,1.3270,0.2580,2021-10-20
2,160.98,162.080,159.105,161.30,161.30,96361,0.0,1.0,0.1988,0.2580,2021-10-19
3,158.92,160.170,157.340,159.33,159.33,167277,0.0,1.0,0.2580,-0.2307,2021-10-18
4,160.41,162.265,159.640,160.04,160.04,150105,0.0,1.0,-0.2307,-0.3128,2021-10-15
5,154.59,158.970,153.160,158.86,158.86,166248,0.0,1.0,2.7621,-0.5004,2021-10-14
6,149.11,152.700,147.550,151.93,151.93,125747,0.0,1.0,1.8912,-0.5004,2021-10-13
7,149.81,151.380,147.320,147.82,147.82,121658,0.0,1.0,-1.3283,-0.3128,2021-10-12
8,153.23,154.920,149.960,149.99,149.99,100720,0.0,1.0,-2.1145,-0.3128,2021-10-11
9,153.46,154.990,152.310,152.98,152.98,80673,0.0,1.0,-0.3128,0.7186,2021-10-08
10,153.87,155.900,152.840,153.10,153.10,151998,0.0,1.0,-0.5004,0.7186,2021-10-07
11,150.30,152.890,147.120,151.38,151.38,184058,0.0,1.0,0.7186,-0.6542,2021-10-06
12,150.36,154.080,149.900,152.46,152.46,206011,0.0,1.0,1.3966,-1.5598,2021-10-05
13,151.94,154.700,147.825,149.57,149.57,273637,0.0,1.0,-1.5598,-0.6542,2021-10-04
14,151.40,154.820,150.940,153.28,153.28,213619,0.0,1.0,1.2417,-0.6542,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
60,164.14,165.8300,153.49,155.83,155.820561,409647,0.0,1.0,-5.0685,0.0538,2021-07-28,0,0,-0.5152,0.0655,437.414777,0
120,160.19,164.0500,157.20,161.41,161.390065,394405,0.0,1.0,0.7492,-0.7967,2021-05-03,1,1,-0.9433,-0.7304,415.473598,0
178,118.27,132.7799,118.27,132.10,132.074537,1412518,0.0,1.0,11.6721,0.2737,2021-02-08,1,1,-0.6614,-0.4812,386.695467,0
249,79.26,80.2300,76.45,78.77,78.744711,542334,0.0,1.0,-0.6501,-0.6540,2020-10-26,1,1,-2.1885,-1.4416,334.642622,0
313,70.34,73.0100,68.76,71.52,71.486931,687268,0.0,1.0,1.6306,-0.6285,2020-07-27,1,1,-1.3111,-1.8180,317.413197,1
376,62.18,67.6200,60.38,66.72,66.678510,904185,0.0,1.0,7.2347,-1.2254,2020-04-27,1,0,-1.5675,-2.5822,280.650665,1
434,82.47,82.5000,78.71,80.25,79.894681,1461144,0.0,1.0,-3.1227,-0.5929,2020-02-03,0,0,-2.5949,-2.6849,314.959396,1
500,78.10,82.2400,76.80,81.50,80.837549,1020099,0.0,1.0,3.5052,-0.5102,2019-10-28,1,0,-3.1847,-3.1156,293.292142,0
564,91.38,92.7100,86.43,86.65,85.599395,727481,0.0,1.0,-6.3259,-0.1704,2019-07-29,0,0,-3.8801,-3.4598,290.166871,0
622,106.49,106.4900,96.14,97.96,96.433937,2128694,0.0,1.0,-9.4432,-2.8443,2019-05-06,0,0,-3.0303,-4.0951,280.484749,1
685,107.00,109.0500,105.12,107.41,105.419847,862587,0.0,1.0,-1.4768,-1.8061,2019-02-04,1,0,-3.9774,-4.4966,259.366578,1
750,119.96,119.9600,110.27,111.42,109.077431,1342635,0.0,1.0,-9.0718,-3.5386,2018-10-29,0,0,-6.9383,-5.4063,250.149904,0
814,152.39,160.4700,152.39,158.72,155.076307,999404,0.0,1.0,1.7628,-1.9920,2018-07-30,1,0,-6.1465,-5.5768,264.207117,0
877,161.23,170.7300,160.31,164.86,160.780397,993884,0.0,1.0,-0.2789,-2.4746,2018-04-30,1,0,-7.0125,-6.2006,248.518379,0
940,206.15,212.8400,203.56,209.21,203.707628,566061,0.0,1.0,-1.1848,-3.0490,2018-01-29,1,1,-6.8292,-6.2380,266.403357,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-28,4.03,3.8522,0.1778,4.6155,155.820561,-5.0685,0.0538,437.414777,-0.5152,0.0655,158.820380,1.93,0,1,0,0,0,1
1,2021-05-03,4.28,4.2391,0.0409,0.9648,161.390065,0.7492,-0.7967,415.473598,-0.9433,-0.7304,162.979869,0.99,1,1,1,1,0,0
2,2021-02-08,4.22,3.6799,0.5401,14.6770,132.074537,11.6721,0.2737,386.695467,-0.6614,-0.4812,142.092606,7.59,1,1,1,1,0,0
3,2020-10-26,3.27,2.8451,0.4249,14.9344,78.744711,-0.6501,-0.6540,334.642622,-2.1885,-1.4416,76.865314,-2.39,1,1,1,1,0,0
4,2020-07-27,2.74,2.7101,0.0299,1.1033,71.486931,1.6306,-0.6285,317.413197,-1.3111,-1.8180,69.597805,-2.64,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2001-01-25,0.67,0.6500,0.02,3.0769,38.041010,-38.4549,-34.4728,91.819270,-32.6097,-32.1714,37.233414,-2.12,1,1,1,0,0,0
83,2000-10-19,0.66,0.4300,0.23,53.4884,34.326068,-28.3979,-36.2336,93.739696,-31.4987,-32.3300,35.372712,3.05,1,1,1,1,1,1
84,2000-07-20,0.63,0.4000,0.23,57.5000,29.680774,-31.6741,-35.5705,101.091704,-32.1532,-32.9761,29.965048,0.96,1,1,1,1,1,0
85,2000-04-20,0.61,0.3800,0.23,60.5263,25.927067,-33.0914,-34.7971,96.290653,-32.9277,-33.6814,25.927067,0.00,0,1,1,1,1,0
86,2000-01-26,1.28,0.4700,0.81,172.3404,23.459053,-36.3909,-36.2062,94.044644,-33.3017,-33.7006,23.504279,0.19,1,1,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,0,0,0,1
1,1,1,1,1,0,0
2,1,1,1,1,0,0
3,1,1,1,1,0,0
4,0,1,1,1,1,0
...,...,...,...,...,...,...
82,1,1,1,0,0,0
83,1,1,1,1,1,1
84,1,1,1,1,1,0
85,0,1,1,1,1,0
86,1,1,0,0,1,0

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,AMG

This is the ticker:

ARE

2021-10-25



ARE has reported earnings 94 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ARE's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        2.61       0.6265   1.9835           316.6002
1    2021-04-26        0.04       0.5322  -0.4922            -92.484
2    2021-02-01        3.26       0.6577   2.6023           395.6667
3    2020-10-26        0.63        0.885   -0.255           -28.8136
4    2020-07-27        1.82       0.5261   1.2939           245.9418
5    2020-04-27        0.14       0.6694  -0.5294           -79.0857
6    2020-02-03        1.74       0.5891   1.1509           195.3658
7    2019-10-28       -0.44       0.4276  -0.8676          -202.8999
8    2019-07-29        0.68         0.56     0.12            21.4286
9    2019-04-29        1.11       0.5735   0.5365            93.5484
10   2019-02-04        -0.3       0.5344  -0.8344          -156.1377
11   2018-10-29        1.99       0.5371   1.4529           270.5083
12   2018-07-30        0.51       0.5369  -0.0269            -5.0102
13   2018-04-30        1.32       0.5169   0.8031           155.3685
14   2018-01-29        0.38       0.4033  -0.0233            -5.7773

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ARE's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,2.61,0.6265,1.9835,316.6002,1,1
1,2021-04-26,0.04,0.5322,-0.4922,-92.4840,0,0
2,2021-02-01,3.26,0.6577,2.6023,395.6667,1,1
3,2020-10-26,0.63,0.8850,-0.255,-28.8136,0,0
4,2020-07-27,1.82,0.5261,1.2939,245.9418,1,1
5,2020-04-27,0.14,0.6694,-0.5294,-79.0857,0,0
6,2020-02-03,1.74,0.5891,1.1509,195.3658,1,1
7,2019-10-28,-0.44,0.4276,-0.8676,-202.8999,0,0
8,2019-07-29,0.68,0.5600,0.12,21.4286,0,1
9,2019-04-29,1.11,0.5735,0.5365,93.5484,1,1
10,2019-02-04,-0.30,0.5344,-0.8344,-156.1377,0,0
11,2018-10-29,1.99,0.5371,1.4529,270.5083,1,1
12,2018-07-30,0.51,0.5369,-0.0269,-5.0102,0,0
13,2018-04-30,1.32,0.5169,0.8031,155.3685,1,1
14,2018-01-29,0.38,0.4033,-0.0233,-5.7773,0,0

3. Retrieve the last 5,000 daily adjusted prices for ARE in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,206.35,207.075,205.020,206.56,206.56,457900,0.0,1.0,0.1018,0.8637,2021-10-21
1,203.91,206.020,203.910,205.75,205.75,561276,0.0,1.0,0.9024,0.8637,2021-10-20
2,203.65,203.760,201.935,203.16,203.16,324841,0.0,1.0,-0.2406,0.8637,2021-10-19
3,200.13,202.950,199.690,202.79,202.79,554403,0.0,1.0,1.3291,0.6417,2021-10-18
4,201.91,202.860,200.390,201.65,201.65,508736,0.0,1.0,-0.1288,0.6417,2021-10-15
5,199.14,201.090,198.860,200.86,200.86,596646,0.0,1.0,0.8637,0.1932,2021-10-14
6,194.24,197.700,193.445,197.52,197.52,606700,0.0,1.0,1.6886,0.1932,2021-10-13
7,193.24,194.830,191.950,194.48,194.48,448510,0.0,1.0,0.6417,-0.7124,2021-10-12
8,191.49,192.760,189.800,191.86,191.86,589974,0.0,1.0,0.1932,-0.7124,2021-10-11
9,195.33,195.330,192.405,192.44,192.44,299772,0.0,1.0,-1.4795,0.2893,2021-10-08
10,196.53,197.275,194.690,195.13,195.13,489675,0.0,1.0,-0.7124,0.2893,2021-10-07
11,191.34,195.280,189.470,195.18,195.18,590330,0.0,1.0,2.0069,0.2893,2021-10-06
12,194.37,195.150,192.010,192.13,192.13,555235,0.0,1.0,-1.1524,0.2893,2021-10-05
13,193.58,195.380,193.550,194.14,194.14,462929,0.0,1.0,0.2893,-0.2755,2021-10-04
14,192.67,195.030,191.085,194.03,194.03,782833,0.0,1.0,0.7059,-1.0938,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,195.96,197.09,195.14,196.18,195.047181,712908,0.0,1.0,-0.4658,-0.6233,2021-07-26,1,1,0.0655,0.1870,439.597714,0
125,179.70,181.02,178.59,179.57,177.447196,565827,0.0,1.0,-1.2536,-1.0832,2021-04-26,0,1,-0.6115,-0.9025,414.887444,1
183,167.60,169.57,166.67,169.56,166.464257,952395,0.0,1.0,-0.6777,-1.7964,2021-02-01,1,1,-0.3117,-1.3930,372.554955,1
249,159.27,159.85,155.83,156.83,153.014106,823656,0.0,1.0,-3.9279,-2.3844,2020-10-26,0,0,-2.1885,-1.4416,334.642622,0
313,167.80,170.63,165.81,170.36,165.120500,639356,0.0,1.0,-1.5968,-2.8796,2020-07-27,1,1,-1.3111,-1.8180,317.413197,1
376,151.23,151.89,148.80,150.78,145.190505,619170,0.0,1.0,-3.9936,-3.7593,2020-04-27,0,0,-1.5675,-2.5822,280.650665,1
434,163.85,166.00,163.70,164.81,157.578347,1126687,0.0,1.0,-3.8277,-4.2944,2020-02-03,1,1,-2.5949,-2.6849,314.959396,1
500,158.12,158.88,157.47,158.88,150.934897,748732,0.0,1.0,-4.5441,-4.7410,2019-10-28,1,1,-3.1847,-3.1156,293.292142,0
564,143.90,145.48,143.50,144.15,136.052903,535662,0.0,1.0,-5.4532,-5.5181,2019-07-29,1,1,-3.8801,-3.4598,290.166871,0
627,143.15,143.37,140.73,140.89,132.033330,554290,0.0,1.0,-7.7657,-5.8564,2019-04-29,0,1,-4.0951,-3.8482,281.490517,0
685,130.38,130.94,129.36,130.94,121.883377,841312,0.0,1.0,-6.5168,-5.8579,2019-02-04,0,1,-3.9774,-4.4966,259.366578,1
750,122.00,123.43,121.81,123.19,113.701446,443427,0.0,1.0,-6.8021,-6.9778,2018-10-29,1,1,-6.9383,-5.4063,250.149904,0
814,122.50,122.94,121.61,122.82,112.507407,615037,0.0,1.0,-8.1572,-8.9523,2018-07-30,1,0,-6.1465,-5.5768,264.207117,0
877,125.28,125.28,124.08,124.57,113.276629,657254,0.0,1.0,-9.5812,-8.7138,2018-04-30,0,1,-7.0125,-6.2006,248.518379,0
940,126.21,126.21,124.17,124.51,112.403333,560553,0.0,1.0,-10.9394,-9.4611,2018-01-29,0,1,-6.8292,-6.2380,266.403357,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,2.6100,0.6265,1.9835,316.6002,195.047181,-0.4658,-0.6233,439.597714,0.0655,0.1870,199.590792,2.33,1,1,1,1,0,1
1,2021-04-26,0.0400,0.5322,-0.4922,-92.4840,177.447196,-1.2536,-1.0832,414.887444,-0.6115,-0.9025,175.905638,-0.87,0,0,1,0,1,0
2,2021-02-01,3.2600,0.6577,2.6023,395.6667,166.464257,-0.6777,-1.7964,372.554955,-0.3117,-1.3930,163.420855,-1.83,1,1,1,1,1,0
3,2020-10-26,0.6300,0.8850,-0.255,-28.8136,153.014106,-3.9279,-2.3844,334.642622,-2.1885,-1.4416,152.360408,-0.43,0,0,0,0,0,0
4,2020-07-27,1.8200,0.5261,1.2939,245.9418,165.120500,-1.5968,-2.8796,317.413197,-1.3111,-1.8180,168.445009,2.01,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,2003-05-15,0.5200,0.5300,-0.01,-1.8868,23.975380,-45.3864,-44.9600,66.312765,-30.1162,-30.1451,23.893178,-0.34,0,0,1,0,1,0
59,2003-02-21,0.5300,0.7600,-0.23,-30.2632,22.528027,-45.5055,-45.7495,59.155566,-29.8939,-30.3832,22.316979,-0.94,1,0,1,1,1,0
60,2002-02-07,0.4400,0.5200,-0.08,-15.3846,20.601886,-48.8787,-48.4282,73.849557,-32.0736,-31.8994,20.720823,0.58,1,0,1,0,0,0
61,2001-11-08,0.3981,0.4600,-0.0619,-13.4565,20.086336,-49.0195,-49.1213,76.718609,-32.0292,-31.3573,19.994291,-0.46,1,0,0,1,0,0
62,2001-08-09,0.3900,0.4400,-0.05,-11.3636,20.138765,-49.1702,-49.5271,80.691331,-32.0208,-32.4652,20.143819,0.03,0,0,0,1,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,1
1,0,0,1,0,1,0
2,1,1,1,1,1,0
3,0,0,0,0,0,0
4,1,1,1,1,1,1
...,...,...,...,...,...,...
58,0,0,1,0,1,0
59,1,0,1,1,1,0
60,1,0,1,0,0,0
61,1,0,0,1,0,0
62,0,0,0,1,1,0

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,1,0,3,0.5625,0.75,0.642857,75.0,Invalid,ARE

This is the ticker:

ARI

2021-10-25




Model has been put to sleep after historical earnings call
ARI has reported earnings 48 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ARI's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.27        0.365   -0.095           -26.0274
1    2021-04-22        0.39       0.3252   0.0648            19.9262
2    2021-02-10        0.16       0.3183  -0.1583            -49.733
3    2020-10-26        0.36        0.298    0.062            20.8054
4    2020-07-30       -0.07       0.2911  -0.3611          -124.0467
5    2020-05-07         0.4       0.3998   0.0002               0.05
6    2020-02-13        0.46       0.4553   0.0047             1.0323
7    2019-10-23        0.47       0.4668   0.0032             0.6855
8    2019-07-24        0.47       0.4526   0.0174             3.8445
9    2019-04-24         0.5       0.4632   0.0368             7.9447
10   2019-02-13        0.46       0.4617  -0.0017            -0.3682
11   2018-10-24        0.45         0.47    -0.02            -4.2553
12   2018-07-25        0.44        0.442   -0.002            -0.4525
13   2018-05-02        0.43       0.4468  -0.0168            -3.7601
14   2018-02-14        0.49       0.2139   0.2761            129.079

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ARI's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.27,0.3650,-0.095,-26.0274,0,0
1,2021-04-22,0.39,0.3252,0.0648,19.9262,1,1
2,2021-02-10,0.16,0.3183,-0.1583,-49.7330,0,0
3,2020-10-26,0.36,0.2980,0.062,20.8054,1,1
4,2020-07-30,-0.07,0.2911,-0.3611,-124.0467,0,0
5,2020-05-07,0.40,0.3998,0.0002,0.0500,0,1
6,2020-02-13,0.46,0.4553,0.0047,1.0323,0,1
7,2019-10-23,0.47,0.4668,0.0032,0.6855,0,1
8,2019-07-24,0.47,0.4526,0.0174,3.8445,0,1
9,2019-04-24,0.50,0.4632,0.0368,7.9447,1,1
10,2019-02-13,0.46,0.4617,-0.0017,-0.3682,1,0
11,2018-10-24,0.45,0.4700,-0.02,-4.2553,1,0
12,2018-07-25,0.44,0.4420,-0.002,-0.4525,1,0
13,2018-05-02,0.43,0.4468,-0.0168,-3.7601,0,0
14,2018-02-14,0.49,0.2139,0.2761,129.0790,1,1

3. Retrieve the last 5,000 daily adjusted prices for ARI in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,15.55,15.7050,15.415,15.49,15.49,685199,0.0,1.0,-0.3859,0.1948,2021-10-21
1,15.27,15.6150,15.260,15.53,15.53,485333,0.0,1.0,1.7027,0.1948,2021-10-20
2,15.44,15.4400,15.280,15.32,15.32,430601,0.0,1.0,-0.7772,0.5236,2021-10-19
3,15.28,15.4400,15.235,15.38,15.38,468585,0.0,1.0,0.6545,0.1948,2021-10-18
4,15.66,15.9800,15.320,15.32,15.32,682721,0.0,1.0,-2.1711,0.1948,2021-10-15
5,15.40,15.5500,15.380,15.43,15.43,488436,0.0,1.0,0.1948,-0.0661,2021-10-14
6,15.28,15.3800,15.160,15.36,15.36,405556,0.0,1.0,0.5236,-0.0661,2021-10-13
7,15.17,15.5000,15.090,15.28,15.28,653603,0.0,1.0,0.7251,-0.0661,2021-10-12
8,15.15,15.2800,15.030,15.11,15.11,336261,0.0,1.0,-0.2640,-0.0661,2021-10-11
9,15.13,15.2500,15.080,15.12,15.12,269451,0.0,1.0,-0.0661,0.4642,2021-10-08
10,15.21,15.3791,15.090,15.15,15.15,677704,0.0,1.0,-0.3945,0.4642,2021-10-07
11,15.01,15.1700,14.860,15.16,15.16,452041,0.0,1.0,0.9993,0.0000,2021-10-06
12,15.08,15.2200,14.950,15.15,15.15,531700,0.0,1.0,0.4642,-0.6592,2021-10-05
13,15.17,15.3400,15.050,15.07,15.07,596596,0.0,1.0,-0.6592,-1.7230,2021-10-04
14,14.92,15.2400,14.830,15.13,15.13,868787,0.0,1.0,1.4075,-1.8345,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,15.59,15.92,15.59,15.65,15.293160,746270,0.0,1.0,-1.9040,-2.3431,2021-07-26,1,1,0.0655,0.1870,439.597714,0
127,14.97,15.05,14.78,14.81,14.159446,752991,0.0,1.0,-5.4145,-4.4564,2021-04-22,0,1,-1.5167,-0.6496,409.582258,0
176,12.29,12.46,12.21,12.39,11.560995,803098,0.0,1.0,-5.9317,-6.5373,2021-02-10,1,1,-1.4920,-0.8141,386.269667,0
249,9.04,9.04,8.44,8.66,7.836546,1550142,0.0,1.0,-13.3125,-8.8938,2020-10-26,0,0,-2.1885,-1.4416,334.642622,0
310,9.15,9.32,9.09,9.31,8.109037,861286,0.0,1.0,-11.3766,-13.0916,2020-07-30,1,1,-1.1681,-1.8180,318.139902,1
368,7.60,8.10,7.60,7.98,6.712336,1081274,0.0,1.0,-11.6798,-17.3649,2020-05-07,1,0,-2.2531,-2.6416,281.266620,1
426,18.50,18.74,18.46,18.67,14.883041,1425300,0.0,1.0,-19.5511,-20.6698,2020-02-13,1,1,-2.4791,-2.8059,327.533672,1
503,18.96,19.00,18.89,18.96,14.742822,1009102,0.0,1.0,-22.2425,-21.9156,2019-10-23,0,1,-2.9274,-3.4287,289.984990,1
567,18.66,18.68,18.46,18.50,14.047354,1317276,0.0,1.0,-24.7194,-24.1090,2019-07-24,0,1,-3.0223,-3.6524,290.147620,1
630,18.41,18.66,18.41,18.57,13.754389,1289375,0.0,1.0,-25.2885,-25.9724,2019-04-24,1,1,-4.3958,-4.2390,279.919603,0
678,18.44,18.49,18.31,18.40,13.293228,1062064,0.0,1.0,-27.9109,-27.8327,2019-02-13,0,1,-4.6445,-4.6481,262.256271,1
753,18.45,18.63,18.39,18.48,12.995821,1428797,0.0,1.0,-29.5619,-30.0904,2018-10-24,1,0,-7.9742,-5.4970,251.534043,0
817,18.83,19.09,18.82,19.02,13.057103,1443514,0.0,1.0,-30.6580,-31.3871,2018-07-25,1,1,-4.7244,-5.6538,268.038805,1
875,18.04,18.04,17.89,17.91,11.994098,1196034,0.0,1.0,-33.5139,-32.8818,2018-05-02,0,1,-6.5993,-5.7885,247.287578,0
928,17.86,18.05,17.81,18.01,11.757727,1176207,0.0,1.0,-34.1673,-34.8615,2018-02-14,1,1,-4.5507,-6.1689,252.282145,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.27,0.3650,-0.095,-26.0274,15.293160,-1.9040,-2.3431,439.597714,0.0655,0.1870,15.068404,-1.47,0,0,1,1,0,0
1,2021-04-22,0.39,0.3252,0.0648,19.9262,14.159446,-5.4145,-4.4564,409.582258,-1.5167,-0.6496,14.446268,2.03,1,1,1,0,0,1
2,2021-02-10,0.16,0.3183,-0.1583,-49.7330,11.560995,-5.9317,-6.5373,386.269667,-1.4920,-0.8141,11.887577,2.82,0,0,1,1,0,1
3,2020-10-26,0.36,0.2980,0.062,20.8054,7.836546,-13.3125,-8.8938,334.642622,-2.1885,-1.4416,8.162314,4.16,1,1,0,0,0,1
4,2020-07-30,-0.07,0.2911,-0.3611,-124.0467,8.109037,-11.3766,-13.0916,318.139902,-1.1681,-1.8180,8.100327,-0.11,0,0,1,1,1,0
5,2020-05-07,0.40,0.3998,0.0002,0.0500,6.712336,-11.6798,-17.3649,281.266620,-2.2531,-2.6416,6.560930,-2.26,0,1,0,1,1,0
6,2020-02-13,0.46,0.4553,0.0047,1.0323,14.883041,-19.5511,-20.6698,327.533672,-2.4791,-2.8059,14.667806,-1.45,0,1,1,1,1,0
7,2019-10-23,0.47,0.4668,0.0032,0.6855,14.742822,-22.2425,-21.9156,289.984990,-2.9274,-3.4287,14.346258,-2.69,0,1,1,0,1,0
8,2019-07-24,0.47,0.4526,0.0174,3.8445,14.047354,-24.7194,-24.1090,290.147620,-3.0223,-3.6524,14.184031,0.97,0,1,1,0,1,0
9,2019-04-24,0.50,0.4632,0.0368,7.9447,13.754389,-25.2885,-25.9724,279.919603,-4.3958,-4.2390,13.806237,0.38,1,1,1,1,0,0
10,2019-02-13,0.46,0.4617,-0.0017,-0.3682,13.293228,-27.9109,-27.8327,262.256271,-4.6445,-4.6481,12.931999,-2.72,1,0,1,0,1,0
11,2018-10-24,0.45,0.4700,-0.02,-4.2553,12.995821,-29.5619,-30.0904,251.534043,-7.9742,-5.4970,13.122404,0.97,1,0,0,1,0,0
12,2018-07-25,0.44,0.4420,-0.002,-0.4525,13.057103,-30.6580,-31.3871,268.038805,-4.7244,-5.6538,12.933535,-0.95,1,0,1,1,1,0
13,2018-05-02,0.43,0.4468,-0.0168,-3.7601,11.994098,-33.5139,-32.8818,247.287578,-6.5993,-5.7885,12.134733,1.17,0,0,1,0,0,1
14,2018-02-14,0.49,0.2139,0.2761,129.0790,11.757727,-34.1673,-34.8615,252.282145,-4.5507,-6.1689,11.960109,1.72,1,1,1,1,1,1
15,2017-11-01,0.47,0.4577,0.0123,2.6873,11.525228,-36.2543,-36.3599,239.743359,-7.0906,-6.9030,11.627165,0.88,1,1,1,1,0,0
16,2017-08-01,0.46,0.4629,-0.0029,-0.6265,11.128504,-38.3804,-37.9684,229.139058,-7.4036,-7.4708,11.116077,-0.11,1,0,0,0,1,0
17,2017-05-02,0.41,0.4684,-0.0584,-12.4680,11.515689,-40.1782,-39.4219,220.144169,-7.8278,-7.8433,11.157908,-3.11,0,0,1,0,1,0
18,2017-02-27,0.49,0.4437,0.0463,10.4350,10.641585,-40.8472,-40.8143,217.664945,-8.0185,-7.8228,10.884247,2.28,0,1,1,0,0,1
19,2016-10-26,0.52,0.4830,0.037,7.6605,9.500455,-42.3166,-42.2465,195.059603,-8.5129,-8.7355,9.690464,2.00,1,1,1,0,1,1
20,2016-07-26,0.49,0.4806,0.0094,1.9559,9.259277,-43.9511,-43.7477,196.808452,-9.1080,-9.0867,9.091232,-1.81,0,1,1,0,0,0
21,2016-04-26,0.51,0.4927,0.0173,3.5113,8.687233,-45.4662,-45.6034,188.713373,-9.7238,-9.6030,8.681789,-0.06,1,1,1,1,0,0
22,2016-02-09,0.48,0.4660,0.014,3.0043,8.192049,-46.9770,-47.1471,166.639523,-9.1189,-10.3028,8.313766,1.49,0,1,0,1,1,1
23,2015-10-29,0.53,0.4900,0.04,8.1633,8.611069,-48.7741,-48.6494,186.592005,-10.4430,-10.5142,8.564662,-0.54,1,1,1,0,1,0
24,2015-07-28,0.45,0.4500,0,0.0000,8.234872,-49.9400,-50.2945,185.983343,-10.4946,-11.6828,8.345205,1.34,1,0,0,1,1,1
25,2015-04-28,0.44,0.4500,-0.01,-2.2222,8.440109,-50.8439,-51.2425,186.962420,-11.2829,-11.5808,8.357027,-0.98,0,0,1,1,1,0
26,2015-02-25,0.45,0.4400,0.01,2.2727,7.923103,-52.2705,-52.3566,186.306244,-11.9785,-11.7264,8.142263,2.77,1,1,1,1,0,1
27,2014-10-28,0.44,0.4500,-0.01,-2.2222,7.685503,-53.1943,-53.5627,173.713523,-11.7399,-12.2548,7.531979,-2.00,1,0,1,1,1,0
28,2014-07-29,0.42,0.3700,0.05,13.5135,7.426108,-54.6359,-54.5531,171.632087,-13.3915,-12.8374,7.557744,1.77,1,1,0,0,0,1
29,2014-04-29,0.37,0.4100,-0.04,-9.7561,7.492898,-56.0791,-55.7674,162.836308,-13.1447,-13.4405,7.537208,0.59,0,0,1,0,1,0
30,2014-02-26,0.39,0.4000,-0.01,-2.5000,7.167427,-56.7967,-56.8219,159.614255,-13.7733,-13.7547,7.202032,0.48,1,0,1,1,0,0
31,2013-11-04,0.35,0.3400,0.01,2.9412,6.832293,-57.9810,-57.7732,151.869199,-14.0477,-14.0230,6.819625,-0.19,1,1,1,0,0,0
32,2013-07-31,0.31,0.3100,0,0.0000,6.597152,-58.7678,-58.9211,144.187673,-14.6515,-14.5808,6.432531,-2.50,0,0,0,1,0,0
33,2013-05-01,0.39,0.3300,0.06,18.1818,7.033745,-60.3733,-59.6430,134.563848,-15.5439,-14.8870,7.146157,1.60,1,1,1,0,0,1
34,2013-02-27,0.27,0.3000,-0.03,-10.0000,6.901534,-60.3132,-60.9429,128.575917,-14.2198,-15.6632,6.768133,-1.93,0,0,1,1,1,0
35,2012-11-01,0.44,0.4000,0.04,10.0000,6.460593,-61.9069,-61.7953,120.031680,-15.2618,-16.2581,6.276770,-2.85,1,1,1,0,1,0
36,2012-08-06,0.41,0.3900,0.02,5.1282,6.235413,-62.8844,-62.7953,116.710418,-16.4684,-16.3534,6.287812,0.84,0,1,1,0,0,0
37,2012-05-03,0.43,0.4100,0.02,4.8780,5.821131,-63.4581,-63.4351,115.806935,-17.4812,-16.5975,5.751745,-1.19,1,1,1,0,0,0
38,2012-02-28,0.41,0.3900,0.02,5.1282,5.402211,-64.5989,-64.0344,113.903062,-16.9803,-17.1975,5.323867,-1.45,1,1,1,0,1,0
39,2011-11-03,0.28,0.3800,-0.1,-26.3158,4.817325,-65.4672,-65.4424,103.880145,-17.0750,-17.6124,4.730931,-1.79,0,0,0,0,1,0
40,2011-08-04,0.37,0.3600,0.01,2.7778,5.123541,-68.2556,-66.2981,98.445210,-20.8767,-18.3779,5.059790,-1.24,1,1,0,0,0,0
41,2011-05-10,0.29,0.2900,0,0.0000,5.378869,-67.2619,-67.1607,110.676866,-18.1202,-18.8276,5.280655,-1.83,1,0,0,0,1,0
42,2011-03-02,0.22,0.3000,-0.08,-26.6667,5.397339,-68.2509,-67.8933,106.420030,-18.6080,-18.8624,5.358992,-0.71,1,0,1,0,1,0
43,2010-11-10,0.21,0.3200,-0.11,-34.3750,5.261900,-69.1565,-68.7541,98.513870,-18.9720,-19.1350,5.249424,-0.24,0,0,1,0,1,0
44,2010-08-10,0.27,0.3600,-0.09,-25.0000,5.128867,-69.7233,-69.5076,90.188731,-19.4959,-19.4328,5.098429,-0.59,0,0,0,0,0,0
45,2010-05-12,0.28,0.2300,0.05,21.7391,5.278533,-70.0083,-70.4119,93.811500,-19.3297,-19.9483,5.224853,-1.02,1,1,1,1,1,0
46,2010-02-23,-0.15,-0.0300,-0.12,-400.0000,5.238445,-70.8652,-70.7513,87.347342,-21.2093,-20.0820,5.182872,-1.06,0,0,1,0,0,0
47,2009-11-16,-0.01,-0.0800,0.07,87.5000,5.191647,-70.7842,-70.7348,87.989762,-20.2847,-20.6770,5.177022,-0.28,0,1,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,1,1,0,0
1,1,1,1,0,0,1
2,0,0,1,1,0,1
3,1,1,0,0,0,1
4,0,0,1,1,1,0
5,0,1,0,1,1,0
6,0,1,1,1,1,0
7,0,1,1,0,1,0
8,0,1,1,0,1,0
9,1,1,1,1,0,0
10,1,0,1,0,1,0
11,1,0,0,1,0,0
12,1,0,1,1,1,0
13,0,0,1,0,0,1
14,1,1,1,1,1,1
15,1,1,1,1,0,0
16,1,0,0,0,1,0
17,0,0,1,0,1,0
18,0,1,1,0,0,1
19,1,1,1,0,1,1
20,0,1,1,0,0,0
21,1,1,1,1,0,0
22,0,1,0,1,1,1
23,1,1,1,0,1,0
24,1,0,0,1,1,1
25,0,0,1,1,1,0
26,1,1,1,1,0,1
27,1,0,1,1,1,0
28,1,1,0,0,0,1
29,0,0,1,0,1,0
30,1,0,1,1,0,0
31,1,1,1,0,0,0
32,0,0,0,1,0,0
33,1,1,1,0,0,1
34,0,0,1,1,1,0
35,1,1,1,0,1,0
36,0,1,1,0,0,0
37,1,1,1,0,0,0
38,1,1,1,0,1,0
39,0,0,0,0,1,0
40,1,1,0,0,0,0
41,1,0,0,0,1,0
42,1,0,1,0,1,0
43,0,0,1,0,1,0
44,0,0,0,0,0,0
45,1,1,1,1,1,0
46,0,0,1,0,0,0
47,0,1,0,0,1,0

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,3,0,1,0.0625,0.25,0.1,25.0,Invalid,ARI

This is the ticker:

ARLP

2021-10-25



ARLP has reported earnings 88 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains ARLP's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.34         0.21     0.13            61.9048
1    2021-04-26        0.19        0.235   -0.045           -19.1489
2    2021-02-01        0.27         0.26     0.01             3.8462
3    2020-10-26        0.21       -0.055    0.265           481.8182
4    2020-07-27       -0.37       -0.435    0.065            14.9425
5    2020-05-08      0.0962       0.1333  -0.0371            -27.832
6    2020-01-27         0.2         0.22    -0.02            -9.0909
7    2019-10-28      0.4226         0.46  -0.0374            -8.1304
8    2019-07-26        0.44        0.665   -0.225           -33.8346
9    2019-04-29        0.78        0.695    0.085            12.2302
10   2019-01-28      0.7036       0.7633  -0.0597            -7.8213
11   2018-10-29        0.55         0.76    -0.21           -27.6316
12   2018-07-30        0.64       0.6633  -0.0233            -3.5127
13   2018-04-30      0.5683       0.5601   0.0082              1.464
14   2018-01-29        0.55       0.5958  -0.0458            -7.6871

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is ARLP's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.3400,0.2100,0.13,61.9048,1,1
1,2021-04-26,0.1900,0.2350,-0.045,-19.1489,0,0
2,2021-02-01,0.2700,0.2600,0.01,3.8462,1,1
3,2020-10-26,0.2100,-0.0550,0.265,481.8182,1,1
4,2020-07-27,-0.3700,-0.4350,0.065,14.9425,0,1
5,2020-05-08,0.0962,0.1333,-0.0371,-27.8320,0,0
6,2020-01-27,0.2000,0.2200,-0.02,-9.0909,0,0
7,2019-10-28,0.4226,0.4600,-0.0374,-8.1304,0,0
8,2019-07-26,0.4400,0.6650,-0.225,-33.8346,0,0
9,2019-04-29,0.7800,0.6950,0.085,12.2302,1,1
10,2019-01-28,0.7036,0.7633,-0.0597,-7.8213,1,0
11,2018-10-29,0.5500,0.7600,-0.21,-27.6316,0,0
12,2018-07-30,0.6400,0.6633,-0.0233,-3.5127,1,0
13,2018-04-30,0.5683,0.5601,0.0082,1.4640,1,1
14,2018-01-29,0.5500,0.5958,-0.0458,-7.6871,1,0

3. Retrieve the last 5,000 daily adjusted prices for ARLP in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,11.8200,11.8500,11.1600,11.30,11.30,917569,0.0,1.0,-4.3993,-0.2532,2021-10-21
1,11.8500,11.8800,11.6000,11.82,11.82,733615,0.0,1.0,-0.2532,-1.8787,2021-10-20
2,12.8391,12.9000,11.7000,11.93,11.93,1357256,0.0,1.0,-7.0807,0.6791,2021-10-19
3,11.9000,12.8500,11.8400,12.56,12.56,1350861,0.0,1.0,5.5462,-1.0059,2021-10-18
4,11.6500,11.8400,11.4401,11.74,11.74,470789,0.0,1.0,0.7725,-1.6722,2021-10-15
5,11.7100,11.9199,11.3300,11.49,11.49,732493,0.0,1.0,-1.8787,-1.0059,2021-10-14
6,11.9400,11.9500,11.4100,11.59,11.59,353881,0.0,1.0,-2.9313,-1.0059,2021-10-13
7,11.7800,11.9700,11.7220,11.86,11.86,387880,0.0,1.0,0.6791,-1.1453,2021-10-12
8,11.9300,12.2296,11.7900,11.81,11.81,674072,0.0,1.0,-1.0059,-1.1453,2021-10-11
9,11.9600,12.0500,11.6328,11.76,11.76,572895,0.0,1.0,-1.6722,1.4468,2021-10-08
10,11.1000,11.9000,11.0600,11.77,11.77,649379,0.0,1.0,6.0360,1.4468,2021-10-07
11,11.9400,12.0000,11.3800,11.39,11.39,755131,0.0,1.0,-4.6064,1.4468,2021-10-06
12,12.1188,12.2700,11.5200,11.98,11.98,1299573,0.0,1.0,-1.1453,1.4468,2021-10-05
13,11.7500,12.2100,11.6200,11.92,11.92,2096949,0.0,1.0,1.4468,3.4413,2021-10-04
14,11.0000,11.6400,10.7100,11.50,11.50,1360049,0.0,1.0,4.5455,2.7368,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,7.6300,7.9300,7.5100,7.78,7.680639,650022,0.0,1.0,0.6637,-0.1071,2021-07-26,1,1,0.0655,0.1870,439.597714,0
125,6.0800,6.3200,5.8500,6.00,5.823819,2040687,0.0,1.0,-4.2135,-2.4741,2021-04-26,0,1,-0.6115,-0.9025,414.887444,1
183,5.4551,5.7600,5.2804,5.57,5.406445,2235615,0.0,1.0,-0.8919,-4.6163,2021-02-01,1,1,-0.3117,-1.3930,372.554955,1
249,3.2400,3.4901,3.1300,3.36,3.261339,1826788,0.0,1.0,0.6586,-0.7633,2020-10-26,1,0,-2.1885,-1.4416,334.642622,0
313,3.4400,3.4550,3.2500,3.42,3.319577,643974,0.0,1.0,-3.5007,-1.1050,2020-07-27,0,1,-1.3111,-1.8180,317.413197,1
367,3.3300,3.4200,3.2000,3.36,3.261339,989388,0.0,1.0,-2.0619,-5.5456,2020-05-08,1,0,-1.7759,-2.3828,285.920504,1
439,9.6500,9.8000,8.9900,9.22,8.566821,2352646,0.0,1.0,-11.2246,-9.2771,2020-01-27,0,0,-2.6849,-2.7531,314.356919,1
500,13.5500,13.8200,12.3900,12.55,11.165484,1885488,0.0,1.0,-17.5979,-10.6534,2019-10-28,0,0,-3.1847,-3.1156,293.292142,0
565,17.0000,17.4700,16.9600,17.13,14.756117,679807,0.0,1.0,-13.1993,-13.9085,2019-07-26,1,0,-3.3461,-3.6524,290.696267,1
627,19.8700,19.9000,19.2300,19.34,16.195029,851317,0.0,1.0,-18.4951,-15.5648,2019-04-29,0,1,-4.0951,-3.8482,281.490517,0
690,18.6300,19.5000,18.6300,19.41,15.814358,703910,0.0,1.0,-15.1135,-18.4363,2019-01-28,1,1,-4.4966,-4.5696,251.546289,1
750,19.4400,19.8700,19.1000,19.39,15.380756,862726,0.0,1.0,-20.8809,-21.2757,2018-10-29,1,1,-6.9383,-5.4063,250.149904,0
814,19.9500,20.0000,19.2500,19.60,15.146511,504048,0.0,1.0,-24.0776,-22.7219,2018-07-30,0,1,-6.1465,-5.5768,264.207117,0
877,16.8500,17.7300,16.8000,17.65,13.259171,1338208,0.0,1.0,-21.3106,-25.3438,2018-04-30,1,0,-7.0125,-6.2006,248.518379,0
940,21.5500,21.8000,21.0000,21.10,15.438671,394752,0.0,1.0,-28.3588,-26.4758,2018-01-29,0,1,-6.8292,-6.2380,266.403357,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.34,0.210,0.13,61.9048,7.680639,0.6637,-0.1071,439.597714,0.0655,0.1870,7.710255,0.39,1,1,1,1,0,0
1,2021-04-26,0.19,0.235,-0.045,-19.1489,5.823819,-4.2135,-2.4741,414.887444,-0.6115,-0.9025,5.852938,0.50,0,0,1,0,1,0
2,2021-02-01,0.27,0.260,0.01,3.8462,5.406445,-0.8919,-4.6163,372.554955,-0.3117,-1.3930,5.979121,10.59,1,1,1,1,1,0
3,2020-10-26,0.21,-0.055,0.265,481.8182,3.261339,0.6586,-0.7633,334.642622,-2.1885,-1.4416,3.154569,-3.27,1,1,0,1,0,0
4,2020-07-27,-0.37,-0.435,0.065,14.9425,3.319577,-3.5007,-1.1050,317.413197,-1.3111,-1.8180,3.183688,-4.09,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2000-10-26,0.03,0.030,0,0.0000,0.871950,-94.6962,-94.6544,91.973403,-32.9273,-32.4272,0.875133,0.36,0,0,1,0,0,0
84,2000-07-24,0.07,0.040,0.03,75.0000,0.821673,-95.0769,-94.9412,98.553894,-33.4657,-33.2681,0.783157,-4.69,1,1,1,0,0,0
85,2000-04-24,0.04,0.040,0,0.0000,0.668076,-94.8610,-95.0513,95.244471,-32.6894,-32.9277,0.668076,0.00,0,0,1,1,1,0
86,2000-01-26,0.05,0.050,0,0.0000,0.655705,-95.2520,-95.1847,94.044644,-33.3017,-33.7006,0.667627,1.82,0,0,1,0,1,1
87,1999-11-01,0.10,0.090,0.01,11.1111,0.640921,-95.2524,NaN,90.318326,-33.8327,NaN,0.629000,-1.86,0,1,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,0,0
1,0,0,1,0,1,0
2,1,1,1,1,1,0
3,1,1,0,1,0,0
4,0,1,1,0,1,0
...,...,...,...,...,...,...
83,0,0,1,0,0,0
84,1,1,1,0,0,0
85,0,0,1,1,1,0
86,0,0,1,0,1,1
87,0,1,0,0,0,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,ARLP

This is the ticker:

AUB

2021-10-25

Model has been put to sleep after the alpha spy


AUB has reported earnings 101 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains AUB's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-22        1.05       0.7117   0.3383            47.5341
1    2021-04-22        0.82       0.7367   0.0833            11.3072
2    2021-01-26        0.93        0.702    0.228            32.4786
3    2020-10-22        0.74        0.455    0.285            62.6374
4    2020-07-23       0.433       0.3125   0.1205              38.56
5    2020-04-28        0.09         0.48    -0.39             -81.25
6    2020-01-21        0.71        0.706    0.004             0.5666
7    2019-10-17        0.69        0.688    0.002             0.2907
8    2019-07-18         0.7         0.67     0.03             4.4776
9    2019-04-24        0.66         0.68    -0.02            -2.9412
10   2019-01-22         0.7       0.6757   0.0243             3.5963
11   2018-10-17         0.6        0.635   -0.035            -5.5118
12   2018-07-18        0.82         0.62      0.2            32.2581
13   2018-04-24        0.59       0.5275   0.0625            11.8483
14   2018-01-23        0.52       0.5086   0.0114             2.2414

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AUB's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-22,1.050,0.7117,0.3383,47.5341,1,1
1,2021-04-22,0.820,0.7367,0.0833,11.3072,0,1
2,2021-01-26,0.930,0.7020,0.228,32.4786,1,1
3,2020-10-22,0.740,0.4550,0.285,62.6374,1,1
4,2020-07-23,0.433,0.3125,0.1205,38.5600,1,1
5,2020-04-28,0.090,0.4800,-0.39,-81.2500,0,0
6,2020-01-21,0.710,0.7060,0.004,0.5666,1,1
7,2019-10-17,0.690,0.6880,0.002,0.2907,0,1
8,2019-07-18,0.700,0.6700,0.03,4.4776,1,1
9,2019-04-24,0.660,0.6800,-0.02,-2.9412,0,0
10,2019-01-22,0.700,0.6757,0.0243,3.5963,1,1
11,2018-10-17,0.600,0.6350,-0.035,-5.5118,0,0
12,2018-07-18,0.820,0.6200,0.2,32.2581,1,1
13,2018-04-24,0.590,0.5275,0.0625,11.8483,1,1
14,2018-01-23,0.520,0.5086,0.0114,2.2414,1,1

3. Retrieve the last 5,000 daily adjusted prices for AUB in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,37.64,37.9200,36.4101,37.29,37.29,136880,0.0,1.0,-0.9299,-0.3514,2021-10-21
1,36.77,37.6500,36.1000,37.64,37.64,142744,0.0,1.0,2.3661,-0.3514,2021-10-20
2,36.99,37.1000,36.4100,36.86,36.86,179871,0.0,1.0,-0.3514,-0.3728,2021-10-19
3,37.22,37.5500,36.7100,36.75,36.75,156259,0.0,1.0,-1.2628,-0.3728,2021-10-18
4,38.28,38.2800,37.3500,37.38,37.38,256597,0.0,1.0,-2.3511,0.1607,2021-10-15
5,37.34,37.6300,37.1200,37.40,37.40,239814,0.0,1.0,0.1607,-0.1312,2021-10-14
6,37.04,37.4650,36.6000,37.15,37.15,195890,0.0,1.0,0.2970,-0.1312,2021-10-13
7,37.55,37.5500,37.0600,37.41,37.41,160929,0.0,1.0,-0.3728,-0.1312,2021-10-12
8,38.50,38.5000,37.0900,37.54,37.54,169218,0.0,1.0,-2.4935,0.3440,2021-10-11
9,38.08,38.4900,37.8800,38.36,38.36,126382,0.0,1.0,0.7353,0.3440,2021-10-08
10,38.10,38.3500,37.9600,38.05,38.05,354026,0.0,1.0,-0.1312,0.3440,2021-10-07
11,37.54,37.8000,36.9600,37.74,37.74,127451,0.0,1.0,0.5328,0.3440,2021-10-06
12,38.21,38.3200,37.6200,37.93,37.93,122501,0.0,1.0,-0.7328,0.3440,2021-10-05
13,37.79,38.3185,37.4900,37.92,37.92,238854,0.0,1.0,0.3440,1.3301,2021-10-04
14,37.01,38.0500,36.8700,37.79,37.79,166354,0.0,1.0,2.1075,1.3027,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
64,35.59,36.950,34.37,34.46,34.207876,392186,0.0,1.0,-3.8835,-0.5102,2021-07-22,0,0,-0.1574,-0.3363,434.055645,1
127,38.18,38.370,37.28,37.34,36.816171,193323,0.0,1.0,-3.5721,-1.5296,2021-04-22,0,1,-1.5167,-0.6496,409.582258,0
187,38.00,38.000,34.32,34.46,33.740363,222119,0.0,1.0,-11.2096,-2.4597,2021-01-26,0,1,-1.3930,-0.8136,380.041108,0
251,25.60,26.435,25.50,26.33,25.557363,282115,0.0,1.0,-0.1665,-1.9292,2020-10-22,1,1,-0.9244,-1.5711,339.789605,1
315,22.53,24.270,22.53,23.79,22.843277,303955,0.0,1.0,1.3905,-2.8699,2020-07-23,1,0,-2.8524,-1.4895,317.157868,0
375,24.96,25.450,24.18,24.58,23.308576,506908,0.0,1.0,-6.6163,-3.9551,2020-04-28,0,0,-4.0066,-1.9659,279.360093,0
443,36.00,36.220,35.00,35.60,33.521020,610848,0.0,1.0,-6.8861,-5.3780,2020-01-21,0,0,-2.7088,-2.5769,321.936467,0
507,37.99,37.990,36.00,37.31,34.903861,537277,0.0,1.0,-8.1236,-6.5755,2019-10-17,0,1,-3.4287,-3.2899,289.404788,0
571,34.98,35.700,34.24,35.67,33.145005,277424,0.0,1.0,-5.2458,-7.4765,2019-07-18,1,1,-3.2150,-3.8676,287.635394,1
630,34.30,36.010,34.13,35.59,32.857965,326768,0.0,1.0,-4.2042,-6.6766,2019-04-24,1,1,-4.3958,-4.2390,279.919603,0
694,32.13,32.790,31.64,32.51,29.806655,744871,0.0,1.0,-7.2311,-6.9633,2019-01-22,0,0,-5.3365,-4.0979,250.687964,0
758,35.10,36.230,34.60,35.65,32.471981,825161,0.0,1.0,-7.4872,-10.4035,2018-10-17,1,0,-5.1926,-5.5916,265.877892,1
822,40.15,42.740,39.70,41.60,37.682172,1091551,0.0,1.0,-6.1465,-10.2953,2018-07-18,1,1,-5.4553,-5.4815,265.254697,1
881,36.93,37.800,36.66,37.69,33.963909,463153,0.0,1.0,-8.0317,-9.8126,2018-04-24,1,0,-7.7127,-6.2883,247.080879,0
944,38.41,39.100,38.17,39.01,34.949426,219526,0.0,1.0,-9.0096,-10.3858,2018-01-23,1,1,-6.2380,-6.2160,265.102596,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-22,1.050,0.7117,0.3383,47.5341,34.207876,-3.8835,-0.5102,434.055645,-0.1574,-0.3363,34.902754,2.03,1,1,0,0,1,1
1,2021-04-22,0.820,0.7367,0.0833,11.3072,36.816171,-3.5721,-1.5296,409.582258,-1.5167,-0.6496,38.600780,4.85,0,1,1,0,0,1
2,2021-01-26,0.930,0.7020,0.228,32.4786,33.740363,-11.2096,-2.4597,380.041108,-1.3930,-0.8136,32.771037,-2.87,1,1,1,0,0,0
3,2020-10-22,0.740,0.4550,0.285,62.6374,25.557363,-0.1665,-1.9292,339.789605,-0.9244,-1.5711,25.819441,1.03,1,1,1,1,1,1
4,2020-07-23,0.433,0.3125,0.1205,38.5600,22.843277,1.3905,-2.8699,317.157868,-2.8524,-1.4895,22.641634,-0.88,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2001-01-29,0.210,0.1500,0.06,40.0000,4.855469,-62.4771,-60.5443,92.203204,-31.9534,-32.1714,5.049687,4.00,1,1,1,0,1,1
82,2000-10-18,0.170,0.1500,0.02,13.3333,3.617800,-60.8886,-61.9179,90.333274,-31.8882,-33.2474,3.617800,0.00,0,1,0,1,1,0
83,2000-07-24,0.170,0.1400,0.03,21.4286,4.189032,-61.9179,-61.9179,98.553894,-33.4657,-33.2681,4.189032,0.00,1,1,1,0,0,0
84,2000-04-27,0.130,0.1600,-0.03,-18.7500,4.019053,-62.6135,-62.6135,97.755309,-31.6396,-32.9277,4.019053,0.00,0,0,0,0,1,0
85,2000-01-26,0.150,0.1500,0,0.0000,4.789216,-64.2062,-62.6135,94.044644,-33.3017,-33.7006,4.766784,-0.47,1,0,0,0,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,0,1,1
1,0,1,1,0,0,1
2,1,1,1,0,0,0
3,1,1,1,1,1,1
4,1,1,0,1,0,0
...,...,...,...,...,...,...
81,1,1,1,0,1,1
82,0,1,0,1,1,0
83,1,1,1,0,0,0
84,0,0,0,0,1,0
85,1,0,0,0,1,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,Invalid,AUB

This is the ticker:

AXTA

2021-10-25



AXTA has reported earnings 28 times, as of the current date.


model has been put to sleep after the daily adjusted call


1. Retrieve the historical earnings report for the stock:

This dataframe contains AXTA's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.48       0.4571   0.0229             5.0098
1    2021-04-26         0.5       0.4218   0.0782            18.5396
2    2021-02-17        0.58       0.4303   0.1497            34.7897
3    2020-10-21        0.59        0.333    0.257            77.1772
4    2020-07-29       -0.15      -0.1126  -0.0374           -33.2149
5    2020-05-05        0.31       0.2935   0.0165             5.6218
6    2020-01-30        0.42       0.4343  -0.0143            -3.2927
7    2019-10-24        0.52       0.4437   0.0763            17.1963
8    2019-07-25        0.52       0.4309   0.0891            20.6777
9    2019-04-24        0.34       0.2167   0.1233            56.8989
10   2019-01-30        0.34       0.3223   0.0177             5.4918
11   2018-10-25        0.32       0.2948   0.0252             8.5482
12   2018-07-25        0.36       0.3524   0.0076             2.1566
13   2018-04-25        0.27       0.2349   0.0351            14.9425
14   2018-02-06        0.37       0.3049   0.0651            21.3513

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is AXTA's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.48,0.4571,0.0229,5.0098,0,1
1,2021-04-26,0.50,0.4218,0.0782,18.5396,0,1
2,2021-02-17,0.58,0.4303,0.1497,34.7897,0,1
3,2020-10-21,0.59,0.3330,0.257,77.1772,1,1
4,2020-07-29,-0.15,-0.1126,-0.0374,-33.2149,0,0
5,2020-05-05,0.31,0.2935,0.0165,5.6218,0,1
6,2020-01-30,0.42,0.4343,-0.0143,-3.2927,0,0
7,2019-10-24,0.52,0.4437,0.0763,17.1963,0,1
8,2019-07-25,0.52,0.4309,0.0891,20.6777,1,1
9,2019-04-24,0.34,0.2167,0.1233,56.8989,0,1
10,2019-01-30,0.34,0.3223,0.0177,5.4918,1,1
11,2018-10-25,0.32,0.2948,0.0252,8.5482,0,1
12,2018-07-25,0.36,0.3524,0.0076,2.1566,1,1
13,2018-04-25,0.27,0.2349,0.0351,14.9425,0,1
14,2018-02-06,0.37,0.3049,0.0651,21.3513,1,1

3. Retrieve the last 5,000 daily adjusted prices for AXTA in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,31.75,32.8300,31.6050,32.82,32.82,3920398,0.0,1.0,3.3701,0.2577,2021-10-21
1,31.20,31.8900,31.0500,31.83,31.83,2676776,0.0,1.0,2.0192,0.0641,2021-10-20
2,31.19,31.3400,30.8600,31.21,31.21,2570747,0.0,1.0,0.0641,0.2577,2021-10-19
3,31.04,31.2350,30.8000,31.12,31.12,2335282,0.0,1.0,0.2577,-0.0324,2021-10-18
4,31.45,31.6050,31.2050,31.31,31.31,2215075,0.0,1.0,-0.4452,0.3940,2021-10-15
5,31.00,31.2000,30.8600,31.13,31.13,2246941,0.0,1.0,0.4194,0.3940,2021-10-14
6,30.84,30.9700,30.6150,30.83,30.83,2393308,0.0,1.0,-0.0324,0.7251,2021-10-13
7,30.46,30.8000,30.4400,30.58,30.58,2505928,0.0,1.0,0.3940,0.7251,2021-10-12
8,30.75,30.9600,30.5100,30.54,30.54,1327505,0.0,1.0,-0.6829,0.7251,2021-10-11
9,30.16,30.7650,30.0750,30.62,30.62,1763606,0.0,1.0,1.5252,0.6889,2021-10-08
10,29.46,30.3300,29.3500,30.11,30.11,2528127,0.0,1.0,2.2064,-0.3067,2021-10-07
11,28.96,29.2100,28.6450,29.17,29.17,1874701,0.0,1.0,0.7251,-0.3067,2021-10-06
12,29.03,29.3400,28.8175,29.23,29.23,2834562,0.0,1.0,0.6889,-0.5818,2021-10-05
13,29.22,29.7599,29.0300,29.05,29.05,1791380,0.0,1.0,-0.5818,-0.3067,2021-10-04
14,29.34,29.5500,28.6500,29.25,29.25,2249669,0.0,1.0,-0.3067,0.0334,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,29.0600,29.500,28.680,29.38,29.38,4493979,0.0,1.0,1.1012,1.2429,2021-07-26,0,0,0.0655,0.1870,439.597714,0
125,32.8800,32.930,32.460,32.52,32.52,4791236,0.0,1.0,-1.0949,0.3801,2021-04-26,0,1,-0.6115,-0.9025,414.887444,1
172,26.8800,27.090,26.550,27.03,27.03,2597588,0.0,1.0,0.5580,-0.8993,2021-02-17,1,1,-0.4772,-1.1110,388.557103,1
252,25.4600,26.390,25.460,25.69,25.69,3703818,0.0,1.0,0.9034,-0.8891,2020-10-21,1,1,-1.5711,-1.8707,337.935903,1
311,20.5032,23.160,20.250,23.05,23.05,4643755,0.0,1.0,12.4215,0.1311,2020-07-29,1,1,-0.8820,-1.8180,319.279062,1
370,19.3900,19.730,19.210,19.30,19.30,1530337,0.0,1.0,-0.4642,0.2532,2020-05-05,0,0,-2.3828,-2.6416,279.809838,1
436,27.4700,28.655,27.410,28.56,28.56,3451563,0.0,1.0,3.9680,-0.5640,2020-01-30,1,0,-1.8317,-2.6849,318.418779,1
502,29.4000,29.627,28.420,28.81,28.81,2709975,0.0,1.0,-2.0068,-0.0347,2019-10-24,0,0,-3.4732,-3.4287,290.458822,0
566,30.4600,31.200,30.040,30.73,30.73,4665769,0.0,1.0,0.8864,-0.0993,2019-07-25,1,1,-4.0468,-3.4598,288.761564,0
630,27.8000,28.150,26.490,26.50,26.50,4236584,0.0,1.0,-4.6763,-0.2176,2019-04-24,0,1,-4.3958,-4.2390,279.919603,0
688,25.8700,26.450,25.610,25.66,25.66,3963344,0.0,1.0,-0.8118,-0.0782,2019-01-30,0,1,-3.7384,-4.5696,255.189399,1
752,24.3900,25.200,23.645,24.86,24.86,5116523,0.0,1.0,1.9270,-0.5460,2018-10-25,1,0,-4.2386,-5.8771,256.046715,1
817,29.9100,30.125,29.540,29.85,29.85,3366132,0.0,1.0,-0.2006,-0.2636,2018-07-25,1,0,-4.7244,-5.6538,268.038805,1
880,30.7500,31.480,29.990,30.74,30.74,3964160,0.0,1.0,-0.0325,-1.8740,2018-04-25,1,1,-5.7885,-6.3106,247.691582,1
934,29.1100,31.230,28.920,30.27,30.27,3701461,0.0,1.0,3.9849,-0.8571,2018-02-06,1,1,-3.1116,-6.6982,251.851677,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.48,0.4571,0.0229,5.0098,29.38,1.1012,1.2429,439.597714,0.0655,0.1870,30.24,2.93,0,1,0,0,0,1
1,2021-04-26,0.50,0.4218,0.0782,18.5396,32.52,-1.0949,0.3801,414.887444,-0.6115,-0.9025,32.45,-0.22,0,1,1,0,1,0
2,2021-02-17,0.58,0.4303,0.1497,34.7897,27.03,0.5580,-0.8993,388.557103,-0.4772,-1.1110,27.60,2.11,0,1,1,1,1,1
3,2020-10-21,0.59,0.3330,0.257,77.1772,25.69,0.9034,-0.8891,337.935903,-1.5711,-1.8707,26.68,3.85,1,1,1,1,1,1
4,2020-07-29,-0.15,-0.1126,-0.0374,-33.2149,23.05,12.4215,0.1311,319.279062,-0.8820,-1.8180,22.22,-3.60,0,0,1,1,1,0
5,2020-05-05,0.31,0.2935,0.0165,5.6218,19.30,-0.4642,0.2532,279.809838,-2.3828,-2.6416,18.45,-4.40,0,1,0,0,1,0
6,2020-01-30,0.42,0.4343,-0.0143,-3.2927,28.56,3.9680,-0.5640,318.418779,-1.8317,-2.6849,28.81,0.88,0,0,0,1,1,0
7,2019-10-24,0.52,0.4437,0.0763,17.1963,28.81,-2.0068,-0.0347,290.458822,-3.4732,-3.4287,29.39,2.01,0,1,0,0,0,1
8,2019-07-25,0.52,0.4309,0.0891,20.6777,30.73,0.8864,-0.0993,288.761564,-4.0468,-3.4598,30.87,0.46,1,1,1,1,0,0
9,2019-04-24,0.34,0.2167,0.1233,56.8989,26.50,-4.6763,-0.2176,279.919603,-4.3958,-4.2390,26.75,0.94,0,1,1,0,0,0
10,2019-01-30,0.34,0.3223,0.0177,5.4918,25.66,-0.8118,-0.0782,255.189399,-3.7384,-4.5696,25.62,-0.16,1,1,1,0,1,0
11,2018-10-25,0.32,0.2948,0.0252,8.5482,24.86,1.9270,-0.5460,256.046715,-4.2386,-5.8771,24.25,-2.45,0,1,0,1,1,0
12,2018-07-25,0.36,0.3524,0.0076,2.1566,29.85,-0.2006,-0.2636,268.038805,-4.7244,-5.6538,30.36,1.71,1,1,0,1,1,1
13,2018-04-25,0.27,0.2349,0.0351,14.9425,30.74,-0.0325,-1.8740,247.691582,-5.7885,-6.3106,30.75,0.03,0,1,1,1,1,0
14,2018-02-06,0.37,0.3049,0.0651,21.3513,30.27,3.9849,-0.8571,251.851677,-3.1116,-6.6982,30.25,-0.07,1,1,1,1,1,0
15,2017-10-26,0.26,0.2295,0.0305,13.2898,28.34,-3.1111,0.2046,238.002243,-7.0267,-6.9067,33.15,16.97,0,1,0,0,0,0
16,2017-08-03,0.31,0.3887,-0.0787,-20.2470,29.25,-2.5000,0.0945,228.805522,-7.4823,-7.4036,28.24,-3.45,1,0,0,0,0,0
17,2017-04-26,0.26,0.2400,0.02,8.3333,31.83,-2.7795,0.4405,219.803022,-7.8433,-7.8046,31.99,0.50,0,1,1,0,0,0
18,2017-02-08,0.28,0.2897,-0.0097,-3.3483,29.44,-0.5741,0.1350,210.440356,-8.0806,-8.1645,29.43,-0.03,0,0,1,0,1,0
19,2016-10-27,0.32,0.3097,0.0103,3.3258,25.08,1.5385,0.2285,194.539413,-9.3394,-8.7355,25.04,-0.16,0,1,0,1,0,0
20,2016-07-26,0.34,0.3434,-0.0034,-0.9901,28.74,0.4193,0.2122,196.808452,-9.1080,-9.0867,28.97,0.80,1,0,0,1,0,0
21,2016-04-28,0.17,0.1807,-0.0107,-5.9214,28.88,-1.1298,-0.5360,187.385550,-10.1096,-9.5201,28.47,-1.42,0,0,1,0,0,0
22,2016-02-10,0.24,0.2539,-0.0139,-5.4746,23.58,6.1684,-0.1278,166.495746,-10.6830,-10.1851,23.45,-0.55,0,0,0,1,0,0
23,2015-10-28,0.27,0.2600,0.01,3.8462,28.77,0.2788,0.0000,186.636668,-9.8374,-10.5581,28.17,-2.09,0,1,0,1,1,0
24,2015-08-04,0.35,0.3000,0.05,16.6667,31.12,-2.7500,1.1830,185.992229,-11.3056,-10.8655,31.02,-0.32,1,1,0,0,0,0
25,2015-05-06,0.24,0.1400,0.1,71.4286,32.30,0.3417,0.2857,183.956024,-12.2180,-11.9404,32.20,-0.31,0,1,1,1,0,0
26,2015-03-10,0.24,0.2300,0.01,4.3478,27.55,-0.7565,0.3664,180.451987,-12.7028,-12.0372,28.25,2.54,0,1,0,0,0,1

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,1,0,0,0,1
1,0,1,1,0,1,0
2,0,1,1,1,1,1
3,1,1,1,1,1,1
4,0,0,1,1,1,0
5,0,1,0,0,1,0
6,0,0,0,1,1,0
7,0,1,0,0,0,1
8,1,1,1,1,0,0
9,0,1,1,0,0,0
10,1,1,1,0,1,0
11,0,1,0,1,1,0
12,1,1,0,1,1,1
13,0,1,1,1,1,0
14,1,1,1,1,1,0
15,0,1,0,0,0,0
16,1,0,0,0,0,0
17,0,1,1,0,0,0
18,0,0,1,0,1,0
19,0,1,0,1,0,0
20,1,0,0,1,0,0
21,0,0,1,0,0,0
22,0,0,0,1,0,0
23,0,1,0,1,1,0
24,1,1,0,0,0,0
25,0,1,1,1,0,0
26,0,1,0,0,0,1

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,3,0,1,0.0625,0.25,0.1,25.0,Invalid,AXTA

This is the ticker:

BCLI

2021-10-25



BCLI has reported earnings 66 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains BCLI's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-08-05       -0.17         -0.2     0.03                 15
1    2021-04-26       -0.19        -0.26     0.07            26.9231
2    2021-02-04       -0.37       -0.195   -0.175           -89.7436
3    2020-10-15       -0.14       -0.255    0.115             45.098
4    2020-08-05       -0.25       -0.255    0.005             1.9608
5    2020-05-07       -0.32        -0.22     -0.1           -45.4545
6    2020-02-18       -0.34         -0.2    -0.14                -70
7    2019-11-14       -0.25        -0.22    -0.03           -13.6364
8    2019-08-13       -0.23        -0.19    -0.04           -21.0526
9    2019-05-10       -0.24        -0.11    -0.13          -118.1818
10   2019-03-29       -0.27        -0.14    -0.13           -92.8571
11   2018-10-29       -0.15        -0.16     0.01               6.25
12   2018-07-23       -0.16      -0.1267  -0.0333           -26.2826
13   2018-05-14       -0.12        -0.14     0.02            14.2857
14   2018-03-08        0.03        -0.09     0.12           133.3333

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is BCLI's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-08-05,-0.17,-0.2000,0.03,15.0000,1,1
1,2021-04-26,-0.19,-0.2600,0.07,26.9231,1,1
2,2021-02-04,-0.37,-0.1950,-0.175,-89.7436,0,0
3,2020-10-15,-0.14,-0.2550,0.115,45.0980,1,1
4,2020-08-05,-0.25,-0.2550,0.005,1.9608,1,1
5,2020-05-07,-0.32,-0.2200,-0.1,-45.4545,1,0
6,2020-02-18,-0.34,-0.2000,-0.14,-70.0000,0,0
7,2019-11-14,-0.25,-0.2200,-0.03,-13.6364,0,0
8,2019-08-13,-0.23,-0.1900,-0.04,-21.0526,1,0
9,2019-05-10,-0.24,-0.1100,-0.13,-118.1818,1,0
10,2019-03-29,-0.27,-0.1400,-0.13,-92.8571,0,0
11,2018-10-29,-0.15,-0.1600,0.01,6.2500,1,1
12,2018-07-23,-0.16,-0.1267,-0.0333,-26.2826,0,0
13,2018-05-14,-0.12,-0.1400,0.02,14.2857,0,1
14,2018-03-08,0.03,-0.0900,0.12,133.3333,1,1

3. Retrieve the last 5,000 daily adjusted prices for BCLI in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,3.10,3.1500,3.080,3.10,3.10,48030,0.0,1.0,0.0000,0.3205,2021-10-21
1,3.12,3.1799,3.050,3.13,3.13,61947,0.0,1.0,0.3205,0.6494,2021-10-20
2,3.11,3.1700,3.060,3.14,3.14,88912,0.0,1.0,0.9646,0.0000,2021-10-19
3,3.08,3.1360,3.040,3.10,3.10,149549,0.0,1.0,0.6494,0.0000,2021-10-18
4,3.20,3.2200,3.060,3.08,3.08,100627,0.0,1.0,-3.7500,0.0000,2021-10-15
5,3.25,3.2500,3.130,3.14,3.14,75965,0.0,1.0,-3.3846,0.9615,2021-10-14
6,3.12,3.2100,3.060,3.15,3.15,81291,0.0,1.0,0.9615,0.0000,2021-10-13
7,3.14,3.1800,3.100,3.14,3.14,43265,0.0,1.0,0.0000,-0.9375,2021-10-12
8,3.09,3.2000,3.060,3.14,3.14,70031,0.0,1.0,1.6181,-2.2293,2021-10-11
9,3.21,3.2100,3.040,3.12,3.12,128590,0.0,1.0,-2.8037,-0.9375,2021-10-08
10,3.08,3.3000,3.080,3.18,3.18,127694,0.0,1.0,3.2468,-0.9375,2021-10-07
11,3.14,3.1400,3.034,3.07,3.07,131515,0.0,1.0,-2.2293,-0.9375,2021-10-06
12,3.20,3.2400,3.130,3.17,3.17,67015,0.0,1.0,-0.9375,-2.4691,2021-10-05
13,3.24,3.2400,3.160,3.16,3.16,62327,0.0,1.0,-2.4691,-0.3058,2021-10-04
14,3.27,3.2800,3.180,3.26,3.26,95105,0.0,1.0,-0.3058,-0.2959,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
54,3.7000,4.0300,3.6935,3.94,3.94,243390,0.0,1.0,6.4865,0.2660,2021-08-05,1,1,0.0262,-0.1859,440.335328,1
125,3.5300,3.6900,3.3200,3.61,3.61,685428,0.0,1.0,2.2663,1.3029,2021-04-26,1,0,-0.6115,-0.9025,414.887444,1
180,6.2663,8.1400,6.2064,7.88,7.88,4907832,0.0,1.0,25.7520,-0.1214,2021-02-04,1,0,-0.1416,-0.6427,382.417665,1
256,16.8200,17.1515,14.6000,15.29,15.29,1137774,0.0,1.0,-9.0963,-1.0710,2020-10-15,0,1,-0.3115,-1.1313,342.639180,1
306,13.3900,13.6800,12.3000,13.11,13.11,1018031,0.0,1.0,-2.0911,-3.6958,2020-08-05,1,1,-1.6069,-1.1681,326.143483,0
368,6.4900,6.5000,5.4400,5.91,5.91,1301648,0.0,1.0,-8.9368,2.6230,2020-05-07,0,0,-2.2531,-2.6416,281.266620,1
424,5.1900,6.4400,5.0100,6.33,6.33,1266731,0.0,1.0,21.9653,-0.2114,2020-02-18,1,1,-2.7628,-2.6561,327.212999,0
487,3.6100,3.8000,3.6100,3.70,3.70,120314,0.0,1.0,2.4931,0.0000,2019-11-14,1,0,-3.0617,-3.0071,299.335913,0
553,3.5800,3.8200,3.5200,3.77,3.77,201287,0.0,1.0,5.3073,0.0000,2019-08-13,1,0,-2.1371,-3.1099,281.590652,1
618,4.0200,4.0200,3.8500,3.95,3.95,45683,0.0,1.0,-1.7413,0.2571,2019-05-10,0,0,-3.3809,-3.8168,275.963582,1
647,4.2500,4.3500,4.1900,4.34,4.34,96810,0.0,1.0,2.1176,0.4890,2019-03-29,1,1,-4.1820,-4.1683,270.580328,0
750,3.1500,3.4000,3.1500,3.19,3.19,122858,0.0,1.0,1.2698,-0.9174,2018-10-29,1,0,-6.9383,-5.4063,250.149904,0
819,4.2100,4.2400,4.0000,4.09,4.09,44875,0.0,1.0,-2.8504,0.2398,2018-07-23,0,1,-5.3702,-5.6538,264.443059,1
867,3.7200,3.8500,3.7000,3.78,3.78,146427,0.0,1.0,1.6129,-3.2432,2018-05-14,1,1,-6.1695,-5.8076,256.476304,0
913,3.3500,3.5800,3.1800,3.50,3.50,70668,0.0,1.0,4.4776,1.4881,2018-03-08,1,0,-6.2319,-5.6034,256.502600,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-08-05,-0.17,-0.2000,0.03,15.0000,3.940,6.4865,0.2660,440.335328,0.0262,-0.1859,3.960,0.51,1,1,1,1,1,0
1,2021-04-26,-0.19,-0.2600,0.07,26.9231,3.610,2.2663,1.3029,414.887444,-0.6115,-0.9025,3.530,-2.22,1,1,0,1,1,0
2,2021-02-04,-0.37,-0.1950,-0.175,-89.7436,7.880,25.7520,-0.1214,382.417665,-0.1416,-0.6427,7.050,-10.53,0,0,0,1,1,0
3,2020-10-15,-0.14,-0.2550,0.115,45.0980,15.290,-9.0963,-1.0710,342.639180,-0.3115,-1.1313,13.860,-9.35,1,1,1,0,1,0
4,2020-08-05,-0.25,-0.2550,0.005,1.9608,13.110,-2.0911,-3.6958,326.143483,-1.6069,-1.1681,12.150,-7.32,1,1,1,1,0,0
5,2020-05-07,-0.32,-0.2200,-0.1,-45.4545,5.910,-8.9368,2.6230,281.266620,-2.2531,-2.6416,5.870,-0.68,1,0,0,0,1,0
6,2020-02-18,-0.34,-0.2000,-0.14,-70.0000,6.330,21.9653,-0.2114,327.212999,-2.7628,-2.6561,5.960,-5.85,0,0,1,1,0,0
7,2019-11-14,-0.25,-0.2200,-0.03,-13.6364,3.700,2.4931,0.0000,299.335913,-3.0617,-3.0071,3.750,1.35,0,0,0,1,0,1
8,2019-08-13,-0.23,-0.1900,-0.04,-21.0526,3.770,5.3073,0.0000,281.590652,-2.1371,-3.1099,3.590,-4.77,1,0,0,1,1,0
9,2019-05-10,-0.24,-0.1100,-0.13,-118.1818,3.950,-1.7413,0.2571,275.963582,-3.3809,-3.8168,3.870,-2.03,1,0,0,0,1,0
10,2019-03-29,-0.27,-0.1400,-0.13,-92.8571,4.340,2.1176,0.4890,270.580328,-4.1820,-4.1683,4.300,-0.92,0,0,1,1,0,0
11,2018-10-29,-0.15,-0.1600,0.01,6.2500,3.190,1.2698,-0.9174,250.149904,-6.9383,-5.4063,3.120,-2.19,1,1,0,1,0,0
12,2018-07-23,-0.16,-0.1267,-0.0333,-26.2826,4.090,-2.8504,0.2398,264.443059,-5.3702,-5.6538,4.270,4.40,0,0,1,0,1,1
13,2018-05-14,-0.12,-0.1400,0.02,14.2857,3.780,1.6129,-3.2432,256.476304,-6.1695,-5.8076,3.930,3.97,0,1,1,1,0,1
14,2018-03-08,0.03,-0.0900,0.12,133.3333,3.500,4.4776,1.4881,256.502600,-6.2319,-5.6034,3.410,-2.57,1,1,0,1,0,0
15,2017-10-17,-0.13,-0.1600,0.03,18.7500,3.915,-2.1250,0.2532,237.862581,-6.8046,-6.8849,4.110,4.98,0,1,0,0,1,1
16,2017-08-14,-0.06,-0.1250,0.065,52.0000,4.230,0.7143,0.0000,228.416397,-6.9928,-7.3132,4.200,-0.71,1,1,1,1,1,0
17,2017-05-15,-0.10,-0.1700,0.07,41.1765,4.130,1.2255,0.2494,221.554817,-7.4812,-7.8354,4.140,0.24,0,1,1,1,1,0
18,2017-03-29,-0.04,-0.0850,0.045,52.9412,3.990,-1.2376,1.8041,217.166123,-7.5850,-7.5996,3.870,-3.01,1,1,1,0,1,0
19,2016-11-14,-0.09,-0.1050,0.015,14.2857,2.240,-0.4444,0.0000,197.660511,-8.9248,-8.1305,2.165,-3.35,0,1,0,0,0,0
20,2016-08-11,-0.05,-0.1400,0.09,64.2857,2.350,-5.6225,-0.8264,198.533641,-9.0380,-9.1794,2.370,0.85,1,1,1,0,1,0
21,2016-05-10,-0.10,-0.0800,-0.02,-25.0000,2.290,9.0476,-0.0046,188.288831,-8.9160,-9.6631,2.220,-3.06,0,0,0,1,1,0
22,2016-03-09,-0.08,-0.1500,0.07,46.6667,2.430,-0.8163,1.6878,179.175916,-10.1244,-9.6859,2.460,1.23,1,1,0,0,0,1
23,2015-11-16,-0.14,-0.1500,0.01,6.6667,2.760,-4.8276,0.6969,183.671062,-9.2175,-11.1994,2.710,-1.81,0,1,0,0,1,0
24,2015-08-13,-0.12,-0.1400,0.02,14.2857,2.980,-8.0247,-1.0526,185.441325,-11.1573,-11.2470,2.880,-3.36,0,1,0,0,1,0
25,2015-05-14,-0.12,-0.1300,0.01,7.6923,3.700,-3.6458,0.5420,187.643280,-11.1706,-11.4205,3.660,-1.08,1,1,0,0,1,0
26,2015-03-26,-0.18,-0.1500,-0.03,-20.0000,4.270,-1.6129,1.6509,181.506696,-11.4429,-12.0106,4.540,6.32,0,0,1,0,1,0
27,2014-11-13,-0.16,-0.2000,0.04,20.0000,3.580,-4.5333,0.0000,178.774075,-12.4343,-12.1889,3.470,-3.07,0,1,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,1,0
1,1,1,0,1,1,0
2,0,0,0,1,1,0
3,1,1,1,0,1,0
4,1,1,1,1,0,0
5,1,0,0,0,1,0
6,0,0,1,1,0,0
7,0,0,0,1,0,1
8,1,0,0,1,1,0
9,1,0,0,0,1,0
10,0,0,1,1,0,0
11,1,1,0,1,0,0
12,0,0,1,0,1,1
13,0,1,1,1,0,1
14,1,1,0,1,0,0
15,0,1,0,0,1,1
16,1,1,1,1,1,0
17,0,1,1,1,1,0
18,1,1,1,0,1,0
19,0,1,0,0,0,0
20,1,1,1,0,1,0
21,0,0,0,1,1,0
22,1,1,0,0,0,1
23,0,1,0,0,1,0
24,0,1,0,0,1,0
25,1,1,0,0,1,0
26,0,0,1,0,1,0
27,0,1,0,0,0,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,BCLI

This is the ticker:

BDN

2021-10-25




Model has been put to sleep after historical earnings call
BDN has reported earnings 94 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains BDN's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-26        0.32       0.3224  -0.0024            -0.7444
1    2021-04-21        0.35       0.3448   0.0052             1.5081
2    2021-02-02        0.36       0.3637  -0.0037            -1.0173
3    2020-10-21        0.35       0.3515  -0.0015            -0.4267
4    2020-07-22        0.34       0.3346   0.0054             1.6139
5    2020-04-22        0.35       0.3459   0.0041             1.1853
6    2020-01-29        0.38       0.3703   0.0097             2.6195
7    2019-10-17        0.36       0.3639  -0.0039            -1.0717
8    2019-07-22        0.35       0.3543  -0.0043            -1.2137
9    2019-04-24        0.34       0.3321   0.0079             2.3788
10   2019-01-30        0.36        0.355    0.005             1.4085
11   2018-10-17        0.35        0.349    0.001             0.2865
12   2018-07-19        0.35       0.3376   0.0124              3.673
13   2018-04-19        0.32       0.3229  -0.0029            -0.8981
14   2018-01-25        0.33       0.3255   0.0045             1.3825

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is BDN's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-26,0.32,0.3224,-0.0024,-0.7444,0,0
1,2021-04-21,0.35,0.3448,0.0052,1.5081,0,1
2,2021-02-02,0.36,0.3637,-0.0037,-1.0173,1,0
3,2020-10-21,0.35,0.3515,-0.0015,-0.4267,1,0
4,2020-07-22,0.34,0.3346,0.0054,1.6139,0,1
5,2020-04-22,0.35,0.3459,0.0041,1.1853,0,1
6,2020-01-29,0.38,0.3703,0.0097,2.6195,1,1
7,2019-10-17,0.36,0.3639,-0.0039,-1.0717,1,0
8,2019-07-22,0.35,0.3543,-0.0043,-1.2137,1,0
9,2019-04-24,0.34,0.3321,0.0079,2.3788,0,1
10,2019-01-30,0.36,0.3550,0.005,1.4085,1,1
11,2018-10-17,0.35,0.3490,0.001,0.2865,0,1
12,2018-07-19,0.35,0.3376,0.0124,3.6730,1,1
13,2018-04-19,0.32,0.3229,-0.0029,-0.8981,0,0
14,2018-01-25,0.33,0.3255,0.0045,1.3825,0,1

3. Retrieve the last 5,000 daily adjusted prices for BDN in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,14.20,14.230,13.830,13.90,13.900000,842367,0.00,1.0,-2.1127,-0.3574,2021-10-21
1,13.82,14.190,13.780,14.19,14.190000,974062,0.00,1.0,2.6773,-0.4261,2021-10-20
2,14.01,14.010,13.820,13.86,13.860000,979997,0.00,1.0,-1.0707,-0.3574,2021-10-19
3,13.99,14.140,13.910,13.94,13.940000,1169833,0.00,1.0,-0.3574,-0.3539,2021-10-18
4,14.31,14.310,14.060,14.07,14.070000,1105170,0.00,1.0,-1.6771,0.2203,2021-10-15
5,14.13,14.165,14.045,14.08,14.080000,661129,0.00,1.0,-0.3539,0.2203,2021-10-14
6,14.08,14.105,13.860,14.02,14.020000,846825,0.00,1.0,-0.4261,0.8571,2021-10-13
7,14.00,14.225,13.900,14.12,14.120000,1250402,0.00,1.0,0.8571,0.2203,2021-10-12
8,13.70,13.960,13.650,13.95,13.950000,1405163,0.00,1.0,1.8248,0.2203,2021-10-11
9,13.62,13.840,13.600,13.65,13.650000,1116052,0.00,1.0,0.2203,0.2203,2021-10-08
10,13.62,13.850,13.580,13.65,13.650000,1178904,0.00,1.0,0.2203,-0.3838,2021-10-07
11,13.36,13.610,13.200,13.57,13.570000,1638554,0.00,1.0,1.5719,-1.6035,2021-10-06
12,13.74,13.830,13.460,13.50,13.500000,2225627,0.19,1.0,-1.7467,-1.6035,2021-10-05
13,13.75,13.940,13.750,13.89,13.697224,1380556,0.00,1.0,-0.3838,-1.6054,2021-10-04
14,13.50,13.845,13.430,13.77,13.578890,1550182,0.00,1.0,0.5844,-1.6054,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
62,14.02,14.210,13.92,14.08,13.884587,1679506,0.0,1.0,-0.9659,-2.5037,2021-07-26,1,1,0.0655,0.1870,439.597714,0
128,13.22,13.420,13.12,13.25,12.887505,2087776,0.0,1.0,-2.5151,-2.4399,2021-04-21,0,1,0.4490,-0.9025,413.357484,1
182,11.16,11.260,10.97,11.00,10.543408,2783829,0.0,1.0,-5.5250,-4.7343,2021-02-02,0,1,-0.4812,-1.3930,377.822989,1
252,9.99,10.025,9.80,9.82,9.256336,2068292,0.0,1.0,-7.3440,-6.7447,2020-10-21,0,0,-1.5711,-1.8707,337.935903,1
316,10.37,10.860,10.37,10.85,10.048779,2349804,0.0,1.0,-3.0976,-7.9820,2020-07-22,1,1,-1.1189,-1.8454,320.987802,1
379,9.59,9.800,9.36,9.74,8.856419,1403648,0.0,1.0,-7.6494,-12.0415,2020-04-22,1,0,-1.9659,-2.2469,272.877898,1
437,16.17,16.200,15.96,16.08,14.341794,1458427,0.0,1.0,-11.3062,-10.3610,2020-01-29,0,1,-3.3471,-2.6849,317.388738,0
507,14.54,14.700,14.52,14.70,12.951793,955056,0.0,1.0,-10.9230,-11.7707,2019-10-17,1,1,-3.4287,-3.2899,289.404788,0
569,14.37,14.420,14.26,14.32,12.454791,842145,0.0,1.0,-13.3278,-13.1455,2019-07-22,0,0,-3.6524,-4.0247,286.740233,1
630,15.58,15.660,15.45,15.47,13.281565,1145345,0.0,1.0,-14.7525,-14.2027,2019-04-24,0,1,-4.3958,-4.2390,279.919603,0
688,15.20,15.350,15.13,15.21,12.904527,2119161,0.0,1.0,-15.1018,-13.9710,2019-01-30,0,1,-3.7384,-4.5696,255.189399,1
758,14.62,14.690,14.42,14.58,12.195536,1610081,0.0,1.0,-16.5832,-16.9601,2018-10-17,1,0,-5.1926,-5.5916,265.877892,1
821,16.75,16.780,16.41,16.69,13.796647,1336081,0.0,1.0,-17.6320,-17.6764,2018-07-19,1,1,-5.7278,-5.4553,264.254306,0
884,15.44,15.490,15.22,15.41,12.605699,2848419,0.0,1.0,-18.3569,-18.2507,2018-04-19,0,0,-6.3106,-5.9296,252.633575,0
942,17.97,18.050,17.78,17.90,14.474479,1535283,0.0,1.0,-19.4520,-18.5751,2018-01-25,0,1,-6.7033,-6.2380,265.111954,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-26,0.32,0.3224,-0.0024,-0.7444,13.884587,-0.9659,-2.5037,439.597714,0.0655,0.1870,13.766253,-0.85,0,0,1,1,0,0
1,2021-04-21,0.35,0.3448,0.0052,1.5081,12.887505,-2.5151,-2.4399,413.357484,0.4490,-0.9025,12.761062,-0.98,0,1,1,0,1,0
2,2021-02-02,0.36,0.3637,-0.0037,-1.0173,10.543408,-5.5250,-4.7343,377.822989,-0.4812,-1.3930,10.715937,1.64,1,0,1,0,1,1
3,2020-10-21,0.35,0.3515,-0.0015,-0.4267,9.256336,-7.3440,-6.7447,337.935903,-1.5711,-1.8707,9.369448,1.22,1,0,0,0,1,1
4,2020-07-22,0.34,0.3346,0.0054,1.6139,10.048779,-3.0976,-7.9820,320.987802,-1.1189,-1.8454,10.224748,1.75,0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,2005-11-01,0.24,0.1200,0.12,100.0000,10.787869,-60.0449,-60.2032,87.731125,-27.2424,-27.2733,10.771869,-0.15,1,1,0,1,1,0
59,2005-07-21,0.12,0.0800,0.04,50.0000,12.494678,-61.3407,-60.4236,88.978967,-27.9814,-27.4648,12.758761,2.11,0,1,1,0,0,1
60,2004-11-04,0.39,0.3600,0.03,8.3333,11.297077,-61.9627,-62.2292,83.194156,-27.5186,-28.6504,10.886343,-3.64,1,1,1,1,1,0
61,2003-10-23,0.37,0.2900,0.08,27.5862,8.782278,-65.2737,-64.4902,72.597998,-29.4412,-29.7284,8.725596,-0.65,1,1,1,0,1,0
62,2003-02-27,0.27,0.3300,-0.06,-18.1818,6.672308,-66.1304,-66.7291,58.572203,-30.0213,-31.1970,6.896954,3.37,0,0,0,1,1,1

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,0,0,1,1,0,0
1,0,1,1,0,1,0
2,1,0,1,0,1,1
3,1,0,0,0,1,1
4,0,1,1,1,1,1
...,...,...,...,...,...,...
58,1,1,0,1,1,0
59,0,1,1,0,0,1
60,1,1,1,1,1,0
61,1,1,1,0,1,0
62,0,0,0,1,1,1

C:\Users\Papi\Documents\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,2,0,2,0.25,0.5,0.333333,50.0,Invalid,BDN

This is the ticker:

BEN

2021-10-25



BEN has reported earnings 102 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains BEN's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-08-03        0.96       0.7812   0.1788            22.8879
1    2021-05-04        0.79       0.7508   0.0392             5.2211
2    2021-02-02        0.73        0.705    0.025             3.5461
3    2020-10-27        0.56       0.6813  -0.1213           -17.8042
4    2020-07-28         0.7       0.5462   0.1538            28.1582
5    2020-04-30        0.66       0.4557   0.2043            44.8321
6    2020-01-30         0.7       0.6717   0.0283             4.2132
7    2019-10-25        0.61       0.6423  -0.0323            -5.0288
8    2019-07-30        0.65       0.6191   0.0309             4.9911
9    2019-04-26        0.72       0.6278   0.0922            14.6862
10   2019-01-30        0.54       0.6449  -0.1049           -16.2661
11   2018-10-25        0.96       0.7363   0.2237            30.3816
12   2018-07-27        0.75       0.7414   0.0086               1.16
13   2018-04-26        0.78       0.7497   0.0303             4.0416
14   2018-01-30        0.88       0.7604   0.1196            15.7286

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is BEN's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-08-03,0.96,0.7812,0.1788,22.8879,1,1
1,2021-05-04,0.79,0.7508,0.0392,5.2211,1,1
2,2021-02-02,0.73,0.7050,0.025,3.5461,1,1
3,2020-10-27,0.56,0.6813,-0.1213,-17.8042,0,0
4,2020-07-28,0.70,0.5462,0.1538,28.1582,1,1
5,2020-04-30,0.66,0.4557,0.2043,44.8321,0,1
6,2020-01-30,0.70,0.6717,0.0283,4.2132,1,1
7,2019-10-25,0.61,0.6423,-0.0323,-5.0288,0,0
8,2019-07-30,0.65,0.6191,0.0309,4.9911,0,1
9,2019-04-26,0.72,0.6278,0.0922,14.6862,1,1
10,2019-01-30,0.54,0.6449,-0.1049,-16.2661,0,0
11,2018-10-25,0.96,0.7363,0.2237,30.3816,1,1
12,2018-07-27,0.75,0.7414,0.0086,1.1600,0,1
13,2018-04-26,0.78,0.7497,0.0303,4.0416,0,1
14,2018-01-30,0.88,0.7604,0.1196,15.7286,1,1

3. Retrieve the last 5,000 daily adjusted prices for BEN in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,30.43,30.4900,29.9200,30.21,30.21,1838029,0.0,1.0,-0.7230,0.0000,2021-10-21
1,29.96,30.5600,29.8558,30.45,30.45,2689007,0.0,1.0,1.6355,0.0000,2021-10-20
2,29.93,30.0300,29.6300,29.93,29.93,1727891,0.0,1.0,0.0000,-0.4348,2021-10-19
3,29.90,29.9350,29.5850,29.77,29.77,2023616,0.0,1.0,-0.4348,-0.5646,2021-10-18
4,30.56,30.6400,30.0100,30.05,30.05,2347321,0.0,1.0,-1.6688,-0.5646,2021-10-15
5,29.47,30.2700,29.4000,30.14,30.14,2541801,0.0,1.0,2.2735,-0.8905,2021-10-14
6,28.84,29.1554,28.5210,28.93,28.93,2460372,0.0,1.0,0.3121,-0.8905,2021-10-13
7,29.81,29.8900,28.8300,28.89,28.89,5264480,0.0,1.0,-3.0862,-0.5646,2021-10-12
8,30.11,30.9100,29.8900,29.94,29.94,2751269,0.0,1.0,-0.5646,-0.8905,2021-10-11
9,30.32,30.4700,29.9600,30.05,30.05,3098026,0.0,1.0,-0.8905,0.9390,2021-10-08
10,30.87,31.0400,30.4800,30.51,30.51,1828168,0.0,1.0,-1.1662,0.9390,2021-10-07
11,29.76,30.4700,29.5700,30.44,30.44,2376933,0.0,1.0,2.2849,-1.0382,2021-10-06
12,29.82,30.4800,29.5900,30.20,30.20,1774833,0.0,1.0,1.2743,-1.0718,2021-10-05
13,29.86,30.1600,29.4700,29.55,29.55,2427022,0.0,1.0,-1.0382,-1.0718,2021-10-04
14,29.82,30.3700,29.6100,30.10,30.10,2429275,0.0,1.0,0.9390,-1.0718,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
56,30.15,30.90,29.48,30.71,30.430273,3914331,0.0,1.0,0.9296,-1.2797,2021-08-03,1,0,0.2936,-0.5152,439.727295,1
119,30.37,32.45,30.26,32.04,31.472088,6036622,0.0,1.0,3.6289,-1.7725,2021-05-04,1,1,-0.7594,-0.7494,412.910418,0
182,27.01,27.59,25.45,25.62,24.927908,5255353,0.0,1.0,-7.7086,-2.1121,2021-02-02,0,1,-0.4812,-1.3930,377.822989,1
248,22.60,22.60,19.66,19.73,18.982527,11141910,0.0,1.0,-16.0065,-4.0777,2020-10-27,0,0,-1.8457,-1.4416,333.488988,0
312,20.76,20.79,19.78,20.56,19.518114,7233290,0.0,1.0,-5.9821,-4.8388,2020-07-28,0,1,-2.1803,-1.8180,315.400026,0
373,18.49,19.35,17.78,18.84,17.655650,14449769,0.0,1.0,-4.5124,-5.9078,2020-04-30,1,0,-2.6416,-1.6659,284.004199,0
436,25.07,26.24,24.47,26.21,24.194523,8693704,0.0,1.0,-3.4921,-8.5092,2020-01-30,1,0,-1.8317,-2.6849,318.418779,1
501,27.41,28.13,26.81,27.83,25.424089,4208741,0.0,1.0,-7.2452,-8.4498,2019-10-25,1,0,-2.6996,-3.4732,291.648236,1
563,33.99,34.20,33.47,33.83,30.627250,4100167,0.0,1.0,-9.8934,-9.4931,2019-07-30,0,0,-3.4862,-3.4598,289.454592,0
628,35.61,35.61,34.45,35.11,31.549810,3660296,0.0,1.0,-11.4018,-10.3958,2019-04-26,0,1,-3.7830,-4.2355,281.049894,1
688,30.56,30.56,28.77,29.09,25.935285,7381212,0.0,1.0,-15.1332,-10.7882,2019-01-30,0,1,-3.7384,-4.5696,255.189399,1
752,28.66,30.11,28.22,29.34,25.927078,7980042,0.0,1.0,-9.5357,-12.5061,2018-10-25,1,0,-4.2386,-5.8771,256.046715,1
815,32.76,33.01,32.29,32.45,28.464330,3819798,0.0,1.0,-13.1125,-12.3900,2018-07-27,0,0,-6.3852,-5.5768,265.594453,0
879,33.54,33.96,32.86,33.78,29.418200,3789982,0.0,1.0,-12.2892,-13.1929,2018-04-26,1,0,-5.5064,-6.3106,250.209555,1
939,44.64,45.21,42.45,42.72,33.985612,4729838,0.0,1.0,-23.8674,-20.7763,2018-01-30,0,0,-6.6982,-6.6968,263.670823,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-08-03,0.96,0.7812,0.1788,22.8879,30.430273,0.9296,-1.2797,439.727295,0.2936,-0.5152,30.321275,-0.36,1,1,0,1,1,0
1,2021-05-04,0.79,0.7508,0.0392,5.2211,31.472088,3.6289,-1.7725,412.910418,-0.7594,-0.7494,33.073196,5.09,1,1,1,1,0,0
2,2021-02-02,0.73,0.7050,0.025,3.5461,24.927908,-7.7086,-2.1121,377.822989,-0.4812,-1.3930,25.161424,0.94,1,1,1,0,1,0
3,2020-10-27,0.56,0.6813,-0.1213,-17.8042,18.982527,-16.0065,-4.0777,333.488988,-1.8457,-1.4416,17.933822,-5.52,0,0,0,0,0,0
4,2020-07-28,0.70,0.5462,0.1538,28.1582,19.518114,-5.9821,-4.8388,315.400026,-2.1803,-1.8180,20.049735,2.72,1,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2001-01-25,0.20,0.1900,0.01,5.2632,8.565736,-79.5470,-79.6175,91.819270,-32.6097,-32.1714,8.755101,2.21,1,1,1,1,0,1
83,2000-10-25,0.19,0.1900,0,0.0000,7.985985,-80.0350,-79.2194,91.721076,-33.8947,-31.9681,7.821077,-2.06,0,0,1,0,0,0
84,2000-07-27,0.19,0.1900,0,0.0000,6.916807,-79.1976,-79.9933,97.568176,-33.1439,-33.3846,6.954966,0.55,0,0,1,1,1,0
85,2000-04-20,0.19,0.1800,0.01,5.5556,6.676889,-79.2191,-80.0346,96.290653,-32.9277,-33.6814,6.753058,1.14,1,1,0,1,1,1
86,2000-01-27,0.18,0.1700,0.01,5.8824,7.378567,-80.5212,-79.3913,93.668967,-33.9633,-33.7006,7.152488,-3.06,1,1,0,0,0,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,1,1,0
1,1,1,1,1,0,0
2,1,1,1,0,1,0
3,0,0,0,0,0,0
4,1,1,1,0,0,1
...,...,...,...,...,...,...
82,1,1,1,1,0,1
83,0,0,1,0,0,0
84,0,0,1,1,1,0
85,1,1,0,1,1,1
86,1,1,0,0,0,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,BEN

This is the ticker:

BGFV

2021-10-25

Model has been put to sleep after the alpha spy


BGFV has reported earnings 77 times, as of the current date.



1. Retrieve the historical earnings report for the stock:

This dataframe contains BGFV's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-08-03        1.63         1.08     0.55            50.9259
1    2021-05-04         0.9          0.5      0.4                 80
2    2021-03-02        0.95          0.9     0.05             5.5556
3    2020-10-27        1.31          1.1     0.21            19.0909
4    2020-07-29        0.52         None     None               None
5    2020-05-27       -0.22         None     None               None
6    2020-02-25      0.0168         None     None               None
7    2019-10-29      0.3024         None     None               None
8    2019-07-30        0.03         0.03        0                  0
9    2019-04-30         0.1       0.0759   0.0241            31.7523
10   2019-02-26     -0.1567      -0.1584   0.0017             1.0732
11   2018-10-30        0.15       0.1908  -0.0408           -21.3836
12   2018-07-31       -0.01       0.1066  -0.1166          -109.3809
13   2018-05-01       -0.05      -0.1403   0.0903            64.3621
14   2018-02-27        -0.1      -0.0966  -0.0034            -3.5197

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is BGFV's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-08-03,1.6300,1.0800,0.55,50.9259,1,1
1,2021-05-04,0.9000,0.5000,0.4,80.0000,0,1
2,2021-03-02,0.9500,0.9000,0.05,5.5556,0,1
3,2020-10-27,1.3100,1.1000,0.21,19.0909,1,1
8,2019-07-30,0.0300,0.0300,0,0.0000,0,0
9,2019-04-30,0.1000,0.0759,0.0241,31.7523,1,1
10,2019-02-26,-0.1567,-0.1584,0.0017,1.0732,0,1
11,2018-10-30,0.1500,0.1908,-0.0408,-21.3836,1,0
12,2018-07-31,-0.0100,0.1066,-0.1166,-109.3809,1,0
13,2018-05-01,-0.0500,-0.1403,0.0903,64.3621,1,1
14,2018-02-27,-0.1000,-0.0966,-0.0034,-3.5197,0,0
15,2017-10-31,0.2800,0.2840,-0.004,-1.4085,1,0
16,2017-08-01,0.1300,0.1896,-0.0596,-31.4346,0,0
17,2017-05-02,0.2400,0.1450,0.095,65.5172,0,1
18,2017-02-28,0.3700,0.3428,0.0272,7.9347,0,1

3. Retrieve the last 5,000 daily adjusted prices for BGFV in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,23.40,24.6400,23.3000,24.38,24.38,626175,0.0,1.0,4.1880,-1.9665,2021-10-21
1,23.90,24.1650,23.2300,23.43,23.43,705804,0.0,1.0,-1.9665,-1.7558,2021-10-20
2,24.73,24.7400,23.8400,23.90,23.90,563525,0.0,1.0,-3.3562,-0.4239,2021-10-19
3,23.95,24.6992,23.5000,24.50,24.50,640825,0.0,1.0,2.2965,-1.7558,2021-10-18
4,24.49,24.8000,23.8679,23.92,23.92,704268,0.0,1.0,-2.3275,-0.9709,2021-10-15
5,24.49,24.5400,23.8400,24.06,24.06,439747,0.0,1.0,-1.7558,-0.9709,2021-10-14
6,23.52,24.2950,23.4000,24.09,24.09,517080,0.0,1.0,2.4235,-0.9709,2021-10-13
7,23.59,23.8879,23.2600,23.49,23.49,464072,0.0,1.0,-0.4239,-1.0163,2021-10-12
8,24.78,25.0300,23.2500,23.26,23.26,746579,0.0,1.0,-6.1340,-0.9709,2021-10-11
9,24.72,25.1700,24.4253,24.48,24.48,346802,0.0,1.0,-0.9709,2.4728,2021-10-08
10,25.00,25.6000,24.6700,24.72,24.72,602154,0.0,1.0,-1.1200,2.4728,2021-10-07
11,23.86,24.7800,23.6200,24.45,24.45,461586,0.0,1.0,2.4728,-1.0163,2021-10-06
12,24.60,25.3000,24.0900,24.35,24.35,768687,0.0,1.0,-1.0163,-1.5951,2021-10-05
13,23.69,24.5500,23.5300,24.42,24.42,759592,0.0,1.0,3.0815,-1.5951,2021-10-04
14,23.34,24.4700,23.0100,24.11,24.11,1334048,0.0,1.0,3.2991,-1.5951,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
56,23.28,24.16,22.1100,23.90,23.686988,2470134,0.0,1.0,1.7482,-0.0028,2021-08-03,1,1,0.2936,-0.5152,439.727295,1
119,19.00,19.11,17.7600,19.07,18.144561,1207751,0.0,1.0,-4.5023,-4.5965,2021-05-04,1,1,-0.7594,-0.7494,412.910418,0
163,14.95,15.40,14.5200,14.72,13.867990,1022430,0.0,1.0,-7.2375,-7.9088,2021-03-02,1,1,-1.8100,-0.2457,382.764246,0
248,8.06,8.45,7.6352,8.12,7.570566,2619272,0.0,1.0,-6.0724,-8.7088,2020-10-27,1,1,-1.8457,-1.4416,333.488988,0
563,1.66,1.69,1.6000,1.65,1.415031,313313,0.0,1.0,-14.7572,-16.7778,2019-07-30,1,0,-3.4862,-3.4598,289.454592,0
626,2.64,2.70,2.5200,2.63,2.202279,376362,0.0,1.0,-16.5803,-14.9234,2019-04-30,0,0,-4.0396,-4.0951,281.634198,1
670,4.27,4.77,4.2600,4.68,3.867455,1156272,0.0,1.0,-9.4273,-16.9350,2019-02-26,1,1,-4.5657,-4.4246,266.385765,0
749,4.21,4.46,4.2000,4.24,3.455851,1068608,0.0,1.0,-17.9133,-18.3281,2018-10-30,1,0,-3.7218,-5.4063,253.856742,1
813,6.55,6.70,6.3000,6.45,5.122333,517620,0.0,1.0,-21.7964,-20.5840,2018-07-31,0,0,-5.4487,-5.6837,265.509514,1
876,8.40,8.75,8.1000,8.65,6.746081,941944,0.0,1.0,-19.6895,-22.0106,2018-05-01,1,1,-5.6505,-6.2006,248.959964,1
920,6.25,6.50,5.9000,5.95,4.528101,1170577,0.0,1.0,-27.5504,-23.8975,2018-02-27,0,0,-7.6583,-6.6368,256.811413,0
1000,7.10,7.10,6.2500,6.35,4.738371,2509120,0.0,1.0,-33.2624,-25.3800,2017-10-31,0,0,-6.9030,-6.9067,239.426793,1
1064,10.85,11.10,10.7500,10.95,8.012746,870400,0.0,1.0,-26.1498,-27.1539,2017-08-01,1,0,-7.4036,-7.4708,229.139058,1
1127,15.35,16.10,15.1000,15.90,11.510286,1081586,0.0,1.0,-25.0144,-29.3902,2017-05-02,1,1,-7.8278,-7.8433,220.144169,1
1171,13.75,13.78,13.0500,13.45,9.642463,878296,0.0,1.0,-29.8730,-27.5033,2017-02-28,0,0,-8.2784,-8.0185,217.077430,0

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-08-03,1.63,1.08,0.55,50.9259,23.686988,1.7482,-0.0028,439.727295,0.2936,-0.5152,21.457041,-9.41,1,1,1,1,1,0
1,2021-05-04,0.90,0.50,0.4,80.0000,18.144561,-4.5023,-4.5965,412.910418,-0.7594,-0.7494,23.796301,31.15,0,1,1,1,0,0
2,2021-03-02,0.95,0.90,0.05,5.5556,13.867990,-7.2375,-7.9088,382.764246,-1.8100,-0.2457,12.897607,-7.00,0,1,1,1,0,0
3,2020-10-27,1.31,1.10,0.21,19.0909,7.570566,-6.0724,-8.7088,333.488988,-1.8457,-1.4416,7.011164,-7.39,1,1,1,1,0,0
4,2019-07-30,0.03,0.03,0,0.0000,1.415031,-14.7572,-16.7778,289.454592,-3.4862,-3.4598,1.826677,29.09,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2003-10-29,0.30,0.28,0.02,7.1429,9.053557,-48.2654,-47.8300,73.883479,-29.4803,-29.4412,9.463916,4.53,1,1,1,0,0,1
68,2003-07-30,0.28,0.30,-0.02,-6.6667,7.925068,-47.7927,-49.3800,69.386982,-30.3344,-30.3808,7.535740,-4.91,1,0,1,1,1,0
69,2003-05-01,0.19,0.17,0.02,11.7647,6.232335,-49.6987,-48.0270,64.074684,-30.2930,-30.3005,6.924817,11.11,0,1,1,0,1,0
70,2003-02-12,0.39,0.39,0,0.0000,5.309026,-47.8485,-49.9528,57.016575,-31.4375,-31.2812,4.509338,-15.06,1,0,0,1,0,0
71,2002-10-30,0.24,0.21,0.03,14.2857,5.498818,-47.6801,-49.3666,61.807747,-30.3025,-31.2827,6.057932,10.17,0,1,0,1,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,1,1,1,0
1,0,1,1,1,0,0
2,0,1,1,1,0,0
3,1,1,1,1,0,0
4,0,0,0,1,0,0
...,...,...,...,...,...,...
67,1,1,1,0,0,1
68,1,0,1,1,1,0
69,0,1,1,0,1,0
70,1,0,0,1,0,0
71,0,1,0,1,1,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,0,0,0,4,1.0,1.0,1.0,100.0,Valid,BGFV

This is the ticker:

BMRC

2021-10-25



BMRC has reported earnings 88 times, as of the current date.


model has been put to sleep after the daily adjusted call


1. Retrieve the historical earnings report for the stock:

This dataframe contains BMRC's historical earnings report. The first row pertains to either the most recent earnings date (if the date is in the past/the same as today) or the upcoming earnings report date (if the date is in the future)

   reportedDate reportedEPS estimatedEPS surprise surprisePercentage
0    2021-07-19        0.71         0.62     0.09            14.5161
1    2021-04-19        0.66         0.55     0.11                 20
2    2021-01-25         0.6        0.474    0.126            26.5823
3    2020-10-26        0.55        0.516    0.034             6.5891
4    2020-07-20      0.5389        0.344   0.1949             56.657
5    2020-04-20       0.485        0.508   -0.023            -4.5276
6    2020-01-27        0.66        0.615    0.045             7.3171
7    2019-10-21        0.69       0.6033   0.0867             14.371
8    2019-07-22         0.6          0.6        0                  0
9    2019-04-22        0.54       0.6175  -0.0775           -12.5506
10   2019-01-28      0.6864       0.6033   0.0831            13.7742
11   2018-10-22       0.615       0.5825   0.0325             5.5794
12   2018-07-23        0.56        0.515    0.045             8.7379
13   2018-04-23       0.455       0.4525   0.0025             0.5525
14   2018-01-22         0.4         0.43    -0.03            -6.9767

2. Insert the historical earnings report into the historicalEarningsTransformer function:

This is BMRC's most updated earnings table that contains the earnings_event and surprise_event variables that will be used in the analysis:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_event,surprise_event
0,2021-07-19,0.7100,0.6200,0.09,14.5161,1,1
1,2021-04-19,0.6600,0.5500,0.11,20.0000,1,1
2,2021-01-25,0.6000,0.4740,0.126,26.5823,1,1
3,2020-10-26,0.5500,0.5160,0.034,6.5891,1,1
4,2020-07-20,0.5389,0.3440,0.1949,56.6570,1,1
5,2020-04-20,0.4850,0.5080,-0.023,-4.5276,0,0
6,2020-01-27,0.6600,0.6150,0.045,7.3171,0,1
7,2019-10-21,0.6900,0.6033,0.0867,14.3710,1,1
8,2019-07-22,0.6000,0.6000,0,0.0000,1,0
9,2019-04-22,0.5400,0.6175,-0.0775,-12.5506,0,0
10,2019-01-28,0.6864,0.6033,0.0831,13.7742,1,1
11,2018-10-22,0.6150,0.5825,0.0325,5.5794,1,1
12,2018-07-23,0.5600,0.5150,0.045,8.7379,1,1
13,2018-04-23,0.4550,0.4525,0.0025,0.5525,1,1
14,2018-01-22,0.4000,0.4300,-0.03,-6.9767,0,0

3. Retrieve the last 5,000 daily adjusted prices for BMRC in order to create the intraday_event and adjusted_price_event variables:

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient,Intraday_Returns,Weekly_Median_Return,trading_date
0,38.17,38.27,37.930,38.08,38.08,28310,0.0,1.0,-0.2358,-0.2392,2021-10-21
1,37.66,38.11,37.290,38.04,38.04,30505,0.0,1.0,1.0090,-0.2392,2021-10-20
2,37.71,37.82,37.057,37.81,37.81,29326,0.0,1.0,0.2652,-0.2392,2021-10-19
3,37.62,37.91,37.520,37.53,37.53,32216,0.0,1.0,-0.2392,-0.3150,2021-10-18
4,38.32,38.32,37.720,37.77,37.77,57765,0.0,1.0,-1.4353,-0.2103,2021-10-15
5,38.22,38.22,37.270,37.97,37.97,39302,0.0,1.0,-0.6541,-0.2103,2021-10-14
6,37.76,37.90,37.420,37.88,37.88,28850,0.0,1.0,0.3178,-0.2103,2021-10-13
7,37.98,38.20,37.940,38.00,38.00,68615,0.0,1.0,0.0527,-0.3150,2021-10-12
8,38.09,38.20,37.680,37.97,37.97,72657,0.0,1.0,-0.3150,-0.2103,2021-10-11
9,38.04,38.28,37.960,37.96,37.96,23208,0.0,1.0,-0.2103,-0.0785,2021-10-08
10,38.44,38.46,37.960,38.15,38.15,39092,0.0,1.0,-0.7544,-0.0785,2021-10-07
11,37.97,38.16,37.580,38.16,38.16,30775,0.0,1.0,0.5004,-0.0785,2021-10-06
12,38.46,38.46,38.100,38.10,38.10,24216,0.0,1.0,-0.9360,-0.0785,2021-10-05
13,38.21,38.47,38.008,38.18,38.18,39395,0.0,1.0,-0.0785,0.8177,2021-10-04
14,37.79,38.48,37.790,38.35,38.35,52683,0.0,1.0,1.4819,0.8177,2021-10-01

4. Retrieve the last 5,000 daily adjusted prices for SPY in order to create the spy_event variable:

,1. open,2. high,3. low,4. close,spy_adjusted_close,6. volume,7. dividend amount,8. split coefficient,spy_intraday_returns,spy_weekly_median_return,column_of_interest,spy_event
0,451.77,453.8290,451.31,453.59,453.59,41305438,0.0,1.0,0.4029,0.3831,2021-10-21,1
1,451.13,452.7320,451.01,452.41,452.41,49571569,0.0,1.0,0.2837,0.3831,2021-10-20,0
2,448.92,450.7100,448.27,450.64,450.64,46996827,0.0,1.0,0.3831,0.2518,2021-10-19,1
3,443.97,447.5500,443.27,447.19,447.19,62213228,0.0,1.0,0.7253,0.1081,2021-10-18,1
4,444.75,446.2600,444.09,445.87,445.87,66260210,0.0,1.0,0.2518,-0.3686,2021-10-15,1
5,439.08,442.6600,438.58,442.50,442.50,70236825,0.0,1.0,0.7789,-0.3686,2021-10-14,1
6,434.71,436.0500,431.54,435.18,435.18,72973979,0.0,1.0,0.1081,-0.3686,2021-10-13,1
7,435.67,436.1000,432.78,433.62,433.62,71181163,0.0,1.0,-0.4705,0.0616,2021-10-12,0
8,437.16,440.2600,434.62,434.69,434.69,65233285,0.0,1.0,-0.5650,0.0616,2021-10-11,0
9,439.48,439.8900,437.19,437.86,437.86,74557404,0.0,1.0,-0.3686,0.6647,2021-10-08,0
10,438.39,441.6800,438.20,438.66,438.66,72437499,0.0,1.0,0.0616,0.6647,2021-10-07,0
11,429.27,435.1199,427.54,434.90,434.90,113032245,0.0,1.0,1.3115,-0.1700,2021-10-06,1
12,430.24,435.4900,429.39,433.10,433.10,90682520,0.0,1.0,0.6647,-1.0069,2021-10-05,1
13,433.00,433.9600,426.36,428.64,428.64,128569957,0.0,1.0,-1.0069,-0.1700,2021-10-04,0
14,430.98,436.0329,427.23,434.24,434.24,129240106,0.0,1.0,0.7564,-0.1700,2021-10-01,1

5. Connect both daily adjusted price dataframes (Stock Prices and SPY Prices) with the historical earnings report in order to calculate the x variables intraday_event, adjusted_price_event, spy_event:

,1. open,2. high,3. low,4. close,stock_adjusted_close,6. volume,7. dividend amount,8. split coefficient,stock_intraday_returns,stock_weekly_median_return,column_of_interest,intraday_event,adjusted_price_event,spy_intraday_returns,spy_weekly_median_return,spy_adjusted_close,spy_event
67,31.75,32.535,31.4800,31.75,31.528166,54549,0.0,1.0,-0.6987,-0.5425,2021-07-19,0,0,-0.6078,-0.4710,423.599475,0
130,38.81,38.810,35.9300,36.15,35.670661,166523,0.0,1.0,-8.0890,-2.3262,2021-04-19,0,0,-0.9025,-0.4609,412.503091,0
188,39.42,40.390,38.9600,39.94,39.166084,58062,0.0,1.0,-0.6441,-1.4722,2021-01-25,1,1,-0.7910,-0.8957,380.635247,1
249,31.77,32.510,30.9828,31.59,30.747078,22842,0.0,1.0,-3.2198,-2.0706,2020-10-26,0,1,-2.1885,-1.4416,334.642622,0
318,31.92,31.960,31.2400,31.46,30.400324,24610,0.0,1.0,-4.7609,-3.7872,2020-07-20,0,1,-0.9136,-1.8454,318.493435,1
381,30.40,30.750,29.3400,30.65,29.412363,45196,0.0,1.0,-3.2488,-5.8804,2020-04-20,1,0,-2.5822,-2.1624,275.312387,0
439,44.18,45.760,44.1000,45.46,43.398765,37927,0.0,1.0,-1.7683,-4.5342,2020-01-27,1,1,-2.6849,-2.7531,314.356919,1
505,42.07,43.940,42.0700,42.63,40.503198,45870,0.0,1.0,-3.7243,-4.0859,2019-10-21,1,1,-3.1156,-3.2931,290.091360,1
569,42.28,43.000,41.7700,42.70,40.369150,35204,0.0,1.0,-4.5195,-5.0549,2019-07-22,1,1,-3.6524,-4.0247,286.740233,1
632,41.54,42.500,41.5400,42.30,39.809207,71784,0.0,1.0,-4.1666,-6.0422,2019-04-22,1,1,-3.8482,-4.3017,278.042169,1
690,42.89,44.080,41.6200,41.62,38.992685,43956,0.0,1.0,-9.0868,-6.3343,2019-01-28,0,1,-4.4966,-4.5696,251.546289,1
755,79.47,80.030,78.5100,78.51,36.626147,14050,0.0,1.0,-53.9120,-53.1529,2018-10-22,0,0,-5.8771,-5.4970,260.720553,0
819,87.00,87.000,83.1000,86.55,40.232842,15260,0.0,1.0,-53.7554,-53.3167,2018-07-23,0,1,-5.3702,-5.6538,264.443059,1
882,70.90,74.000,70.6500,73.30,33.935239,24774,0.0,1.0,-52.1365,-53.7368,2018-04-23,1,1,-6.2883,-6.1499,250.453837,0
945,71.45,71.450,67.1400,69.85,32.202180,41332,0.0,1.0,-54.9305,-53.9943,2018-01-22,0,0,-5.5784,-6.2160,264.541116,1

6. Run the final tranformer function to generate the class variable:


Run the analysis with just clean variables


This is the dataframe with the columns that were used to construct the variables of the model:

,column_of_interest,reportedEPS,estimatedEPS,surprise,surprisePercentage,stock_adjusted_close,stock_intraday_returns,stock_weekly_median_return,spy_adjusted_close,spy_intraday_returns,spy_weekly_median_return,after_report_adjusted_price,return_pct_difference,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,2021-07-19,0.7100,0.6200,0.09,14.5161,31.528166,-0.6987,-0.5425,423.599475,-0.6078,-0.4710,32.819083,4.09,1,1,0,0,0,1
1,2021-04-19,0.6600,0.5500,0.11,20.0000,35.670661,-8.0890,-2.3262,412.503091,-0.9025,-0.4609,34.693789,-2.74,1,1,0,0,0,0
2,2021-01-25,0.6000,0.4740,0.126,26.5823,39.166084,-0.6441,-1.4722,380.635247,-0.7910,-0.8957,38.960153,-0.53,1,1,1,1,1,0
3,2020-10-26,0.5500,0.5160,0.034,6.5891,30.747078,-3.2198,-2.0706,334.642622,-2.1885,-1.4416,29.510965,-4.02,1,1,1,0,0,0
4,2020-07-20,0.5389,0.3440,0.1949,56.6570,30.400324,-4.7609,-3.7872,318.493435,-0.9136,-1.8454,31.724178,4.35,1,1,1,0,1,1
5,2020-04-20,0.4850,0.5080,-0.023,-4.5276,29.412363,-3.2488,-5.8804,275.312387,-2.5822,-2.1624,29.700249,0.98,0,0,0,1,0,0
6,2020-01-27,0.6600,0.6150,0.045,7.3171,43.398765,-1.7683,-4.5342,314.356919,-2.6849,-2.7531,43.436951,0.09,0,1,1,1,1,0
7,2019-10-21,0.6900,0.6033,0.0867,14.3710,40.503198,-3.7243,-4.0859,290.091360,-3.1156,-3.2931,41.728841,3.03,1,1,1,1,1,1
8,2019-07-22,0.6000,0.6000,0,0.0000,40.369150,-4.5195,-5.0549,286.740233,-3.6524,-4.0247,40.822948,1.12,1,0,1,1,1,1
9,2019-04-22,0.5400,0.6175,-0.0775,-12.5506,39.809207,-4.1666,-6.0422,278.042169,-3.8482,-4.3017,40.091542,0.71,0,0,1,1,1,0
10,2019-01-28,0.6864,0.6033,0.0831,13.7742,38.992685,-9.0868,-6.3343,251.546289,-4.4966,-4.5696,39.929558,2.40,1,1,1,0,1,1
11,2018-10-22,0.6150,0.5825,0.0325,5.5794,36.626147,-53.9120,-53.1529,260.720553,-5.8771,-5.4970,37.741119,3.04,1,1,0,0,0,1
12,2018-07-23,0.5600,0.5150,0.045,8.7379,40.232842,-53.7554,-53.3167,264.443059,-5.3702,-5.6538,40.465268,0.58,1,1,1,0,1,0
13,2018-04-23,0.4550,0.4525,0.0025,0.5525,33.935239,-52.1365,-53.7368,250.453837,-6.2883,-6.1499,34.953759,3.00,1,1,1,1,0,1
14,2018-01-22,0.4000,0.4300,-0.03,-6.9767,32.202180,-54.9305,-53.9943,264.541116,-5.5784,-6.2160,32.202180,0.00,0,0,0,0,1,0
15,2017-10-23,0.4150,0.4130,0.002,0.4843,32.527083,-51.6326,-54.3927,238.458471,-7.3876,-6.8046,32.274579,-0.78,0,1,1,1,0,0
16,2017-07-24,0.4200,0.3990,0.021,5.2632,29.206645,-53.1194,-53.7250,228.675814,-7.3399,-7.1858,28.978111,-0.78,1,1,0,1,0,0
17,2017-04-24,0.3700,0.4000,-0.03,-7.5000,30.628467,-53.0958,-53.1396,218.668975,-7.8046,-7.7416,30.878774,0.82,0,0,0,1,0,0
18,2017-01-23,0.4650,0.4100,0.055,13.4146,31.527542,-53.0141,-54.6692,207.603753,-8.4397,-8.1847,31.867523,1.08,0,1,1,1,0,1
19,2016-10-24,0.5700,0.3938,0.1762,44.7435,22.904832,-54.5088,-54.8674,196.109090,-8.7865,-8.7355,22.747023,-0.69,1,1,1,1,0,0
20,2016-07-25,0.3950,0.3933,0.0017,0.4322,22.366139,-56.6716,-55.4257,196.717646,-9.3467,-9.0153,22.603886,1.06,0,1,1,0,0,1
21,2016-04-25,0.4650,0.3863,0.0787,20.3728,21.832787,-55.4251,-55.4070,188.433359,-9.5201,-9.6030,21.980065,0.67,1,1,0,0,1,0
22,2016-01-25,0.4050,0.3888,0.0162,4.1667,23.295171,-54.9678,-55.4127,168.625579,-11.2123,-9.8323,23.748195,1.94,0,1,1,1,0,1
23,2015-10-16,0.7900,0.7300,0.06,8.2192,22.493458,-55.0311,-55.8543,181.571913,-10.4807,-10.6967,23.992433,6.66,1,1,1,1,1,0
24,2015-07-20,0.7100,0.7600,-0.05,-6.5789,20.826540,-57.8666,-56.0320,188.924459,-11.1988,-10.9768,20.883755,0.27,0,0,0,0,0,0
25,2015-04-20,0.7400,0.7800,-0.04,-5.1282,22.479959,-55.5556,-56.2049,185.556488,-11.2425,-11.4335,22.436139,-0.19,0,0,1,1,1,0
26,2015-01-26,0.7800,0.8400,-0.06,-7.1429,22.263233,-56.4150,-56.2857,180.865746,-11.6478,-11.2758,21.792053,-2.12,0,0,1,0,0,0
27,2014-10-20,0.8900,0.8500,0.04,4.7059,20.273426,-56.1656,-56.4383,166.612990,-11.4373,-12.4240,20.195251,-0.39,1,1,1,1,1,0
28,2014-07-21,0.4300,0.4000,0.03,7.5000,19.073014,-56.7799,-56.9728,171.971952,-12.7445,-12.9210,19.734581,3.47,1,1,0,1,1,1
29,2014-04-23,0.4100,0.3500,0.06,17.1429,19.695413,-56.9405,-56.9978,162.576117,-13.4405,-12.9639,19.596376,-0.50,1,1,1,1,0,0
30,2014-01-27,0.4000,0.3400,0.06,17.6471,18.618963,-57.5878,-57.1288,153.708053,-14.1584,-13.8951,18.751864,0.71,1,1,1,0,0,0
31,2013-10-21,0.3600,0.3600,0,0.0000,18.277652,-57.8565,-56.7967,149.782210,-14.1403,-13.4366,18.597788,1.75,1,0,0,0,0,1
32,2013-07-22,0.2800,0.3900,-0.11,-28.2051,18.977240,-57.9312,-57.0847,144.862845,-14.4898,-14.4436,18.042191,-4.93,0,0,1,0,0,0
33,2013-04-22,0.4500,0.3800,0.07,18.4211,16.851235,-56.8691,-57.8242,132.770003,-14.7708,-15.6255,16.834312,-0.10,1,1,1,1,1,0
34,2013-01-22,0.4300,0.3800,0.05,13.1579,16.632130,-57.2878,-57.6928,126.222938,-14.9040,-15.1886,16.779541,0.89,1,1,1,1,1,0
35,2012-10-22,0.3000,0.4300,-0.13,-30.2326,16.514593,-59.0209,-58.6434,120.519101,-15.8092,-15.6387,16.175080,-2.06,0,0,1,0,0,0
36,2012-07-23,0.4600,0.4000,0.06,15.0000,15.538671,-57.1347,-58.4647,112.923724,-16.0231,-16.3599,15.471928,-0.43,0,1,1,1,1,0
37,2012-04-23,0.4600,0.3900,0.07,17.9487,15.077448,-58.7484,-58.5868,113.761082,-16.6830,-17.0637,15.330746,1.68,1,1,0,0,1,1
38,2012-01-20,0.3200,0.3900,-0.07,-17.9487,15.933876,-57.5097,-58.5185,109.257844,-16.7496,-17.0688,15.913204,-0.13,0,0,1,1,1,0
39,2011-10-24,0.4000,0.3900,0.01,2.5641,14.524103,-59.6553,-59.2192,103.254807,-16.8440,-17.5628,14.079865,-3.06,1,1,0,0,1,0
40,2011-07-25,0.3200,0.3700,-0.05,-13.5135,15.156265,-58.4760,-58.8471,109.553654,-17.8142,-18.1032,15.402043,1.62,0,0,0,1,1,1
41,2011-04-25,0.4200,0.3400,0.08,23.5294,15.476817,-59.0344,-59.5132,108.860355,-18.5665,-18.4072,15.493130,0.11,1,1,1,1,0,0
42,2011-01-24,0.3700,0.3100,0.06,19.3548,13.670076,-58.4496,-59.4230,104.708679,-18.3813,-18.8173,13.783756,0.83,1,1,1,1,1,0
43,2010-10-25,0.3200,0.3000,0.02,6.6667,13.628775,-59.2806,-59.8115,95.770650,-19.6150,-19.2898,13.770194,1.04,0,1,1,1,0,1
44,2010-07-19,0.3200,0.2800,0.04,14.2857,12.485776,-58.7928,-60.1728,86.103835,-19.5667,-19.4970,12.783440,2.38,1,1,0,1,0,1
45,2010-04-19,0.2800,0.2600,0.02,7.6923,13.505604,-58.8996,-59.5722,95.696516,-19.5895,-19.9862,13.617750,0.83,1,1,1,1,1,0
46,2010-01-25,0.2600,0.3100,-0.05,-16.1290,12.703950,-60.8507,-60.1507,87.315525,-20.7735,-21.2116,12.604296,-0.78,0,0,0,0,1,0
47,2009-10-19,0.3400,0.2800,0.06,21.4286,13.091290,-59.0257,-60.5286,86.866253,-20.3573,-20.8142,13.202402,0.85,1,1,1,1,1,0
48,2009-07-20,0.3000,0.2900,0.01,3.4483,11.299228,-59.9460,-60.3068,74.910390,-20.8804,-21.0543,11.583684,2.52,1,1,1,1,1,1
49,2009-04-20,0.1900,0.2700,-0.08,-29.6296,9.426066,-60.7247,-60.5852,65.329386,-23.6271,-21.1762,9.822912,4.21,0,0,1,0,0,1
50,2009-01-16,0.2600,0.3100,-0.05,-16.1290,8.291579,-62.2424,-61.6729,66.121810,-22.9888,-23.3278,8.194031,-1.18,0,0,0,0,1,0
51,2008-10-17,0.2600,0.3300,-0.07,-21.2121,11.353781,-58.3500,-61.1837,71.871023,-21.8708,-21.3470,11.629377,2.43,0,0,1,1,0,1
52,2008-07-18,0.3300,0.3100,0.02,6.4516,10.293723,-59.9622,-61.0718,96.601111,-23.4358,-23.4007,10.421187,1.24,1,1,0,1,0,1
53,2008-04-18,0.3200,0.3000,0.02,6.6667,11.158862,-62.0576,-61.5609,105.648737,-23.9609,-23.8572,11.327994,1.52,1,1,1,0,0,1
54,2008-01-18,0.3100,0.2800,0.03,10.7143,10.809468,-59.9649,-61.8594,100.263500,-25.5874,-24.4171,10.736768,-0.67,1,1,0,1,0,0
55,2007-10-18,0.3000,0.2700,0.03,11.1111,12.261224,-61.0755,-61.9098,116.077952,-24.3545,-24.8284,12.245988,-0.12,1,1,0,1,1,0
56,2007-07-12,0.2700,0.2500,0.02,8.0000,12.328117,-62.0206,-62.0443,116.057763,-23.8316,-24.8576,12.328117,0.00,0,1,0,1,1,0
57,2007-04-19,0.2800,0.2700,0.01,3.7037,13.492984,-62.0877,-62.1202,110.203456,-24.8015,-24.8067,13.379630,-0.84,0,1,0,1,1,0

,earnings_event,surprise_event,adjusted_price_event,intraday_event,spy_event,class_variable
0,1,1,0,0,0,1
1,1,1,0,0,0,0
2,1,1,1,1,1,0
3,1,1,1,0,0,0
4,1,1,1,0,1,1
5,0,0,0,1,0,0
6,0,1,1,1,1,0
7,1,1,1,1,1,1
8,1,0,1,1,1,1
9,0,0,1,1,1,0
10,1,1,1,0,1,1
11,1,1,0,0,0,1
12,1,1,1,0,1,0
13,1,1,1,1,0,1
14,0,0,0,0,1,0
15,0,1,1,1,0,0
16,1,1,0,1,0,0
17,0,0,0,1,0,0
18,0,1,1,1,0,1
19,1,1,1,1,0,0
20,0,1,1,0,0,1
21,1,1,0,0,1,0
22,0,1,1,1,0,1
23,1,1,1,1,1,0
24,0,0,0,0,0,0
25,0,0,1,1,1,0
26,0,0,1,0,0,0
27,1,1,1,1,1,0
28,1,1,0,1,1,1
29,1,1,1,1,0,0
30,1,1,1,0,0,0
31,1,0,0,0,0,1
32,0,0,1,0,0,0
33,1,1,1,1,1,0
34,1,1,1,1,1,0
35,0,0,1,0,0,0
36,0,1,1,1,1,0
37,1,1,0,0,1,1
38,0,0,1,1,1,0
39,1,1,0,0,1,0
40,0,0,0,1,1,1
41,1,1,1,1,0,0
42,1,1,1,1,1,0
43,0,1,1,1,0,1
44,1,1,0,1,0,1
45,1,1,1,1,1,0
46,0,0,0,0,1,0
47,1,1,1,1,1,0
48,1,1,1,1,1,1
49,0,0,1,0,0,1
50,0,0,0,0,1,0
51,0,0,1,1,0,1
52,1,1,0,1,0,1
53,1,1,1,0,0,1
54,1,1,0,1,0,0
55,1,1,0,1,1,0
56,0,1,0,1,1,0
57,0,1,0,1,1,0

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,1,0,2,1,0.833333,0.5,0.5,50.0,Valid,BMRC

Model performance across all the stock in the list:

,TP,FP,FN,TN,Precision WA,Recall WA,F1-Score WA,Model Score %,Model Recommendation,symbol
0,[0],[3],[0],[1],[0.0625],[0.25],[0.1],[25.0],[Invalid],ACC
1,[0],[2],[1],[1],[0.16666666666666666],[0.25],[0.2],[25.0],[Invalid],AGNC
2,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],AIN
3,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],AJRD
4,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],AMG
5,[0],[1],[0],[3],[0.5625],[0.75],[0.6428571428571428],[75.0],[Invalid],ARE
6,[0],[3],[0],[1],[0.0625],[0.25],[0.1],[25.0],[Invalid],ARI
7,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],ARLP
8,[0.0],[3.0],[1.0],[0.0],[0.0],[0.0],[0.0],[0.0],[Invalid],AUB
9,[0],[3],[0],[1],[0.0625],[0.25],[0.1],[25.0],[Invalid],AXTA
10,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],BCLI
11,[0],[2],[0],[2],[0.25],[0.5],[0.3333333333333333],[50.0],[Invalid],BDN
12,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],BEN
13,[0],[0],[0],[4],[1.0],[1.0],[1.0],[100.0],[Valid],BGFV
14,[1],[0],[2],[1],[0.8333333333333334],[0.5],[0.5],[50.0],[Valid],BMRC

Thank you for using the model.
Please wait 60 seconds before running the model again.